### ISSUE TITLE
Cannot easily add or remove class

### ISSUE THREAD

**Issue by nde-agridea** [zzzprojects/html-agility-pack#10]
The library does not allow to add or remove a class to a tag in an easy and straightforward way. Methods like Node.AddClass() or .RemoveClass() would greatly simplify the operation, instead of fumbling around with the Node.Attributes["class"] HtmlAttribute. Classes should be treated as first class citizens IMHO. Please add these in the API.

**Comment by JonathanMagnan** [comment]
Hello @nde-agridea ,

You are 100% right. A lot of good methods which could easily make the code easier are missing.

We are currently mainly focusing on adding documentation: http://html-agility-pack.net/api

But we also add from time to time new methods && options. By example, a change I believe will happen soon will be to support CSS selector as jQuery do.

I will check this request during the weekend and will let you know when we will implement it if it's not implemented during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @nde-agridea ,

Sorry for the delay, it seem I forget to answer you.

Class helper has been added today, it should be available within a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jonalbrecht ,

The version v1.5.0-beta9 has been released:
https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta9

We added the following helper:
- AddClass
- RemoveClass
- ReplaceClass

Let us know if these helpers are what you were looking for.

Best Regards,

Jonathan

**Comment by nde-agridea** [comment]
Hi Jonathan,

Many thanks for the update and congrats for the good work. Good on you and kudos for this great project.

Kins regards,
Nicolas Destrez
Technologie de l’information, Ingénieur Développement Web
AGRIDEA, Jordils 1, CP 1080, CH-1001 Lausanne
Nicolas.destrez@agridea.ch<mailto:Nicolas.destrez@agridea.ch>
+41 (0)21 619 44 89<tel:%2B41%20%280%2921%20619%2044%2089> Direct
+41 (0)21 619 44 00<tel:%2B41%20%280%2921%20619%2044%2000> Centrale,
+41 (0)21 617 02 61<tel:%2B41%20%280%2921%20617%2002%2061> Fax
www.agridea.ch<http://www.agridea.ch/>
Formation continue AGRIDEA : Programme 2017<http://www.agridea.ch/fileadmin/Cours/formation_continue_programme_2017.pdf> – Restez à jour

________________________________

**Comment by JonathanMagnan** [comment]
Closing comment: version released.
