### ISSUE TITLE
Perform control actions on HtmlNode 

### ISSUE THREAD

**Issue by ankurkh4** [zzzprojects/html-agility-pack#100]
Kindly suggest a way to perform various operations on HtmlNode.
1. Click (Button/Link Label/hyperlink etc)
2. SetValue (TextBox/Rich TextBox/DropDownlist/Numeric updown etc)
3. Toggle states
4. Double click
5. Send Keys 
6. Windows Click

Any help is appreciated. I tried using reflection and then invoking member.But no luck.

**Comment by JonathanMagnan** [comment]
Hello @ankurkh4 ,

HAP is an HTML parser, I'm not sure if this library (even if possible) is the right library for you.

You can do pretty much all you want to do via the `LoadFromBrowser` method:
```csharp
var doc1 = web1.LoadFromBrowser(url, o =>
{
	var webBrowser = (WebBrowser) o;

	// WAIT or do some stuff here
});
```

But probably using directly a WebBrowser control or using a library that act like a WebBrowser will be a better solution.

Let me know if that answer successfully to your question even if no real answer has been provided.

Best Regards,

Jonathan

**Comment by ankurkh4** [comment]
Hello JonathanMagnan,

Yes truely HAP is very faster while locating with ID/Name/Xpath. Thank you for your help. Currently I am using mshtml to perform action and locating using HtmlNode but mapping is quite cumbersome. So, was looking for it.
