### ISSUE TITLE
Add HtmlNode.GetClasses

### ISSUE THREAD

**Issue by ohadschn** [zzzprojects/html-agility-pack#102]
There are `AddClass()`, `RemoveClass()`, and even `ReplaceClass()` on `HtmlNode`. IMHO it would be both consistent and useful to have something like `string[] GetClasses()` to get all the classes of the node.

For now I'm just doing `GetAttributeValue("class", "").Split(' ')` but I suspect it is not fully compliant with the [standard](https://www.w3.org/TR/html401/struct/global.html#h-7.5.2) which states _Multiple class names must be separated by white space characters_. Not sure if that means tabs, multiple spaces, Unicode whitespace characters etc. should be allowed as well.

**Comment by JonathanMagnan** [comment]
Hello @ohadschn ,

Thank you for your feedback. I agree it should have something similar to this.

I will try to include something similar to this in the next release.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ohadschn ,

The v1.6.4 has been released.

Let us know if the new method works as expected.

Best Regards,

Jonathan

**Comment by ohadschn** [comment]
Wow, that was fast! Thanks :)

Forgive my density, but only now I realize that another natural addition would be `bool HasClass(string cls)`. No pressure though, it's trivial to implement using `GetClasses`.

**Comment by JonathanMagnan** [comment]
Hello @ohadschn ,

Sure, it will be part of the next HAP release that will happen probably next weekend.

I will check at the same time if there is no other method that should be implemented for css class.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ohadschn ,

The v1.6.5 has been released.

The `HasClass` method has been added.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Thank a lot for the donation ;)
