### ISSUE TITLE
I cant Build project after forking and cloning to VS2017

### ISSUE THREAD

**Issue by parsalotfy** [zzzprojects/html-agility-pack#104]
Hi.
Recently I forked from HAP , after that I cloned it to VS2017 , then when I Click on Build button , it failed . In addition I cant see the .sln file and instead i see .snk file

I want to make some changes in your library and do a pull request , I like to be contributer :)
so I need to open this project in Visual Studio.
**What should I do ?**
Thank you.

![screenshot 58](https://user-images.githubusercontent.com/30390810/32837379-91ba85f8-ca22-11e7-985f-a02511eb1b4c.png)

![screenshot 59](https://user-images.githubusercontent.com/30390810/32837374-90f28576-ca22-11e7-9f48-f2558e8abc48.png)

![screenshot 61](https://user-images.githubusercontent.com/30390810/32837377-912e5dc6-ca22-11e7-9a47-091e8ea947b7.png)

![screenshot 62](https://user-images.githubusercontent.com/30390810/32837378-91706fa4-ca22-11e7-9d12-aef3f0c8d3c3.png)

The out-put after build :

1>------ Build started: Project: HtmlAgilityPack, Configuration: Debug Any CPU ------
1>C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack.Shared\HtmlDocument.cs(37,17,37,22): warning CS0618: 'Crc32' is obsolete: 'This type should not be used; it is intended for internal use in HTML Agility Pack.'
1>C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack.Shared\HtmlDocument.cs(1199,30,1199,35): warning CS0618: 'Crc32' is obsolete: 'This type should not be used; it is intended for internal use in HTML Agility Pack.'
1>C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack.Shared\HtmlDocument.cs(291,30,291,40): warning CS1591: Missing XML comment for publicly visible type or member 'HtmlDocument.GetXmlName(string, bool)'
1>  HtmlAgilityPack -> C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack\bin\Debug\HtmlAgilityPack.dll
1>  The system cannot find the path specified.
1>  C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack\bin\Debug\HtmlAgilityPack.dll
1>  The system cannot find the path specified.
1>  C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack\bin\Debug\HtmlAgilityPack.pdb
1>  C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack\bin\Debug\HtmlAgilityPack.xml
1>  The system cannot find the path specified.
1>  The system cannot find the path specified.
1>          0 file(s) copied.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5019,5): error MSB3073: The command "del /f /q C:\Users\Parsa\Source\Repos\html-agility-pack\src\Solutions\..\Nuget\lib\Net20\*
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5019,5): error MSB3073: copy "C:\Users\Parsa\Source\Repos\html-agility-pack\src\HtmlAgilityPack\bin\Debug\Html*.*" C:\Users\Parsa\Source\Repos\html-agility-pack\src\Solutions\..\Nuget\lib\Net20\" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

Thank you,

You are right, I opened it from `GitHub` (real source are currently on visual studio online) and I get some error as well.

I will try to fix it today or during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

The solution has been fixed, you should be able to successfully built.

Let me know if something is missing.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by parsalotfy** [comment]
Thank you for fixing that 👍 
I have a question , why the HtmlAgilityPack project does not have any .cs code and there is not any .sln file ?
and there is .snk file instead ...
for making changes in your library we should work with HtmlAgilityPack.Shared ?
we don't need HtmlAgilityPack  at all ?
Thank you.

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

Yes, all modification should be only done on `HtmlAgilityPack.Shared`

There is no code in the `HtmlAgilityPack` since all file are shared across multiple output project. So instead to have every file included in every project, I choose to create a `Shared` project to make it easier for maintenance.

Best Regards,

Jonathan
