### ISSUE TITLE
Newly added element cannot be found using ID attribute

### ISSUE THREAD

**Issue by DaveWellman** [zzzprojects/html-agility-pack#105]
Hi,
I'm using v1.6.3.0 and I think I've found a bug.

As part of my processing I need to add an html element and then later on find that element using it's ID attribute. However, although the element adds ok and I can extract the document as a string (OuterHTML property) and see it there, using the GetElementbyId method does not find it.

However I have found a workaround as follows:
- that after adding the element
- extract the OuterHTML property into a string variable 
- set my document variable to Nothing
- initialise my document variable as a new HTMLDocument
- load the string into my new document

At this point I can now find the recently added element using GetElementbyId.

If I'm correct then it looks like the InsertAfter method (which is the one that I'm using) does not rebuild whichever internal structure the GetElementbyId method uses.
(or of course I'm doing it wrong!)

In my case this is not a major issue, the above work-around is acceptable for my processing.

Cheers,
Dave

**Comment by JonathanMagnan** [comment]
Hello @DaveWellman ,

Do you think you could reproduce the full issue in a code sample?

That will be easier/faster for me to investigate it.

Best Regards,

Jonathan

**Comment by DaveWellman** [comment]
Hi Jonathan,

 

Thanks for the speedy response.

 

As is often the case, when you start producing a simple example you work out what is going wrong. I think this is my mistake and I don’t think there is anything the HtmlAgilityPack code can do about it.

 

What I’m doing is adding a complete table row which has multiple ‘td’ elements in it. The id attribute that I’m looking for (and couldn’t find) is in one of those ‘td’ elements, but of course the HtmlAgilityPack code doesn’t see that as it is ‘buried’ in a string.

 

Here are a couple of examples from my test project.

 

1)      Add a simple html element which has an id attribute. This can be found..



2)      Add a more complex html string (in my case a complete row in a table) where the ‘tr’ element has an id attribute. This can be found.



3)      Add a more complex html string (in my case a complete row in a table) where one of the ‘td’ elements has an id attribute. This can NOT be found. 

 

At the end of this email is my test project, a simple vb.net console program.

 

If you look for the two ‘NOTE’ comments, they describe the situation.

 

If you can handle this that would be great, but if not then I’ll sort it in my code.

 

Cheers,

Dave

 

 

 

Imports HAP = HtmlAgilityPack

 

Module Module1

 

    Sub Main()

        Dim lHTMLDoc As HAP.HtmlDocument

        Dim lELM As HAP.HtmlNode

        Dim lNewELM As HAP.HtmlNode

 

        Dim lStr As String

 

        Try

 

            Console.WriteLine("Starting")

            lHTMLDoc = New HAP.HtmlDocument

 

            lStr = "<!DOCTYPE html>"

            lStr = lStr & "<head>"

            lStr = lStr & "<title>Users Configuration</title>"

            lStr = lStr & "</head>"

            lStr = lStr & "<body>"

            lStr = lStr & "<p id=" & Chr(34) & "id1" & Chr(34) & "> This Is some text for id=id1</p>"

            lStr = lStr & "<p id=" & Chr(34) & "id2" & Chr(34) & "> This Is some text for id=id2</p>"

            lStr = lStr & "<p id=" & Chr(34) & "id3" & Chr(34) & "> This Is some text for id=id3</p>"

 

            lStr = lStr & "<table id=" & Chr(34) & "tbl1" & Chr(34) & ">"

            lStr = lStr & "<tr id=" & Chr(34) & "tr1" & Chr(34) & ">"

            lStr = lStr & "<th>&nbsp;</th>"

            lStr = lStr & "<th>Admin</th>"

            lStr = lStr & "<th>Write</th>"

            lStr = lStr & "<th>Read</th>"

            lStr = lStr & "<th>None</th>"

            lStr = lStr & "<th>Delete</th>"

            lStr = lStr & "</tr>"

            lStr = lStr & "</table>"

 

 

            lStr = lStr & "</body>"

            lStr = lStr & "</html>"

 

            lHTMLDoc.LoadHtml(lStr)

 

            lELM = lHTMLDoc.GetElementbyId("id1") ' show that we can get an element based on it's id attribute

            Console.WriteLine("id1 retrieved: " & lELM.InnerText)

 

            lStr = "<p id=" & Chr(34) & "id4" & Chr(34) & "> This Is some text for id=id4</p>"

 

            lNewELM = HAP.HtmlNode.CreateNode(lStr) ' create the node

            lELM.AppendChild(lNewELM) ' add the new element

            lELM = Nothing

            lNewELM = Nothing

 

 

            lELM = lHTMLDoc.GetElementbyId("id4") ' show that we can get an element based on it's id attribute

            If (Not lELM Is Nothing) Then

                Console.WriteLine("id4 retrieved: " & lELM.InnerText)

            Else

                Console.WriteLine("id4 NOT found!")

                Console.WriteLine(lHTMLDoc.DocumentNode.OuterHtml())

            End If

 

 

            ' NOTE: one of the 'td' cells in the following conains an id attribute value (cell4).

            lStr = "<tr id=" & Chr(34) & "tr2" & Chr(34) & ">"

            lStr = lStr & "<th>David</th>"

            lStr = lStr & "<td>21</td>"

            lStr = lStr & "<td id=" & Chr(34) & "cell4" & Chr(34) & ">22</td>"

            lStr = lStr & "<td>23</td>"

            lStr = lStr & "<td>24</td>"

            lStr = lStr & "</tr>"

 

            lNewELM = HAP.HtmlNode.CreateNode(lStr) ' create the node

 

            lELM = lHTMLDoc.GetElementbyId("tbl1") ' this finds our 'table'

            If (Not lELM Is Nothing) Then

                Console.WriteLine("tbl1 retrieved: " & lELM.InnerHtml)

            Else

                Console.WriteLine("tbl1 NOT found!")

                Console.WriteLine(lHTMLDoc.DocumentNode.OuterHtml())

            End If

 

            lELM.AppendChild(lNewELM) ' add the new element

 

            lELM = Nothing

            lNewELM = Nothing

 

 

            lELM = lHTMLDoc.GetElementbyId("tr2") ' show that we can get an element based on it's id attribute

            If (Not lELM Is Nothing) Then

                Console.WriteLine("tr2 retrieved: " & lELM.InnerHtml)

            Else

                Console.WriteLine("tr2 NOT found!")

                Console.WriteLine(lHTMLDoc.DocumentNode.OuterHtml())

            End If

 

            ' NOTE: it is this bit which 'fails'

            lELM = lHTMLDoc.GetElementbyId("cell4") ' show that we can get an element based on it's id attribute

            If (Not lELM Is Nothing) Then

                Console.WriteLine("cell4 retrieved: " & lELM.InnerHtml)

            Else

                Console.WriteLine("cell4 NOT found!")

                Console.WriteLine(lHTMLDoc.DocumentNode.OuterHtml())

            End If

 

 

        Catch ex As Exception

            Console.WriteLine(ex.ToString)

        Finally

            ' Clean up

            lELM = Nothing ' clear this reference

            lNewELM = Nothing ' clear this reference

            lHTMLDoc = Nothing ' clear this reference

 

        End Try

    End Sub

 

End Module

 

 

 

 

 

Ward Analytics Ltd - information in motion

Tel: +44 (0) 118 9740191

Fax: +44 (0) 118 9740192

www: http://www.ward-analytics.com

 

Registered office address: The Oriel, Sydenham Road, Guildford, Surrey, United Kingdom, GU1 3SR

Registered company number: 3917021 Registered in England and Wales.

**Comment by JonathanMagnan** [comment]
Thank you @DaveWellman,

I will try to check it during the weekend.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @DaveWellman ,

Sorry for the long delay,

The v1.6.10 has been released. We have improved the way we handle newly ID.

Let me know if that's fixed if you have time to check it.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate

**Comment by DaveWellman** [comment]
Hi Jonathan,

 

No problem with the delay, as I said in my original post I had an acceptable work around.

 

I’ve installed this version and it fixes the problem that I reported.

 

Many thanks,

Dave

 

 

Ward Analytics Ltd - information in motion

Tel: +44 (0) 118 9740191

Fax: +44 (0) 118 9740192

www: http://www.ward-analytics.com

 

Registered office address: The Oriel, Sydenham Road, Guildford, Surrey, United Kingdom, GU1 3SR

Registered company number: 3917021 Registered in England and Wales.
