### ISSUE TITLE
Tags incorrectly identified

### ISSUE THREAD

**Issue by catalinmurariu** [zzzprojects/html-agility-pack#107]
According to specs a tag is an angle bracket followed immediately by text. But consider the following example:
```
var htmlDoc = new HtmlDocument();
 htmlDoc.LoadHtml("< this is just simple text!");
 var rendered = htmlDoc.DocumentNode.OuterHtml;
 Console.WriteLine(rendered);
```

Outputs: 
> < this is just simple text! this="" is="" just="" simple=""></ this is just simple text!>

Instead of:
> < this is just simple text!

So the parser considers that a tag, when a browser that correctly adheres to the spec won't (e.g. Chrome).
See relevant stackoverflow question with link to spec -> https://stackoverflow.com/questions/3314535/white-space-inside-xml-html-tags

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

I remember having done something about it, I will check it this week.

Best Regards,

Jonathan

**Comment by catalinmurariu** [comment]
Yes, it's actually fixed in the latest version. I was on an older version brought by the HtmlRuleSanitizer project. Sorry about that. 

Closing this.
