### ISSUE TITLE
HtmlAttributeCollection.Contains - consider using string.Equals(value, StringComparison) 

### ISSUE THREAD

**Issue by jpmnteiro** [zzzprojects/html-agility-pack#108]
Hi,

First off, thank you for the library, it's great.

One potential issue I found when working with attributes, performance wise, is the usage of `.ToLower()` in `HtmlAttributeCollection.Contains()` et al. This could be avoided by either using the `string.Equals(value, StringComparison.OrdinalIgnoreCase)` or allowing the caller to specify the type of string comparison it wants to execute.

I can submit a PR if you're comfortable with the idea.

**Comment by JonathanMagnan** [comment]
Hello @jpmnteiro ,

It's already part of the following pull: #97 

However, I believe it's faster to move the lower outside of the loop instead to use `StringComparison`

By example:

```csharp
var lName = name.ToLower();
for (int i = 0; i < items.Count; i++)
{
	if (items[i].Name.Equals(name))
		return true;
}
```

Let me know if that answer successfully to your question.

Best Regards,

Jonathan
---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by jpmnteiro** [comment]
Had not seen #97, but the changes there would sort the issue in my view. 

The problem here is that the call to `.ToLower()` occur every time when you check if an attribute exists on the collection, even if the input's already a lowercase string (which is fine, you can't trust the input). 

But by allowing the caller to specify the type of comparison (overload of the current `.Contains(string)` method), you could avoid unnecessary work as the caller would know what comparison would suit him/her best.

**Comment by JonathanMagnan** [comment]
Hello @jpmnteiro ,

You got a good point ;)

👍

**Comment by JonathanMagnan** [comment]
Hello @jpmnteiro ,

I will close this issue, I believe we fixed most of this kind of issue.

Feel free to reopen if that should have not been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/co

**Comment by jpmnteiro** [comment]
@JonathanMagnan  I'd argue otherwise, the issue was not been solved. I'm looking at `HtmlAttributeCollection` (master) and there are several instances of `.ToLower()`.

E.g (line 247):

    for (int i = 0; i < items.Count; i++)
    {
        if (items[i].Name.Equals(name.ToLower()))
            return true;
    }

This has an unnecessary performance hit due to the repeat call to `.ToLower()` on each iteration.
A simple solution would be to move the `.ToLower()` outside of the loop. Or you could lookup the item in the dictionary instead of looking at the list, using the unmodified name (assuming you initialised the dictionary with the `StringComparer.OrdinalComparison` comparer).
