### ISSUE TITLE
Question - Does LoadFromBrowser method work in Windows Server Core? 

### ISSUE THREAD

**Issue by Geogboe** [zzzprojects/html-agility-pack#110]
### Overview
I can put together some examples and submit a real issue, but wanted to check first to see if this is a known limitation? 

**Background**
I'm using HAP with PowerShell and .NET 45 and it works great! In a desktop OS I can do this: 

```powershell
Add-Type -Path .\HtmlAgilityPack.dll
$w = New-Object HtmlAgilityPack.HtmlWeb
$d = $w.LoadFromBrowser("https://google.com")
```
When trying to do the same from Windows Server Core I get this exception: 

```powershell

try { $d = $w.LoadFromBrowser("http
s://google.com") } catch { $_ | select * }


PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "LoadFromBrowser"
                        with "1" argument(s): "Class not registered (Exception from HRESULT: 0x80040154
                        (REGDB_E_CLASSNOTREG))" ---> System.Runtime.InteropServices.COMException: Class not registered
                        (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
                           at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter,
                        Int32 context, Guid& iid)
                           at System.Windows.Forms.WebBrowserBase.TransitionFromPassiveToLoaded()
                           at System.Windows.Forms.WebBrowserBase.TransitionUpTo(AXState state)
                           at System.Windows.Forms.WebBrowser.get_AxIWebBrowser2()
                           at System.Windows.Forms.WebBrowser.set_ScriptErrorsSuppressed(Boolean value)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : COMException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

### Thoughts
- The system.Windows.Forms namespace is loaded. (That's what HAP uses for this method right) . I'm wondering if WebBrowser uses the IE engine...which I know isn't available in server core? 

If this is something that should be working, let me know and I'll dive in a get more information. 
Thanks!

**Comment by JonathanMagnan** [comment]
Hello @Geogboe ,

Looking at the stack trace, it looks the code successfully find the `System.Windows.Forms.WebBrowser` class. 

However, I'm not sure if the `WebBrowser` is yet supported in `Windows Server Core`. I may be wrong, but I believe it's not supported yet and that's why this error happens.

I believe the best way to find out is creating a very simple console application without our library and you will be sure at 100%.

Best Regards,

Jonathan

**Comment by Geogboe** [comment]
@JonathanMagnan Thanks for looking into this! One thing I should have mentioned, I did verify that I **can** create an object from System.Windows.Forms.WebBrowser while on server server core using PowerShell. So that means the assembly and namespace exists right?

What I didn't try was actually attempting to use it to try web browsing. My guess is that it uses the IE engine--which isn't available on server core--so it won't work. 

**Work around**
I was able to find a workaround though. By watching network traffic for the site I discovered a backend json api that I can target directly so I don't need to use the WebBrowser method and can use a normal web request. 

Please let me know if you'd like me to fully test Forms.WebBrowser on server core and report back. Otherwise feel free to resolve this issue. Thanks!

**Comment by JonathanMagnan** [comment]
Hello @Geogboe ,

I do not have a `server core`, so yes, if you could take a few minutes to look at it, that will be nice and help us to better answer if we get similar issue ;)

Best Regards,

Jonathan

**Comment by Geogboe** [comment]
Ok confirmed it doesn't work in server core. 

**Test Env**
Windows Server 2016 Core = 10.0.14393 N/A Build 14393
Windows Server 2016 with Desktop 10.0.14393 N/A Build 14393
Testing using PowerShell 5.1

Code: 
```powershell
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$Form = New-Object Windows.Forms.Form
$Form.Text = "Test Form"
$Form.Size = New-Object Drawing.size @(500,500)
$WebBrowser = New-object System.Windows.Forms.WebBrowser
$WebBrowser.size = New-object System.Drawing.size(500,500)
$WebBrowser.Navigate("https://wikipedia.com/")
$Form.Controls.Add($WebBrowser)
$Form.ShowDialog()
```

** On the Server 2016 with Desktop it works**
![image](https://user-images.githubusercontent.com/3868453/33692286-84f01ede-daba-11e7-8750-89d055905a3c.png)


** On Server 2016 Core it fails with these errors**
```cmd
************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.WebBrowserBase.TransitionFromPassiveToLoaded()
   at System.Windows.Forms.WebBrowserBase.TransitionUpTo(AXState state)
   at System.Windows.Forms.WebBrowserBase.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
What's interesting is that the form DOES show up. It's just the web browser in the form doesn't. So I really think the WebBrowser class uses IE and, as that's not available, doesn't work. 

![image](https://user-images.githubusercontent.com/3868453/33692320-bcb6f892-daba-11e7-8b0d-d9db762c388a.png)

**Comment by JonathanMagnan** [comment]
Hello @Geogboe ,

Thank a lot for your investigation ;)

I will link to your answer to all future questions related to this.

Best Regards,

Jonathan
