### ISSUE TITLE
End tag </option> is not required

### ISSUE THREAD

**Issue by ahlec** [zzzprojects/html-agility-pack#111]
I was previously on v1.5.5 via NuGET and attempting to call HtmlDocument.Load on properly formed XML was giving me an exception. There's a <select>...</select> tag in the document that I'm deserializing, and it contains a fair number of properly formatted <option>...</option> tags. Each one of these causes a parse error of "EndTagNotRequired". This seems to be something that [other people have encountered as well](http://stackoverflow.com/questions/293342/htmlagilitypack-drops-option-end-tags). Updating to the latest (v.1.6.5 on NuGET) has not resolved the problem.

For reference, the page that I'm deserializing is https://archiveofourown.org/works/search. If you would like to see the code that I'm using to repro this error, it can be found [here](https://github.com/ahlec/Alexandria/blob/4d25a8dff7da1439b6e453764f98faed28d74a14/Alexandria/Utils/HtmlUtils.cs) (the specific function is HtmlUtils.ParseHtmlDocument).

I love this library a whole lot, and a proper fix or workaround for this would be amazing in terms of allowing me to continue using this! Thank you so much!!

**Comment by JonathanMagnan** [comment]
Hello @ahlec ,

Thank you for reporting. I will for sure look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ahlec 

The v1.6.6 has been released.

We changed the behavior how `option` tag was handled. Please let me know if you find any issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by ahlec** [comment]
Thank you so much!! The speed and the response is VERY appreciated! Thank you for all of your hard work!
