### ISSUE TITLE
xlink:href attribute not recognized

### ISSUE THREAD

**Issue by alexandregregoire** [zzzprojects/html-agility-pack#112]
Hi guys,

Using `document.DocumentNode.QuerySelectorAll` in C#, I am trying to get the node with xlink:href="#iconKM" with a class selector.

`<div>`
`  <svg version="1.1" class="cldt-icon">`
`    <use xlink:href="#icon_km"></use>`
`  </svg>`
`  <span class="sc-font-l cldt-stage-primary-keyfact">XXXXXXX</span>`
`  <span class="sc-font-s cldt-stage-att-description">YYYYYYY</span>`
`</div>`

However, HAP does not seem to be able to handle the ":", while I am not able to escape the ":" character, leaving me stuck. 

any idea? 

thx!

**Comment by JonathanMagnan** [comment]
Hello @alexandregregoire ,

Our library doesn't have a `QuerySelectorAll` feature. So I believe the answer may depend on which third-party library you are using with HAP.

Let me know which third-party library you use and I will have someone trying it Friday.
Best Regards,

Jonathan

**Comment by alexandregregoire** [comment]
Hi Jonathan!

Thanks for the swift feedback! I am using the class
Fizzler.Systems.HtmlAgilityPack.QuerySelectorAll with the .NET Framework
4.6.1 (Visual Studio 2017).

The following packages are included in my project :


   - Fizzler.systems.htmlagilitypack 1.0.0 by Atif Aziz and Colin Ramsay
   - HtmlAgilityPack 1.4.9 by Simon Mourrier and Jeff Klawiter

When using the following QuerySelector("use[xlink:href=\"#icon_km\"]") I am
getting the following exception :
"Unexpected token {Char} where {Char: ]} was expected."

Kind Regards,

Alexandre

**Comment by JonathanMagnan** [comment]
Hello @alexandregregoire ,

I looked a little bit on `Fizzler` but I have not found the error.

I recommend you to contact `Atif` on the [Fizzle](https://github.com/atifaziz/Fizzler) since the error happens in this package and not in the `HAP` package.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @alexandregregoire ,

I will close this issue since it's not related to our library.

Feel free to reopen it if you believe it should not have been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
