### ISSUE TITLE
Parsing invalid attribute

### ISSUE THREAD

**Issue by Waynezhi** [zzzprojects/html-agility-pack#113]
Hello, i just failed to parse an attribute with unformatted tag inside:
from
```html
<li><a href="/Navigate?lid=%2F%2Fproductsuniverse%2Fen_GB%2Fproduct_online%3DY%2Finsearch%3D1%2Fcategories<%7Bproductsuniverse_18661%7D%2Fcategories<%7Bproductsuniverse_18661_141601%7D%2Fheel_height>%7Bhigh20heel%7D">High heel shoes</a></li>
```
to
```html
<li><a  href="/navigate?lid=%2f%2fproductsuniverse%2fen_gb%2fproduct_online%3dy%2finsearch%3d1%2fcategories<%7bproductsuniverse_18661%7d%2fcategories<%7bproductsuniverse_18661_141601%7d%2fheel_height>%7bhigh20heel%7d">high heel shoes</a></li> href=""></a  href="/navigate?lid=%2f%2fproductsuniverse%2fen_gb%2fproduct_online%3dy%2finsearch%3d1%2fcategories<%7bproductsuniverse_18661%7d%2fcategories<%7bproductsuniverse_18661_141601%7d%2fheel_height>%7bhigh20heel%7d">high heel shoes</a></li>></li>
```

should validation also inside double quote attributes ?

**Comment by JonathanMagnan** [comment]
Hello @Waynezhi ,

Thank you for reporting. We successfully reproduce and fixed the issue

Here is the new output

```html
<li><a href="/Navigate?lid=%2F%2Fproductsuniverse%2Fen_GB%2Fproduct_online%3DY%2Finsearch%3D1%2Fcategories<%7Bproductsuniverse_18661%7D%2Fcategories<%7Bproductsuniverse_18661_141601%7D%2Fheel_height>%7Bhigh20heel%7D">High heel shoes</a></li>
```

The issue was caused because the library was thinking some `server code` tag was here due to `<%`

The fix will be released for next Monday.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Waynezhi ,

The v1.6.7 has been released. We have added some logic to better handle this scenario.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by Waynezhi** [comment]
Cool, thanks @JonathanMagnan for your recent fix.
