### ISSUE TITLE
HtmlNode id attribute is not set succesfully

### ISSUE THREAD

**Issue by Janek91** [zzzprojects/html-agility-pack#115]
Because SetId method is never adding created HtmlAttribute to Attributes collection after setting Id attribute of node it's still an empty string.
Please fix this bug.
```c#
        internal void SetId(string id)
        {
            HtmlAttribute att = Attributes["id"] ?? _ownerdocument.CreateAttribute("id");
            att.Value = id;
            _ownerdocument.SetIdForNode(this, att.Value);
            Attributes.Add(att); // missing line
            SetChanged();
        }
```

**Comment by JonathanMagnan** [comment]
Hello @Janek91 ,

Thank you for reporting, we will look at it this week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Janek91 ,

The v1.6.8 has been released.

Your fix has been included in this version.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Janek91 ,

I will close this issue since it should be solved.

Feel free to reopen it if there is something else.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
