### ISSUE TITLE
Null Reference Exception in Nuget Package Manager

### ISSUE THREAD

**Issue by DmitryDem** [zzzprojects/html-agility-pack#117]
Hi.
The HtmlAgilityPack (version > 1.4.9.5) breake the Nuget Package Manager. The Nuget Package Manager throws Null Reference Exception when the HtmlAgilityPack upper than 1.4.9.5 was installed.

**Comment by JonathanMagnan** [comment]
Hello @DmitryDem ,

Do you have the latest version of the Nuget Package manager?

It should work fine with the latest version.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @DmitryDem ,

I will close this issue since it's not related to our library.

Feel free to reopen it if you believe it should not have been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
