### ISSUE TITLE
Missing  one HtmlWeb.Load implementation

### ISSUE THREAD

**Issue by aconsuegra2014** [zzzprojects/html-agility-pack#118]
In the HAP repo I found a method Load with signature
 public HtmlDocument Load(string url, string proxyHost, int proxyPort, string userId, string password)

I installed HAP via nuget in Visual Studio 2017, version 1.6.7
and Visual Studio tell me that the methods with these arguments don't exists.

Why is that?

**Comment by JonathanMagnan** [comment]
Hello @aconsuegra2014 ,

Could you point me out the path of the file with this signature?

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by aconsuegra2014** [comment]
https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack/HtmlWeb.cs
Line 1172.

**Comment by aconsuegra2014** [comment]
The problem was that  the destination platform was netstandar not netframework
when I switch it all work fine.
My fault

**Comment by JonathanMagnan** [comment]
No problem ;)

Be careful, real source are now part of a shared project: https://github.com/zzzprojects/html-agility-pack/tree/master/src/HtmlAgilityPack.Shared

We will try to clean up some the repository to makes sure people don't get confused.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
