### ISSUE TITLE
MimeTypes dictionary has duplicate keys

### ISSUE THREAD

**Issue by jnyrup** [zzzprojects/html-agility-pack#123]
The `MimeTypes` dictionary in `HtmlWeb` contains 100's of duplicate file extensions.
E.g. 
```csharp
_mimeTypes.Add(".aif", "audio/aiff");
_mimeTypes.Add(".aif", "audio/x-aiff");
```
So only the last mime type of each duplicate file extension is saved as all previous are overwritten.

**Comment by JonathanMagnan** [comment]
Hello @jnyrup ,

In fact, that's worse than this.

A duplicate key cannot exist so the first duplicate line threw an error.

We will look at it to check what's the best way to fix it.

Best Regards,

Jonathan


---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @jnyrup  ,

The v1.6.10 has been released.

After review, we took the decision to comment all this code. This part of the code has never worked which mean probably no one currently uses it.

Currently, we prefer to concentrate our effort on feature people currently use.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by jnyrup** [comment]
Sounds like a good choice
