### ISSUE TITLE
Html-Agility-Pack for custom intellisene

### ISSUE THREAD

**Issue by VE-2016** [zzzprojects/html-agility-pack#126]
My question is whether Html-Agility-Pack can be used for writing custom intellisense (code completion)?

JK

**Comment by JonathanMagnan** [comment]
Hello @VE-2016 ,

I'm not sure to understand correctly the purpose.

`HtmlAgilityPack` is an `HTML Parser`, so the answer is probably no.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @VE-2016 ,

I will close this issue since it's not related to our library.

Feel free to reopen it if you believe it should not have been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
