### ISSUE TITLE
[Regression] HAP wrongly parses website when using tr-TR language.

### ISSUE THREAD

**Issue by JustArchi** [zzzprojects/html-agility-pack#128]
There is some inner parsing problem when HAP is working under `tr-TR` culture. The same HTML being parsed under `en-US` and `tr-TR` gives two totally different results.

The regression happened between 1.6.1 and 1.6.2. 1.6.1 is last working version, 1.6.2 is first one with the bug introduced.

I attached the best possible reproducible case I could come up with. Important notice - I actually couldn't reproduce this on Linux. It seems only Windows boxes are affected. I reproduced it with .NET Core 2.0 (`netcoreapp2.0`) as well as .NET Framework 4.6.1. The reproducible case is `netcoreapp2.0` you can run with `dotnet run`.

Thank you in advance for looking into this, it's quite important regression to me.

[HAPRegression.zip](https://github.com/zzzprojects/html-agility-pack/files/1589438/HAPRegression.zip)

![image](https://user-images.githubusercontent.com/1069029/34387006-f5adb830-eb2b-11e7-9b65-b1eb5dfc7019.png)

**Comment by JonathanMagnan** [comment]
Hello @JustArchi ,

Thank you for reporting,

We will for sure look at it and fix it.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @JustArchi ,

The v1.6.11 has been released.

It should no longer cause this issue. However, we also fixed some part of the code that was not parsing correctly before with the `tr-TR` culture.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribut

**Comment by JustArchi** [comment]
Hey Jonathan.

I'm very happy to say that indeed I couldn't reproduce the issue neither with my own app, nor the reproducible case I attached above for testing purposes. Thank you a lot for fixing the issue! ❤️
