### ISSUE TITLE
HtmlWeb.Load and HtmlDocument.LoadHtml Methods NOT loading newly requested URL

### ISSUE THREAD

**Issue by jamesab** [zzzprojects/html-agility-pack#131]
So everything works fine with the first url. The problem is when I try to load the second URL. It loads html from the first URL.

https://www.amazon.com/Best-Sellers-Electronics/zgbs/electronics/#1
https://www.amazon.com/Best-Sellers-Electronics/zgbs/electronics/#2

HtmlWeb web = new HtmlWeb();
HtmlDocument doc = web.Load(url); 
// Tried this method as well with the same result.
string html = new MyWebClient().DownloadString(url);
HtmlDocument doc = new HtmlDocument();
doc.LoadHtml(html);

**Comment by JonathanMagnan** [comment]
Hello @jamesab ,

It seems you don't use `HAP` to download the `HTML` from Amazon.

You are currently using your own `MyWebClient`.

The issue seems not related to the library

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute

**Comment by jamesab** [comment]
Okay then forget i ever put that code in my comment.  I still have the issue.:
So everything works fine with the first url. The problem is when I try to load the second URL. It loads html from the first URL.

https://www.amazon.com/Best-Sellers-Electronics/zgbs/electronics/#1
https://www.amazon.com/Best-Sellers-Electronics/zgbs/electronics/#2

HtmlWeb web = new HtmlWeb();
HtmlDocument doc = web.Load(url);

**Comment by zgabi** [comment]
And the 2 URLs are the same, only the fragment (after #) is different, which is a client side thing. In the browser you can see that the 2nd url shown the first page too for a very short time and a script loads the 2nd page. But HAP is not a script engine, so it can't execute that script (which is event not downloaded)

**Comment by jamesab** [comment]
zgabi, that sound like the issue. Thank you for clarifying what was happening.
