### ISSUE TITLE
Problem with ascent on xpath

### ISSUE THREAD

**Issue by eyanson** [zzzprojects/html-agility-pack#132]
NOT WORK:
var node = htmlDoc.DocumentNode.SelectSingleNode(".//strong[. = \"Dolar Banco Nación\"]");

WORK:
var node = htmlDoc.DocumentNode.SelectSingleNode(".//strong[. = \"Dolar Bolsa (AO20D)\"]");

COMPLETE SAMPLE:

```csharp
using System;
using System.Xml;
using HtmlAgilityPack;

public class Program
{
	public static void Main()
	{
		HtmlWeb web = new HtmlWeb();
		var html = @"http://www.invertironline.com/mercado/cotizaciones/argentina/monedas/principales-divisas";
		var htmlDoc = web.Load(html);

var node = htmlDoc.DocumentNode.SelectSingleNode(".//strong[. = \"Dolar Banco Nación\"]");
//var node = htmlDoc.DocumentNode.SelectSingleNode(".//strong[. = \"Dolar Bolsa (AO20D)\"]");
		
		string name = node.InnerText;
		Console.WriteLine(name);
	}
}
```

**Comment by JonathanMagnan** [comment]
Hello @eyanson ,

Thank you for reporting,

We will investigate this issue soon.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @eyanson ,

I will close this issue since it's not related to our library.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
