### ISSUE TITLE
Is XPath 2.0 and specifically the union operator supported?

### ISSUE THREAD

**Issue by fmeyertoens** [zzzprojects/html-agility-pack#134]
I want to extract data from an html table but I want the tbody element to be optional.
As [this](https://stackoverflow.com/a/39298691) post suggests it should be possible with the following xpath expression:
//table/(tbody|.)/tr/td
But somehow it doesn't return a node and I wondered whether the union operator is even implemented.

Here is the code I tested it with: [http://xpatheval.apphb.com/6haWaI74q](http://xpatheval.apphb.com/6haWaI74q)

**Comment by JonathanMagnan** [comment]
Hello @fmeyertoens ,

Unfortunately, it looks we get the same result as you.

Looking at some post and result we get, I believe the XPath 2.0 is not supported

See: 
- https://groups.google.com/forum/#!topic/microsoft.public.dotnet.xml/aUFPG94LtCM
- https://stackoverflow.com/questions/7520557/how-to-use-xpath-2-0-methods-in-net-4-0

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @fmeyertoens ,

I will close this issue since there is nothing we can do for it.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
