### ISSUE TITLE
Setting an attribute via index on the HtmlAttributeCollection does not update the underlying dictionary

### ISSUE THREAD

**Issue by jpmnteiro** [zzzprojects/html-agility-pack#135]
It seems that setting an attribute, via the index (HtmlAttributeCollection.cs, line 72), fails to update the internal dictionary used by the attribute collection.

A test to repro the bug:

    [Test]
    public void HtmlAgilityPack_AttributeCollectionBug()
    {
        const string firstAttrName = "first";
        const string secondAttrName = "second";
        const string value = "value";
            
        HtmlNode firstNode = HtmlNode.CreateNode("<div></div>");
        firstNode.Attributes.Add(firstAttrName, value);

        HtmlNode secondNode = HtmlNode.CreateNode("<div></div>");
        secondNode.Attributes.Add(secondAttrName, value);
            
        secondNode.Attributes[0] = firstNode.Attributes[0];
            
        Assert.IsNotNull(secondNode.Attributes[0]);
        Assert.AreEqual(firstAttrName, secondNode.Attributes[0].Name);

        Assert.IsNotNull(secondNode.Attributes[firstAttrName], $"'{firstAttrName}' should exist in the collection");
        Assert.AreEqual(firstAttrName, secondNode.Attributes[firstAttrName].Name);

        Assert.IsNull(secondNode.Attributes[secondAttrName], $"{secondAttrName} should not exist in the collection");
    }

The solution should be straightforward:

    public HtmlAttribute this[int index]
    {
        get { return items[index]; }
        // ORIGINAL set { items[index] = value; }
       set { Append(item); }
    }

(Tested on HtmlAgilityPack 1.6.13)

**Comment by JonathanMagnan** [comment]
Hello @jpmnteiro ,

Thank you for reporting,

We will probably look at it this Friday.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @jpmnteiro ,

Sorry for the long delay. It seems this fix has been completed since the January 12 but I forget to release it. Oops!

The v1.6.15 is now released and should fix this issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by jpmnteiro** [comment]
@JonathanMagnan Just tested on v1.6.15, test case is now passing, thank you!
