### ISSUE TITLE
Cannot specify custom encoding for HtmlWeb instance

### ISSUE THREAD

**Issue by taoothereporter** [zzzprojects/html-agility-pack#136]
When I am trying to get HTML document with cyrilic charset using `HtmlWeb` instance with `OverrideEncoding` field specified with `Encoding.GetEncoding(1251)` I find that `OverrideEncoding` field value has no effect on the character encoding in resulting parsed `HtmlDocument` instance.

```c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

HtmlWeb cWeb = new HtmlWeb
{
       AutoDetectEncoding = false,
       OverrideEncoding = Encoding.GetEncoding(1251)
};

HtmlDocument cDoc = cWeb.Load("http://www.interfax.ru/world/595314");

Console.Write(cDoc.DocumentNode.OuterHtml); <--- A lot of invalid characters in output
```

Checking `cDoc.StreamEncoding` field value shows that it has a default encoding.

Described problem only occurs when I am using .NET Core SDK

**Comment by JonathanMagnan** [comment]
Hello @taoothereporter ,

Thank you for reporting, we will investigate to see if we missed a line with this framework.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @taoothereporter ,

The v1.6.16 has been released.

We fixed a case when the `Encoding` was not working in .NET Core

Let me know if your issue is now fixed.

Best Regards,

Jonathan

**Comment by taoothereporter** [comment]
Hello @JonathanMagnan ,

Just checked the issue! Thank you!
