### ISSUE TITLE
Difficult to understand organization of sources

### ISSUE THREAD

**Issue by vhatsura** [zzzprojects/html-agility-pack#137]
The organization of sources is very difficult to understand. Сan be this is simplified?
In the current organization is difficult to help project with development.

Why project need so many solution files? I believe TargetFrameworks can be used for the projects to reduce amount of projects for different platforms.
I can help with it, but I need explanation of current organization.

**Comment by JonathanMagnan** [comment]
Hello @vhatsura ,

All sources have been moved to a shared project to make it easier: https://github.com/zzzprojects/html-agility-pack/tree/master/src/HtmlAgilityPack.Shared

However, every solution have their own project to make it easier to deploy.

This repository need a lot of cleanups and we will for sure work on it soon but I believe it will be easier if that's done on our side. Unfortunately, only time is missing ;(

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @vhatsura ,

This issue will be closed since it has been answered

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
