### ISSUE TITLE
How to scrape a page which at the end of page load executes a script to build parts of the UI?

### ISSUE THREAD

**Issue by Legends** [zzzprojects/html-agility-pack#138]
How to scrape a page which at the end of page load executes a script to build parts of the UI?
The script is about 788,000 characters large.
The problem is I only get the directly rendered HTML part.

I've added a browserscript completed condition, but then the request never returns.

```
var web1 = new HtmlWeb();
web1.BrowserTimeout = TimeSpan.MaxValue;
var doc1 = web1.LoadFromBrowser(url, o =>
{
	var b = (WebBrowser)o;
	
	// WAIT until the dynamic text is set
	return !string.IsNullOrEmpty(b.Document.GetElementById("j-bp-banner").InnerText);
});
```

If it's not possible, is there another tool that can do it?
(.NET background)

**Comment by taoothereporter** [comment]
Hello, @Legends ,

The problem you described has been solved [here](https://stackoverflow.com/questions/11393075/running-scripts-in-htmlagilitypack)

**Comment by Legends** [comment]
As you can see in my question, I am using a webbrowser control, but it doesn't work.
I have downloaded Phantom.js and installed the NReco.PhantomJS wrapper, but it takes a way to long to get the markup back, it's always about 10 seconds!

 ```
static void Main(string[] args)
        {

            var p = new NReco.PhantomJS.PhantomJS();
            p.ErrorReceived += P_ErrorReceived;

            p.OutputReceived += (sender, e) =>
            {
                if (e != null && !string.IsNullOrWhiteSpace(e.Data))
                {
                    sc.WriteLine(e.Data);
                }

            };

            var sw = new Stopwatch();
            sw.Start();
            p.Run(@"C:/test.js", new string[] { url });

            sw.Stop();
            sc.WriteLine(sw.Elapsed.TotalSeconds);
            sc.ReadLine();
        }

        private static void P_ErrorReceived(object sender, System.Diagnostics.DataReceivedEventArgs e)
        {
            sc.WriteLine(e.Data);
        }
```

**Comment by JonathanMagnan** [comment]
Hello @Legends ,

Unfortunately, HAP is not the best tool to work with dynamic content.

Perhaps what you are looking only show when the page is scrolled (or another event) which explain why the LoadFromBrowser doesn't work the way you did it.

Do you think you could share the page you are tried? We will try to take a few minutes to look at it.

I'm not sure yet what's the best tools for doing this but perhaps you could try: http://www.seleniumhq.org/

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by Legends** [comment]
[Here is the url](https://www.aliexpress.com/item/White-Goose-Down-Coats-Women-2017-New-Women-s-Long-Down-Jacket-Female-Thickening-Outerwear-Large/32849151244.html?spm=2114.search0104.3.118.785c3ee80zU66k&ws_ab_test=searchweb0_0,searchweb201602_4_10320_10321_10065_10344_10068_10342_10547_10343_10322_10340_10548_10341_10193_10194_10084_10083_10618_10304_10615_10307_10302_10180_10313_10059_10184_10534_100031_10319_10103_441_10624_442_10623_10622_10186_10621_10620_10142,searchweb201603_32,ppcSwitch_7&algo_expid=c8b6eee0-9ed8-4f40-8a71-4843b1f05f3e-16&algo_pvid=c8b6eee0-9ed8-4f40-8a71-4843b1f05f3e&priceBeautifyAB=4)

And I check if this element exists:
`<li class="pt-amex"></li>`

It's dynamically loaded into this section:
`ul.payment-type-list`

So, this all works now with phantomjs, but it is unacceptably slow, not the parsing itself, but it takes 6-7sec to get the phantomjs process up and running.

**Comment by JonathanMagnan** [comment]
Thank you @Legends ,

We tried some stuff but unfortunately, it looks the payments never appears as we would have expected.

Dynamic content is not our best friend ;(

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by Legends** [comment]
If someone is interested in an easy solution:

It works with Phantomjs, but I find, that it goes quicker with Selenium.WebDriver + ChromDriver.
On Win10, with Chrome >= v60.x

**Just install:**

> Install-Package Selenium.WebDriver
> Install-Package Selenium.WebDriver.ChromeDriver

```
[TestMethod]
public void ChromeDriverTest()
{
var co = new ChromeOptions();
co.AddArgument("headless");
co.AcceptInsecureCertificates = true;
co.PageLoadStrategy = PageLoadStrategy.Normal;

using (var driver = new ChromeDriver(co))
{
	try
	{
		driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
		driver.Navigate().GoToUrl(noPaypalUrl);
		var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));

		wait.Until(wt => !string.IsNullOrWhiteSpace(wt.FindElement(By.CssSelector("ul.payment-type-list")).Text));

		var ul = driver.FindElementByCssSelector("li.pt-paypal");

		if (ul == null)
		{
			Debug.WriteLine(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><  no paypal  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
		}
		else
		{
			Debug.WriteLine(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  payyyyyyyyyyypaaaaaaaaaaaaaaaalll yeaaaah   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
		}

		driver.Close();
	}
	catch (Exception ex)
	{
		try
		{
			var screenshot = driver as ITakesScreenshot;
			var pic = screenshot.GetScreenshot();
			pic.SaveAsFile(@"C:/screenshot.png", ScreenshotImageFormat.Png);
		}
		catch (Exception ex2)
		{
			throw;
		}
	}
}
}
```

It throws a "`NoSuchElement`" exception on line:

`var ul = driver.FindElementByCssSelector("li.pt-paypal");`

Don't know if this the default behaviour, just raised an issue on Github.

**Comment by Legends** [comment]
Yes, it is default behavior, just checked with the [Selenium Team](https://github.com/SeleniumHQ/selenium/issues/5424)
