### ISSUE TITLE
Where can I download the source code for latest release 1.4.9.5

### ISSUE THREAD

**Issue by jonalbrecht** [zzzprojects/html-agility-pack#14]
Where can I download the source code for latest release 1.4.9.5?

**Comment by JonathanMagnan** [comment]
Hello @jonalbrecht ,

The latest release is currently 1.5.x which is currently under this GitHub.

If you want the 1.4.9.5 source, the easier way is simply downloading it from the CodePlex project: https://htmlagilitypack.codeplex.com/SourceControl/latest

The latest version here contains theses source.

Let me know if I answered correctly to your question.

Best Regards,

Jonathan

**Comment by jonalbrecht** [comment]
Thanks Jonathan. I believe that answers my question

**Comment by JonathanMagnan** [comment]
Closing comment: answered
