### ISSUE TITLE
any timeline to CSS Selector ?

### ISSUE THREAD

**Issue by zlzforever** [zzzprojects/html-agility-pack#141]
3q

**Comment by JonathanMagnan** [comment]
Hello @zlzforever ,

We don't have any timeline for this feature.

We recommend you to try using some third party library for HAP that already supports it:
- https://www.nuget.org/packages/HtmlAgilityPack.CssSelectors/
- https://www.nuget.org/packages/HtmlAgilityPack.CssSelectors.NetCore/

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by zlzforever** [comment]
Thank you very much.
