### ISSUE TITLE
MSBuild - target platform .net471

### ISSUE THREAD

**Issue by JBaltika** [zzzprojects/html-agility-pack#142]
Hi guys,
It's almost 4 month since MS released .NET4.7.1. It would good time to make build, nuget & project changes to build against that framework , not with help of all these binding redirects make it run net471 as many project cannot be converted to .dotnet core.
The .NET4.7.1 is good & solid framework release since 4.6.1. This would allow other dependent projects also create build with .NET4.7.1 .

**Comment by JonathanMagnan** [comment]
Hello @JBaltika ,

Thank you for reporting.

However, I'm not sure to understand the purpose.

Why do we need a new project that builds on that framework? I mean, a project under `.NET4.7.1` will use the `.NET45` version. So unless we add some specific feature for `.NET4.7.1`, I don't see any reason on our side to create a new project.

Perhaps I'm missing something.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JBaltika ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
