### ISSUE TITLE
Form submission with Html Agility Pack 

### ISSUE THREAD

**Issue by sohaibameen** [zzzprojects/html-agility-pack#143]
Hi, 

I have been using HTML agility pack to write a custom web scrapper. 

Few websites allow data scrapping and few requires user to login by using their account credentials to get somewhere in the website. 

I have been trying to submit form through agility but I am not anywhere near. 

I have to confirm if we can submit a form with the help of HAP or not? 

If we can then please put some demo or direct me towards an example. 

That would be a huge help. 

Best Regards, 
Sohaib

**Comment by JonathanMagnan** [comment]
Hello @sohaibameen ,

I know that's possible to do such thing but I have never done it on my side and I don't have any example.

I recommend you to try https://stackoverflow.com/questions/tagged/html-agility-pack and hope someone that knows how to do it answer.

Best Regards,

Jonathan
