### ISSUE TITLE
How to get current node's text

### ISSUE THREAD

**Issue by wddpct** [zzzprojects/html-agility-pack#146]
I found a property named 'InnerText', however, this property's value included all nodes' text belongs to current node.

`<span>span_text<label>label_text</label></span>`

how could I fetch the 'span_text'?

**Comment by JonathanMagnan** [comment]
Hello @wddpct ,

I don't think there is a function that does it.

One weird way is to simply make a substring when a '<' character is found.

Best Regards,

Jonathan

**Comment by wddpct** [comment]
Hah… The weired way can not solve my PM's requirements, but I have found some other methods. Thanks anyway.

Last, I think it is a urgent and actual requirement, hoping the next release may include the feature. Property named 'NodeText'
