### ISSUE TITLE
HtmlWeb LoadFromWebAsync not available in Android

### ISSUE THREAD

**Issue by rik1599** [zzzprojects/html-agility-pack#148]
Xamarin Forms for Android Oreo 8.0.
After the latest update (1.7.0) the method LoadFromWebAsync from HtmlWeb class seems it doesn't exist in Android, but it exist in UWP (I didn't try IOS). Resolved downgrading the library to 1.6.17 version.

**Comment by JonathanMagnan** [comment]
Hello @rik1599 ,

The v1.7.1 has been released.

Async method should now be back. Let me know if there are some other methods missed.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rik1599 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
