### ISSUE TITLE
Wrong-closed HTML comment

### ISSUE THREAD

**Issue by Oblomoff** [zzzprojects/html-agility-pack#150]
Hello!

This type of wrong-closed comment causes all after it is commented, but browsers handle this situation as correct comment ending.
```html
<!--title="Title"--!>
```

**Comment by JonathanMagnan** [comment]
Hello @Oblomoff ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Oblomoff ,

The v1.7.1 has been released.

This ending comment should be now supported.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Oblomoff ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
