### ISSUE TITLE
SelectSingleNode Method not visible

### ISSUE THREAD

**Issue by kiddsr** [zzzprojects/html-agility-pack#151]
In release 1.7.0, I noticed that I am unable to see the SelectSingleNode method on any Node. I'm using the .NetStandard Library 2.0 and in a Portable Class Library targeting .Net framework 4.5.

**Comment by zmjack** [comment]
As far as I know, **Standard Library 2.0** cann't run in **NET Framework 4.5**.

This library requires at least **NET Framework 4.6.1** or .**NET Core 2.0**.

You can search the information you need in [https://docs.microsoft.com/en-us/dotnet/standard/net-standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). The details are in section **.NET implementation support**.

**Comment by JonathanMagnan** [comment]
Hello @kiddsr ,

In addition to @zmjack  answer,

Unfortunately, `SelectSingleNode` is not available for portable class.

However, it should be available for a project targeting .NET Standard 2.0

Best Regards,

Jonathan
