### ISSUE TITLE
Problem with html_agility-pack

### ISSUE THREAD

**Issue by kgohar1350** [zzzprojects/html-agility-pack#152]
Hi, thanks for the great job. am using the package. but am getting some error as below.

in my HtmlAgilityPack.dll and HtmlAgilityPack.pdb files the following address is hard coded.
C:\Users\Jonathan\Desktop\Z\zzzproject\HtmlAgilityPack\HtmlAgilityPack\obj\Release\HtmlAgilityPack.pdb
saw the address when opened the .dll and .pdb files with a hex editor.

used both 1.7.0 and 1.6.17 version. the problem is much more serious in 1.7.0 version
Exception thrown when I was using LoadFromBrowser method from HtmlWeb object.

let mo know if I am missing something.

thanks

**Comment by zgabi** [comment]
I'm only a user of HtmlAgilityPack, but why it this a problem? I checked some popular nuget packages (AutoMapper, Moq, NHibernate, Postsharp), all of them contains the path for the pdb file, similar to this one.

**Comment by kgohar1350** [comment]
The problem is that this address is pointing to a location on the developers system (apparently Jonathan is a user account in that system) . and it is hard coded, therefore when it is trying to find the file on my system it can not find it and throws an exception.

**Comment by zgabi** [comment]
It is always pointing to a location on the developer system.  Usually it is not in the c:\Users folder, but on the developer system. Check any other dll.

**Comment by kgohar1350** [comment]
that is my point. a .dll file that is supposed to be used by many people on many computers is not supposed to have an address from the developer's system hard coded in it. I am hoping some one from development team see my posting and either fix the problem or let me know how to work around this issue. right now the specific function I am planning to use in this library is not working because of this issue.

**Comment by zgabi** [comment]
Write to the compiler team in Microsoft:)

If something is not working in HAP, it is not related to the pdb path "problem".

**Comment by zgabi** [comment]
What is the problem with the `LoadFromBrowser` method?

I tried the following:
`var x = new HtmlWeb().LoadFromBrowser(@"http://index.hu");`

it works fine.

Is there any exceptoion?

**Comment by kgohar1350** [comment]
the address "http://index.hu" is it a local address on your system?

I am trying to get at "http://www.google.com" and this is the exception i get

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation. ---> System.Threading.ThreadStateExc
eption: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instant
iated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, B
inder binder, Object[] parameters, CultureInfo culture)
   at HtmlAgilityPack.HtmlWeb.LoadFromBrowser(String url, Func`2 isBrowserScript
Completed) in C:\Users\Jonathan\Desktop\Z\zzzproject\HtmlAgilityPack\HtmlAgility
Pack.Shared\HtmlWeb.cs:line 2466
   at HtmlAgilityPack.HtmlWeb.LoadFromBrowser(String url) in C:\Users\Jonathan\D
esktop\Z\zzzproject\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlWeb.cs:line 2383
   at ConsoleApplication1.Program.ParseFromBrowser() in C:\Users\Administrator\D
ocuments\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Pro
gram.cs:line 26
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\Administrator\
Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Pr
ogram.cs:line 18

**Comment by zgabi** [comment]
http://index.hu is a public news portal, biggest in Hungary, people usually use that for trying the ping, too:)

The exception message is clear, you should use STA thread.

Is this a console application?
The simplest solution is to add a [STAThread] attribute to your main method:

```
        [STAThread]
        static void Main(string[] args)
        {
            var x = new HtmlWeb().LoadFromBrowser(@"http://www.google.com");
        }

```
Or you can create a new thread.

**Comment by kgohar1350** [comment]
it worked. thanks. so that is what i was missing. thanks a lot.

**Comment by kgohar1350** [comment]
the [STAThread] solved my problem. it appears that I need some more reading on this as i never came across this keyword. but anyway I still don't understand why having a problem on my system throws an exception with some address that does not exist on my system and probably is referring to a folder on developer's system. doesn't that mean that some address is hard coded in the .dll file and isn't that a mistake?
anyway thanks for the solution. you saved my day.

**Comment by JonathanMagnan** [comment]
Hello @kgohar1350 ,

And thank @zgabi for the support ;)

I believe you get fully answered so I will close this request.

Best Regards,

Jonathan
