### ISSUE TITLE
Wrong Node Selection

### ISSUE THREAD

**Issue by raupes** [zzzprojects/html-agility-pack#153]
In [HTMLNode.Xpath.cs](https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack/HtmlNode.Xpath.cs) in the Method SelectSingleNode is a bug. Because if you select a node collection from the original HTML document. Iterating through this nodes and try to subselect then with this method always the first occurance will be returned because the OwnerDocument is used for the XPath and not the subitem (the currently selected node).

**Comment by raupes** [comment]
Workaround: Create a new HTMLDocument from the node.InnerHtml and select in this document.
```
            var doc = new HtmlDocument();
            doc.LoadHtml(node.InnerHtml);
            var content = doc.DocumentNode.SelectSingleNode($"//*[@itemprop='{search}']")?.InnerText;
```

**Comment by JonathanMagnan** [comment]
Hello @raupes ,

I'm happy that you have found a workaround.

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by raupes** [comment]
Hi Jonathan,

here is a link to the project: [OneDrive Download Bug Demo](https://1drv.ms/u/s!Ak1b5xVMIM6SguIGeFinH1E2roCmGw) 

And here the Code you find in the zip file
```
        static void Main(string[] args)
        {
            Console.WriteLine("Demo app shows a bug on selecting sub items!");
            string content = System.IO.File.ReadAllText("DemoFile.html");
            var doc = new HtmlAgilityPack.HtmlDocument();
            doc.LoadHtml(content);

            // Load the li-nodes
            var nodeList = doc.DocumentNode.SelectNodes("//li");
            foreach(var node in nodeList) {
                // Subselect and element within this node. - and here we get the wrong result.
                string street = node.SelectSingleNode("//*[@itemprop='streetAddress']")?.InnerText;
                Console.WriteLine(street);
            }
            Console.ReadKey();
        }

```
And the demo html file

```
<a href="http://www.sales-suckers.com">Best Sales Tool ever</a>
<ul class="result-list">
    <li itemscope="company" itemtype="https://schema.org/LocalBusiness">
        <div class="result-content">
            <h2 class="card-heading pull-left" itemprop="name">First Name</h2>
            <div class="address" itemprop="address" itemscope="company" itemtype="https://schema.org/PostalAddress">
                <span itemprop="streetAddress">If you can read this twice it is a bug</span><br />
                <span itemprop="postalCode">1234</span>
                <span itemprop="addressLocality">Somewhere</span><br />
            </div>
        </div>
    </li>
    <li itemscope="company" itemtype="https://schema.org/LocalBusiness">
        <div class="result-content">
            <h2 class="card-heading pull-left" itemprop="name">Second Name</h2>
            <div class="address" itemprop="address" itemscope="company" itemtype="https://schema.org/PostalAddress">
                <span itemprop="streetAddress">If you can read this the bug is fixed</span><br />
                <span itemprop="postalCode">4711</span>
                <span itemprop="addressLocality">Somewhere in the woods</span><br />
            </div>
        </div>
    </li>
</ul>

```

Happy Fixing ;-)
Best Regards 
Bernhard

**Comment by JonathanMagnan** [comment]
Thank a lot @raupes ,

I will have my developer to look at it perhaps today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @raupes 

The problem is the `//` always search from the root.

However, you can use by example `/.` to start to search from the current node.

For example:
```csharp
var html = @"<ul><li>a</li></ul>";

var document = new HtmlAgilityPack.HtmlDocument();
document.LoadHtml(html);
var nodes = document.DocumentNode.SelectNodes("/ul").First();
var t = nodes.SelectNodes("./li");
var text = document.DocumentNode.InnerHtml;
```

You can also do it at once:
```csharp
var t =  doc.DocumentNode.SelectSingleNode("//li/span[@itemprop='streetAddress']")?.InnerText; 
```

Let me know if that answer to your issue.

Best Regards,

Jonathan

**Comment by raupes** [comment]
@JonathanMagnan thank you very much. Would mean that the only change needed to do is doing **./** instead of **//**. Doesn't work. (can be tested in demo code). Null is returned.

The thing is (see html in demo project): First the elements with attribute **Itemscope="company"** of the html structure are selected and then  (in a method - that why i don't do it at once) sub items (that arn't direct childs of the **li**. But occure somewhere in the sub element (not definitive known at which level or at which tag).
So it isn't a first level child of the node and would require a **//**. I expected that this should only select elements somewhere within the node. Am I wrong?

best regards!

**Comment by JonathanMagnan** [comment]
Hello @raupes ,

Sorry, I should have provided you the fix with your example instead of my own example.

The `.//` will select any element within the node.

Here is what I believe what you are looking for:

```csharp
Console.WriteLine("Demo app shows a bug on selecting sub items!");
string content = System.IO.File.ReadAllText("DemoFile.html");
var doc = new HtmlAgilityPack.HtmlDocument();
doc.LoadHtml(content);

// Load the li-nodes
var nodeList = doc.DocumentNode.SelectNodes("//li");
foreach(var node in nodeList) {
    // Subselect and element within this node. - and here we get the wrong result.
    string street = node.SelectSingleNode(".//*[@itemprop='streetAddress']")?.InnerText;
    Console.WriteLine(street);
}
```

Let me know if that's working fine.

Best Regards,

Jonathan

**Comment by raupes** [comment]
Hi @JonathanMagnan 
with `.//` it works well. Thank you very very much.
best regards
>Raupes
