### ISSUE TITLE
Process is terminated due to StackOverflowException

### ISSUE THREAD

**Issue by Lance-NS3** [zzzprojects/html-agility-pack#156]
I have exception with parsing this file: 
[html.txt](https://github.com/zzzprojects/html-agility-pack/files/1830282/html.txt)

You can reproduce it using this code:
``` c#
var html = File.ReadAllText("html.txt");
var document = new HtmlDocument();
document.LoadHtml(html ?? string.Empty);
```

Can you fix it?

**Comment by JonathanMagnan** [comment]
Hello @Lance-NS3 ,

Thank you for reporting,

We will look at this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Lance-NS3 ,

The v1.7.2 has been released.

Let me know if that fixed your issue.

Best Regards,

Jonathan

**Comment by Lance-NS3** [comment]
Thank you for this fix! I couldn't imagine you will do it so FAST, I appreciate it so much!
You are awesome 🙂

**Comment by JonathanMagnan** [comment]
Hello @Lance-NS3 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
