### ISSUE TITLE
Parsing attribute without quotes

### ISSUE THREAD

**Issue by arabcewicz** [zzzprojects/html-agility-pack#157]
Parsed attribute without any quotes has  `QuoteType` set to `AttributeValueQuote.DoubleQuote`, i.e.:
test:
```
            var html =
                "<html><body>" +
                "<div attr=value>" +
                "</div>" +
                "</body></html>";
            var htmlDoc = new HtmlDocument();
            htmlDoc.LoadHtml(html);
            htmlDoc.DocumentNode
                .SelectSingleNode("//body/div")
                .Attributes[0]
                .QuoteType.Should().NotBe(AttributeValueQuote.DoubleQuote);
```
fails. But unquoted attribute values are valid in HTML!
There should be a dedicated `AttributeValueQuote` to reflect this fact.

**Comment by JonathanMagnan** [comment]
Hello @arabcewicz ,

Yes, you are probably right and attribute without a quote is valid. But it also depends on the doctype.

To keep some backward compatibility, I do not think anything will be done about it as it doesn't seem to be a major issue for most scenarios. We probably prefer to keep it as this and work on some other improvement instead.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @arabcewicz ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by arabcewicz** [comment]
Thanks @JonathanMagnan for your responses. I understand your point of view.
Best,
Adam
