### ISSUE TITLE
Paragraph tag not closing correctly

### ISSUE THREAD

**Issue by FireFlame74** [zzzprojects/html-agility-pack#159]
Version 1.7.2

```
string html = @"https://www.somerandomwebsite.com;

HtmlWeb web = new HtmlWeb();

HtmlDocument htmlDoc = web.Load(html);

HtmlNode address = htmlDoc.DocumentNode.SelectSingleNode("//*[@id=\"result-list-container\"]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/p[1]");
```

Example output after parsing:
```
<h2 class="some-class">
    <a href="https://www.somerandomwebsite.com/" data-clickpos="name">
        <span itemprop="name">
            Some random text
        </span>
    </a>
</h2>
<p class="some-class">
    Some random text
    <p class="some-other-class">
        Some random text
    </p>
</p>
```
Expected output (original HTML):
```
<h2 class="some-class">
    <a href="https://www.somerandomwebsite.com/" data-clickpos="name">
        <span itemprop="name">
            Some random text
        </span>
    </a>
</h2>
<p class="some-class">
    Some random text
</p>
<p class="some-other-class">
    Some random text
</p>
<p></p>
```

As you can see it included the second `<p>` tag in the first one. Additionally it removed the empty `<p>` tag entirely.
I don't know if the removal of the empty tag is intentional and/or might be related to the issue #55.

**Comment by JonathanMagnan** [comment]
Hello @FireFlame74 ,

Could you provide me the original input, it will make easier for my developer to get started with the issue.

Best Regards,

Jonathan

**Comment by FireFlame74** [comment]
Have a look at the paste on [https://pastebin.com/mNFYqX8P](https://pastebin.com/mNFYqX8P).

The misbehavior from above occurs when accessing the DOM object with this XPath:
`"//*[@id="result-list-container"]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]"`

**Comment by JonathanMagnan** [comment]
Hello @FireFlame74 ,

Thank you for the text but I'm not sure to understand.

You first talked about an issue with the `p` tag but there is no `p` in the html provided.

Best Regards,

Jonathan

**Comment by FireFlame74** [comment]
There are several <p> tags in the HTML provided. Setting `HtmlDocument.DisableBehavaiorTagP` to `true` somehow fixes the problem I was having.
