### ISSUE TITLE
Load method doesn't work in Android using Xamarin Forms

### ISSUE THREAD

**Issue by eliams99** [zzzprojects/html-agility-pack#160]
I use HtmlDocument.Load(string path) method in a Xamarin Forms Project. It works in the UWP app, but in my Sony Xperia XZ1 (Android 8.0) causes an exception:
System.Reflection.TargetInvocationException: <Timeout exceeded getting exception details>

I use the HtmlAgilityPack 1.7.2 version, but I have this issue since the previous version.

**Comment by JonathanMagnan** [comment]
Hello @eliams99 ,

Thank you for contacting us.

Just to be sure, it was working before the version 1.7.x?

Best Regards,

Jonathan

**Comment by eliams99** [comment]
Hello,

No, if I remember well I started using HtmlAgilityPack on this progect two weeks ago. I think version 1.7.1.

Thanks,

Elia

**Comment by JonathanMagnan** [comment]
Hello @eliams99 ,

I have checked with my developer and unfortunately `Xamarin` is not on our supported list.

There is no plan to support it for now unless you can use .NET Standard 2.x

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
