### ISSUE TITLE
Latest HtmlAgility pack not loading my URL

### ISSUE THREAD

**Issue by abhishekvats** [zzzprojects/html-agility-pack#163]
![image](https://user-images.githubusercontent.com/5195111/38403715-4568a344-391a-11e8-8dc7-95491839efbd.png)

**Comment by abhishekvats** [comment]
https://chp.tbe.taleo.net/chp03/ats/servlet/Rss?org=DRAGADOS&cws=1&WebPage=SRCHR&WebVersion=0&_rss_version=2


Above is the Url that's not getting loaded.

**Comment by JonathanMagnan** [comment]
Hello @abhishekvats ,

Thank you for reporting, we will try to fix it for next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
