### ISSUE TITLE
HtmlAgilityPack 1.7.3 can no longer be used in the project

### ISSUE THREAD

**Issue by JustArchi** [zzzprojects/html-agility-pack#164]
Please refer to my **[CI output](https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/363561338#L891)**:

```
CSC : error CS1685: The predefined type 'ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'HtmlAgilityPack, Version=1.7.3.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' [/home/travis/build/JustArchi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
```

After **[reverting HAP back to 1.7.2](https://github.com/JustArchi/ArchiSteamFarm/commit/8e08c3266c91930d7adf8696653792f8773998d9)**, **[all is fine](https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/363562858#L894)**.

Very likely it's caused by specific configuration of my project, since other one does not suffer from this problem. I'm not sure if there is anything to fix on my side though, considering all versions up to 1.7.3 worked just fine, including 1.7.2.

Thank you in advance for looking into this.

**Comment by chrismsimpson** [comment]
Getting a similar error on vscode/dotnet 2.1.101. It seems like the warning is no longer being suppressed with the `#pragma` statement in **src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs**.

**Comment by JonathanMagnan** [comment]
Hello @JustArchi , @chrismsimpson 

Thank you for reporting, we will look at it later today and we will try to provide a fix.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JustArchi , @chrismsimpson ,

The v1.7.4 has been released.

Could you try it and let me know if everything is back to the normal?

Best Regards,

Jonathan

**Comment by JustArchi** [comment]
I can confirm that the issue is solved on my side, lots of thanks @JonathanMagnan and the entire team! ❤️
