### ISSUE TITLE
HtmlNode.OuterHtml.Length is incorrect

### ISSUE THREAD

**Issue by rfreas** [zzzprojects/html-agility-pack#167]
Related reference: [https://stackoverflow.com/questions/12861994/possible-to-get-htmlnodes-position-length-within-original-input?noredirect=1&lq=1](url)

It seems that `HtmlNode.OuterHtml.Length` is incorrect, but can be retrieved using reflection from the private variable `_outerlength`.  In my use case, I needed to know the true length of the outer HTML without the removal of line breaks that HAP was doing internally and therefore causing a discrepancy between the `HtmlNode.OuterHtml.Length` value and the true length as stored in the private `_outerlength` variable.

For now, we're going to use reflection to get the true value.  Perhaps the `_outerlength` variable should be exposed as public in the HtmlNode API?

**Comment by JonathanMagnan** [comment]
Hello @rfreas ,

I don't mind creating a public property for `OuterLength`, it should be part of the next release.

Best Regards,

Jonathan

**Comment by rfreas** [comment]
Excellent, I'll watch for it, thanks!

Rob

**Comment by JonathanMagnan** [comment]
Hello @rfreas ,

The v1.8.0 has been released.

It should now expose more properties as public.

Let me know if everything is working.

Best Regards,

Jonathan
