### ISSUE TITLE
Colon in Element Names Mangled With OptionOutputAsXml and DocumentNode.WriteTo()

### ISSUE THREAD

**Issue by GeorgDangl** [zzzprojects/html-agility-pack#168]
This issue is related to #95, where it was reported for attribute names.

I'm using HtmlAgilityPack for a library where I sanitize Xml documents from third parties. Its working great for me to fix Xml errors in the documents, but I've found one thing it doesn't handle correctly when `OptionOutputAsXml` is enabled: Element names with Xml namespace discriminators.

Here's a repro:

        [Fact]
        public void TransformToXmlWithNamespace()
        {
            var input = @"<RootElement xmlns:MyNamespace=""value"">
      <value:element />
    </RootElement>";
            var htmlDoc = new HtmlAgilityPack.HtmlDocument();
            htmlDoc.LoadHtml(input);
            htmlDoc.OptionOutputAsXml = true;
            htmlDoc.OptionOutputOriginalCase = true;
            var xmlDoc = htmlDoc.DocumentNode.WriteTo();

            var expected = @"<?xml version=""1.0"" encoding=""utf-8""?>" +
                           @"<RootElement xmlns:MyNamespace=""value"">
      <value:element />
    </RootElement>";

            Assert.Equal(expected, xmlDoc);
        }

The actual `xmlDoc ` is:

    <?xml version="1.0" encoding="utf-8"?>
    <RootElement xmlns:MyNamespace="value">
      <_value3a_element></_value3a_element>
    </RootElement>

It keeps the attribute `xmlns:MyNamespace` but sanitizes the `_value3a_element`.

That's because colons `:` are only valid characters for attribute names, not for elements, see [HtmlDocument.GetXmlName()](https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlDocument.cs#L318).

Would it be possible to allow colons also for elements? What's the reason it is disallowed? Maybe you could add an `OptionPreserveXmlNamespaces` to the `HtmlDocument` so the behavior can be controlled?

Can I just create a PR for this?

Thanks for the great library!

**Comment by JonathanMagnan** [comment]
Hello @GeorgDangl ,

Sure go ahead. If the default behavior is preserved and you add an option for this purpose, I have no problem.

Best Regards,

Jonathan

**Comment by GeorgDangl** [comment]
Done, @JonathanMagnan, see PR #169.

Any estimate on how long it would take to release a new NuGet package (if the PR is accepted)?

Looking forward to your feedback!

**Comment by JonathanMagnan** [comment]
Hello @GeorgDangl ,

My developer will look at it tomorrow.

So if the pull is accepted, the new version should be released Friday or on next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @GeorgDangl ,

Your pull has been released in the v1.8.0

Let me know if there is anything missing.

Best Regards,

Jonathan
