### ISSUE TITLE
Expose HTMLNode and HTMLAttribute exact position

### ISSUE THREAD

**Issue by ahitrov** [zzzprojects/html-agility-pack#170]
I'm using HTMLAgilityPack for parsing HTML files in an extension for Visual Studio that provides enhanced IntelliSense for HTML.

It works great when the HTML in the document is compacted - all white spaces between the attributes in a HtmlNode have length of 1 and there are no white spaces between HmtlNodes but it gets complicated in the other case.

Exposing ```_valuestartindex``` and ```_valuelength``` in ```HtmlAttribute``` and ```_innerstartindex```, ```_innerlength```, ```_outerstartindex```, ```_outerlength``` and ```_endnode``` in ```HtmlNode``` (e.g.: as readonly properties) will make my task considerably easier.

Can I just create a PR for this?

Thanks!

**Comment by JonathanMagnan** [comment]
Hello @ahitrov ,

Sure go ahead.

As long as your property is readonly (no setter), I have no problem to expose any kind of private/internal property. 

Best Regards,

Jonathan

**Comment by ahitrov** [comment]
Done, @JonathanMagnan, see PR #172 .

**Comment by JonathanMagnan** [comment]
Hello @ahitrov ,

Your pull has been released in the v1.8.0

Let me know if there is anything missing.

Best Regards,

Jonathan
