### ISSUE TITLE
Inconsistent behavior when invalid tag is present

### ISSUE THREAD

**Issue by arabcewicz** [zzzprojects/html-agility-pack#173]
Hello,
take a look at this test:
```
[Fact]
public void InvalidBrTag()
{
    var html =
        @"<html><body><br\>bar</body></html>";
    var htmlDoc = new HtmlDocument();
    htmlDoc.LoadHtml(html);

    var element = htmlDoc.DocumentNode
        .SelectSingleNode("//*[text()[contains(., 'bar')]]");
    element.Name.Should().Be(@"br\");
    var xpath = element.XPath;
    xpath.Should().Be(@"/html[1]/body[1]/br\[1]");

    Action action = () => htmlDoc.DocumentNode.SelectSingleNode(xpath);
    action.Should().Throw<XPathException>();
}
```
It passes. As you can see, searching by text placed after the invalid `<br\>` tag results in element that has  the `"/html[1]/body[1]/br\[1]` XPath.  On the other side, this xpath is not allowed to be used for searching.
I can see these options:
* interpret the `<br\>` as `<br/>` when parsing,
* do not interpret  `<br\>` as html node
* allow `br\`-like strings in XPath specification when selecting nodes.

I'm not an html/xpath expert, but I think the first is the best as the browser works like that (I believe).

**Comment by arabcewicz** [comment]
Hi @JonathanMagnan ,
I've just created the pull request.

The example of a "real" page with broken `<br\>`:
http://www.webscantest.com/crosstraining/search.php?q=foo

**Comment by JonathanMagnan** [comment]
Hello @arabcewicz ,

Unfortunately, browser interpret `br/` as a node so we have to do the same.

However, we coded a solution #4 (Adding a `ParseExecuting` event)

The v1.8.1 has been released.

You will be able to solve some weird HTML issue on your side

Example:

```csharp
var html1 = @"<html><body><br\>bar</body></html>";

var doc1 = new HtmlAgilityPack.HtmlDocument();
doc1.ParseExecuting = x => x.Text = x.Text.Replace(@"<br\>", "<br/>");

doc1.LoadHtml(html1);
```

Let me know if that solution works fine.

Best Regards,

Jonathan

**Comment by arabcewicz** [comment]
Hello @JonathanMagnan ,
yeap, your solution is ok for me, thanks a lot!
Best,
Adam

**Comment by JonathanMagnan** [comment]
Hello @arabcewicz ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan.
