### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by serdam55** [zzzprojects/html-agility-pack#181]
I just start to write a new application with Net Core 2.0 and I have this structure:

    ConsoleApp
    Library

the ConsoleApp import the Library reference that is a dll, and Library import `HtmlAgilityPack 1.8.0` that's actually the last version available.

When I run the ConsoleApp, I get this error:

> Unhandled exception of type 'System.IO.FileNotFoundException' in Library.dll Could not load file or assembly 'HtmlAgilityPack, Version=1.8.0.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a'. The specified file could not be found.

The file is available, as you can see in the image:

![hay0z](https://user-images.githubusercontent.com/30700983/39082528-d5adf832-4554-11e8-9ee2-b106fa1bdd0f.jpg)

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

I just tried the v1.8.0 from NuGet and everything works fine.

I believe your issue may be more related to some weird NuGet issue we get sometimes.

- Make sure you have the latest NuGet packages manager
- Close & re-open the solution may work sometime

There is not so much we can do on our side for this kind of issue since it's not related directly to the library.

Let me know if one of these solutions worked.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

We have released the v1.8.1.

Perhaps we had an issue on our side with a file assembly that we forgot to update the version.

Let me know if that's working with the newest version.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

Here is an example to get you started to get the first `a` tag for every li.

```csharp
var html1 = @"<div id='page_competition_1_block_competition_left_tree_2'> <div> <ul> <li> <a href=""#"" >foo</a><a href=""#"" >foo2</a> <ul> <li> <a href=""#"">foo2</a> </li> </ul> </li> <li> <a href=""#"" >foo3</a> </li></ul>";

var doc1 = new HtmlAgilityPack.HtmlDocument();
doc1.LoadHtml(html1);

var nodes = doc1.DocumentNode.SelectNodes("//div[@id='page_competition_1_block_competition_left_tree_2']/div/ul/li/a[1]").ToList();
```

Hope that helped ;)

Best Regards,

Jonathan

**Comment by serdam55** [comment]
@JonathanMagnan  

mm nope, sorry maybe I didn't explained well. Lets's take in consideration another div structure:

`
      <div class="redesign">
  <ul class="left-tree">
    <li class="expanded current odd">
      <a href="/national/italy/serie-a/c13/" class="" title="Serie A">Serie A</a>
      <ul class="level-1 expanded">
        <li class="leaf current">
          <a href="/national/italy/serie-a/20172018/s14181/">2017/2018</a>
        </li>
      </ul>
    </li>
    <li class="  even">
      <a href="/national/italy/serie-b/c14/" class="" title="Serie B">Serie B</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/serie-c1/c53/" class="" title="Serie C">Serie C</a>
    </li>
    <li class="  even">
      <a href="/national/italy/serie-d/c659/" class="" title="Serie D">Serie D</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/coppa-italia/c135/" class="" title="Coppa Italia">Coppa Italia</a>
    </li>
    <li class="  even">
      <a href="/national/italy/super-cup/c171/" class="" title="Super Cup">Super Cup</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/coppa-italia-serie-c/c684/" class="" title="Coppa Italia Serie C">Coppa Italia &hellip;</a>
    </li>
    <li class="  even">
      <a href="/national/italy/coppa-italia-serie-d/c1498/" class="" title="Coppa Italia Serie D">Coppa Italia &hellip;</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/campionato-nazionale-primavera/c952/" class="" title="Campionato Primavera 1">Campionato Pr&hellip;</a>
    </li>
    <li class="  even">
      <a href="/national/italy/campionato-primavera-2/c1600/" class="" title="Campionato Primavera 2">Campionato Pr&hellip;</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/coppa-italia-primavera/c1070/" class="" title="Coppa Italia Primavera">Coppa Italia &hellip;</a>
    </li>
    <li class="  even">
      <a href="/national/italy/super-coppa-primavera/c1171/" class="" title="Super Cup Primavera">Super Cup Pri&hellip;</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/dante-berretti/c1092/" class="" title="Dante Berretti">Dante Berretti</a>
    </li>
    <li class="  even">
      <a href="/national/italy/serie-a-women/c293/" class="" title="Serie A Women">Serie A Women</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/serie-a2/c457/" class="" title="Serie B Women">Serie B Women</a>
    </li>
    <li class="  even">
      <a href="/national/italy/coppa-italia-women/c852/" class="" title="Coppa Italia Women">Coppa Italia &hellip;</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/womens-play-offs-12/c1607/" class="" title="Women's Play-offs 1/2">Women's Play-&hellip;</a>
    </li>
    <li class="  even">
      <a href="/national/italy/serie-c2/c358/" class="" title="Lega Pro 2">Lega Pro 2</a>
    </li>
    <li class="  odd">
      <a href="/national/italy/super-cup-women/c851/" class="" title="Super Cup Women">Super Cup Women</a>
    </li>
    <li class=" even">
      <a href="/national/italy/club-friendlies/" class="">Club Friendlies</a>
    </li>
  </ul>  
</div>`

as you can see the first `<li>` tag have:

`<a href="/national/italy/serie-a/c13/" class="" title="Serie A">Serie A</a>
      <ul class="level-1 expanded">
        <li class="leaf current">
          <a href="/national/italy/serie-a/20172018/s14181/">2017/2018</a>
        </li>`

I need to get only the first `a` no the 2017/2018. With your code I also get both a tag. Thanks

**Comment by JonathanMagnan** [comment]
What about using the `ul` class name then?

```
var nodes = doc1.DocumentNode.SelectNodes("//ul[@class='left-tree']/li/a").ToList();
```

**Comment by serdam55** [comment]
@JonathanMagnan  well I also get 2018/2019 if I use this:

` HtmlNodeCollection compsLi = compsDiv.SelectNodes("div//ul[@class='left-tree']//li//a");`

**Comment by JonathanMagnan** [comment]
Of course you will get `2018/2019`,

Look at the number of slash between my string and you ;)

``//` has not the same behavior as  `/`. Using two slashes will check from the root instead of the current element.

```csharp
HtmlNodeCollection compsLi = compsDiv.SelectNodes("//ul[@class='left-tree']/li/a");
```

**Comment by serdam55** [comment]
@JonathanMagnan  you're indeed right! Thanks for the support. What's the difference against "/" and "//"? Are this things available in the documentation? I not able to find that, thanks again :)

**Comment by JonathanMagnan** [comment]
We are currently writing some `XPath` documentation. It will be available in around 2 months probably.

It may be not exact but it's something like this:

`/`: search for the current node
`//`: search from the root document node
