### ISSUE TITLE
Parsing error with Double quotes in Attribute Value (InnerHTML/OuterHTML)

### ISSUE THREAD

**Issue by MartinHenkeQP** [zzzprojects/html-agility-pack#182]
I assign HTML to a node (via innerHTML or OuterHTML) . The HTML contains a style attribute that contains a value with use double quotes, e.g. font-family:"Courier New".
Parsing fails, no matter if the double quotes are escaped or not.
The following code shows the error:
```
private static void TryWithDoubleQuotes()
        {
            HtmlDocument doc = new HtmlDocument();
            doc.LoadHtml("<html><head><title>Test</title></head><body><p>Hello, <span style=\"font-family:Arial;\">world!</span></p></body></html>");
            HtmlNode node = doc.DocumentNode.SelectSingleNode("//*/p");
            node.InnerHtml = "<span style=\"font-family:\\\"Courier New\\\";font-size:12.0pt;\">world!</span>";
            node = null;
            node = doc.DocumentNode.SelectSingleNode("//*/span");
            int count = node.Attributes.Count;
            if (count == 0)
            {
                Console.WriteLine("No attributes");
            }
            else if (count == 1)
            {
                Console.WriteLine("Attribute count is OK.");
            }
            else
            {
                Console.Write("Too many attributes: ");
                Console.WriteLine(count);
            }
        }
```

**Comment by JonathanMagnan** [comment]
Hello @MartinHenkeQP ,

Thank you for reporting,

I will have one of my developers to look at it this week.

Best Regards,

Jonathan

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation Libraries**
`Eval.Execute("x + y, new {x = 1, y = 2}"); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @MartinHenkeQP ,

One problem with your code is you try to set the font with the double quote inside a style that uses a double quote which is not valid either in the browser

```html
<span style="font-family:\"Courier New\";font-size:12.0pt;">world!</span>
```

You should instead use single quote:

```html
<span style="font-family:'Courier New';font-size:12.0pt;">world!</span>
```

Or in your code:
```csharp
node.InnerHtml = "<span style=\"font-family:'ourier New';font-size:12.0pt;\">world!</span>";
```

If I understand correctly the issue, there is nothing we can do as it work as expected and even the browser cannot interpret the HTML you provide correctly.

Let me know if that answer correctly to this issue.

Best Regards,

Jonathan

**Comment by MartinHenkeQP** [comment]
Dear Jonathan,

Thank you for your help. The case can be closed.
I solved the problem by replacing the quotes in the style with &quot;.

Best regards,

Martin Henke

**Comment by JonathanMagnan** [comment]
Great ;)

This issue will be closed since it has been resolved.

Best Regards,

Jonathan.
