### ISSUE TITLE
<textarea> tag has real html child nodes when it should not

### ISSUE THREAD

**Issue by sperlis** [zzzprojects/html-agility-pack#183]
Tested using version 1.8.1.
Also opened [https://stackoverflow.com/questions/49995303/html-agility-pack-avoid-parsing-nodes-within-textarea](url)
<textarea> tag should only have a single #text node as its child.
When loading html with the following example:
`<TEXTAREA>Text in the <div>hello</div>area</TEXTAREA>`
and then calling:
'HtmlNodeCollection divs = doc.DocumentNode.SelectNodes("//div");`
should yield and empty 'divs' collection. 

'HtmlNode ta = doc.DocumentNode.SelectSingleNode("//textarea");'
'ta' should have:
1. No child nodes except a single #text node
2. innerHTML should yield _Text in the &lt;div&gt;hello&lt;/div&gt;area_
3. innerText should either yield nothing (like most browsers) or _Text in the <div>hello</div>area_ (like IE)

Thanks in advance.

**Comment by JonathanMagnan** [comment]
Hello @sperlis ,

Thank you for reporting.

I will have my developer to look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @sperlis ,

The v1.8.3 has been released.

You should not have this issue anymore.

Best Regards,

Jonathan

**Comment by sperlis** [comment]
Problem is resolved.
Thank you for the quick fix!
