### ISSUE TITLE
How to get multiple tr by class?

### ISSUE THREAD

**Issue by serdam55** [zzzprojects/html-agility-pack#184]
Suppose I have a table which have tr with odd, even, total classes I want return only tr with odd and even classes, so I wrote this xpath expression, using HtmlAgilityPack:

`doc.DocumentNode.SelectNodes("//table//tr[contains(@class, 'odd | even')]");`

but this will return null, if instead I write:

`doc.DocumentNode.SelectNodes("//table//tr[contains(@class, 'odd')]");`

this will return all tr with odd class, what am I doing wrong?

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

You are currently checking for a class that's equal to `odd | even`.

From my understand, you are looking more for a `xpath` similar to:

```csharp
doc.DocumentNode.SelectNodes("//table/tr[contains(@class, 'odd')|contains(@class, 'even')]");
```

Note also there is only one `slash` for the `tr`

Let me know if that helped you.

Best Regards,

Jonathan

---

**Performance**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by serdam55** [comment]
Hi @JonathanMagnan  thanks for the fast answer, if I want skip the first tr should I write this:

```
 HtmlNodeCollection tr = doc.DocumentNode
                .SelectNodes("//table/tr[contains(@class, 'odd')|contains(@class, 'even')][position()>1]");
```
because this will return "expression must evaluate a node-set"

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

Could you send me a full example that my developer could try?

Best Regards,

Jonathan

**Comment by serdam55** [comment]
@JonathanMagnan for sure this is the html:

`<table class="popup-matches-table player"><tbody><tr class="subhead"><td colspan="4">&nbsp;</td><td class="eventicon"><img src="https://s1.swimg.net/gsmf/673/img/events/G.png" width="13" height="13" alt="Lineups" title="Goals"></td></tr><tr class="odd"><td class="date">11-05-13</td><td class="team-a "> <a href="/teams/germany/vfl-wolfsburg/968/">Wolfsburg</a></td>        <td class="score-time score"><a href="/matches/2013/05/11/germany/bundesliga/vfl-wolfsburg/bv-borussia-09-dortmund/1301063/">3 - 3</a></td><td class="team-b "> <a href="/teams/germany/bv-borussia-09-dortmund/964/">Borussia Dortmund</a></td><td class="points">2</td></tr><tr class="even"><td class="date">22-09-12</td><td class="team-a "> <a href="/teams/germany/hamburger-sv/967/">Hamburger SV</a></td>        <td class="score-time score"><a href="/matches/2012/09/22/germany/bundesliga/hamburger-sv/bv-borussia-09-dortmund/1300806/">3 - 2</a></td><td class="team-b "> <a href="/teams/germany/bv-borussia-09-dortmund/964/">Borussia Dortmund</a></td><td class="points">2</td></tr><tr class="total"><td colspan="4">&nbsp;</td><td>4</td></tr></tbody></table>`

thanks for the help

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

My bad, the `or` should be used instead of `|`.

Here is a working example with your XML:

```csharp
var nodes = doc.DocumentNode.SelectNodes("//table//tr[contains(@class, 'odd') or contains(@class, 'even')][position()>1]");
```

It will skip the first result.

But perhaps you want to skip the first `tr` since it may be the header so the final solution should look more like this:

```csharp
var nodes = doc.DocumentNode.SelectNodes("//table//tr[position()>1][contains(@class, 'odd') or contains(@class, 'even')]");
```

Best Regards,

Jonathan

**Comment by serdam55** [comment]
@JonathanMagnan no problem, I'm new on that task, thanks a lot for this amazing library and for your support :)
