### ISSUE TITLE
Multi-thread: no gain with paralellization

### ISSUE THREAD

**Issue by BenoitSa** [zzzprojects/html-agility-pack#191]
Hello,

I'm using HTMLAgilityPack in multi-thread where each thread is responsible for parsing pages from raw html. I compare:
- parsing 1000 pages with one thread
- parsing (a total of) 1000 pages with 8 threads (I've got 8 processors)

I takes roughly the same time even though the multi-thread version needs 2 to 3 times more CPU. 

This happens no matter what page I'm parsing and on machines with higher number of processors just the same.  This happens with Parallel.For as well as other ways of programming threads.

What is going on?

Code:
```
string url = "http://www.bfmtv.com/politique/melenchon-regrette-que-macron-soit-le-porte-parole-de-la-droite-1437284.html";
string html = new HtmlWeb().Load(url).DocumentNode.OuterHtml;
//One thread
for (int i = 0; i < 1000; i++)
   new HtmlDocument().LoadHtml(html);
//Several threads
Parallel.For(0, 1000, (int i) => new HtmlDocument().LoadHtml(html));
```

**Comment by JonathanMagnan** [comment]
Hello @BenoitSa ,

On my computer,

Single thread: Take around 14s
Multi-thread: take around 9.5s

This is slightly faster, but it was to be expected.

So it means, every thread takes around 9.5ms to run which is pretty fast. Using multi-thread come with a cost. So for a very short task like this one, using multi-threading may even be slower than single threading due to the cost of multi-threading.

I believe you will find plenty of article on this subject on Google.

Let me know if that answered correctly to your question.

Best Regards,

Jonathan

**Comment by BenoitSa** [comment]
Hello @JonathanMagnan 

Here are mine (core i7 2017 - Release mode - run without debugging):

Single thread: Take around 8s
Multi-thread: take around 8s
(with some slight variations up to 0.5 sec)

I understand what you say. I'm quite familiar with parallelization issues. Maybe it is caused by RAM rather than CPU, something like a bandwidth limit. This becomes more an more blatant as CPUs are faster.

You can consider my question as answered. Many thanks.

**Comment by JonathanMagnan** [comment]
Great :)

I believe it's more an issue about thread creation/dispose cost and thing related to threading.

Best Regards,

Jonathan

**Comment by camanchaca** [comment]
Simple test shows a problem with multithreading.
CPU has 4 cores.
The task is to execute LoadHtml 1000 times for monimal time with maximum CPU usage.
1 thread - it takes 8700ms. CPU usage 25% (one core). Fine
2 threads - 7100ms. CPU usage 39%.
3 threads - 7300ms. CPU usage ~40%. 
4 threads - 9100ms. CPU usage 45%.
Сonclusion - HAP doesn't love multithreading. 2 threads is best choise, but it takes more CPU (CPU per doc).
`var html = (new HttpClient()).GetStringAsync("https://ru.wikipedia.org/wiki/14_марта").Result;
            var threads = 4;
            var start = DateTime.Now;
            Parallel.For(0, threads, i =>
            {
                for (var x = 1; x <= 1000/threads; x++)
                {
                    HtmlDocument doc = new HtmlDocument();
                    doc.LoadHtml((string) html);
                }
            });
            Console.WriteLine("Done " + (DateTime.Now - start).TotalMilliseconds);
            Console.ReadLine();`

**Comment by BenoitSa** [comment]
The bottleneck can't realistically be RAM bandwidth since bandwidth is like 20 GB/s and this is huge compared to the quantity of RAM possibly used here: my page = 100 Kchars = 200 KB and even the objects related to it use 10x this amount, we get 200 MB/s with 100 pages/s. We are very far from the bandwidth. And this is a worst case estimation assuming the cache is useless. Even RAM latency does not seem to explain the phenomenon (as far as I understand it).

For the moment, the only possible explanation I see is some RAM unfriendly processing related to creating a tree. It might be about extremely non continuous RAM access or something with the C# memory manager and creating a lot of new objects (nodes, strings...). It sounds quite complicated to understand...

For info AngleSharp has exactly the same behaviour.

**Comment by camanchaca** [comment]
Profiler VS2015 for my examle shows a lot of blocking methods. So two+ threads works almost consecutively with resource conflicts, which couse higher CPU usage.
CPU has 16 cores, but program's usage is 15-20% maximum.

**Comment by BenoitSa** [comment]
Profiler VS2015 in multi-threads seems to indicate that one of the bottlenecks is memory allocation. Looking a the "Functions" I get:

[clr.dll] : 21%   (most of it is explicit calls to new)
string.SubString, string.ToLower, string.Concat: 23%    (actually they involve mainly mem allocation)
Dictionary.Set, Dictionary.Add, List.Add.... : 11%   (they involve allocation too)

Around 50% of the time could be spent in allocation. It is possible the CLR does a kind of lock when allocating resulting in higher CPU but no faster computation. 

Also if the RAM being allocated is interleaved between threads (which is very likely), the cache may be subject to frequent resetting: when one thread modifies the content of its own cache, this causes resets of the cache of the other CPUs: cache is made much less efficient and there is more CPU consumption.

Using objects pools could solve the problem for nodes. Sadly, it is more cumbersome with strings.
