### ISSUE TITLE
Could not load type 'HtmlNodeEnumerator' from assembly HtmlAgilityPack, Version=1.8.1.0

### ISSUE THREAD

**Issue by JeremyQtweb** [zzzprojects/html-agility-pack#193]
Hi guys,

Just upgraded from 1.3.0 to 1.8.1 finally and received this error right off the bat. I cannot find any information on it online so not sure how to proceed. Is this a bug or merely a deprecation issue which can be resolved via some kind of migration process?

Cheers,
Jeremy

**Comment by JonathanMagnan** [comment]
Hello @JeremyQtweb ,

I'm not the original owner of the library but this class has been removed before we take the ownership last year.

It was before inside this file: https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlNodeCollection.cs

Unfortunately, I don't think I will be able to help you more about it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JeremyQtweb** [comment]
No worries Jonathan I figured as much :)

Thanks for responding so quickly.
