### ISSUE TITLE
HAP fails to parse tag with space after opening bracket

### ISSUE THREAD

**Issue by JorgenLindell** [zzzprojects/html-agility-pack#194]
It seems like HAP fails to recognize
"
< table"
 as the start of a TABLE-tag.
Instead I get a #text element that starts with "\r\n< table"

I had to workaround this by parsing the document twice, first time modifying innerHtml of  text nodes regex-replacing "^\s*<\s+" with "<", then reparsing the corrected document.

Browsers are perfectly happy with a space there so I think HAP also should be.

Running 1.8.1 from nuget.

**Comment by JonathanMagnan** [comment]
Hello @JorgenLindell 

> Browsers are perfectly happy with a space there

I disagree here, most browser (if not all) will parse is as text.

The following HTML: `< table><tr><td>asa</td></tr></table>` will parse the `< table>` as a text field like HAP do.

The HTML will display the following output: `< table>asa`

I'm not sure which browser you use, but one we tried didn't supported the additional space.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JorgenLindell** [comment]
Hi,

You are right, sorry. I was convinced that fragment came from an actual working page. Obviously it wasn't. (Or it was, but that page was broken...)

Sorry for wasting your time.

brgds
Jörgen
