### ISSUE TITLE
inaccurate and inconsistent examples on the html-agility-pack.net home page

### ISSUE THREAD

**Issue by pjdennis** [zzzprojects/html-agility-pack#20]
The first example on the home page shows a wrong variable name: htmlDoc vs. html:

var htmlDoc = new HtmlDocument();
html.Load(filePath);

Also, there are inconsistencies in the use of 'var' vs. explicit type:

var htmlDoc = new HtmlDocument();
vs. 
HtmlWeb web = new HtmlWeb();

**Comment by JonathanMagnan** [comment]
Hello @pjdennis ,

You are right, almost every example was inconsistent.

We revised them all and fixed everything on the homepage. We will soon try to revise the documentation as well.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Homepage fixed
