### ISSUE TITLE
How to get only the text without tag?

### ISSUE THREAD

**Issue by serdam55** [zzzprojects/html-agility-pack#206]
I  have a div with this structure:

```
<div>
    <span class="minute">31'</span>
    <a href="/players/erjon-haki-xhafa/98132/">E. Xhafa</a> (OG)
</div>
```

I want get: (OG) content, so I did:
```

string text = tr.SelectSingleNode(".//div/text()")
  .InnerText.Trim().Replace("(", "").Replace(")", "");
```

this will return an empty string, why?

**Comment by JonathanMagnan** [comment]
Hello @serdam55 ,

That's caused because `text()` return an array. The first node is a `\r\n`.

Just execute the following code

```csharp
var node = tr.DocumentNode.SelectNodes(".//div/text()").Select(x => x.InnerText).ToList();
```

And you will find out your next as the last item in the array.

Let me know if that answered correctly to your question.

Best Regards,

Jonathan
