### ISSUE TITLE
Struggling to get started, reading an html file vis SSIS C#

### ISSUE THREAD

**Issue by Ismailc001** [zzzprojects/html-agility-pack#21]
Good day, I urgently need help on HAP

I have html files and via ssis using c# i would like to write the values to a database.
i installed the:

1. nutmeg 
2. Install-Package HtmlAgilityPack -Version 1.4.9.5 
3. in c# script i added reference to the "\packages\HtmlAgilityPack.1.4.9.5\lib\Net40\HtmlAgilityPack.dll"

```csharp
using System;
using System.Data;
using Microsoft.SqlServer.Dts.Runtime;
using System.Windows.Forms;
using System.Windows;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;       // HttpWebRequest
using System.IO;        // Stream
using HtmlAgilityPack;  // Html parse
using System.Text;      // Encoding
using System.Xml;
using System.Xml.XPath;
using System.Xml.Xsl;
namespace ST_43f237fb54624596ad8d1aacf94e650c
{ Microsoft.SqlServer.Dts.Tasks.ScriptTask.VSTARTScriptObjectModelBase
	{
             var doc = new HtmlAgilityPack.HtmlDocument();
        }
}
```

It keeps on failing on the first and only line, no errors in the script as it allows me to select the htmldocument etc but in ssis i cant see the error.

Anybody please help, any ideas as i have been struggling for days to get past this 1 line and im running out of time.

Thank You

**Comment by JonathanMagnan** [comment]
Hello @Ismailc001 ,

Have you copied the HtmlAgilityPack dll in the NET40 directory?
`C:\Windows\Microsoft.NET\Framework\v4.0.30319\`

There is some basic getting started blog about SSIS && Html Agility Pack like this one:
- https://jamessummerlin.com/tag/htmlagilitypack/

Let me know if that helped you.

Best Regards,

Jonathan

**Comment by Ismailc001** [comment]
Hi,

Thank you very much for assisting ☺

I manage to get the script to work with PowerShell

add-type -Path 'C:\Software\HtmlAgilityPack.1.4.9.5\lib\Net40\HtmlAgilityPack.dll'
$filename = 'c:\temp\test.html'
$HTMLDocument = New-Object HtmlAgilityPack.HtmlDocument
$wc = New-Object System.Net.WebClient
$result = $HTMLDocument.LoadHTML($wc.DownloadString($filename))
$HTMLDocument.DocumentNode.SelectSingleNode("(//table)[2]").InnerText

C# via SSIS no luck. I really prefer C# in SSIS as I have more control with variables etc…
Please Help

[cid:image003.jpg@01D2E9D2.5F5A67D0]

[cid:image005.jpg@01D2E9D2.5F5A67D0]

[cid:image009.jpg@01D2E9D2.5F5A67D0]

**Comment by JonathanMagnan** [comment]
Hello @Ismailc001 ,

Sorry to ask again, but have you done this step:

> Since we are using SSIS on SQL Server 2014, copy the files in the .Net40 directory to the C:\Windows\Microsoft.NET\Framework\v4.0.30319\ directory of the server that will be running your SSIS packages

If the SSIS fail on the first line, it's probably because it cannot find the assembly reference.

**Comment by Ismailc001** [comment]
Hi,
I tried but still no luck, I am going to continue using Powershell.
Can you assist me perhaps on how I go about capturing e columns and values on the attached.

Regards

**Comment by JonathanMagnan** [comment]
Closing Comment: Feel free to re-open if you need more support from our part.

**Comment by chjquest** [comment]
I am having the same issue in the very beginning (add reference manually and copy the dll file to almost everywhere). Looks like copying file and add reference won't work. 

The solution is to install HtmlAgilityPack by run the command - Install-Package HtmlAgilityPack -Version 1.8.0
inside Script Task (Through Tools -> Nuget Package Manager, inside SSIS, my version is VS2015 Prof.)
