### ISSUE TITLE
Can not validate p tag is closed certainly.

### ISSUE THREAD

**Issue by Aldin-Xia** [zzzprojects/html-agility-pack#210]
Hi, @JonathanMagnan 
Here is an issue with me that cased when I use HAP:
HAP 1.8.4
```c#
request.CustomCode = "<div>root div 1<div>child div<p> 1-1</div></div><div>root div 2</div>";
var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(request.CustomCode);
HtmlDocument.DisableBehavaiorTagP = true;
var htmlNodes = htmlDoc.DocumentNode.Descendants().Where(s => s.NodeType == HtmlNodeType.Element);
foreach (var node in htmlNodes)
{
    if (!node.Closed)
    {
        // do something
        break;
    }
}
```
Look at the `if (!node.Closed)` block, when node is "p", expected that is `Closed == false`, but `true`. The p tag does not closed explicitly in the original html partial.

When I print the `node.InnerHtml`, the value is `root div 1<div>child div<p> 1-1</div>`.

So, that makes me confused.

THANKS

**Comment by JonathanMagnan** [comment]
Hello @Aldin-Xia ,

Thank you for reporting, we will look at it as soon as we can (We are currently at the end of a big development)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Aldin-Xia** [comment]
Thank you for replying  to me  during your busy schedule. @JonathanMagnan 
I'll trying to solve it with other method. If I have any effective way, I will be happy share it.

Best Regards
