### ISSUE TITLE
LoadFromBrowser doesn't exists 

### ISSUE THREAD

**Issue by douglasoliveirabh** [zzzprojects/html-agility-pack#212]
I see an example of load html document from browser, but when i tried to use, i see that method LoadFromBrowser doesn't exists.

I'm using .net standard 2.0

Where can i find this method ?
This method was changed ?

**Comment by JonathanMagnan** [comment]
Hello @douglasoliveirabh ,

This method doesn't exist in .NET Standard 2.0 since it doesn't contain a `WebBrowser` as the `NET Framework` does.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @douglasoliveirabh ,

Unless you use a web browser compatible with .NET Core, we can do nothing on our side.

I suggest you to try something like Selenium: https://www.nuget.org/packages/Selenium.WebDriver/

Best Regards,

Jonathan

**Comment by douglasoliveirabh** [comment]
Ok. 

Thanks.
