### ISSUE TITLE
Using LoadFromBrowser to get HTML generated by JS

### ISSUE THREAD

**Issue by Fractally** [zzzprojects/html-agility-pack#219]
Hey guys,

I have been able to use HTMLAgilityPack successfully for a few sites (thanks!), but I am struggling getting the html of the table generated on this site: https://www.sanctionsmap.eu/#/main

It seems as if my code is not waiting long enough for the JS to execute. I am using this official example as base: http://html-agility-pack.net/from-browser

`webBrowser.Document.GetElementsById()` 

Are there any other ways of waiting for the JS to complete? If you look at the source on the provided site, you will notice that there aren't really any IDs used in the HTML that I can reference. 

Not sure what the recommended approach is when waiting for JS to execute. Any tips?

**Comment by JonathanMagnan** [comment]
Hello @Fractally ,

We tried this webpage but unfortunately, it looks the JavaScript is never updated or modified in a way that our library cannot currently read it.

I recommend you to try https://stackoverflow.com/questions/tagged/html-agility-pack

Perhaps someone else will have an answer how to do it.

An alternative way is to get the HTML from a web browser such as [Selenium](https://www.seleniumhq.org/)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Fractally** [comment]
Thanks for checking, I'll close the issue.
