### ISSUE TITLE
How to get the data which by js load

### ISSUE THREAD

**Issue by heyixiaoran** [zzzprojects/html-agility-pack#221]
I want to get the data from http://zhishu.31.zqsos.com:896/scoreOdds.aspx.
But the score data is load by js. Document can not get the part .
How can I get the score part data?

**Comment by raiytu4** [comment]
did you figure it out?

**Comment by heyixiaoran** [comment]
```
var htmlWeb = new HtmlWeb(); 

var html = htmlWeb.LoadFromBrowser(UrlText); 

htmlWeb.BrowserDelay = TimeSpan.FromSeconds(20); 

htmlWeb.BrowserTimeout = TimeSpan.Zero;
```

I user this code get the html. I set the 'BrowserTimeout '  property to Zero.  Before I set 20s . So now I can get the score part . tks.
