### ISSUE TITLE
Bug in HtmlNode.Descendants(int value) ?

### ISSUE THREAD

**Issue by andrei-kotau-epam** [zzzprojects/html-agility-pack#224]
HtmlAgilityPack version: 1.8.5.0
Here is my simple html:
```
<html>
    <head>
    <title></title>
    </head>
    <body>
    <p class="descendants">
	  <div id="desc-1"> textA
	    <div>textB</div>
	  </div>
      <span id="desc-2">
        <span id="desc-3">textC</span>
      </span>
    </p>
    </body>
</html>
```

And here is a code:
```
        var html = File.ReadAllText(@"d:\Downloads\xx.txt"); // xx.txt contains html above
        var doc = new HtmlAgilityPack.HtmlDocument();
        doc.LoadHtml(html);

        var pTag = doc.DocumentNode.SelectNodes("//p[@class='descendants']").First();
        Console.WriteLine(string.Join("\n", pTag.Descendants(0)
            .Select(x => $"{x.Name} {x.Id} {(x as HtmlTextNode)?.Text}")));
```

Console output:
```
#text

div desc-1
#text   textA

div
#text  textB
#text

#text

span desc-2
#text

span desc-3
#text  textC
#text

#text
```

Question/Issue:
If I change `pTag.Descendants(0)` to `pTag.Descendants(2)` or to `pTag.Descendants(999)` or to `pTag.Descendants(-4)` or to any other int value - output remains same. According to [documentation](http://html-agility-pack.net/descendants) I expect different output depending on depths value. Please help me find out is it a bug or I am doing something wrong?

**Comment by JonathanMagnan** [comment]
Hello @andrei-kotau-epam ,

Looking at the code, it doesn't work this way

```csharp
        /// <summary>
        /// Gets all Descendant nodes in enumerated list
        /// </summary>
        /// <returns></returns>
        public IEnumerable<HtmlNode> Descendants(int level)
        {
            if (level > HtmlDocument.MaxDepthLevel)
            {
                throw new ArgumentException(HtmlNode.DepthLevelExceptionMessage);
            }

            foreach (HtmlNode node in ChildNodes)
            {
                yield return node;

                foreach (HtmlNode descendant in node.Descendants(level + 1))
                {
                    yield return descendant;
                }
            }
        }
```

It takes all descendant and takes childs by incrementing the level by one until no more descendant or the max level is reached (int.MaxValue).

However, I agree with you, it should probably return descendant until the specified level is reached.

Unfortunately, for backward compatibility, we will probably do nothing on this method for not affecting current applications.

If you need a method like this, something we could probably do is adding a new method `DescendantsUntil(int)` or something with a better name that will work as you would have expected. 

Let me know if you need such method.

Best Regards,

Jonathan

**Comment by andrei-kotau-epam** [comment]
Thank you Jonathan for the answer.
Nope, I don't need such method as I can leave without it :). 
I was just wondering why `Descendants` behaves like this. And now, I have no questions.

**Comment by JonathanMagnan** [comment]
Great ;)

So I will close this request.

Best Regards,

Jonathan
