### ISSUE TITLE
A-tag in A-tag : only one parse error (expected 2)

### ISSUE THREAD

**Issue by Styxxy** [zzzprojects/html-agility-pack#227]
Given the HTML below; there is an A-tag defined inside another A-tag.
This is invalid HTML (you can also check on https://validator.w3.org/).

With the latest version, it correctly shows that there is a "stray end tag", but I would also expect to see the error "Start tag a seen but an element of the same type was already open.".

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Hello world</title>
</head>

<body>
  <p>
    <a href="hello"><a href="world">Hello world</a></a>
  </p>
</body>

</html>
```

Test code:

```cs
using System;
using System.Linq;
using HtmlAgilityPack;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Test.HtmlAgility
{
    [TestClass]
    public class HtmlDocumentTest
    {
        [TestMethod]
        public void InvalidHtml_AnchorInAnchor_ShouldHaveTwoParseErrors()
        {
            // Arrange
            var html = @"<!DOCTYPE html>
<html lang=""en"">

<head>
  <meta charset=""utf-8"">
  <title>Hello world</title>
</head>

<body>
  <p>
    <a href=""hello""><a href=""world"">Hello world</a></a>
  </p>
</body>

</html>";

            //Console.WriteLine(html);

            // Act
            var htmlDoc = new HtmlDocument();
            htmlDoc.LoadHtml(html);

            // Assert

            // Expected two errors (as per https://validator.w3.org/)
            // 1. Start tag a seen but an element of the same type was already open.
            // 2. Stray end tag a.

            Assert.AreEqual(2, htmlDoc.ParseErrors.Count());
        }
    }
}
```

**Comment by JonathanMagnan** [comment]
Hello @Styxxy ,

If you are looking for a library that will show all errors, I would not recommend you `HAP`.

There is so much `HTML` rule that's currently not supported in this library.

It will be eventually `HTML5` compatible in the future but there is no short-term plan for this as we currently concentrate all our effort on a new prime library.

It could probably be fixed very easily but then you will find something else again and again since this library is missing a lot of those validations.

Let me know if that explains correctly the current situation.

Best Regards,

Jonathan

**Comment by Styxxy** [comment]
@JonathanMagnan Thank you for the explanation. Indeed there will always be a rule that is not parsed "correctly". If you know a good html validator for .NET, you can always let me know :-).

**Comment by JonathanMagnan** [comment]
Pretty much the only solid alternative is `AngleSharp` and unless I'm wrong, I don't think they have this features ;(

So until we start to code the v2.x, I would not recommend you a C# library. Perhaps you might find something better in some other language.

**Comment by JonathanMagnan** [comment]
Hello @Styxxy ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
