### ISSUE TITLE
IOException on load html

### ISSUE THREAD

**Issue by mikhail-khalizev** [zzzprojects/html-agility-pack#228]
Example:

var web = new HtmlWeb();
web.CachePath = Path.Combine(Directory.GetCurrentDirectory(), "web-cache");
web.UsingCache = true;
web.UsingCacheIfExists = true;

var url = "https://www.felixcloutier.com/x86/CBW:CWDE:CDQE.html";
var htmlDocument = web.Load(url);

In the last line exception generated:
`
System.IO.IOException: 'The filename, directory name, or volume label syntax is incorrect : '<...>\bin\Debug\netcoreapp2.1\web-cache\www.felixcloutier.com\x86\CBW:CWDE:CDQE.html''
`

**Comment by JonathanMagnan** [comment]
Hello @micky53 ,

Thank you for reporting,

We will look at it and escape illegal character from the file name.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @micky53 ,

The v1.8.6 has been released.

The file name should now be correctly escaped.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by micky53** [comment]
Hello!
All works fine!
