### ISSUE TITLE
DocumentNode.SelectNodes returns null

### ISSUE THREAD

**Issue by poma** [zzzprojects/html-agility-pack#23]
DocumentNode.SelectNodes returns null instead of empty collection when it doesn't find any nodes.

What is the current state on this issue? Did it end up as "won't fix"?

Currently the best workaround is this extension method but it's easy to forget to put it everywhere
```
public static IEnumerable<T> NullGuard<T>(this IEnumerable<T> collection)
{
	return collection ?? new T[0];
}
```

[original discussion](https://htmlagilitypack.codeplex.com/workitem/29175)

**Comment by JonathanMagnan** [comment]
Hello @poma ,

Unfortunately, we currently don't have the time to dig in the old issue tracker. We currently only fix problems that is reported in this new issue tracker.

We will try to add a global options to fix this issue.

Unfortunately, we cannot change the default behavior since some people have now code that depends on this null value returned. However, we can an option that if enabled, return an empty collection instead of null.

This issue should be completed by the start of next week.

Best Regards,

Jonathan

**Comment by poma** [comment]
Thanks! I think adding it as a global option it the best choice.

Most issues in the old tracker are ancient anyway but it may worth to look at [top 10 most voted ones](https://htmlagilitypack.codeplex.com/workitem/list/basic?field=Votes&direction=Descending&issuesToDisplay=Open)

**Comment by JonathanMagnan** [comment]
Yup, this is what I have already done even if I have said we didn't support the old Issue Tracker ;)

We are currently working on [CSS Selector Query Engine](https://htmlagilitypack.codeplex.com/workitem/28970) 

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @poma ,

We added a new option for the `HtmlDocument.OptionEmptyCollection` which return an empty collection instead of null when SelectNodes return nothing.

Let me know if this new option is working correctly for you.

Best Regards,

Jonathan

**Comment by poma** [comment]
Yep works perfectly

**Comment by andras-ferencz** [comment]
While I understand changing the behavior would end up breaking a ton of old projects that check for null instead of empty, it still fills me with rage that this wasn't the default behavior in the first place seeing as this is how C# collection objects are _supposed to work_ by _default_.

**Comment by JonathanMagnan** [comment]
I understand your frustration.

Just to let you known, I'm not the original author of the library, just the one who support it ;)

We will for sure redo this library in the future and make sure this becomes the default behavior.

Best Regards,

Jonathan
