### ISSUE TITLE
HtmlNodeCollection.FindFirst finds <br> elements when searching for "b"

### ISSUE THREAD

**Issue by kimsey0** [zzzprojects/html-agility-pack#233]
The `FindFirst` method on `HtmlNodeCollection` [searches for nodes](https://github.com/zzzprojects/html-agility-pack/blob/4bb622f3936c0b3724f3ea5553e3713709c86301/src/HtmlAgilityPack/HtmlNodeCollection.cs#L279) where the node name `Contains` the name that was searched for. This means that `FindFirst` will match `<br>` nodes when searching for nodes with name `b`.

The indexer [behaves differently](https://github.com/zzzprojects/html-agility-pack/blob/4bb622f3936c0b3724f3ea5553e3713709c86301/src/HtmlAgilityPack/HtmlNodeCollection.cs#L68) and returns the first node where the node name `Equals` the name that was searched for.

**Comment by JonathanMagnan** [comment]
Hello @kimsey0 ,

Thank you for reporting, the issue has been fixed and should be released tomorrow.

Best Regards,

Jonathan

**Comment by kimsey0** [comment]
Thanks! I can't find a commit with the code yet, but I'm looking forward to being able to use FindFirst.

**Comment by JonathanMagnan** [comment]
`GitHub` is not the real source repository (We are on TFS online),

We normally push change on GitHub at the same time we release (sometime every x release when we are busy).

That's why you don't see it yet.

**Comment by kimsey0** [comment]
Ah, I see. That one is not public, is it?

**Comment by JonathanMagnan** [comment]
Hello @kimsey0 ,

The v1.8.7 has been released with this fix.

The source has also been updated

Let me know if everything is working as expected

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kimsey0 ,

The first one is no longer used. All projects now use the should from the `HtmlAgilityPack.Shared`

I have added a task to cleanup correctly this repository correctly to remove this kind of confusion.

**Comment by kimsey0** [comment]
OK. Thank you! FindFirst seems to work as expected in the new version on NuGet.
