### ISSUE TITLE
NuGet Package : Add `repository` metadata. 

### ISSUE THREAD

**Issue by MaximRouiller** [zzzprojects/html-agility-pack#234]
Basically, we can now add a repository metadata on a nuspec file to allow the repository to be surfaced on NuGet. This allows you to have a `projectUrl` as well a repository URL now.

I've talked about it [on Twitter](https://twitter.com/MaximRouiller/status/1030468873945075712) but the most basic things to know is here:

[NuSpec Reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=social-github-marouill#repository)

Reference Implementation in Json .NET
![image](https://user-images.githubusercontent.com/209384/44277447-b1c20f00-a218-11e8-9406-4f1f05879d47.png)

**Comment by JonathanMagnan** [comment]
Hello @MaximRouiller ,

Thank you for letting us known. We will add it on the next release.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MaximRouiller ,

The v1.8.7 has been released.

The `Source Code` url now appears as expected.

Thank you for letting us known.

Best Regards,

Jonathan
