### ISSUE TITLE
How to disable auto correction in OuterHTML when doing some changes in the node

### ISSUE THREAD

**Issue by rgalapate** [zzzprojects/html-agility-pack#235]
I'm very new to HTML Agility Pack.

I only tried changing some attributes inside the nodes which contains `i18n` attributes and replace them with translation attribute instead.

When I tried to get the outerHTML of the document, the attributes have changed as expected but there are some changes that html agility pack auto corrected.

Is there a way to disable the auto correction?

Here is my code snippet:

    HtmlAgilityPack.HtmlDocument doc = new HtmlAgilityPack.HtmlDocument();
    doc.Load(file);            
    
    HtmlNodeCollection i18nNodes = doc.DocumentNode.SelectNodes("//*[@i18n]");
    
    if (i18nNodes != null)
    {
    	foreach (HtmlNode node in i18nNodes)
    	{
    		node.Attributes.Add("translation", node.Attributes["i18n"].Value);
    		node.Attributes.Remove("i18n");		
    	}
    }
    
    // Do export the changed html to new html file
    // doc.DocumentNode.OuterHtml

Here are the before and after changes:

before:

    <ng-container *ngIf="!settingsLoaded">
    	<section class="container" id="main-loading">
    		<div class="logo">
    			<img src="assets/img/LogoKatapult-01.png" alt="Katapul Logo">
    		</div>
    		<div>
    			<div class="mx-1 my-2">
    				<mat-progress-bar mode="determinate" [value]="settingsProgress"></mat-progress-bar>
    			</div>
    			<div class="my-2 alert alert-danger" *ngIf="settingsError">
    				{{settingsError}}
    			</div>
    			<div class="text-center">
    				Loading...
    			</div>
    		</div>
    	</section>
    </ng-container>
    <ng-container *ngIf="settingsLoaded">
    	<app-header [(navigationState)]="navigationState" *ngIf="(authService.isAuthenticated() | async) === true && isNavigationVisible()"></app-header>
    	<mat-sidenav-container>
    		<mat-sidenav  mode="side" [opened]="(authService.isAuthenticated() | async) === true && isNavigationVisible()">
    			<nav class="side-navigation" role="navigation" [class.visible]="navigationState">
    				<ul class="nav flex-column">
    					<li class="nav-item" hidden>
    						<a class="nav-link" routerLink="/alliance" routerLinkActive="active">
    							<i class="nav-icon material-icons">people</i>
    							<span class="nav-text" i18n="@@menu.alliance">
    								Alliance
    							</span>
    						</a>
    					</li>
    				</ul>
    			</nav>
    		</mat-sidenav>
    		<mat-sidenav-content id="content-wrapper" [ngClass]="{'anonymous': !(authService.isAuthenticated() | async) || !isNavigationVisible()}">
    			<router-outlet></router-outlet>
    		</mat-sidenav-content>
    	</mat-sidenav-container>
    </ng-container>

after:

    <ng-container *ngif="!settingsLoaded">
    	<section class="container" id="main-loading">
    		<div class="logo">
    			<img src="assets/img/LogoKatapult-01.png" alt="Katapul Logo">
    		</div>
    		<div>
    			<div class="mx-1 my-2">
    				<mat-progress-bar mode="determinate" [value]="settingsProgress"></mat-progress-bar>
    			</div>
    			<div class="my-2 alert alert-danger" *ngif="settingsError">
    				{{settingsError}}
    			</div>
    			<div class="text-center">
    				Loading...
    			</div>
    		</div>
    	</section>
    </ng-container>
    <ng-container *ngif="settingsLoaded">
    	<app-header [(navigationstate)]="navigationState" *ngif="(authService.isAuthenticated() | async) === true && isNavigationVisible()"></app-header>
    	<mat-sidenav-container>
    		<mat-sidenav mode="side" [opened]="(authService.isAuthenticated() | async) === true && isNavigationVisible()">
    			<nav class="side-navigation" role="navigation" [class.visible]="navigationState">
    				<ul class="nav flex-column">
    					<li class="nav-item" hidden="">
    						<a class="nav-link" routerlink="/alliance" routerlinkactive="active">
    							<i class="nav-icon material-icons">people</i>
    							<span class="nav-text" translation="new_id">
    								Alliance
    							</span>
    						</a>
    					</li>
    				</ul>
    			</nav>
    		</mat-sidenav>
    		<mat-sidenav-content id="content-wrapper" [ngclass]="{'anonymous': !(authService.isAuthenticated() | async) || !isNavigationVisible()}">
    			<router-outlet></router-outlet>
    		</mat-sidenav-content>
    	</mat-sidenav-container>
    </ng-container>

To enumerate the auto corrections made:

 1. The ngIf and other attributes are now lower-cased
 2. hidden becomes hidden=""
 3. `<path>` nodes that are self closed `<path />` now becomes `</path>`

These are just what I observed.

I only want what I change to be affected by the outerHTML.

**Comment by JonathanMagnan** [comment]
Hello @rgalapate ,

1. The ngIf and other attributes are now lower-cased

It's possible to keep casing with the following options:
```csharp
var doc = new HtmlAgilityPack.HtmlDocument();
doc.OptionOutputOriginalCase = true;
```

2. hidden becomes hidden=""
I don't think that's currently possible.

3. <path> nodes that are self closed <path /> now becomes </path>
Since that's a `SVG` attribute, it's currently not possible.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by rgalapate** [comment]
The answer is fine. 
Thanks 👍
