### ISSUE TITLE
Where is version 1.4.7 ?

### ISSUE THREAD

**Issue by paulbackhouse** [zzzprojects/html-agility-pack#236]
Version 1.4.7 is missing which Abot depends on - where has it gone?

**Comment by JonathanMagnan** [comment]
Hello @paulbackhouse ,

It seems this version doesn't exist at all on `NuGet` (even in the `unlisted` version).

I would recommend you to upgrade to a newest version, perhaps `1.4.8` since I don't have any idea why this version is not on `NuGet` or how to recover it.

Best Regards,

Jonathan

**Comment by paulbackhouse** [comment]
I get manifest errors within the crawl method of Abot based on Manifest version differencies. 

I fixed by rolling abot to version 1.6.0.1 - this restored HtmlAgilityPack to 1.4.7 (:S), you should add to dependency list though as it is currently not listed as a dependency

**Comment by paulbackhouse** [comment]
Abot has a dependency on HtmlAgilityPack, perhaps it is within AngleSharp - you may be right, both Abot and AngleSharp do not mention this dependency though

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
