### ISSUE TITLE
DocumentNode.SelectNodes does not return all selected nodes using XPATH in newer versions

### ISSUE THREAD

**Issue by deepumi** [zzzprojects/html-agility-pack#238]
Hi, 

The following code works fine in older version of nuget packages starting from 1.5.5  to 1.6.5. However, I switched to latest version which 1.8.7 the SelectNodes method does not return all selected nodes. 

I noticed a strange behavior, first time I get all additional node properly based on img xpath expression. 

```csharp
var additionalNodes = doc.DocumentNode.SelectNodes("//img[not(ancestor::*[@class = \"notranslate\"])]");

// I get one anchor tag node instead of 100 anchor tags comparing to 1.5.5 nuget version.
additionalNodes = doc.DocumentNode.SelectNodes("//a[not(ancestor::*[@class = \"notranslate\"])]")
```

Also, If I switch the order to get all anchor tags first,  I get 100 anchor tags and then get 1 image tag.
```csharp
var additionalNodes = doc.DocumentNode.SelectNodes("//a[not(ancestor::*[@class = \"notranslate\"])]");
.
// return one image tag.
additionalNodes = doc.DocumentNode.SelectNodes("//img[not(ancestor::*[@class = \"notranslate\"])]")
```
## Complete code 

```csharp
var doc = new HtmlDocument();
doc.LoadHtml(content);

var nodes = doc.DocumentNode.SelectNodes("//text()[not(ancestor::*[@class = \"notranslate\"])]");

var additionalNodes = doc.DocumentNode.SelectNodes("//img[not(ancestor::*[@class = \"notranslate\"])]");

if (additionalNodes != null)
{
	foreach (HtmlNode node in additionalNodes)
	{
		nodes.Add(node);
	}
}

additionalNodes = doc.DocumentNode.SelectNodes("//a[not(ancestor::*[@class = \"notranslate\"])]");

if (additionalNodes != null)
{
	foreach (HtmlNode node in additionalNodes)
	{
		nodes.Add(node);
	}
}
```
I've tried downgrading nuget package up to 1.7.0 but still does not work!

Any help would be appreciated!

Thank you
Deepu Madhusoodanan

**Comment by JonathanMagnan** [comment]
Hello @deepumi ,

Is it possible to get the `HTML` content to reproduce exactly this issue?

You can send it in private at info@zzzprojects.com if you cannot share it here.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by deepumi** [comment]
Hello @JonathanMagnan,

Please find the sample console app, The project contain html file called "Page.html", The app uses 1.5.5 nuget package. I have specified expected count which is commented on each row in the code. All works fine in 1.5.5 version. However, if you update the package to 1.8.7 count does not match.

Please let me know if you need any further info. 

[ConsoleApp1.zip](https://github.com/zzzprojects/html-agility-pack/files/2325581/ConsoleApp1.zip)

Thank you!
Deepu

**Comment by JonathanMagnan** [comment]
Hello @deepumi ,

You are currently adding nodes to a collection.  Unfortunately, some fixes about handling parent made some side effect like this one.

When adding a node, you need to specify the second argument to false to avoid the parent made a "changes". Otherwise, the original collection will be modified.

```csharp
nodes.Add(node, false);
```

Best Regards,

Jonathan

**Comment by deepumi** [comment]
Thank you @JonathanMagnan

I will try your approach.

**Comment by LinZhouWebDev** [comment]
Hi, I am having a similar issue where` SelectNodes("xpath")` will only work till it reaches a part where the node tree has been modified by a previous operation. 
For example, if I do a replace child on the third paragraph, and then try to select all the span tags using `doc.DocumentNode.SelectNodes("//span")`, it will only return span tags from the first two paragraphs.
Is there a way to "refresh" the node tree so that the second operation will still work? Thanks!

**Comment by JonathanMagnan** [comment]
Hello @LinZhouWebDev ,

Could you try to provide us a Fiddle with this example so we answer you with exactly your scenario.

Example: https://dotnetfiddle.net/z2y3yl

Best Regards,

Jonathan

**Comment by LinZhouWebDev** [comment]
Hello @JonathanMagnan,
Thank you for the reply! Please see the fiddle below for the behavior I was describing: 
https://dotnetfiddle.net/RheeeB

**Comment by JonathanMagnan** [comment]
Thank you @LinZhouWebDev ,

I will assign a developer to look at it.

**Comment by LinZhouWebDev** [comment]
Thank you @JonathanMagnan,
This fix does make `SelectNodes` give the correct results.

**Comment by JonathanMagnan** [comment]
Great ;)

We will close the issue then.

Best Regards,

Jonathan
