### ISSUE TITLE
Is the LoadFromBrowser() method not supported in .NET Core applications? 

### ISSUE THREAD

**Issue by zhaobingwang** [zzzprojects/html-agility-pack#240]
I want to parse the web page generated by JavaScript，but it seems that the method LoadFromBrowser() doesn't supported in .NET Core applications. any solution?

**Comment by JonathanMagnan** [comment]
Hello @zhaobingwang ,

Unfortunately, the `WebBrowser` is not yet supported in `.NET Core`.

An alternative way is to get the HTML from a web browser such as Selenium

There is to built-in features in `HAP` for it yet.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
