### ISSUE TITLE
HasClass whitespace bug

### ISSUE THREAD

**Issue by rmcrackan** [zzzprojects/html-agility-pack#243]
Since HtmlNode.HasClass and HtmlNode.GetClasses only split on the space character, they do not correctly split class names separated by other types of whitespace. The easiest fix would be for HasClass and GetClasses to pass null to Split:

GetClasses()

                var classNames = att.Value.Split(null as char[], StringSplitOptions.RemoveEmptyEntries);

HasClass()

                var classNames = @class.Split(null as char[], StringSplitOptions.RemoveEmptyEntries);

Citation:

https://docs.microsoft.com/en-us/dotnet/api/system.string.split

"If the separator parameter is null or contains no characters, white-space characters are assumed to be the delimiters"

**Comment by JonathanMagnan** [comment]
Hello @rmcrackan ,

Make sense ;) We will check it and make some test but your fix look good.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @rmcrackan ,

Sorry for the delay,

Your fix has been merged in the v1.8.8,

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by rmcrackan** [comment]
So far so good. Thank you for your quick update!

**Comment by JonathanMagnan** [comment]
Hello @rmcrackan ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
