### ISSUE TITLE
.Remove() of an EMBED tag keeps all the inner html

### ISSUE THREAD

**Issue by alex-jitbit** [zzzprojects/html-agility-pack#245]
If the html document contains an `<embed>` tag - calling `.Remove()` on that `HtmlNode` does not remove inner content

`<embed>test</embed>`

Then .Remove the embed-node results in

`test`

**Comment by JonathanMagnan** [comment]
Hello @alex-jitbit ,

The `embed` tag has no closing.

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_embed

The same behavior will happen if you put this text in an `HTML` file and you look at the HTML console. The text will be outside of the embed tag.

Let me know if that explains correctly this behavior.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by alex-jitbit** [comment]
Got it, thanks. Sorry for wasting your time.
