### ISSUE TITLE
multiple tables/tbody on a page are not parsed correctly.

### ISSUE THREAD

**Issue by davvit** [zzzprojects/html-agility-pack#246]
I have a document with multiple tables. i am trying to parse each table body one after another.

I get the first tbody from all available tbody nodes in a doc.  Then i select the rows. At this moment it gives me all the rows in the document - not in the current 'scope' tbody.  ( i am expecting 35 for   `tableBody.SelectNodes("//tr").Count` )  

590 is the total rows in the document - (thats what its outputting to the console from the for loop)

![devenv_2018-09-13_02-21-58](https://user-images.githubusercontent.com/4433698/45474261-eb464700-b6fe-11e8-9af1-a11c35fe858b.png)

Here is a fiddle  https://dotnetfiddle.net/kPUz4N

ps: i know i can do  tbody/tr  but the tables are not even and each row needs to parsed differently...some has 2 col other have 3,5,8 cols.

**Comment by JonathanMagnan** [comment]
Hello @davvit ,

Thank you for reporting, we will soon look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by davvit** [comment]
any idea when to expect fix?

**Comment by JonathanMagnan** [comment]
Hello @davvit ,

Sorry  for the delay,

To select node starting from the current node, you must use the '.'

- "./" : Selects from the current node
- ".//": Selects nodes in the document from the current node that matches the selection no matter where they are 

For example: https://dotnetfiddle.net/14xh1G

Let me know if that answer successfully to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
