### ISSUE TITLE
attributes are being changed

### ISSUE THREAD

**Issue by thdotnet** [zzzprojects/html-agility-pack#248]
I'm using Html Agility Pack to customize shopify templates. The problem is that we have logic inside custom data- attributes.

eg: data-image-id="{{ image.id }}"{% if enable_zoom %} 

After loading the html, it's being updated to:

data-image-id="{{ image.id }}" {%="" if="" enable_zoom="" %}="" 

is there any way to avoid that?

**Comment by JonathanMagnan** [comment]
Hello @thdotnet ,

Unfortunately not at this moment. We do not support or plan to support soon `text templating`.

Let me know if that successfully answer your question.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by thdotnet** [comment]
Not really, in the end I've figure out that attributes are being parsed as key value pairs. And sometimes, if the value is not set, it assumes "" as the value and it's breaking the shopify template.

I had to work with string replaces to "solve" this problem.

**Comment by JonathanMagnan** [comment]
Hello @thdotnet ,

This issue will be closed since we have no plan to support text templating at this moment.

You will need to do this part on your side as you already made to solve this problem.

Best Regards,

Jonathan
