### ISSUE TITLE
HtmlNode.SelectSingleNode search in all Document

### ISSUE THREAD

**Issue by sirjo66** [zzzprojects/html-agility-pack#249]
Hello to all,
I have this code (VB.NET):
```
' a simple html definition:
Dim html = "<DIV class=item__description>ERROR</DIV>" & _
    "<DIV id=moreinfo><DIV class=item__description>Correct</DIV></DIV>"
' load it in HtmlAgilityPack:
Dim hap As New HtmlAgilityPack.HtmlDocument
hap.LoadHtml(html)
' extract DIV with id=moreinfo
Dim div1 = hap.GetElementbyId("moreinfo")
' into div1 I search and extract div with class=item__description
Dim div2 = div1.SelectSingleNode("//div[@class='item__description']")
' now extract InnerText
Dim txt = div2.InnerText
' if it is correct at this point my txt variable = "Correct", but it is = ERROR

```
I don't understand why **div1.SelectSingleNode("//div[@class='item__description']")** search in whole **html** text and not only in **div1** element

Thanks for your help
Sergio

**Comment by JonathanMagnan** [comment]
Hello @sirjo66 ,

To search starting from the current node, you must use the `.`

For example 

```vbnet
Dim div2 = div1.SelectSingleNode(".//div[@class='item__description']")
```

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by sirjo66** [comment]
Perfect !! Many thanks

**Comment by JonathanMagnan** [comment]
Hello @sirjo66 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
