### ISSUE TITLE
select node seems working not correct

### ISSUE THREAD

**Issue by liesauer** [zzzprojects/html-agility-pack#251]
this is my html
```html
<a>first</a>
<td>
    <a>second</a>
</td>
```
and my code
```csharp
var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(html);

var a = htmlDoc.DocumentNode.SelectSingleNode("//td").SelectSingleNode("//a").InnerHtml;
```
`a` is the first one, it seems a little weird, when i select the td node, the after operation should be nothing about the DocumentNode, because it is base on the td node, so `a` should be the second one. but however, the following code works fine.

```csharp
var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(html);

var a = htmlDoc.DocumentNode.SelectSingleNode("//td").SelectSingleNode(".//a").InnerHtml;
```

**Comment by JonathanMagnan** [comment]
Hello @liesauer ,

That's how `XPath` work.

- `//`: selects all nodes starting from the root
- `.//`: selects all nodes starting from the current node

There is no so much we can do here ;)

Let me know if that explains correctly the current behavior.

Best Regards,

Jonathan

**Comment by liesauer** [comment]
that is right, so the call chain only make sense when using `.//`.

**Comment by JonathanMagnan** [comment]
Great ;)

We will close this request since it's has been answered.

Best Regards,

Jonathan
