### ISSUE TITLE
Relative xpath not working

### ISSUE THREAD

**Issue by Warix3** [zzzprojects/html-agility-pack#262]
Selecting with xpath doesn't work when selecting from an element in this case.

HTML:

 ```HTML
<table id="vmlist" class="table table-striped table-bordered table-hover">
 <thead>
 <tr>
 <th class="hidden-phone" width="1">VT</th>
 <th align="left">Hostname</th>
 <th class="hidden-phone" align="left">IP Address</th>
 <th class="hidden-phone" align="left">Operating System</th>
 <th class="hidden-phone" align="left">Memory</th>
 <th class="hidden-phone" align="left">Disk</th>
 <th class="hidden-phone" width="1"></th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td align="center" class="hidden-phone"><img src="Masked1"> </td>
 <td><a href="control.php?_v=Masked">Masked</a></td>
 <td class="hidden-phone">Masked1</td>
 <td class="hidden-phone">Masked1</td>
 <td class="hidden-phone">Masked1</td>
 <td class="hidden-phone">Masked1</td>
 <td class="hidden-phone"><input class="btn btn-small btn-primary" name="manage" type="button" value="Manage" onclick="window.location='Masked1'"></td>
 </tr>
 <tr>
 <td align="center" class="hidden-phone"><img src="Masked2"> </td>
 <td><a href="Masked">Masked2</a></td>
 <td class="hidden-phone">Masked2</td>
 <td class="hidden-phone">Masked2</td>
 <td class="hidden-phone">Masked2</td>
 <td class="hidden-phone">Masked2</td>
 <td class="hidden-phone"><input class="btn btn-small btn-primary" name="manage" type="button" value="Manage" onclick="window.location='Masked2'"></td>
 </tr>
 </tbody>
 </table>
```

Code:

```C#  
private Dictionary<string, string> ScrapeServerList()
         {
             var response = _httpClient.GetAsync(_urls.HomeUrl);
             var home = response.Result.Content.ReadAsStringAsync().Result;
             var homeDoc = new HtmlDocument();
             homeDoc.LoadHtml(home);
             var table = homeDoc.DocumentNode.SelectSingleNode("//*[@id='vmlist']");
             var servers = new Dictionary<string, string>();
             var rows = table.SelectNodes("//tbody/tr");
             foreach(var row in rows)
             {
                 Console.WriteLine(row.InnerHtml);
                 var hostname = row.SelectSingleNode("//td[2]/a").InnerText;
                 var serverId = row.SelectSingleNode("//td[7]/input").GetAttributeValue("onclick", "fail");
                 
                 servers.Add(hostname, serverId);
             }
             return servers;
         }
```

But it works just fine when I append the xpath of the elements to the relative selection, so now it's the full path manually instead of the buggy relative path:

```C#
         private Dictionary<string, string> ScrapeServerList()
         {
             var response = _httpClient.GetAsync(_urls.HomeUrl);
             var home = response.Result.Content.ReadAsStringAsync().Result;
             var homeDoc = new HtmlDocument();
             homeDoc.LoadHtml(home);
             var table = homeDoc.DocumentNode.SelectSingleNode("//*[@id='vmlist']");
             var servers = new Dictionary<string, string>();
             var rows = table.SelectNodes( table.XPath + "//tbody/tr");
             foreach(var row in rows)
             {
                 Console.WriteLine(row.InnerHtml);
                 var hostname = row.SelectSingleNode(row.XPath + "//td[2]/a").InnerText;
                 var serverId = row.SelectSingleNode(row.XPath + "//td[7]/input").GetAttributeValue("onclick", "fail");
                 servers.Add(hostname, serverId);
             }
             return servers;
         }
```

For the first code I posted the expected behaviour is to select different hostnames for 2 different rows, but what happens is that it selects the same hostname twice (because it doesn't take into the account that I'm selecting from an element and not source document). It should automatically append the element's xpath or do it in some other way so it's relative and not always from the document root. Because then the option to select from elements is useless if it will select from root anyway. 

Version: 1.8.10 on .net standard 2.0 with C# 7.3
Environment: Windows 10 64bit

**Comment by JonathanMagnan** [comment]
Hello @Warix3 ,

When selecting from a node, you must use the `.` (dot) to specify it should start from the current node

That's how `XPath` work.

- `//`: selects all nodes starting from the root
- `.//`: selects all nodes starting from the current node

That look to be the issue in your case, you need to use `.//`

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Warix3** [comment]
Thank you for the clarification. I was confused by this, because I had the same code in python with the [requests](https://html.python-requests.org/) library and it's xpath function and it was working fine without the dot. I guess their implementation is just different then.
