### ISSUE TITLE
HTML load error on <script/>

### ISSUE THREAD

**Issue by kalesh13** [zzzprojects/html-agility-pack#263]
Following is the Html I am trying to load. But it is unable to process the g tag element with <script/> tag. If I replace it with <script></script>, everything works fine. Why is it like that?
```
<svg onload="call_execInitLoadProc_svg('system')" style="overflow:visible;  enable-background:new 0 0 2975.028 710.000" viewBox="0 0 2975.028 710.000" height="710.000" width="2975.028" xml:space="preserve" ewd:ver="2.2.1.11" 
	xmlns="&ns_svg;" 
	xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/" 
	xmlns:ewd="http://shcl.co.jp/ewd" 
	xmlns:xlink="&ns_xlink;">
	<script type="text/javascript" xlink:href="../../../../../system/js/ewd/fig/svgfig.js" 
		xmlns:xlink="http://www.w3.org/1999/xlink"/>
	<g id="ewd_top">
        </g>
</svg>
```

The code I am using to load the html

```
HtmlDocument doc=new HtmlDocument()
doc.LoadHtml(properly_escaped_above_html_in_a_string_variable);
```

**Comment by JonathanMagnan** [comment]
Hello @kalesh13 ,

Thank you for reporting,

`svg` are not supported but that don't explain the `script` behavior, so we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by kalesh13** [comment]
You said `svg` is not supported. Does that mean HtmlAgilityPack doesn't support XML?

**Comment by JonathanMagnan** [comment]
Hello @kalesh13 ,

`HAP` is a html parser, not a `XML` parser. So no, we doesn't support XML.

After looking at this issue, I don't think we will support this scenario.

A script tag should always end with `</script>`, even browser doesn't work correctly when you don't end the `script` tag correctly.

Best Regards,

Jonathan

**Comment by kalesh13** [comment]
Okay. I know my files will have just one script tag. So I am replacing `/>` with `></script>`
