### ISSUE TITLE
TRACE constant is defined for release configuration of .net standard project 

### ISSUE THREAD

**Issue by krasin-ga** [zzzprojects/html-agility-pack#265]
HtmlNodeNavigator class has an **[Conditional("TRACE")]InternalTrace()** method that adds a lot of overhead. 

Related issue: #207

**Comment by JonathanMagnan** [comment]
Hello @krasin-ga ,

Thank for letting us know, that's for sure something we will look do understand why that attribute is here.

Best Regards,

Jonathan
