### ISSUE TITLE
Exception : the document is too complex to parse

### ISSUE THREAD

**Issue by iliass3** [zzzprojects/html-agility-pack#267]
Hello developers,

I am having an issue with parsing an XML document, when I select one of the nodes from this document i get a Null value, the other nodes work fine ,when I started investigating a found the following : 

![depth level exception message](https://user-images.githubusercontent.com/44297364/49789233-c9735500-fd2b-11e8-83b4-ff7217767fd9.png)

Here is the code i use : 

```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using System.Xml;
using System.Xml.Linq;

`           var FD = new System.Windows.Forms.OpenFileDialog(); // open the file selector (choose a file)
            FD.Filter = "txt files (*.twb)|*.twb|All files (*.*)|*.*"; // we only accept twb files or all files
            if (FD.ShowDialog() == System.Windows.Forms.DialogResult.OK){ // after a file has been selected
                file_path = FD.FileName;  // we save the path of the file to the variable file_path
            }
            // reading the selected file
            try
            {
                System.IO.FileInfo File = new System.IO.FileInfo(FD.FileName); // declare a new file reader
                dashboard_content = System.IO.File.ReadAllText(file_path); //read and store the file content at dashboard_content
            }
            catch{
                Console.WriteLine("an exception occured"); // catch exceptions
            }
            //   **********************************************************
            HtmlAgilityPack.HtmlDocument xml_doc = new HtmlAgilityPack.HtmlDocument(); // we create an empty html document
            xml_doc.LoadHtml(dashboard_content); // we load the content of the file to the document
            //   **********************************************************
            HtmlAgilityPack.HtmlNode thumbnails = xml_doc.DocumentNode.SelectSingleNode("//thumbnail");`
```

The file I try to parse : 

Ages.txt
[Ages.txt](https://github.com/zzzprojects/html-agility-pack/files/2666766/Ages.txt)

Thank you in advance

**Comment by iliass3** [comment]
here is a code file as well, as the code isn't clear on the previous post
[code.txt](https://github.com/zzzprojects/html-agility-pack/files/2667010/code.txt)

**Comment by JonathanMagnan** [comment]
Thank you @iliass3 ,

We will look at it.

Btw, for code... you need to use "```csharp" and close it with "```" to format the code (You can edit your comment to see how I did it).

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by iliass3** [comment]
Thank you @JonathanMagnan 

Regards

**Comment by JonathanMagnan** [comment]
Hello @iliass3 ,

Is there a reason why you don't use a `XML` parser for `.NET`?

`HAP` has been created to support `HTML` and not `XML`

**Comment by iliass3** [comment]
hi @JonathanMagnan ,

No there is no reason for using HAP specifically, I just assumed it would work with XML as well.

by the way HAP is a great tool, but I think I will be switching to an XML library for this project.

Thank you

**Comment by JonathanMagnan** [comment]
No problem ;)

I will close this issue then.

Best Regards,

Jonathan
