### ISSUE TITLE
Compile Error in WP 8.1 app after adding HtmlAgilityPack 1.8.11.0

### ISSUE THREAD

**Issue by mkostersitz** [zzzprojects/html-agility-pack#269]
After adding HTMLAgilityPack to an WP 8.1 App I am updating for a customer the App will not compile anymore with a series of these errors.
Cannot resolve dependency to assembly 'System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

The errors only happen in the XAML App project. DLL projects I have in the same solution work fine with HTMLAgilityPack.

**Comment by JonathanMagnan** [comment]
Hello @mkostersitz ,

I'm not sure to understand.

Are you saying your project work fine for some client and for some other, this error is thrown? Is there a version which this error started to pop beside the latest one?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by mkostersitz** [comment]
Hello @JonathanMagnan 
sorry for not being clear. 
I have a Windows Phone 8.1 solution with a legacy application a customer of mine has. They want me to help fix some issues with their home grown HTML parsing, so I am looking into replacing the error prone homegrown parsing engine with HAP. 
The solution consists of 5 projects total. The break down of the solution is as follows:
- 1 XAML App
- Networking functions DLL
- DB functions DLL
- Imaging functions DLL
- Business logic DLL.

All are set to WP 8.1 
if I add another DLL for parsing and reference the HAP there the DLL builds fine and I can reference it from the App and everything works.
initially for prototyping I added the HAP to the app directly and the compiler errors were happening as soon as the reference was there.
It is not blocking me as I am going with the DLL implementation anyhow but I thought it would make sense to raise the issue just in case.

Mike

**Comment by JonathanMagnan** [comment]
Oh thank for the clarification,

That's indeed weird.

Did your AppConfig has been modified when installing `HAP`? That's something I remember I got with a few libraries and I had to undo changes from other third-party libraries which modified my config.

For example, there is some similar issue that look similar to the one I explained such as: https://stackoverflow.com/a/49078929/5619143

Best Regards,

Jonathan

**Comment by mkostersitz** [comment]
Thanks for the reply. I saw that issue too. But that was not it. 
really odd. I think it is some collision with the way the solution got built originally (WP 7) and then it was upgraded to 7.5, 8.0 and subsequently to 8.1.

I could try and create a new solution and copy all the code over file by file but I don't think that is worth it as the customer is moving away from WP mid next year and needs the fix just as a stop gap until then.
the new app for iOS and Android is in the works and in testing already.

Mike

**Comment by JonathanMagnan** [comment]
Can we close this issue then? I don't think there is anything we can do on our side about this issue.

**Comment by mkostersitz** [comment]
@JonathanMagnan thanks for taking a look
