### ISSUE TITLE
InnerText is incorrect for TEXTAREA nodes

### ISSUE THREAD

**Issue by Stevie-O** [zzzprojects/html-agility-pack#272]
Probably related to the fix for #183, parsing the contents of this URL:

http://ngu-idle.wikia.com/wiki/Template:Item_data_THE_CUBE?action=edit

The InnerText of the lone 'textarea' element comes back starting like this:

`{{{{{1&lt;noinclude>|Item data&lt;/noinclude>}}}`

When it should be:

`{{{{{1<noinclude>|Item data</noinclude>}}}`

**Comment by JonathanMagnan** [comment]
Hello @Stevie-O ,

If you look at the source code,

You will see the following line: 

```html
<textarea readonly="" accesskey="," id="wpTextbox1" cols="80" rows="25" style="" lang="en" dir="ltr" name="wpTextbox1">{{{{{1&lt;noinclude>|Item data&lt;/noinclude>}}}|THE CUBE|id = 100|caption = Leading 2-Dimensional scientists developed this artifact over a dozen years of research. Too bad you destroyed their civilization.|set = 2D|type = Accessory|lvldrop = 0|2Dlvldrop = 0|powervalbase  = 363|powervalbasemax = 650|powervalmax = 1300|hpvalbase = 1089|hpvalbasemax = 1950|hpvalmax = 3900|toughnessvalbase = 363|toughnessvalbasemax = 650|toughnessvalmax = 1300|regenvalbase = 10.89|regenvalbasemax = 19.5|regenvalmax = 39|effectiveness_lvl = 58|daycare = 6}}
</textarea>
```

So in fact, `HtmlAgilityPack` return the value found.

But you might be right, InnerText normally returns the value escaped ('<' and '>'). We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Stevie-O ,

After investigating it, I was wrong. The `InnerText` seems to always return the original text.

For some backward compatibility reason, we cannot change this behavior.

So, unfortunately, you will need to `unescape` the text on your side.
