### ISSUE TITLE
Cloned nodes do not preserve original element name casing

### ISSUE THREAD

**Issue by JeffHelman** [zzzprojects/html-agility-pack#273]
If an element has non-standard name casing (e.g. <someElement>) that a user wishes to preserve via the OptionOutputOriginalCase flag on a document, that non-standard name casing is not preserved if the element is cloned.  Instead, the optimized version of the name (all lowercase) is used for the clone.

It appears that the issue is in that the cloned element (in the CloneNode(bool deep) method) is getting its name from the Name attribute of the original node, rather than from the OriginalName attribute. I believe that making this change would fix it, but I'm not familiar enough with the codebase to know whether that change might affect anything else.

**Comment by JonathanMagnan** [comment]
Hello @JeffHelman ,

Thank for reporting. We will look at your suggested fix to see if there is any side impact.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @JeffHelman ,

The v1.8.12 has been released.

We now clone the `OriginalName`, so the casing is now preserved.

Let me know if everything is working as expected.

Best Regards,

Jonathan
