### ISSUE TITLE
CRITICAL BUG: Empty p elements will strip away the end tag

### ISSUE THREAD

**Issue by Assassinbeast** [zzzprojects/html-agility-pack#276]
If you have an empty p element, then the end tag will not be drawn.
For example making a `<p></p>` will result in a `<p>`
It will simply strip away the end tag `</p>`

But other tags such as  `h1`, `h2`, `span` etc. works as expected if they are empty

Heres a code example:

```c#
string html =
@"
<!DOCTYPE html>
<html>
<head>
	<title>foo</title>
</head>
<body>
	<p></p>
	<p>Hello</p>
</body>
</html>
";

var doc = new HtmlDocument();
doc.LoadHtml(html);
Console.WriteLine(doc.DocumentNode.OuterHtml);

```

This will result in this:

![image](https://user-images.githubusercontent.com/6762656/51858719-ad586100-2335-11e9-8cca-fb39a75bdc0b.png)

**Comment by JonathanMagnan** [comment]
Hello @Assassinbeast ,

Thank for reporting, we will look at it.

Please, try next time to copy & paste the code instead to show an image. It will save us some time.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Assassinbeast** [comment]
@JonathanMagnan Updated :-)

**Comment by JonathanMagnan** [comment]
Hello @Assassinbeast ,

Sorry for the long waiting, the v1.9.2 has been released.

The `p` tag should now write the ending `</p>` as expected.

Best Regards,

Jonathan
