### ISSUE TITLE
HtmlAgilityPack on Xamarin.Forms issue with SelectSingleNode

### ISSUE THREAD

**Issue by VishalBoxer** [zzzprojects/html-agility-pack#277]
I just added htmlagilitypack in xamarin.forms but it doen't having 'SelectSingleNode' method.
So, is am i doing something wrong its not included for Xamarin. Forms?

Please suggest any alternative if anyone has for the same.

Thank You.

Sample Code:

   var htmlDoc = new HtmlDocument();
   htmlDoc.LoadHtml(HtmlText);
   var htmlBody = htmlDoc.DocumentNode.**SelectSingleNode**("//body");

**Comment by JonathanMagnan** [comment]
Hello @VishalBoxer ,

Witch version of the library is used by your project?

To your library point to the dll in the `.NET Standard`? or is still point to the old Portable Class Library?

**Comment by VishalBoxer** [comment]
Hello @JonathanMagnan 

I tried with the lower version as well as with the latest version. and the DLL points to the PCL.
