### ISSUE TITLE
HtmlNode.PrependChildren() Reverses Order of Source HtmlNodeCollection

### ISSUE THREAD

**Issue by nbcarey** [zzzprojects/html-agility-pack#278]
`HtmlNode.PrependChildren()` does an in-order traversal of the source `HtmlNodeCollection` in doing its work. This causes the source `HtmlNodeCollection` to be reversed in the process of prepending it to destination `HtmlNodeCollection`.

`IList<T>` is an ordered collection: order should be maintained unless the user explicitly changes its order.

**Found In:**  v1.8.14

**Example:**

```C#
using System;
using HtmlAgilityPack;

namespace PrependChildrenTest
{
  class Program
  {
    static void Main( string[] args )
    {
      HtmlNode source = HtmlNode.CreateNode(@"
<ul>
  <li> Alpha   </li>
  <li> Bravo   </li>
  <li> Charlie </li>
</ul>
");
      HtmlNode destination = HtmlNode.CreateNode(@"
<ul>
  <li> Delta   </li>
  <li> Echo    </li>
  <li> Foxtrot </li>
</ul>
");

      destination.PrependChildren( source.ChildNodes );

      destination.WriteTo( Console.Out );

      return;
    }
  }
}
```

**Expected Results:**

```HTML
<ul>

  <li> Alpha   </li>
  <li> Bravo   </li>
  <li> Charlie </li>

  <li> Delta   </li>
  <li> Echo    </li>
  <li> Foxtrot </li>

</ul>
```

**Actual Results:**

```HTML
<ul>

  <li> Charlie </li>
  <li> Bravo   </li>
  <li> Alpha   </li>

  <li> Delta   </li>
  <li> Echo    </li>
  <li> Foxtrot </li>

</ul>
```

**Comment by JonathanMagnan** [comment]
Hello @nbcarey ,

Thank you for the pull, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Closing: pull has been completed
