### ISSUE TITLE
HtmlNode.CreateNode() returns a #text node when its parameter starts with "\n"

### ISSUE THREAD

**Issue by OpportunityLiu** [zzzprojects/html-agility-pack#28]
``` c sharp
HtmlNode node = HtmlNode.CreateNode(@"
<p>text</p>
");
```
You'll get `node.OuterHtml == "\r\n"`.

I don't think it is the expacted result.

In [source](https://github.com/zzzprojects/html-agility-pack/blob/bed94728fdddb6ad265247f7af68e8d6400c4fdd/src/HtmlAgilityPack.Shared/HtmlNode.cs#L572) I found the first element of the document directly returned, maybe we should check it before return.

**Comment by JonathanMagnan** [comment]
Hello @OpportunityLiu ,

Thank you for reporting. I will have my developer assigned to this project to look on this issue during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @OpportunityLiu ,

The v1.5.1-beta1 has been released.

The CreateNode should now return the tag as expected.

Let me know if this version is working with your scenario.

Best Regards,

Jonathan

**Comment by OpportunityLiu** [comment]
It works well, thanks.
