### ISSUE TITLE
support namespaceuri

### ISSUE THREAD

**Issue by yinyue200** [zzzprojects/html-agility-pack#280]
such as selectnodesns

**Comment by JonathanMagnan** [comment]
Hello @yinyue200 ,

Could you provide an example of code that you would like we make it works?

It will be easier for my developer to get started and try to find if that's possible with our library.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by yinyue200** [comment]
for example

```
<!DOCTYPE html>
<html>  
   <body>
    
      <mathxml:math xmlns:mathxml="http://www.w3.org/1998/Math/MathML">
        
         <mathxml:mrow>
            <mathxml:msup><mathxml:mi>a</mathxml:mi><mathxml:mn>2</mathxml:mn></mathxml:msup>
            <mathxml:mo>+</mathxml:mo>
                
            <mathxml:msup><mathxml:mi>b</mathxml:mi><mathxml:mn>2</mathxml:mn></mathxml:msup>
            <mathxml:mo>=</mathxml:mo>
         </mathxml:mrow>        
      </mathxml:math>
        
   </body>
</html> 
```

var hd = new HtmlAgilityPack.HtmlDocument();
hd.LoadHtml(html);
var odkns = new System.Xml.XmlNamespaceManager(hd.NameTable);
odkns.AddNamespace("a", "http://www.w3.org/1998/Math/MathML");
hd.SelectSingleNodeNS("//a:math",xd);

**Comment by JonathanMagnan** [comment]
Hello @yinyue200 ,

One problem with this scenario is that **HTML** Agility Pack is a **HTML** parser and not an XML parser.

We will try something this week to check the effort for doing such request but I really don't guarantee anything on this one.

**Comment by JonathanMagnan** [comment]
Hello @yinyue200 ,

My developer looked at it last week and unfortunately, way too many code need to be modified to make it work correctly with `XML`.

That's something we will try to support if we re-write this library but unfortunately not something we can implement in a short term.
