### ISSUE TITLE
Closing li tag lost when nested list's list item has no closing tag

### ISSUE THREAD

**Issue by vsevolodp** [zzzprojects/html-agility-pack#282]
There is a problem somewhere in parser or writer.
I noticed this issue when I was reading output second time and looking for descendants. HAP gave me more descendants than I expected for li id="l1".

Input:
```
<html>
<body>
    <ol>
        <li id="l1">
            <ol>
                <li>
            </ol>
        </li>
        <li>
        </li>
    </ol>
</body>
</html>
```

It's ok to add closing li tag for inner list but note that closing li tag is lost for 1st element of outer list
Output:
```
<html>
<body>
    <ol>
        <li id="l1">
            <ol>
                <li></li>
            </ol>        
        <li>
        </li>
    </ol>
</body>
</html>
```

Expected output:
```
<html>
<body>
    <ol>
        <li id="l1">
            <ol>
                <li>
            </ol>
        </li>
        <li>
        </li>
    </ol>
</body>
</html>
```

**Comment by vsevolodp** [comment]
Test code
```
var input = "<html><body><ol><li id=\"l11\"><ol><li id=\"l21\"></ol></li><li id=\"l12\"></li></ol></body></html>";

var document = new HtmlAgilityPack.HtmlDocument();
document.LoadHtml(input);

string output;
using (var writer = new StringWriter())
{
    document.Save(writer);
    output = writer.ToString();
}

Console.WriteLine(output);

Console.WriteLine("Descendants of #l11:");
var l11 = document.DocumentNode.SelectSingleNode("//li[@id='l11']");
foreach (var n in l11.Descendants())
{
    var id = !string.IsNullOrWhiteSpace(n.Id) ? $" id=\"{n.Id}\"" : string.Empty;
    Console.WriteLine($"{n.Name}{id}");
}
```
Output
``` html
<html><body><ol><li id="l11"><ol><li id="l21"></li></ol><li id="l12"></li></ol></body></html>
Descendants of #l11:
ol
li id="l21"
li id="l12"
```

Note 1. Output is missing closing tag for #l11 while input has it.
Note 2. li id="l12" should not be a descendant of #l11. They are siblings.

**Comment by JonathanMagnan** [comment]
Hello @vsevolodp ,

Thank you for reporting and for the code.

We currently have too many requests but we will try to look at it next week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @vsevolodp ,

This issue is fixing starting from v1.11.x

Fiddle: https://dotnetfiddle.net/ZbVor4

Let me know if everything works as expected.

**Comment by vsevolodp** [comment]
It works. Thank you for fixing this!
