### ISSUE TITLE
lib\uap10.0\HtmlAgilityPack.dll targets x86

### ISSUE THREAD

**Issue by OpportunityLiu** [zzzprojects/html-agility-pack#283]
![default](https://user-images.githubusercontent.com/13471233/52939641-a86c5780-339f-11e9-8301-5c6f02efaf65.png)
![default](https://user-images.githubusercontent.com/13471233/52939654-b4581980-339f-11e9-8f58-9d5bc055e63d.png)

**Comment by OpportunityLiu** [comment]
In 1.8.14


![default](https://user-images.githubusercontent.com/13471233/52940013-75769380-33a0-11e9-86f2-3c9dddd774f9.png)

**Comment by JonathanMagnan** [comment]
Hello @OpportunityLiu ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @OpportunityLiu ,

Sorry for the long delay, the v1.9.1 has been released.

Let me know if the new version target AnyCPU correctly this time.

Best Regards,

Jonathan

**Comment by zipswich** [comment]
What a timely fix v1.9.1 is. I was struggling with the following error earlier today:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): error MSB3270: There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users\h9\.nuget\packages\htmlagilitypack\1.9.0\lib\uap10.0\HtmlAgilityPack.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
`
I believe the error was introduced recently.

**Comment by OpportunityLiu** [comment]
It works correctly, thanks for your fix.

**Comment by JonathanMagnan** [comment]
Great :)

Thank for confirming @OpportunityLiu ,

Yes, @zipswich , the error was added in v1.9.0 since the code source got a major structure revamp.
