### ISSUE TITLE
Whitespaces/newlines destroy parsing on HtmlNode.FirstChild

### ISSUE THREAD

**Issue by MuffinMario** [zzzprojects/html-agility-pack#285]
Hello! I'd like to report this issue regarding HtmlNode.FirstChild, which for some reason does not work if the document has multiple lines or tab spaces in between each tags. I am not sure if this is an issue, but it surely looks like one. If you replace FirstChild with ChildNodes and take the first Element, it will work.

Take this example as a demonstration of the issue. Both HTML strings are syntactically identical but their spacing is different
```
public class Program
{
	public static void Main()
	{
		var html =
        @"<body><h1>This is <b>bold</b> heading</h1><p>This is <u>underlined</u> paragraph</p></body>";

		var htmlWhitespace =
        @"<body>
		<h1>This is <b>bold</b> heading</h1>
		<p>This is <u>underlined</u> paragraph</p>
		</body>";
		
		/* NO WHITESPACE: */
        var htmlDoc = new HtmlDocument();
        htmlDoc.LoadHtml(html);

        var htmlBody = htmlDoc.DocumentNode.SelectSingleNode("//body");
		
		HtmlNode firstChild = htmlBody.FirstChild;
		
		Console.WriteLine("no whitespace: " + firstChild.OuterHtml);	
		
		/* WHITESPACE: */
        htmlDoc = new HtmlDocument();
        htmlDoc.LoadHtml(htmlWhitespace);

        htmlBody = htmlDoc.DocumentNode.SelectSingleNode("//body");
		
		firstChild = htmlBody.FirstChild;
		
		Console.WriteLine("whitespace: " + firstChild.OuterHtml);		
	}
}
```
Will output 
```
no whitespace: <h1>This is <b>bold</b> heading</h1>
whitespace:
```

**Comment by JonathanMagnan** [comment]
Hello @MuffinMario ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
