### ISSUE TITLE
1.9.2 regression with unclosed P tags

### ISSUE THREAD

**Issue by cyotek** [zzzprojects/html-agility-pack#287]
### Description
I updated a project from 1.9.0 to 1.9.2 and had a test fail. The cause of the failure was because a unclosed `<p>` tag was now receiving `</p>`. In addition, the new tag was added to the wrong place, directly after the original tag, instead of at the end of the content. Of course, I'd rather it didn't inject anything "extra" at all, regardless of schematic validity.

```html
<html><body>
Paragraph 1.<p>Paragraph 2.
</body></html>
```

Loading the above snippet into a `HtmlDocument` and then pulling it out again via `Save` in 1.9.0 results in exactly the same HTML. However, in 1.9.2 the following output is returned

```html
<html><body>
Paragraph 1.<p></p>Paragraph 2.
</body></html>
```

You can see how the `<p>` has gained a closing tag. However, even if this were the right behaviour it hasn't added it to the correct place as it should have been at the end of the paragraph. One of the reasons I prefer HtmlAgility pack over things like AngelSharp is the fact that I don't like the content being changed unless expressed instructed to do so.

I tested with 1.9.1 and this worked as expected too, so this seems to have been introduced in 1.9.2.

Is there a way to disable this behaviour, assuming it's a feature and not a bug?

### Fiddle or Project
I've attached a sample project to this message.

[HtmlAgilityPackScratch.zip](https://github.com/zzzprojects/html-agility-pack/files/2973691/HtmlAgilityPackScratch.zip)

### Further technical details
- HAP version: 1.9.2
- NET version: .NET 4.6

**Comment by JonathanMagnan** [comment]
Hello @cyotek ,

Thank you for reporting.

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Internal note: That's related to the fix made for #276

**Comment by JonathanMagnan** [comment]
Hello @cyotek ,

The v1.9.2 has been removed.

We have released a new version 1.10.0, in this version, we modified how the `p` tag is working. It had some setting that makes the tag work differently than other tags such as `div`.

I believe this change will cause some side impact as it's a big change for the tag `p`.

Let me know if you see anything weird in this new version.

Best Regards,

Jonathan

**Comment by cyotek** [comment]
Hello,

I just updated my solution to 1.10.2 and can confirm that the regression seems to be resolved; the test that was previously failing is now fine (and nothing else seems amiss). I will keep an eye out for any odd behaviour.

Thanks again for the prompt resolution!

Regards;
Richard Moss

**Comment by JonathanMagnan** [comment]
Great :)

We will close this request.

I believe tomorrow, another big version will be released that will fix A LOT of issues when a tag is not closed.

It should be the version 1.11.0, so make sure to test this one as well if you upgrade.
