### ISSUE TITLE
HtmlNode.LinePosition is not accurate for attributes

### ISSUE THREAD

**Issue by jcoutch** [zzzprojects/html-agility-pack#288]
### Description
HtmlNode.LinePosition when used with attributes is never accurate (always seems to be 2 characters off.)

### Exception
No exceptions thrown

### Fiddle or Project
https://dotnetfiddle.net/GWS8yg

### Further technical details
- HAP version: 1.11.1
- NET version: N/A (occurs in both NetFX and NetCore applications.)

**Comment by jcoutch** [comment]
I also checked ValueStartIndex, and as long as that's zero-based, appears to be correct.  Just the LinePosition appears to be incorrect.

**Comment by JonathanMagnan** [comment]
Hello @jcoutch ,

Thank you for reporting,

My developer is currently looking at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @jcoutch ,

The v1.11.2 has been released.

The LinePosition should be now fixed. Let me know if you get the right value.

Best Regards,

Jonathan
