### ISSUE TITLE
HtmlAgilityPack throws StackOverflowException on pages with lots of nested tags

### ISSUE THREAD

**Issue by atobtech** [zzzprojects/html-agility-pack#289]
Can you please add following feature to latest version to deal with this critical issue

See examples in below link to reproduce it 

https://code.google.com/archive/p/abot/issues/77

**Comment by JonathanMagnan** [comment]
Hello @atobtech ,

My developer looked at it but he is not sure which features you are speaking.

The last post says:

> Turns out that using HtmlDocument.OptionFixNestedTags = true solves this issue without needing the patched version..

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by atobtech** [comment]
I’m talking about HtmlDocument.OptionMaxNestedChildNodes property that let you control how many nested nodes parser can handle and throw error that application can handle instead of crushing applications completely with stock overflow 

Below property does not  help
> HtmlDocument.OptionFixNestedTags = true
> 

Regards
AA

**Comment by JonathanMagnan** [comment]
Hello,

The v1.11.3 has been released, let me know if that's the fix you were looking for.

**Comment by atobtech** [comment]
Thanks for fixing

**Comment by devanshu0987** [comment]
Hi @JonathanMagnan , would it be possible to give a link to the PR for this?
I tried to find it but couldn't.
