### ISSUE TITLE
Nested tags not closing correctly

### ISSUE THREAD

**Issue by LWPNG** [zzzprojects/html-agility-pack#292]
Hi, I noticed nested tags aren't closing correctly, e.g.

**input:** 
`<div><a href="#_bookmark1"><a href="#_bookmark2"><span>abc</span></a></a></div>`
**output:** 
`<div><a href="#_bookmark1"><a href="#_bookmark2"><span>abc</span></a></div>`

**input:** 
`<p><span>Text 1.</span><p><span>Text 2.</span></p></p>`
**output:** 
`<p><span>Text 1.</span><p><span>Text 2.</span></p>`

I know the input aren't exactly clean but these are the input we were provided with hence the request for a fix. 

Best regards,
WP

**Comment by JonathanMagnan** [comment]
Hello @LWPNG ,

What is the error exactly? There is some implicit closing (the ending tag is not always required).

**Comment by LWPNG** [comment]
Sorry, I should have mentioned the output expected would be the same as the input in the cases mention? 
(since both the <a> and <p> tags has child element)

**Comment by JonathanMagnan** [comment]
The output is not necessarily the same as the input.

- It is not valid to have an `a` tag inside an `a` tag
- It is not valid to have an `p` tag inside an `p` tag

That why some closing `</a>` or `</p>` are missing.

**Comment by LWPNG** [comment]
Thank you for your replies.
