### ISSUE TITLE
HtmlWeb.LoadFromBrowser don't sets ResponseUri

### ISSUE THREAD

**Issue by VBWebprofi** [zzzprojects/html-agility-pack#295]
If you use ``System.Windows.Forms.WebBrowser`` instance you should set ``_responseUri`` to ``System.Windows.Forms.WebBrowser.Url`` in one code line after https://github.com/zzzprojects/html-agility-pack/blob/a884b1d51aa757ccf901241ddaaa6a0f95ad15bc/src/HtmlAgilityPack.Shared/HtmlWeb.cs#L2544 .

**Comment by JonathanMagnan** [comment]
Hello @VBWebprofi ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @VBWebprofi ,

The v1.11.4 has been released.

Could you try it and let me know if everything is now working as expected?
