### ISSUE TITLE
HtmlWeb.LoadFromWebAsync does not respect UserAgent

### ISSUE THREAD

**Issue by wiz0u** [zzzprojects/html-agility-pack#298]
LoadFromWebAsync does not apply the given UserAgent property (and possibly other properties)
like the synchronous methods do.

**Comment by JonathanMagnan** [comment]
Thank for letting us know,

We will check if there is a reason behind it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @wiz0u ,

The v1.11.5 has been released.

Let me know if everything is working as expected.

**Comment by wiz0u** [comment]
Tested on 1.11.7
Seems good now, thanks
