### ISSUE TITLE
Cannot add package to visual studio for Mac

### ISSUE THREAD

**Issue by hfb170** [zzzprojects/html-agility-pack#30]
Tried to add the package to a C# project with visual studio for Mac and I got the following error message:
"Could not install package 'HtmlAgilityPack.Net45 2.0.20'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." 
Is there any solution to overcome this issue?

**Comment by JonathanMagnan** [comment]
Hello @hfb170 ,

The project `HtmlAgilityPack.Net45` is not owned by us.

Try the official version instead: https://www.nuget.org/packages/HtmlAgilityPack/1.5.0-beta92

The latest version HtmlAgilityPack v1.5.0-beta92 contains version compatible with .NET Core

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Answered
