### ISSUE TITLE
Feature - Add many attribute and CSS at same time

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#301]
Hello there,

jQuery has the ability to add attribute and CSS using plain objects using the [.attr() function](https://api.jquery.com/attr/#attr-attributes) and the [.css() function](https://api.jquery.com/css/#css-properties).  
But in you API you can only add a single attribute at a time. [Add()](https://html-agility-pack.net/add).

So what would be nice is something like a `AddRange()` method with overrides that accept `Dictionary<string, string>` or `IEnumerable<HtmlAttribute>`.

Whatya think?

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

I'm not sure if that will be very used but sure, we can do it for the Dictionary. That's not hard to code.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

The v1.11.7 has been released.

Both methods have been added.

Let me know if that was what you were looking for.

**Comment by LukeTOBrien** [comment]
Thanks very much, I will give it a try.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LukeTOBrien** [comment]
Hi thanks,

I have tested this out and it works great, now we can add attributes using [collection initializer](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer):

```csharp
element.Attributes.AddRange(new Dictionary<string, string>(){
    { "title", "Hello there"},
    { "data-attr", "123" }
});
```

But I also that an equivelent for the styles would be good, I have just seen [this question](https://html-agility-pack.net/knowledge-base/12062495/better-way-to-add-a-style-attribute-to-html-using-htmlagilitypack).  
I think a property named `Style` (In keeping with the [DOM property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style)) would be ideal:

```csharp
element.Style.AddRange(new Dictionary<string, string>(){
    { "color", "blue"},
    { "display", "inline-block" }
});
```

_Incidentally a helper method to convert [System.Drawing.Color](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color?view=netframework-4.8) to hex might be useful?_  

```csharp
element.Style.SetStyle("color" string.Format("#{0:X2}{1:X2}{2:X2}",
    Color.AliceBlue.R, Color.AliceBlue.G, Color.AliceBlue.B));
```

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

At this moment, we don't handle style like this.

We will for sure consider it when we will be ready to create a version 2.x but at this moment.

If you wish, you can provide a pull and we will be happy to review it.
