### ISSUE TITLE
Rendering extra closing tags

### ISSUE THREAD

**Issue by girishkaturu** [zzzprojects/html-agility-pack#303]
### Description
When scraping "http://www.exhibitforce.com/v2/backendv3/freight_estimate_pro2.asp?LID=52TKTC80CK&BID=6EQ129EP7F", the result HTML varies from the source HTML of the webpage. The differences can be seen in the two attached text documents. In the HTMLDocumentDocumentNodeInnerHTML.txt file, there are some extra 'table', 'tr' and 'td' ending tags are rendered.

[HTMLDocumentDocumentNodeInnerHTML.txt](https://github.com/zzzprojects/html-agility-pack/files/3258871/HTMLDocumentDocumentNodeInnerHTML.txt)
[HTMLDocumentParsedText.txt](https://github.com/zzzprojects/html-agility-pack/files/3258872/HTMLDocumentParsedText.txt)

### Exception
NO EXCEPTION
```
Exception message:
Stack trace:
NO STACK TRACE```

### Fiddle or Project
[CLGQuoteMgmt_ExhibitForce.zip](https://github.com/zzzprojects/html-agility-pack/files/3258856/CLGQuoteMgmt_ExhibitForce.zip)

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- HAP version: v4.0.30319
- NET version (net472, netcore, etc.): .NET Framework 4.6.1

**Comment by JonathanMagnan** [comment]
Hello @girishkaturu ,

I'm not sure what to answer on this one.

Checking the source directly via the browser, this page contains MANY html mistake.

Example:
```html
</tr>
	<td width="40%" height="20" class="inventorytext">Postal Code:</td> 
	<td width="60%" height="20" class="inventorytext">75034</td> 
</tr>
```

There is some that we will look and we will fix but I'm not sure that everything will be fixed.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by girishkaturu** [comment]
Jonathan,
Thank you for addressing the issue quickly. I did not realize the HTML issues as I was viewing the source in the development console of Mozilla Firefox. Thank you for pointing them out. I will clean up the HTML and try to scrape the page. 

Please let me know if the HTMLAgilityPack library has a solution to fix the ill-formed HTML.


Thanks,
Girish Katuru

**Comment by JonathanMagnan** [comment]
One way could potentially be to use "OptionFixNestedTags"

Some tags will be fixed using these options

```csharp
HtmlDocument html = new HtmlDocument();
html.OptionFixNestedTags = true;
```

**Comment by girishkaturu** [comment]
Jonathan,
Thank you very much.


Girish Katuru

Application Developer

*Champion Logistics Group*
200 Champion Way, Northlake, IL 60164
Work: 708-562-4200 x162

Mobile: 251-689-0453

gkaturu@champlog.com

www.championlogisticsgroup.com
