### ISSUE TITLE
LoadHtml(string html) have a bug  after LoadHtml i get DocumentNode OuterHtml

### ISSUE THREAD

**Issue by AtlantisDe** [zzzprojects/html-agility-pack#304]
### Description
Loads the HTML document from the specified string.
 then after  document.DocumentNode.InnerHtml;
The source code has changed
In the title tag section

### before
- LoadHtml(string html);
- here is html 
```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><google></title>
</head>
<body>
</body>
</html>
```

### after
- document.DocumentNode.OuterHtml;
- here is html 
```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><google></google></title>
</head>
<body>
</body>
</html>
```

### Was changed
- Title content has been changed
```html
<title><google></google></title>
```

### pls help me 
 
```html
tks very much
```

**Comment by JonathanMagnan** [comment]
Thank you for reporting.

We will check if that's possible to parse tag inside a tag.

Normally a title doesn't contain any tag, it should be `&lt;google&gt;`

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by AtlantisDe** [comment]
hello but i need  this like style  
```html
<google>
```
thanks  i find other way.....do it

**Comment by JonathanMagnan** [comment]
Hello @AtlantisDe ,

The v1.11.8 has been released.

Let me know if that is now working as you expect.

**Comment by AtlantisDe** [comment]
> Hello @AtlantisDe ,
> 
> The v1.11.8 has been released.
> 
> Let me know if that is now working as you expect.

Thank you  very much....

**Comment by AtlantisDe** [comment]
1.当有写操作时，其他读操作会被驳回

2.当有写操作时，其他写操作会被驳回

3.当开启事务时，在提交事务之前，其他写操作会被驳回

4.当开启事务时，在提交事务之前，其他事务请求会被驳回

5.当有读操作时，其他写操作会被驳回

6.读操作之间能够并发执行
