### ISSUE TITLE
Find x and y position of element

### ISSUE THREAD

**Issue by roshan355** [zzzprojects/html-agility-pack#305]
### Description
I want to get the x and y position of element using html-agility pack.. Is it possible in html-agility pack?

**Comment by JonathanMagnan** [comment]
Hello @roshan355 ,

No, HAP is an HTML parser.

You cannot do such a thing with the library.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
