### ISSUE TITLE
Question about the site

### ISSUE THREAD

**Issue by sfarzoso** [zzzprojects/html-agility-pack#306]
Hi there,

I really enjoy your site and the library too, I would like to create a similar site and for this, I want ask you which CMS did you used and which theme skin, thanks.

**Comment by JonathanMagnan** [comment]
Hello @sfarzoso ,

Thank you for your great comment,

Everything is custom, so no CMS and no skin ;) Like in the old days!

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
