### ISSUE TITLE
XML processing instruction(s) are classified as a textnode?

### ISSUE THREAD

**Issue by PokerPro123** [zzzprojects/html-agility-pack#309]
I'm not sure if this is a bug or not. I don't believe XML processing instructions should be classified as a text node. I want to exclude these. 

https://dotnetfiddle.net/4RXN2i

**Comment by JonathanMagnan** [comment]
You are right, it seem there is an issue

`<?foo note=""I am XML processing instruction. I wish to be excluded"" ?>` should become a comment as it is processed by Chrome and Safari.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by PokerPro123** [comment]
Is this something that could be squeezed into the next release? I have a workaround in place for dealing with these. But it's part of the html-agility-pack code base.

**Comment by JonathanMagnan** [comment]
There is a good chance it will be part of next release but I'm not sure if that will happen this week or next week.

**Comment by JonathanMagnan** [comment]
Hello @PokerPro123 ,

A new version has been released v1.11.9, this part of the text is now considered as a comment (like the browser does).

Let me know if everything works as expected.

**Comment by PokerPro123** [comment]
Thanks! I'll report back in a day or two. I need to catch up on a couple other tasks first.
