### ISSUE TITLE
subdomain crash

### ISSUE THREAD

**Issue by BlaxadowFire** [zzzprojects/html-agility-pack#310]
### Description
When a website contains a different subdomain then a regular one (www. or none), I get multiple exceptions (see Exceptions). This is not the only case I have had.

### Exception
```
IOException,
HttpRequestException,
WebException
```

Exception message:
Stack trace:
```
[System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.]
   at System.Net.HttpWebRequest.GetResponse()
   at HtmlAgilityPack.HtmlWeb.Get(Uri uri, String method, String path, HtmlDocument doc, IWebProxy proxy, ICredentials creds)
   at HtmlAgilityPack.HtmlWeb.LoadUrl(Uri uri, String method, WebProxy proxy, NetworkCredential creds)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at Program.Main() :line 13
```

### Fiddle or Project
https://dotnetfiddle.net/O340ZQ

```
// @nuget: HtmlAgilityPack

using System;
using HtmlAgilityPack;
using System.Collections.Generic;

public class Program
{
	public static void Main()
	{
		// Load
		var web = new HtmlWeb();
		var doc = web.Load("https://blog.getpaint.net/");
		//var doc = web.Load("https://www.getpaint.net/");
		
		
		// ADD code to reproduce the issue here
		
		// Show info
		System.Console.WriteLine(doc.DocumentNode.InnerHtml);
	}
}
```

If you use the `https://blog.getpaint.net` you get the exceptions,
If you use the `https://www.getpaint.net` everything works fine.

### Further technical details
- HAP version: `1.11.7`
- NET version: `.NET Core 2.2`

**Comment by BlaxadowFire** [comment]
After updating HAP to version: `1.11.8`
The problem still persist.

**Comment by JonathanMagnan** [comment]
Hello @BlaxadowFire ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by BlaxadowFire** [comment]
note:
After some more testing I noticed that this happens to multiple subdomains, but not all.
I.E:
the following also gives the error
github raw files:
`https://raw.githubusercontent.com/username/projectname/branch/filename`

the following does NOT give the error
`https://nl.wikipedia.org/wiki/.info`
`https://images.google.com`
`https://docs.microsoft.com`

**Comment by JonathanMagnan** [comment]
Hello @BlaxadowFire ,

Unfortunately, we didn't find a fix using the load method.

The issue happens in the `HttpWebResponse`. We don't know how to fix it, it seems to be related with `ssl`.

Some people suggestion fix like this:

```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
									   | SecurityProtocolType.Tls11
									   | SecurityProtocolType.Tls12;
```

But it doesn't work either.

The only thing that worked on our side was the `LoadFromBrowser` method

```csharp
LoadFromBrowser("https://blog.getpaint.net/");
```

**Comment by BlaxadowFire** [comment]
I might be looking in the wrong place right now, but I can't find where and how to use the `LoadFromBrowser` method.
If I do 

```
		var web = new HtmlWeb();
		var doc = web.LoadFromBrowser("https://blog.getpaint.net/");
```
I get:
```
Error	CS1061	'HtmlWeb' does not contain a definition for 'LoadFromBrowser' and no accessible extension method 'LoadFromBrowser' accepting a first argument of type 'HtmlWeb' could be found (are you missing a using directive or an assembly reference?)
```
Am I missing something?

**Comment by JonathanMagnan** [comment]
Oops no, you are missing nothing.

I just saw that you use .NET Core which doesn't implement a `WebBrowser` yet. So this method is not available in .NET Core ;(

Two alternative could be:
- Try to load the HTML on your side and use HAP
- Use another tools to take the HTML such as Selenium
