### ISSUE TITLE
Xml content inside <title> tag not parsed

### ISSUE THREAD

**Issue by apis-bulgaria** [zzzprojects/html-agility-pack#315]
### Description
Hello, I am using **HAP** to parse custom **xml** (not actual **html**).
I've noticed that the latest versions can't parse the content in **title** tag - the content is parsed as `HtmlTextNode`.

Example code:
```
var htmlDocumnet = new HtmlDocument();
htmlDocumnet.LoadHtml("<bodyType> <title normalized-num=\"4\"> <num>ДЯЛ ЧЕТВЪРТИ</num> <heading>ПРИЛОЖИМ ЗАКОН</heading> </title> </bodyType>");
```

Expanding the DOM you will see that the child node of the <**title**> tag is single `HtmlTextNode`, where in previous versions the <**num**> and <**heading**> are parsed as child nodes.

The issue is not present in HAP 1.11.3.
In releases 1.11.7 and 1.11.8 there is a [fixed issue](https://github.com/zzzprojects/html-agility-pack/issues/304) which i think may be related

### Further technical details
- HAP version: 1.11.9
- NET version (net471):

**Comment by JonathanMagnan** [comment]
Hello @apis-bulgaria ,

I'm not sure but I believe it **now** work as intended.

If you put this code in an html file and open it, you will see the title is `<num>ДЯЛ ЧЕТВЪРТИ</num> <heading>ПРИЛОЖИМ ЗАКОН</heading>` so this is indeed a text node. the `num` and `heading` are not child nodes but part of the text.

**Comment by apis-bulgaria** [comment]
Okay, thanks for the info. 
I will use older version of **HAP** for now and at some point will try to migrate to `System.Xml.Linq`.
