### ISSUE TITLE
HtmlNode.InnerText wrong documentation

### ISSUE THREAD

**Issue by huckjulius** [zzzprojects/html-agility-pack#318]
### Description
The documentation of HtmlNode.InnerText says 'Gets or Sets the text between the start and end tags of the object.'

### Exception
'HtmlNode.InnerText' cannot be assigned to -- it is read only

**Comment by JonathanMagnan** [comment]
Hello @huckjulius ,

Thank you for reporting, we will look at it and fix the documentation.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @huckjulius ,

Thank again for reporting.

The fix has been done. It will be available on next release.

Best Regards,

Jonathan
