### ISSUE TITLE
HAP can't parse document with self-closed <title/> tag

### ISSUE THREAD

**Issue by vitaliy-leschenko** [zzzprojects/html-agility-pack#319]
### Description
HAP can't parse document with self-closed <title/> tag. This is xhtml. The <title/> tag can be empty.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title />
    <link rel="stylesheet" href="style.css" type="text/css" />
    <link rel="stylesheet" href="style.css" type="text/css" />
</head>
<body class="cover">
    <svg xmlns="http://www.w3.org/2000/svg" class="cover-svg" viewBox="0 0 1500 2129">
        <image height="2129" xlink:href="images/cover.jpg" width="1500" xmlns:xlink="http://www.w3.org/1999/xlink" />
    </svg>
</body>
</html>
```

### Further technical details
- HAP version: 1.11.9
- .NETStandard 2.0:

**Comment by JonathanMagnan** [comment]
Hello @vitaliy-leschenko ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @vitaliy-leschenko ,

My developer tried it but it seems to work as expected: https://dotnetfiddle.net/sxxNxF

(Currently using an older version due to an issue with Fiddle).

Could you provide more information or a runnable solution?

Best Regards,

Jonathan

**Comment by vitaliy-leschenko** [comment]
Please see this sample https://dotnetfiddle.net/gzwNFB
HAP can't find //body in this document because title is empty.

**Comment by JonathanMagnan** [comment]
Hello @vitaliy-leschenko ,

We made some test on our side and the title cannot be empty.

If you add the text in an HTML file, even browser will take all the remaining text and include it in the "title" since a tittle cannot be an empty element.

However Browser will add an empty `body` element, but that will not solve your problem. I'm not sure from where you parse this HTML but there is not so much we can do since an empty title is not valid.

![7f46c12c-701f-4ecd-93bf-a3bcc5c66e1c](https://user-images.githubusercontent.com/23240780/61717239-b2b7c680-ad2e-11e9-88e3-dd7271effb7b.png)

**Comment by vitaliy-leschenko** [comment]
Please see new test: https://dotnetfiddle.net/8l02A6
Any browsers (Chrome, Opera, Edge) correctly parse and display this xhtml:
```html
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title/>
</head>
<body>
  test
</body>
</html>
```
You can see `test` at window with empty title.

**Comment by vitaliy-leschenko** [comment]
Also please see test with fixed html: https://dotnetfiddle.net/NqA0FM
Unfortunatelly XHTML is user content, so we need to HAP correcly parse it even if it partialy incorrect.

**Comment by JonathanMagnan** [comment]
I'm not sure why you can see the `test` on your side but that's not our case.

As you can find on this SO answer, a title **must** have both a start tag and an end tag: https://stackoverflow.com/a/19400695/5619143

The next answer also state exactly what is happening here: https://stackoverflow.com/a/19401108/5619143 "the tag <title /> is processed by browsers as if the slash were not there"

Could you just make a find & replace of `<title/>` by `<title></title>` on your side?
