### ISSUE TITLE
attributes containing HTML entities are resolved into the literal characters

### ISSUE THREAD

**Issue by torbenjk** [zzzprojects/html-agility-pack#32]
There is a subtle change in HTML Agility Pack 1.5 that turned out to be a breaking change for us - I'll leave it up to you to figure out if it is an error.
The scenario is this:
We have some XML files which also happens to be almost valid HTML we run through HTML Agility Pack with the OptionWriteEmptyNodes set to true. 
This takes care of some subtle fixes, e.g. a closed span tag: `<span />` - which is valid in XML, but not in HTML - is rewritten as `<span></span> `which *is* valid XML and *also* valid HTML. And this is what we want.
However, when upgrading from version 1.4.9 to version 1.5 a change was introduced.
This:

`<a data-href="http://example.com/path?productId=9788762505032&amp;title=something">...</a>`

is changed into this:

`<a data-href="http://example.com/path?productId=9788762505032&title=something">...</a>`

Notice that the ampersand entity in the attribute value has been resolved into a literal ampersand. This makes the output non-valid XML and breaks our process. I suspect that the same would happen for other html entities. This is almost certainly related to issue #19.

I am not sure if you guarantee that the output of HTML which happens to be valid XML run through the agility pack will produce still valid XML; but until version 1.4.9 it did - and it still does for the vast majority of cases. So it would be great if you could consider to still support this. And I also suspect there might be some cases where this would be an error even for consumers that do not care about XML.

**Comment by JonathanMagnan** [comment]
Hello @torbenjk ,

Thank you for reporting.

Yes, the issue is caused because of the fix for the issue #19 

All the string is DeEntitized. We maybe did something we should not.

We will look at this issue over the weekend. In the worse case, we will provide an option to automatically DeEntitize attribute.

So your code will not be broken anymore and the fix for the issue #19 will still work when the option is enabled.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @torbenjk ,

The version v1.5.1 has been released. 

Value DO NOT longer automatically DeEntitize the value as it was before we released the fix for the issue #19.

Let us know if your code works now as normally.

Best Regards,

Jonathan

**Comment by torbenjk** [comment]
Works for me!

**Comment by deepak-khopade-isdr** [comment]
We are running into a kind of similar issue where its not taking care of `&` in my `InnerText` for `<span>` tag. See below; this is causing `XmlDocument.Load()` to fail.

```
<div class="left" style="margin-left: 0px; margin-right: 0px; text-indent: 48px">
<span style="font-family: Times New Roman; font-size: 13px">This
chart compares the five-year cumulative total return on our common
stock with that of the Standards & Poor 500 index and a custom
peer group, which was selected by the Company. The chart assumes
$100 was invested on January 31, 2013, in our common stock, the
Standards & Poor 500 index and the peer group, and that any
dividends were reinvested. The Peer Group is composed of:
Broadridge Financial Solutions Inc., Cision, Ltd., and Workiva,
Inc. The peer group index utilizes the same method of presentation
and assumptions for the total return calculation as does Issuer
Direct Corporation (ISDR) and the Standards & Poor 500 index.
All companies in the peer group index are weighted in accordance
with their market capitalizations.</span></div>
```
As you can see string literal has `Standards & Poor` which is the reason it fails.

Please let us know more what should we use to make it work.

**Comment by JonathanMagnan** [comment]
Hello @deepak-khopade-isdr ,

It depends on what you need to do.

There is already an option to save the text as XML

```csharp
string html = @"<div class=""left"" style=""margin-left: 0px; margin-right: 0px; text-indent: 48px"">
<span style=""font-family: Times New Roman; font-size: 13px"">This
chart compares the five-year cumulative total return on our common
stock with that of the Standards & Poor 500 index and a custom
peer group, which was selected by the Company. The chart assumes
$100 was invested on January 31, 2013, in our common stock, the
Standards & Poor 500 index and the peer group, and that any
dividends were reinvested. The Peer Group is composed of:
Broadridge Financial Solutions Inc., Cision, Ltd., and Workiva,
Inc. The peer group index utilizes the same method of presentation
and assumptions for the total return calculation as does Issuer
Direct Corporation (ISDR) and the Standards & Poor 500 index.
All companies in the peer group index are weighted in accordance
with their market capitalizations.</span></div>";

var doc = new HtmlAgilityPack.HtmlDocument();
doc.OptionOutputAsXml = true;
doc.LoadHtml(html);

StringWriter sw = new StringWriter();
XmlTextWriter xw = new XmlTextWriter(sw);
doc.Save(xw);

string result = sw.ToString();
```

[Try it](https://dotnetfiddle.net/CCZ2Gu)

Best Regards,

Jonathan
