### ISSUE TITLE
How to load the active page

### ISSUE THREAD

**Issue by 06Games** [zzzprojects/html-agility-pack#321]
### Description
How to parse the page in its current state?
Let me explain, I have a page dynamically modified by javascript and I would like to retrieve the information from the page when a POST request is received.

### My code
I tried to solve my problem like this:
```csharp
var doc = new HtmlAgilityPack.HtmlDocument();
using (var reader = new StreamReader(HttpContext.Request.Body))
    var body = reader.ReadToEnd();
    doc.LoadHtml(body);
```
but the body variable is empty...

### Informations
I'm using **ASP.NET Core 2.2** and HAP v**1.11.12**

**EDIT:** I post the page from a form with the `enctype` attribute set to `multipart/form-data`

**Comment by njy** [comment]
The Request.Body is not html.
I mean, it's not as if it is the `<body>` element of the page doing the request or something like that.

**Comment by 06Games** [comment]
So, is there another solution?

**Comment by JonathanMagnan** [comment]
Hello @06Games ,

HAP is an `HTML` parser. Your request look to be out of the scope of what this library achieve.

I recommend you to try a web browser such as [selenium](https://www.seleniumhq.org/) to get HTML when a POST event occurs

_(I cannot help you more, I never used selenium on my side)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by 06Games** [comment]
I'll see what I can do with that, thank you both !
