### ISSUE TITLE
HtmlEntity.Entitize(): incorrect handling of surrogate pairs (for example, emoji symbol)

### ISSUE THREAD

**Issue by msvprogs** [zzzprojects/html-agility-pack#323]
### Description
HtmlEntity.Entitize() returns incorrect entity codes for surrogate pairs.
For example, 😂 should be converted as `&#x1F602;` or `&#128514;`, but `HtmlEntity.Entitize("😂", true, true)` returns `&#55357;&#56834;`

### Further technical details
- HAP version: 1.11.9
- NET version (net472, netcore, etc.): .NET Core 2.2

**Comment by JonathanMagnan** [comment]
Hello @msvprogs ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @msvprogs ,

We added in the latest version the option `UseWebUtility`

When turned on (`HtmlAgilityPack.HtmlEntity.UseWebUtility = true`), we will use a different strategy to entitize value which should work in your case.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by msvprogs** [comment]
Yes, it works, thank you!
