### ISSUE TITLE
HtmlNode.InnerText Not working properly

### ISSUE THREAD

**Issue by AtlantisDe** [zzzprojects/html-agility-pack#333]
### Description
I will get  element.InnerText ,However, the results did not meet expectations

```
&nbsp; 
&nbsp; 
&nbsp; 
&nbsp; 
```

### Html Code

```
<p id="demo">hello &nbsp; </p>
```

### Html Agility Pack Get  InnerText  is

```
var Text=  htmlNode.InnerText;

//Get:  

hello &nbsp; 
```

### Browser Get the  InnerText  is

```
document.querySelector("#demo").innerText

//Browser Get Is Right

"hello"
```

### Other information reference

- [htmlchar](https://www.jb51.net/onlineread/htmlchar.htm)

**Comment by JonathanMagnan** [comment]
Hello @AtlantisDe ,

I'm not sure to understand this request.

What's currently not working or what are you expecting?

For example, https://dotnetfiddle.net/DlQf6n return "hello   "

What should be the expected result?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by AtlantisDe** [comment]
@JonathanMagnan hello I edited it again, please take a look.

**Comment by JonathanMagnan** [comment]
Hello @AtlantisDe ,

Here is what my browser return me:

```text
document.getElementsByTagName("p")[0].innerText
"hello  " // 2 space
```

A text with 2 space (we have 3 since we don't manage space like a browser)

So the browser still return some space also

**Comment by AtlantisDe** [comment]
hello @JonathanMagnan  Thanks reply . can do it like  browser.? if can not..this issue..will close... ths

**Comment by JonathanMagnan** [comment]
I believe it's better to close it. Always better to keep the current code and breaking some applications.

People should usually do a `TRIM` if they want to remove spacing.
