### ISSUE TITLE
HtmlWeb.Load memory leak

### ISSUE THREAD

**Issue by 1AlexFix1** [zzzprojects/html-agility-pack#335]
```
for(int i = 0; i< 1000; i++)
                {
                    testFunc("https://www.wildberries.ru/catalog/0/brand.aspx");
                }

   private void testFunc(string url)
        {
            Console.WriteLine("Step 1 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
            var web = new HtmlWeb();
            web.Load(url);
            Console.WriteLine("Step 2 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
        }
```
The problem is the following, this code causes the following result. 
When you exit the function, gigabytes of memory are not cleared even if you call gc.collect.
Step 1 239710208
Step 2 508997632
Step 1 508997632
Step 2 618811392
Step 1 618811392
Step 2 736714752
Step 1 736780288
Step 2 868671488
Step 1 868671488
Step 2 1000620032
Step 1 1000620032
Step 2 966635520
Step 1 966635520
Step 2 1030459392
Step 1 1030459392
Step 2 1132990464
Step 1 1132990464
Step 2 1243058176
Step 1 1243058176
Step 2 1351020544
Step 1 1351020544
Step 2 976433152
Step 1 976433152
Step 2 993357824
Step 1 993357824
Step 2 1010507776
Step 1 1010507776
Step 2 1027637248
Step 1 1027637248
Step 2 1044787200
Step 1 1044787200
Step 2 978776064
Step 1 978776064
Step 2 1059405824
Step 1 1059405824
Step 2 1144446976
Step 1 1144446976
Step 2 1229873152
Step 1 1229873152
Step 2 1273733120
Step 1 1273733120
Step 2 1224687616
Step 1 1224687616
Step 2 1243013120
Step 1 1243013120
Step 2 1208184832
Step 1 1208184832
Step 2 1226674176
Step 1 1226674176
Step 2 1248821248
Step 1 1248821248
Step 2 1293643776
Step 1 1293643776
Step 2 1346076672
Step 1 1346076672
Step 2 1282310144
Step 1 1282310144
Step 2 1299505152
Step 1 1299505152
Step 2 1318957056
Step 1 1318957056
Step 2 1344970752
Step 1 1344970752
Step 2 1294401536
Step 1 1294401536
Step 2 1311318016
Step 1 1311318016
Step 2 1337470976
Step 1 1337470976
Step 2 1359917056
Step 1 1359917056
Step 2 1402564608
Step 1 1402564608
Step 2 1249931264
Step 1 1249931264
Step 2 1266765824
Step 1 1266765824
Step 2 1285390336
Step 1 1285390336
Step 2 1053503488
Step 1 1053503488
Step 2 1069314048
Step 1 1069314048
Step 2 1085198336
Step 1 1084940288
Step 2 1082265600
Step 1 1068716032
Step 2 1075240960
Step 1 1075240960
Step 2 1119727616
Step 1 1119727616
Step 2 1183584256
Step 1 1183584256
Step 2 1245990912
Step 1 1245990912
Step 2 1327374336
Step 1 1327374336
Step 2 1450008576
Step 1 1450008576
Step 2 1372622848
Step 1 1372622848
Step 2 1389252608
Step 1 1389252608
Step 2 1427800064
Step 1 1427800064
Step 2 1476616192
Step 1 1476616192
Step 2 988680192
Step 1 988680192
Step 2 1005821952
Step 1 1005821952
Step 2 1022853120

**Comment by JonathanMagnan** [comment]
Hello @1AlexFix1 ,

I don't think you can really check if there is a memory leak like this. You can also see that sometime the memory go down.

You will get the same "memory leak" with a simple object

```csharp
public class NoMemoryLeakHere
{
	public string Test { get; set; }
}

public void testFunc(string url)
{
	Console.WriteLine("Step 1 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
	var noMemoryLeakHere = new NoMemoryLeakHere {Test = url};
	Console.WriteLine("Step 2 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
}
```

```text
Step 1 27815936
Step 2 27881472
Step 1 28012544
Step 2 28078080
Step 1 28143616
Step 2 28209152
Step 1 28340224
Step 2 28405760
Step 1 28471296
Step 2 28602368
Step 1 28667904
Step 2 28733440
Step 1 28798976
Step 2 28930048
Step 1 28995584
Step 2 29061120
Step 1 29126656
Step 2 29257728
Step 1 29323264
Step 2 29392896
Step 1 29523968
Step 2 29589504
Step 1 29655040
Step 2 29720576
Step 1 29851648
Step 2 29917184
Step 1 29982720
Step 2 30048256
Step 1 30179328
Step 2 30244864
Step 1 30310400
Step 2 30441472
Step 1 30507008
Step 2 30572544
Step 1 30638080
Step 2 30769152
Step 1 30834688
Step 2 30900224
Step 1 30965760
Step 2 31096832
Step 1 31162368
Step 2 31227904
Step 1 31358976
Step 2 31424512
```

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by 1AlexFix1** [comment]
> Hello @1AlexFix1 ,
> 
> I don't think you can really check if there is a memory leak like this. You can also see that sometime the memory go down.
> 
> You will get the same "memory leak" with a simple object
> 
> ```cs
> public class NoMemoryLeakHere
> {
> 	public string Test { get; set; }
> }
> 
> public void testFunc(string url)
> {
> 	Console.WriteLine("Step 1 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
> 	var noMemoryLeakHere = new NoMemoryLeakHere {Test = url};
> 	Console.WriteLine("Step 2 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
> }
> ```
> 
> ```
> Step 1 27815936
> Step 2 27881472
> Step 1 28012544
> Step 2 28078080
> Step 1 28143616
> Step 2 28209152
> Step 1 28340224
> Step 2 28405760
> Step 1 28471296
> Step 2 28602368
> Step 1 28667904
> Step 2 28733440
> Step 1 28798976
> Step 2 28930048
> Step 1 28995584
> Step 2 29061120
> Step 1 29126656
> Step 2 29257728
> Step 1 29323264
> Step 2 29392896
> Step 1 29523968
> Step 2 29589504
> Step 1 29655040
> Step 2 29720576
> Step 1 29851648
> Step 2 29917184
> Step 1 29982720
> Step 2 30048256
> Step 1 30179328
> Step 2 30244864
> Step 1 30310400
> Step 2 30441472
> Step 1 30507008
> Step 2 30572544
> Step 1 30638080
> Step 2 30769152
> Step 1 30834688
> Step 2 30900224
> Step 1 30965760
> Step 2 31096832
> Step 1 31162368
> Step 2 31227904
> Step 1 31358976
> Step 2 31424512
> ```
> 
> Best Regards,
> 
> Jonathan
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)


you're right thanks!

**Comment by 1AlexFix1** [comment]
> Hello @1AlexFix1 ,
> 
> I don't think you can really check if there is a memory leak like this. You can also see that sometime the memory go down.
> 
> You will get the same "memory leak" with a simple object
> 
> ```cs
> public class NoMemoryLeakHere
> {
> 	public string Test { get; set; }
> }
> 
> public void testFunc(string url)
> {
> 	Console.WriteLine("Step 1 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
> 	var noMemoryLeakHere = new NoMemoryLeakHere {Test = url};
> 	Console.WriteLine("Step 2 {0}", Process.GetCurrentProcess().PrivateMemorySize64);
> }
> ```
> 
> ```
> Step 1 27815936
> Step 2 27881472
> Step 1 28012544
> Step 2 28078080
> Step 1 28143616
> Step 2 28209152
> Step 1 28340224
> Step 2 28405760
> Step 1 28471296
> Step 2 28602368
> Step 1 28667904
> Step 2 28733440
> Step 1 28798976
> Step 2 28930048
> Step 1 28995584
> Step 2 29061120
> Step 1 29126656
> Step 2 29257728
> Step 1 29323264
> Step 2 29392896
> Step 1 29523968
> Step 2 29589504
> Step 1 29655040
> Step 2 29720576
> Step 1 29851648
> Step 2 29917184
> Step 1 29982720
> Step 2 30048256
> Step 1 30179328
> Step 2 30244864
> Step 1 30310400
> Step 2 30441472
> Step 1 30507008
> Step 2 30572544
> Step 1 30638080
> Step 2 30769152
> Step 1 30834688
> Step 2 30900224
> Step 1 30965760
> Step 2 31096832
> Step 1 31162368
> Step 2 31227904
> Step 1 31358976
> Step 2 31424512
> ```
> 
> Best Regards,
> 
> Jonathan
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

If you run your code without output to the console, then the memory will not clog, in the case of load, the memory is kept at 1gb

**Comment by JonathanMagnan** [comment]
Just to make sure,

Is everything fine? Can we close the ticket?
