### ISSUE TITLE
HtmlNode.AddClass won't add "btn" if "btn-primary" is already added.

### ISSUE THREAD

**Issue by torerikk** [zzzprojects/html-agility-pack#337]
### Description
AddClass checks if any existing classes contains the new class-name, so if "my-btn-class" exists in the class attribute it won't add "btn". 

https://dotnetfiddle.net/vx7O59

### Further technical details
- HAP version: 1.11.5 
- NET version: net472

**Comment by JonathanMagnan** [comment]
Hello @torerikk ,

Thank you for reporting,

My developer will look at it to fix it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @torerikk ,

The v1.11.16 has been released.

Let me know if everything is now working as expected.

Best Regards,

Jonathan

**Comment by torerikk** [comment]
Yes, now it works as expected :) Thank you!
