### ISSUE TITLE
HtmlWeb not reading a site but saying it has

### ISSUE THREAD

**Issue by axtens** [zzzprojects/html-agility-pack#338]
### Description
With an url of "https://www.seekfind.com.au/businesses/hair-and-beauty?maxRows=10&page=54&search" 
```csharp
        var web = new HtmlWeb();
        var doc = web.Load(url);
```
web.StatusCode is "OK" but the doc.Text is empty

### Exception
It'd be nice if there was an exception, but there's not

```
Exception message:
Stack trace:
```

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/YpeN8z

### Further technical details
<package id="HtmlAgilityPack" version="1.11.16" targetFramework="net461" />
Windows 10

**Comment by JonathanMagnan** [comment]
Hello @axtens 

Since our last conversation, I haven't heard from you!

Were you able to find the solution?

If so, please do report it here!

Looking forward to hearing from you, 

Jon

**Comment by axtens** [comment]
Sorry for the delay.

We've decided to continue to use HtmlAgilityPack and the HtmlWeb.Load and treat this one website as an anomaly. As you can see from the wget session below, there actually is nothing for HtmlWeb to work on. Only a web browser makes sense of it.
```
>wget --no-check-certificate "https://www.seekfind.com.au/businesses/hair-and-beauty?maxRows=10&page=54&search"
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Users\bugma\scoop\apps\gow\current/etc/wgetrc
--2019-10-25 08:47:23--  https://www.seekfind.com.au/businesses/hair-and-beauty?maxRows=10&page=54&search
Resolving www.seekfind.com.au... 54.79.99.163
Connecting to www.seekfind.com.au|54.79.99.163|:443... connected.
WARNING: cannot verify www.seekfind.com.au's certificate, issued by `/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA':
  Self-signed certificate encountered.
WARNING: certificate common name `www.ayacoda.com' doesn't match requested host name `www.seekfind.com.au'.
HTTP request sent, awaiting response... 200
Length: 0 [text/html]
Saving to: `hair-and-beauty@maxRows=10&page=54&search'

    [ <=>                                                                           ] 0           --.-K/s   in 0s

2019-10-25 08:48:07 (0.00 B/s) - `hair-and-beauty@maxRows=10&page=54&search' saved [0/0]


>type "hair-and-beauty@maxRows=10&page=54&search"

>
```
In the event that sites like this become the norm then we'll probably use Selenium. As it stands, HtmlWeb is not a browser and is arguably better off not trying to be one. 

Close-able.

**Comment by JonathanMagnan** [comment]
Yup, we don't want to make it like a browser.

However, there is a `LoadFromBrowser` feature as well ;)

https://html-agility-pack.net/from-browser

But you might want to keep using `Selenium` to have more features.

**Comment by axtens** [comment]
Where is the `LoadFromBrowser` symbol declared? When I try to use it, I get
```
Error    CS1061    'HtmlWeb' does not contain a definition for 'LoadFromBrowser' and no accessible extension method 'LoadFromBrowser' accepting a first argument of type 'HtmlWeb' could be found (are you missing a using directive or an assembly reference?) 
```

**Comment by JonathanMagnan** [comment]
Are you in .NET Core? Unfortunately, that's not available in .NET Core since there is no web browser control yet

**Comment by axtens** [comment]
I'm in .NET Framework 4.8. I just tried 4.7.2 but that made no difference. 
```csharp
                HtmlWeb web = new HtmlWeb();
                try
                {
                    document = web.Load(urlAsUri.ToString());
                    analysis.PageStatus = web.StatusCode.ToString();
                    analysis.RequestDurationMilliseconds = web.RequestDuration;
                }
```
When in Visual Studio, the intellisense only offers me .Load and .LoadHtmlAsXml as loading options on the HtmlWeb instance.

**Comment by axtens** [comment]
Having said that, I also use HtmlWeb in JavaScript via ClearScript and in that environment I can create an instance of HtmlWeb and use LoadFromBrowser.

**Comment by JonathanMagnan** [comment]
I'm not exactly sure to understand, so here is a small project in .NET Framework 4.8 that use the LoadFromBrowser method.

[Z.LoadFromBrowser.zip](https://github.com/zzzprojects/html-agility-pack/files/3783855/Z.LoadFromBrowser.zip)

**Comment by axtens** [comment]
Okay, let's close this again. I uninstalled HAP and CssSelectors. Then I installed CssSelectors and it installed HAP 1.4.9. Then Visual Studio suggested updating HAP to 1.11.16. Now I have LoadFromBrowser() available.

**Comment by JonathanMagnan** [comment]
Awesome! 

We will reopen the issue if you have questions, issues or feedback!

Best regards, 

Jon

**Comment by blrvw** [comment]
I am seeing this with a C# .Net 6 solution with HAP 1.11.71 installed.  I have tried a number of different solutions from the web but nothing fixes the issue.  If I actually go to the definition for HtmlWeb the LoadFromBrowser method (several actually, with overrides) is shown in the DLL SourceLink.  What could be preventing these methods from being available?
