### ISSUE TITLE
Wrong Html Encoding

### ISSUE THREAD

**Issue by marcussacana** [zzzprojects/html-agility-pack#339]
### Description
I'm trying open a UTF8 html, I can get the InnerHtml without encoding error, but the OuterHtml return the html with certain characters corrupted, then he save using my specified encoding, but looks like he don't 'parse' the nodes correctly.

`---------------Saved Document--------------------|----------------Original Document-------------`
![image](https://user-images.githubusercontent.com/10576957/67076872-6da40480-f164-11e9-8ddd-95f408e27b83.png)

Special characters that break when save:
```
“”’
```

I really just open and saved the HTML, you can see the html isn't changed at all, then I don't think I need provide my project to reproduce

**Comment by JonathanMagnan** [comment]
Hello @marcussacana ,

Could you still provide a runnable project that reproduces the issue?

We cannot count anymore the number of issues that a little thing was missing and we lost time to try to reproduce it. So we now always ask for a project to save time on our side.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by marcussacana** [comment]
I found the problem, a thousand apologies, i wrote the code at 5am and was totally clueless and ended up making a mistake, it was not the library problem, sorry for creating a wrong issue.
