### ISSUE TITLE
V1.5 breaks webview events

### ISSUE THREAD

**Issue by bobbydharrell** [zzzprojects/html-agility-pack#34]
I updated to 1.5 webview.navigationcompleted stopped working, spent half the day thinking it was my code and trying different events. Works in the Windows Phone emulator but not on an actual device.

**Comment by JonathanMagnan** [comment]
Hello @bobbydharrell ,

Thank you for reporting.

Which version were you using before that was working? We will check if something has changed that could impact that.

So far, I don't remember any changes related to this event.

Best Regards,

Jonathan

**Comment by bobbydharrell** [comment]
Hi 1.4.9.4 is working. Installed via Nuget Package manager in Visual Studio 2017

**Comment by bobbydharrell** [comment]
To duplicate, create a webview, add an event for navigation completed with a few lines of code within it. Then run on a physical device. It will fail to call the event, DOMCompleted would call the event if it only had 1 thing in it. But it all works flawlessly on the Emulator.

**Comment by JonathanMagnan** [comment]
Hello @bobbydharrell ,

What's the relation within webview/navigation completed event and Html Agility Pack?

From the description provided, it looks that you don't need HAP to reproduce this issue.

So I'm not sure what we need to fix.

Best Regards,

Jonathan

**Comment by bobbydharrell** [comment]
Sorry, I am using the HAP to parse the content of the website after it loads to look for a specific element.
I am not currently at my computer but could provide a code snippet on Wednesday.


Sincerely,Bobby HarrellOwner/DeveloperB-Tech Labs, LLCbobbyharrell@b-techlabs.com http://www.b-techlabs.com
-------- Original message --------From: Jonathan Magnan <notifications@github.com> Date: 7/10/17  10:14 PM  (GMT-05:00) To: zzzprojects/html-agility-pack <html-agility-pack@noreply.github.com> Cc: Bobby Harrell <bobbyharrell@b-techlabs.com>, Mention <mention@noreply.github.com> Subject: Re: [zzzprojects/html-agility-pack] V1.5 breaks webview events (#34) 
Hello @bobbydharrell ,
What's the relation within webview/navigation completed event and Html Agility Pack?
From the description provided, it looks that you don't need HAP to reproduce this issue.
So I'm not sure what we need to fix.
Best Regards,
Jonathan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zzzprojects/html-agility-pack","title":"zzzprojects/html-agility-pack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zzzprojects/html-agility-pack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JonathanMagnan in #34: Hello @bobbydharrell ,\r\n\r\nWhat's the relation within webview/navigation completed event and Html Agility Pack?\r\n\r\nFrom the description provided, it looks that you don't need HAP to reproduce this issue.\r\n\r\nSo I'm not sure what we need to fix.\r\n\r\nBest Regards,\r\n\r\nJonathan"}],"action":{"name":"View Issue","url":"https://github.com/zzzprojects/html-agility-pack/issues/34#issuecomment-314302986"}}}

**Comment by JonathanMagnan** [comment]
Hello @bobbydharrell ,

We have not received yet your code snippet,

Best Regards,

Jonathan

**Comment by bobbydharrell** [comment]
My sincerest apologies!!!! I did forget to post back, I am sorry!

You can actually delete this thread, I can no longer duplicate the issue in order to provide any more details, 1.5 and 1.5.1 are working fine. 

Thank you!

**Comment by JonathanMagnan** [comment]
Thank you for letting me know ;)

Best Regards,

Jonathan
