### ISSUE TITLE
Iterating (foreach) over HtmlNodeCollection seemingly only execute operations on the first node

### ISSUE THREAD

**Issue by vikekh** [zzzprojects/html-agility-pack#340]
### Description

I am quite new to HtmlAgilityPack and XPath, but I am selecting a table and then its row `<tr>` elements. I then iterate (foreach) over the returned HtmlNodeCollection, but even though `InnerHtml` changes for each node in the loop, the queries I am performing on each `<tr>` node seems to return based on the very first node.

I have successfully created a fiddle which shows the behavior. I print the InnerHtml and then the object created via HtmlAgilityPack operations, and they never match except for the first one.

### Exception

N/A

### Fiddle or Project

[https://dotnetfiddle.net/A2I4CQ](https://dotnetfiddle.net/A2I4CQ)
[https://stackoverflow.com/questions/58478726/looping-through-htmlnodes-and-collecting-data-gives-me-the-same-result-every-tim](https://stackoverflow.com/questions/58478726/looping-through-htmlnodes-and-collecting-data-gives-me-the-same-result-every-tim)

### Further technical details

- HAP version: v1.11.16
- NET version: Core v3.0

**Comment by JonathanMagnan** [comment]
Hello @vikekh ,

You need to use `.//` and not `//`

Here is the fixed Fiddle: https://dotnetfiddle.net/dZkSRN

`//` will search anywhere in the document.
`.//` will search anywhere in the current node

Let me know if that work

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @vikekh,

A simple follow up to see if you were able to try it.

Looking forward to hearing from you, 

Jon
