### ISSUE TITLE
Get wrong child nodes 

### ISSUE THREAD

**Issue by rocketRobin** [zzzprojects/html-agility-pack#341]
### Description
HtmlNode.ChildNodes gets wrong children

html is:

```
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta http-equiv='X-UA-Compatible' content='ie=edge' charset=utf-8">

</head>

<body>
    <div class="information-desc">
        <p>
            <span>
                测试
            </span>
        </p>
        <p>
            <span>更重要的是，女人戏总是会容易流于平面最后就剩下了谈情说爱</span>+<span>撕逼。</span>
            <ul>
                <li>test1</li>
                <li>test2</li>
                <li>test3</li>
            </ul>
        </p>
    </div>
</body>

</html>
```
and the code

```
var fileString = File.ReadAllText("demo.html");
var doc = new HtmlDocument();
doc.LoadHtml(fileString);
var node = doc.DocumentNode.SelectSingleNode("//div[@class='information-desc']");
```

and the node's value

![图片](https://user-images.githubusercontent.com/9987850/67926763-d6be5a00-fbf1-11e9-8e69-697f6425f287.png)

hap version

1.11.16

please fix this problem, my project has really rely on HAP , thanks a lot

**Comment by JonathanMagnan** [comment]
A `ul` cannot be inside of a `p` tag.

Our code currently handles this code like a browser and close the `p` tag prior to opening the `ul` tag.

You can currently remove this current logic with the following code:

```
HtmlDocument.DisableBehaviorTagP = false;
```

Let me know if that fixes your current issue.

Best Regards,

Jon

**Comment by rocketRobin** [comment]
That works! thanks a lot.  👍

**Comment by JonathanMagnan** [comment]
Hello @rocketRobin,

A simple follow-up to see if you are still satisfied with our library?
 
Let us know if you have any questions, feedback, or issues.

Looking forward to hearing from you,

Jon
