### ISSUE TITLE
HtmlWeb's LoadFromBrowser can't load site

### ISSUE THREAD

**Issue by axtens** [zzzprojects/html-agility-pack#344]
### Description
HtmlWeb's LoadFromBrowser struggles to load from certain site, requiring use of .Load() instead. This is with a 5 minute timeout. I haven't tried with anything longer than that. An example site is "https://www.murdocheye.com.au/latest-news/".

### Exception
It's not particularly helpful. Would longer than 5 minutes help?
```
Unhandled Exception: System.Exception: WebBrowser Execution Timeout Expired. The timeout period elapsed prior to completion of the operation. To avoid this error, increase the WebBrowserTimeout value or set it to 0 (unlimited).
   at HtmlAgilityPack.HtmlWeb.LoadFromBrowser(String url, Func`2 isBrowserScriptCompleted) in C:\Repos\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlWeb.cs:line 2512
   at HtmlAgilityPack.HtmlWeb.LoadFromBrowser(String url) in C:\Repos\HtmlAgilityPack\HtmlAgilityPack.Shared\HtmlWeb.cs:line 2399
   at HAPBug.Program.Main(String[] args) in C:\Users\bugma\Source\Repos\HAPBug\Program.cs:line 31
```
### Fiddle or Project
https://dotnetfiddle.net/scPltC
Don't know how to make it run there though.

### Further technical details
- HAP version: 1.11.16
- NET version 4.8

**Comment by JonathanMagnan** [comment]
Hello @axtens ,

The `LoadFromBrowser` uses the `WebBrowser` from Microsoft under the hood.

There is not too much we can do here. I suggest trying a true web browser to grab the HTML instead: https://selenium.dev/

Perhaps you will have more success.

Let me know if that helped you.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
