### ISSUE TITLE
HtmlWeb's LoadFromBrowser causes IE windows to appear

### ISSUE THREAD

**Issue by axtens** [zzzprojects/html-agility-pack#345]
### Description
While stepping through a list of URLs and using LoadFromBrowser to access them, sometimes an Internet Explorer window appears and gathers tabs titled "This page can't be displayed."

The address bar contains variants on the following: 
`res://ieframe.dll/navcancl.htm%20-#https://bullocks.net.au/cargo/oolu1589778/`
`res://ieframe.dll/navcancl.htm%20-#https://bullocks.net.au/cargo/moru1102339/`

### Further technical details
- HAP version: 1.11.16
- NET version: net48
- OS: Windows Server 2012 R2 (Azure)
- Happening with <https://github.com/axtens/HAPBug>

**Comment by JonathanMagnan** [comment]
Hello @axtens ,

I don't think there is anything we could really do on this one.

We use the `WebBrowser` from Microsoft under the hood, so we are very limited here on what we can do. One alternative could be to grab the `HTML` via https://selenium.dev/ instead.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @axtens 

A simple follow up to see if you tried the HTML via Selenium. 

Don't hesitate to contact us for questions, issues or feedback.

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello, @axtens,

Since our last conversation, we haven't heard from you. 

Was the alternative of HTML on Selenium successful?

looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @axtens,

Unfortunately, we didn't get the chance to hear your feedback. 

However, we will close this issue since we weren't able to reach you. 

Feel free to contact us for questions, issues or feedback.

Best Regards,

Jon
