### ISSUE TITLE
Element not return smart xpath i need smart xpath 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [zzzprojects/html-agility-pack#349]
Hi @JonathanMagnan 

i am explain with example :
i have open Google.com all html load load in dom
```
HtmlAgilityPack.HtmlDocument doc = new HtmlAgilityPack.HtmlDocument();
doc.LoadHtml(HTMLDoc);
var p = doc.DocumentNode.SelectSingleNode("//*[@id='hplogo']");
var xx = p.XPath;
```

Here , xx  variable has xpath :  /html/body/div/div[7]/span/center/div[1]/img
But i need //*[@id='hplogo'] smart xpath 

There are chromium driver native using for smart xpath logic 
https://github.com/chromium/chromium/blob/77578ccb4082ae20a9326d9e673225f1189ebb63/third_party/blink/renderer/devtools/front_end/elements/DOMPath.js#L242

so , i think you understand this issue about generate smart xpath

**Comment by JonathanMagnan** [comment]
Hello @rajesh-smartwebtech ,

Thank you for reporting.

We will look at what the `smart xpath` is

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by rajesh-smartwebtech** [comment]
Hi @JonathanMagnan 
Thank you
is it possible in Performance Libraries ??

**Comment by JonathanMagnan** [comment]
Hello @rajesh-smartwebtech ,

I have checked your request but I believe we already support your "smart xpath": https://dotnetfiddle.net/cUEupp

You can already use xpath expression when searching.

Is it what you were looking for?

**Comment by rajesh-smartwebtech** [comment]
Hi , @JonathanMagnan 
I have checked this it working well 
but one element i get xpath that time not return smart xpath 

"smart xpath" with find element is working best !

Thank you

**Comment by JonathanMagnan** [comment]
I'm not sure if everything now works or you need something else?
