### ISSUE TITLE
.NET 2.0 binary is missing from latest packages

### ISSUE THREAD

**Issue by steveshort455** [zzzprojects/html-agility-pack#351]
### Description
The most recent two NUGET packages, 1.11.17 and 1.11.16, do not contain the .NET 2.0 binary, The last package containing it is 1.11.15. Please can this be added back into the NUGET package ?

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- HAP version:
- NET version (net472, netcore, etc.):

**Comment by JonathanMagnan** [comment]
Hello @steveshort455 ,

Unfortunately no,

limiting ourselves to the v2.0 just make the support harder.

At one point, people need to upgrade either their framework or stick with the latest version that support .NET Framework 2.0

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
