### ISSUE TITLE
HtmlAgilityPack unable to parse html with <title/>

### ISSUE THREAD

**Issue by ac-lap** [zzzprojects/html-agility-pack#352]
I have the following html string (simplified version of the html which is not controlled by me) -

```
<html>
  <head>
    <title/>
  </head>
  <body>
    <p>
      Hello How are you doing?
    </p>
  </body>
</html>
```
and I am using the following code to parse it using HtmlAgilityPack -

```
HtmlDocument htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(htmlStr);
```
but this is the value of `htmlDoc.DocumentNode.InnerHtml`

```
<html>
  <head>
    <title></title></head></html>
```
As you can see the html was not parsed correctly.

On some trial and error I noticed that on replacing `<title/>` in the html string with `<title></title>`, the doc was parsed correctly.

Any idea/help on how to parse such html doc with HAP correctly?

### Further technical details
- HAP version: 1.11.17
- NET version: both net472 and netcore

**Comment by leus** [comment]
This looks like a bug. It's invalid HTML but not too serious as to ignore the whole body. Here's a fiddle: https://dotnetfiddle.net/CZv09l

**Comment by ac-lap** [comment]
@leus Thanks for the fiddle. Following up on this I checked with some other self-closed tags in the html and found that it kind of breaks with `<p/>` as well

```
<html>
  <body>
    <p>
    <p/>
      Hello World!
    </p>
  </body>
</html>
```
is parsed as 
```
<html>
  <body>
    <p>
    <p></p>
      Hello World!
    
  </body>
</html>
```
Fiddle link - https://dotnetfiddle.net/VGJ1G6

**Comment by Birgerg** [comment]
Is there any solution to this bug on the horizon ?
We are experiencing this with the title tag, and it's very serious bug, since all further parsing breaks, and removes entire body.

**Comment by JonathanMagnan** [comment]
Hello @Birgerg ,

You can remove the `title` behavior using the following code:

```csharp
HtmlNode.ElementsFlags.Remove("title");
```

Fiddle: https://dotnetfiddle.net/VoXl1m

Unfortunately, the `title` tag requires the end of the `title` element. Even Firefox or Chrome put even the body in the `title` when there is no closing:

[title_change_txt_to_html.txt](https://github.com/zzzprojects/html-agility-pack/files/6617601/title_change_txt_to_html.txt)

Best Regards,

Jon

**Comment by leus** [comment]
> You can remove the `title` behavior using the following code:

That workaround is hardly useful. But at least it is good to know that Chrome displays the same behaviour.
