### ISSUE TITLE
Attribute Value from Two Identical Ones

### ISSUE THREAD

**Issue by ahmar20** [zzzprojects/html-agility-pack#353]
### Description
I am working with some html where some of the elements contain multiple attributes with same names for example see the following:
```
<video id="vjsplayer" height="480" width="640" class="video-js  vjs-default-skin vjs-16-9" style="width:100%;height:100%;text-align:center;" width="100%" height="100%" crossorigin="anonymous" controls="true" preload="metadata" poster="https://thumb.cloudvideo.tv/74/01/00225/wg3w4i538nsv_xt.jpg">
--
</video>
```
Now I tried to get the attribute value from the html above and it returns the value for last "height" and "width" tags but I want to get the values of the first ones. What is the correct way of doing this? I am currently using `GetAttributeValue()` for this purpose.

I am using latest stable version of HtmlAgilityPack in an Android app.

**Comment by JonathanMagnan** [comment]
Hello @ahmar20 ,

Unfortunately, that's not supported.

If the html has multiple times the same attribute, only the last one will be taken by our library.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ahmar20** [comment]
Alright, thank you for clarifying. I am trying to get the value by the index of the attribute for now.
