### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by moyanming** [zzzprojects/html-agility-pack#356]
Hi,
HtmlAgilityPack v1.11.17 with VS2019 16.0.2, UWP.
`string site = @"https://www.baidu.com";
            try
            {
                HtmlWeb Web = new HtmlWeb();
                var doc = Web.Load(site);
            }
            catch { }`
There is en error: {"An error occurred while sending the request."}
StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at HtmlAgilityPack.HtmlWeb.Get(Uri uri, String method, String path, HtmlDocument doc, IWebProxy proxy, ICredentials creds)
   at HtmlAgilityPack.HtmlWeb.LoadUrl(Uri uri, String method, IWebProxy proxy, ICredentials creds)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at HtmlAgilityPack.HtmlWeb.Load(String url)

The StrackTrace of the InnerExceptions are:
at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

It seems that there is an error when used with the async and await within the HtmlAgilityPack!
Any ideas?

**Comment by JonathanMagnan** [comment]
Unfortunately no,

It looks more like an issue caused by the `HttpClient`. We tried on our side and it works well.

Could you try directly to make a web request, For example: https://stackoverflow.com/a/32932186/5619143

Is there any `InnerException`?

**Comment by moyanming** [comment]
Yes, this error comes from the [System.Net.Http.HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netstandard-2.1)!
This because the UWP project may can't use the System.Net.Http.HttpClient at all! There are more strange errors when using System.Net.Http.HttpClient. The UWP project should use [Windows.Web.Http.HttpClient](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient).
Those codes are tested and work fine:
`
static string EdgeUserAgent = @"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363";
static async Task<string> GetHtmlText(string urlStr)
        {
            string text = null;
            try
            {
                using (var client = new windows.web.http.HttpClient())
                {
                    var headers = client.DefaultRequestHeaders;
                    headers.UserAgent.TryParseAdd(EdgeUserAgent);
                    var pMsg = await client.GetAsync(new Uri(urlStr));
                    if (string.IsNullOrWhiteSpace(pMsg.Content.Headers.ContentType.CharSet))
                    {
                        pMsg.Content.Headers.ContentType.CharSet = "utf-8";
                    }
                    text = await pMsg.Content.ReadAsStringAsync();
                }
            }
            catch { }
            return text;
        }`
`string htmlText = await GetHtmlText(urlStr);
HtmlDocument doc = new HtmlDocument();
doc.LoadHtml(htmlText);`
