### ISSUE TITLE
There is no need "ConfigureAwait(false)"!

### ISSUE THREAD

**Issue by moyanming** [zzzprojects/html-agility-pack#357]
Hi,
There is an "await" of the 
`var e = await client.GetAsync(uri, cancellationToken);`
There is no need to add the ConfigureAwait(false) at all!

https://github.com/zzzprojects/html-agility-pack/blob/5f82294ea08802aac90d53074f6eef6f934634eb/src/HtmlAgilityPack.Shared/HtmlWeb.cs#L2353

**Comment by JonathanMagnan** [comment]
Unless I'm wrong, not adding ConfigureAwait(false) will cause a deadlock in non-async button method for example.

One rule of thumb we have is to always add a `ConfigureAwait(false)

While it's not needed for your application, that's mandatory in a third-party library. Here is an example of a multiple answers you can find about it: https://stackoverflow.com/a/56304619/5619143

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by moyanming** [comment]
Yes, the ConfigureAwait(false) is the right way within the library.
If use async all the way down may be the best way.
Please refer to this [site](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html):
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
![QQ浏览器截图20200129111153](https://user-images.githubusercontent.com/13234209/73325172-670b4a00-4288-11ea-83f9-5944b00b70f1.png)
![QQ浏览器截图20200129111231](https://user-images.githubusercontent.com/13234209/73325174-6bcffe00-4288-11ea-869b-69c0750c2e56.png)
