### ISSUE TITLE
HtmlAttribute escaping

### ISSUE THREAD

**Issue by thurfir** [zzzprojects/html-agility-pack#358]
Hi, we are using the HtmlAgilityPack to build Razor pages. In Razor, this is a valid syntax:

`<div myprop="@GetMyProp("myKey")" ></div>`

However since a few minor versions (1.11.4 => 1.11.17) we no longer can use this syntax in HtmlAgilityPack  as the HtmlAttribute Value fields are escaped on render:

                var attr = node.Attributes["myprop"];
                attr.Value = "@GetMyProp(\"myKey\")";
Becomes: `<div myprop="@GetMyProp(&quot;myKey&quot;)" ></div>`

Is there another way to set an attribute value without escaping?

**Comment by JonathanMagnan** [comment]
Hello @thurfir ,

Unfortunately, I don't think unless you keep referencing a lower version ;(

We could always add an option for not escaping if there attribute start with the `@` but then, it will not work if the code is inside a string such as `"zzz" + @GetMyProp(\"myKey\")`

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by thurfir** [comment]
Hello @JonathanMagnan , thanks for your answer . Disabling escaping if the attribute starts with an @ would be enough in our case, if we need some concat we can always use  @("a" + "b") .

Best regards,
thurfir

**Comment by JonathanMagnan** [comment]
Hello @thurfir ,

The v1.11.18 has been released.

As said, we will support only this case when the attribute start with '@'

Could you confirm that everything is now working?

Best Regards,

Jon

**Comment by thurfir** [comment]
@JonathanMagnan it is working, thanks for the rescue 👍.

Best regards,
thurfir

**Comment by ArmanPopatKite** [comment]
Hi,
I just stumbled across this thread and would like to know if this option still exists? And how could I access it?
Thanks

**Comment by asawyermarathon** [comment]
I just tested with the @ symbol prefix and it worked, thanks.
