### ISSUE TITLE
Malformed output by simply load and saving a file

### ISSUE THREAD

**Issue by Dev-Owl** [zzzprojects/html-agility-pack#359]
### Description
If I load the example document provided below and simply save it again (to and from file) the HTML gets changed and results in broken content. The HTML document is a super simple example of a valid WebForms (ASP.NET) file with inline code using the <% %> operator (historical software, but something we have to use, [example in case somebody is curious](https://weblogs.asp.net/scottgu/new-lt-gt-syntax-for-html-encoding-output-in-asp-net-4-and-asp-net-mvc-2)).
The saved output changes the closing tag to from %> to %="">" , the mentioned tags are used only in attributes and should not be touched.

### Exception
No exception is thrown

### Fiddle or Project
This Gist includes the HTML and code to replicate the problem (input.html) and the result generated (output.html):
https://gist.github.com/Dev-Owl/6b166c08ce7519943f189c2d544a6f03

### Further technical details
- HAP version:1.11.17
- NET version (net472, netcore, etc.):netcore

**Comment by JonathanMagnan** [comment]
Hello @Dev-Owl ,

My developer looked at it and unfortunately, we choose to not do it at this moment.

While `HAP` sometimes accept `ServerSide` code syntax outside of attribute, that stays an HTML parser, so we don't want to complexity too much the code at this moment with all kind of server-side syntax.

Best Regards,

Jon
