### ISSUE TITLE
Unable to Validate HTML Tags and attributes Properly

### ISSUE THREAD

**Issue by NavaneethaDev** [zzzprojects/html-agility-pack#362]
### Description
I have a below case were i want to validate the below piece of HTML. If we observe I have removed "<" in the image tag and i also changed to "href" instead of src. Is there any option in HTML Agility Pack to validate these as well? 

`img href="<Image source>"  unselectable="on" alt="" style="width: 100%;"/>`
`<p><b >Content Content Content</b></p>`
`<p >Content Content Content Content Content Content Content Content Content</p>`

The HtmlDocument ParseErrors checks for only tags which are not closed properly.

**Comment by JonathanMagnan** [comment]
Hello @NavaneethaDev ,

Unfortunately no, we don't plan to add those kinds of validation at this moment either.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
