### ISSUE TITLE
Generic GetAttributeValue method

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#365]
Hi there,

Currently using 1.11.18

The method `GetAttributeValue` has 3 overrides: 1) Returning a string, 2) Returning a bool and 3) Returning a int.  
In my situration I may have a float or a decimal - How about even a JSON string?

So instead of overrides for each type, I purpose that perhaps you could do this with a generic method.  
Also each method accepts a default, but in C# 7.1 we can now use [default literals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default#default-literal) So you could write the single method like this:
```csharp
        public T GetAttributeValue<T>(string name, T def = default)
        {
            // TODO: Get the attribute
            return def;
        }
```

Also it doesn't seem you have attributes anywhere in your [documentation](https://html-agility-pack.net/documentation) ;-)

Whant ya think?

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

Thank you for your suggestion,

I will assign my developer to look at it.

Yup, we will need to eventually re-write this documentation. Unfortunately, it's hard to find this kind of time ;(

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

In the latest version, we added the generic method:

```csharp
public T GetAttributeValue<T>(string name, T def) 
```

Let me know if that's what you were looking for ;)

Best Regards,

Jon

**Comment by LukeTOBrien** [comment]
Thanks, that's awesome!
