### ISSUE TITLE
HtmlAttribueCollection - AttributesWithNames

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#366]
Further to #365 

HtmlAttributeCollection has a `AttributesWithName` method - You could also create a `AttributesWithNames` method that would accept a `param string[] names` as parameter.

```csharp
public IEnumerable<HtmlAttribute> AttributesWithNames(param string[] attributeNames)
{
  // TODO.
}
```

It would also be nice to return all attributes:

```csharp
public IEnumerable<HtmlAttribute> Get()
{
  // TODO.
}
```

That way we could use Linq methods to project the attributes into domain POCOs for eg.

What ya think?

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

We will try to check your 3 requests this week.

I will let you know once my developer looks at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

In the latest versions, we added the following methods:

```csharp
public IEnumerable<HtmlAttribute> GetAttributes(params string[] attributeNames)
```

Not exactly the same name as you but it does the same job ;)

**Comment by LukeTOBrien** [comment]
Thanks, thanks great!
