### ISSUE TITLE
HtmlDataCollection and HtmlDataAttribute type

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#367]
Hi there,

I have been consider a method to get the `data-` attribut of a HtmlNode.  
In my currenct project I am using jQuery with jsdom on NodeJS platform.  
JQuery has a [Data() method](https://api.jquery.com/data/#data) which I am using.  
This method returns and anonymous object that I can iterate over.

So I purpose the same kind of thing in HAP:  
```html
<element data-first="first value" data-second="second value" data-third="third value"></element>
```
Then in C# code:
```csharp
var value = element.Data["first"];  // first value
```

What ya think?

**Comment by LukeTOBrien** [comment]
Likewise with #366 there should be a `Get` method (or an `All` property) to get an IEnumable:
```csharp
public IEnumerable<HtmlAttribute> Get()
{
  // TODO.
}
```

**Comment by LukeTOBrien** [comment]
If we do `Attributes.AttributesWithName("data") would that get all the `data-` attributes?

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

We will try to check your 3 requests this week.

I will let you know once my developer looks at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

In the latest versions, we added the following methods:

```csharp
public HtmlAttribute GetDataAttribute(string key)
public IEnumerable<HtmlAttribute> GetDataAttributes()
```

You only need to specify the last part in the `key` parameter.

Let me know if that's what you were looking for.

**Comment by LukeTOBrien** [comment]
Thanks for all these!
The `data-` one is most useful.

You have the best support from any open-source project I have ever seen!

**Comment by JonathanMagnan** [comment]
Thanks for these kind words @LukeTOBrien !

Feel free to contact us for questions, issues or feedback :)

Best regards,

Jon
