### ISSUE TITLE
HTML agility pack is adding unnecessary string to the outer html

### ISSUE THREAD

**Issue by FurkanGozukara** [zzzprojects/html-agility-pack#368]
I am trying to remove class, style and such attributes from given tagged string

for example string is

`<math>K_B \cap\left \{ |k| < \beta\right \} </math>`

Once i load it to the HtmlDocument it becomes as below

`<math>K_B \cap\left \{ |k| < \beta\right="" \}=""></math>`

![image](https://user-images.githubusercontent.com/19240467/74093966-b18f9080-4aea-11ea-967c-1200c6e8fd7d.png)

How can I prevent this behavior from happening? Because this behavior is breaking my code

My aim is for example if string is like below

`<math style="gg" class="cg" >K_B \cap\left \{ |k| < \beta\right \} </math>`

Turning it like below

`<math>K_B \cap\left \{ |k| < \beta\right \} </math>`

full thread here https://stackoverflow.com/questions/60132255/html-agility-pack-is-adding-unnecessary-string-to-the-outer-html

**Comment by JonathanMagnan** [comment]
Hello @FurkanGozukara ,

I will check with my developer if we can add an option so that `< \` doesn't become considered as a tag which is currently the issue probably

**Comment by JonathanMagnan** [comment]
Hello @FurkanGozukara ,

Do you think you could provide us a runnable example that has this error?

My developer tried it but using your first example, he doesn't get any error.

See the following online example: https://dotnetfiddle.net/HT3Ynt

**Comment by FurkanGozukara** [comment]
> Hello @FurkanGozukara ,
> 
> Do you think you could provide us a runnable example that has this error?
> 
> My developer tried it but using your first example, he doesn't get any error.
> 
> See the following online example: https://dotnetfiddle.net/HT3Ynt

You are right. It turns out that my HtmlAgilityPack version was 1.4.9.5

Updated to latest and fixed :) Ty very much
