### ISSUE TITLE
SelectNodes from HtmlNode

### ISSUE THREAD

**Issue by alirezaseif28** [zzzprojects/html-agility-pack#369]
Hi.
I am a html Document.contain id attribute.
a id has a distinct structure.example :
ContentPlaceHolder1_rptAttributeSet_rptAttribute_0_lblAttributeTitle_0
ContentPlaceHolder1_rptAttributeSet_rptAttribute_0_lblAttributeTitle_1
ContentPlaceHolder1_rptAttributeSet_rptAttribute_0_lblAttributeTitle_2.

how select element by structure id by patern.?
thanks

**Comment by JonathanMagnan** [comment]
Hello @alirezaseif28 ,

Here is an example to get you started: https://dotnetfiddle.net/K3kF9u

```csharp
var htmlNodes = htmlDoc.DocumentNode.SelectNodes("//*[@*[contains(@id, 'ContentPlaceHolder1_rptAttributeSet_rptAttribute_0_lblAttributeTitle_')]]");
```

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by alirezaseif28** [comment]
Hello @JonathanMagnan .
very good for reply.
If I want pattern example
'ContentPlaceHolder1_rptAttributeSet_rptAttribute_0_lblAttributeTitle_0'
'ContentPlaceHolder1_rptAttributeSet_rptAttribute_1_lblAttributeTitle_1'
'ContentPlaceHolder1_rptAttributeSet_rptAttribute_2_lblAttributeTitle_2'
How should I work.?
Best Regards,

**Comment by JonathanMagnan** [comment]
I'm not exactly sure about what you want.

The easy answer would be

```csharp
var htmlNodes = htmlDoc.DocumentNode.SelectNodes("//*[@*[contains(@id, 'ContentPlaceHolder1_rptAttributeSet_rptAttribute_')]]");
```

But that's probably not that.

**Comment by alirezaseif28** [comment]
Thancks a lot.
How Write Pattern look like below
ContentPlaceHolder1_rptAttributeSet_rptAttribute_{digit}_lblAttributeTitle_{digit}

**Comment by JonathanMagnan** [comment]
Hello @alirezaseif28 ,

Unfortunately, for this one, I don't know ;(

I'm not sure if `xpath` support those kinds of pattern or not.

**Comment by alirezaseif28** [comment]
Hello @JonathanMagnan 
Thanks for the help with the documentation.
