### ISSUE TITLE
Issues with unclosed CData tags: style/script.

### ISSUE THREAD

**Issue by janis-veinbergs** [zzzprojects/html-agility-pack#372]
### Description
Input:
```
<html>
  <head>
    <style>
  </head>
  <body>
    <p>Test content</p>
  </body>
</html>
```

Gives output:
```
<html>
  <head>
    <style></style></head></html>
```

Same goes for other [CData tag](https://github.com/pinscript/HtmlAgilityPack/blob/d36ae585beb9a2d879c717aab7e91ecb2cc8d4d4/Source/HtmlAgilityPack/HtmlNode.cs#L81): script. If it' s not closed, DOM parser will loose other tags like in this case whole `body` is lost.

By setting `HtmlNode.ElementsFlags["style"] = HtmlElementFlag.Empty;` the issue is solved. Was monkeying around and tried to set `HtmlElementFlag.CData | HtmlElementFlag.Empty`, but the issue comes back.

I don't know the consequences of changing/setting these flags. Wanted to know if there is a way it should be solved on my side by setting some flags or maybe this is really an issue in HAP?

This got uncovered in a project that uses HAP: https://github.com/mysticmind/reversemarkdown-net/issues/61

### Fiddle or Project
https://dotnetfiddle.net/xEgXGN

### Further technical details
- HAP version: 1.11.18
- NET version: net472

**Comment by JonathanMagnan** [comment]
Hello @janis-veinbergs ,

Thank you for reporting.

Not sure if we want to do something here or not as those tags must be closed.

Even the browser will break on this and have the following html

```html
<html class="gr__"><head>
    <style>
  </head>
  <body>
    <p>Test content</p>
  </body>
</html></style></head><body data-gr-c-s-loaded="true"></body></html>
```

So no text is displayed.

Better than our library but will not work either.

**Comment by janis-veinbergs** [comment]
Alright, that's probably fair. Thanks for responsivness.
