### ISSUE TITLE
Problem of HtmlNode.SelectNodes(string xpath) method

### ISSUE THREAD

**Issue by Leonid1965** [zzzprojects/html-agility-pack#373]
HtmlAgilityPack Version="1.11.18". 
HtmlNode.SelectNodes(string xpath)  method start to search from document root node
instead of node, that it activated from.

**Comment by JonathanMagnan** [comment]
Hello @Leonid1965 ,

Your issue currently look similar to this one: https://github.com/zzzprojects/html-agility-pack/issues/251#issuecomment-425730930

If that's not the case, please provide us a runnable example so we could check it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Leonid1965** [comment]
Hello Jonathan,

If you call method from node of middle part of document it need to start from this point because this is new sub document search by definition. 

Best Regard,
Leo
