### ISSUE TITLE
Duplicate id when setting it using HtmlNode.Id

### ISSUE THREAD

**Issue by EdwinStoteler** [zzzprojects/html-agility-pack#374]
### Description
You get Duplicate id when setting it using HtmlNode.Id. This seems to be happening when the node already had an Id and you set a different one.

### Fiddle or Project
https://dotnetfiddle.net/OGnU9L

(its giving me an internal server error right now, so here is the code) 
```
                var html = @"<body>
                          <div id=""a""></div>
                </body>";
		var htmlDoc = new HtmlDocument()
		{
			OptionEmptyCollection = true, 
			OptionUseIdAttribute = true
		};
		htmlDoc.LoadHtml(html);
		var htmlBody = htmlDoc.DocumentNode.SelectSingleNode("//body");
		HtmlNode oldChild = htmlBody.ChildNodes[1];
		oldChild.Id = "test";
		Console.WriteLine(oldChild.OuterHtml);
```

Workarround: dtControl.SetAttributeValue("id", "test")

**Comment by JonathanMagnan** [comment]
Weird but that definitely looks like an issue.

My developer will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @EdwinStoteler ,

The v1.11.20 has been released.

Could you check it and let us know if everything work as expected now with the `id`?

**Comment by EdwinStoteler** [comment]
Hello @JonathanMagnan ,

The problem seems to be solved, thx for the quick release.
