### ISSUE TITLE
Method not found: 'Int32 HtmlAgilityPack.HtmlNode.GetAttributeValue (binary breaking change)

### ISSUE THREAD

**Issue by ronaldbarendse** [zzzprojects/html-agility-pack#375]
### Description
After upgrading from 1.11.18 to 1.11.19 (or 1.11.20) the following exception is thrown, because this method is removed for some targets:

https://github.com/zzzprojects/html-agility-pack/blob/8d89711919814924751b84b6716a768546a3076f/src/HtmlAgilityPack.Shared/HtmlNode.cs#L1316-L1324

This is a binary breaking change, as libraries using this method will need to be recompiled against this version to work again.

### Exception
```
Exception message: Method not found: 'Int32 HtmlAgilityPack.HtmlNode.GetAttributeValue(System.String, Int32)'.
Stack trace: System.MissingMethodException
```

### Further technical details
- NET version (net472, netcore, etc.): net472

**Comment by JonathanMagnan** [comment]
Hello @ronaldbarendse ,

Yes, you are right.

I will ask my developer to restore those methods and explain to him why he never removes one unless we release a major.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ronaldbarendse** [comment]
These kind of breaking changes are always hard to track, as you would expect it to automatically use the generic method in this case... :wink: And it does without changing the consuming libraries code, but it still requires a recompile, because the binary/IL code will be different.

Adding the methods back for these targets as stubs that call the generic version should be an easy fix :+1: The next major version could then remove these methods again.

**Comment by JonathanMagnan** [comment]
Yup exactly ;)

The v1.11.21 is now released.

Let me know if your project is now working correctly

**Comment by ronaldbarendse** [comment]
Thanks, this patch has fixed the issue 👍
