### ISSUE TITLE
I can't run the Tests in Visual Studio

### ISSUE THREAD

**Issue by parsalotfy** [zzzprojects/html-agility-pack#377]
### Description
Hi,
after cloning the project in Visual Studio 2019 , I wanted to run the tests in TestExplorer.
After hitting the RunAll button, it takes 2 second and then all tests stayed at **NotRun** status as you can see below :

![haptests](https://user-images.githubusercontent.com/30390810/75355594-ffb2db00-58c3-11ea-8cc0-4e51db5226e2.jpg)

I have opened this issue to ask you how I can run these tests ?

I have also another question, is it okay to create a xUnit project in the \src\Tests folder and create some tests for Encapsulator in order to making a pull request ?
Or I should make them in current existing nUnit test project ?

I myself prefer using **xUnit** project if it is acceptable :-)

Regards,
Parsa Lotfy

**Comment by JonathanMagnan** [comment]
Hello @parsalotfy ,

You are right. It looks test doesn't run with `Visual Studio` but using Resharp unit test (which we use), they run without problem.

Sure, it's fine to create test using xUnit in another project.
