### ISSUE TITLE
Does it support Linux?

### ISSUE THREAD

**Issue by he852100** [zzzprojects/html-agility-pack#378]
### Description
Describe the issue or proposed feature.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:

 trace:
InvalidOperation: Method invocation failed because [HtmlAgilityPack.HtmlNode] does not contain a method named 'SelectSingleNode'.


```

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- HAP version:
- NET version (net472, netcore, etc.):

**Comment by JonathanMagnan** [comment]
Are you using the .NET Standard 2.0 dll? Or your project point to another dll?

If yes, could you provide a project with the issue as we cannot reproduce it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
