### ISSUE TITLE
Support for .Net versions > 4.5

### ISSUE THREAD

**Issue by forger** [zzzprojects/html-agility-pack#383]
Are there any plans to add support for .Net versions > 4.5?

**Comment by JonathanMagnan** [comment]
Hello @forger ,

What's the point to release for other version? The .NET45 version already works in a higher version of the .NET Framework.

So we already support .NET Framework 4.8

Let me know if that answers correctly to your question.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
