### ISSUE TITLE
...........

### ISSUE THREAD

**Issue by sezooka** [zzzprojects/html-agility-pack#384]
......

**Comment by zgabi** [comment]
Why did you "delete" the bug description? I think you are right.. the last should have count = 3.

**Comment by JonathanMagnan** [comment]
Hello @sezooka , @zgabi ,

We also got the issue by email so I can still answer even if the description has been deleted.

Some child nodes are text (newline character). That’s why the count is different. (look to be different from the text in the description than the one provided by email)

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
