### ISSUE TITLE
bad URL in docs

### ISSUE THREAD

**Issue by DickBaker** [zzzprojects/html-agility-pack#387]
documentation is missing ".net" on page
https://github.com/zzzprojects/html-agility-pack/blob/master/docs2/pages/documentations/parser/from-browser.md

so the line that is currently
string url = "http://html-agility-pack/from-browser";
should read
string url = "http://html-agility-pack.net/from-browser";

**Comment by JonathanMagnan** [comment]
Hello @DickBaker ,

Thank you for reporting.

The documentation is actually elsewhere but you are right, the wrong URL was in the docs.

We fixed it and released a new version of the website.

Have a great day ;)

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
