### ISSUE TITLE
I got System.IO.PathTooLongException when I'm using DownloadData function

### ISSUE THREAD

**Issue by CoreCarnage** [zzzprojects/html-agility-pack#389]
Hi all,

I'm trying to open  an url by callig function DownloadData of class WebClient.

This is my code.

WebClient wClient = new WebClient();
byte[] data = wClient.DownloadData(url);

When the url exceed 260 characters, I got a PathTooLongExeception.

I'm using the last version of HtmlAgilitypack.

### Exception
System.IO.PathTooLongException occurred
  HResult=0x800700CE
  Message=The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Thanks for the help

**Comment by zgabi** [comment]
But how is this issue related to HtmlAgilityPack? WebClient is in the .NET, it was created by Microsoft.

**Comment by CoreCarnage** [comment]
Thank you. I was so into it, I didn't notice.

It seems that it is a known issue, I'm going to update my framework projet to 4.6.2.

Cheers

**Comment by CoreCarnage** [comment]
My issue is fixed.

 I had to use an Uri instead of String as an Address.
