### ISSUE TITLE
Multiple node elments can't be created Exception

### ISSUE THREAD

**Issue by moikot** [zzzprojects/html-agility-pack#394]
### Description

```csharp
var html = "<p><table>FOO</table><table>BAR</table></p>";
var htmlNode = HtmlNode.CreateNode(html);
```

Throws exception: Multiple node elments can't be created.

### Exception

```
Exception message: Multiple node elments can't be created.
Stack trace:
System.Exception : Multiple node elments can't be created.
   at HtmlAgilityPack.HtmlNode.CreateNode(String html)
```

### Fiddle or Project
https://dotnetfiddle.net/jfdjpB

### Further technical details
- HAP version: 1.11.24
- NET version netcore 3.1

Worked fine in HAP 1.8.14

**Comment by JonathanMagnan** [comment]
Hello @moikot ,

Sorry for the waiting time.

Unfortunately, this issue happen cause we fixed the `P` tag.

> HTML does not allow a paragraph to contain a table.

Ref: https://stackoverflow.com/a/28042932/5619143

This is still possible to go back to the old behavior by disabling the new P behavior `HtmlDocument.DisableBehaviorTagP = false;`

```csharp
HtmlDocument.DisableBehaviorTagP = false;
var html = "<p><table>FOO</table><table>BAR</table></p>";
var htmlNode = HtmlNode.CreateNode(html);
```

Let me know if that solves your issue.

Best Regards,

Jon

**Comment by moikot** [comment]
Hello @JonathanMagnan ,

Thank you for the clarification. As soon as it's not allowed by HTML and there is a workaround, I'm good.
