### ISSUE TITLE
Disposing HTMLWeb

### ISSUE THREAD

**Issue by taha-ghadirian** [zzzprojects/html-agility-pack#395]
Hello. I need to Dispose HtmlWeb because its use a lot ram.
can any one help me?
how can I manage memory used by HTMLAgilityPack?

**Comment by JonathanMagnan** [comment]
Hello @taha-ghadirian ,

We already discussed about `IDispose` in another issue (https://github.com/zzzprojects/html-agility-pack/issues/370) and for now, we don't have any plan to add it.

We currently let the framework handle it like other variables.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
