### ISSUE TITLE
Parsing different collection elements, but output always as for collection[0]

### ISSUE THREAD

**Issue by opadfnezig** [zzzprojects/html-agility-pack#398]
**Description**
I'm trying to parse webpage, get all elements with same class and then parse each seperately. Of course I'm using collections.
Values of collection[a].InnerText and collection[b].InnerText are completely different, but when I'm trying to parse theese elements
(collection[a].SelectSingleNode(xpath).InnerText, collection[b].SelectSingleNode(xpath).InnerText) I always ressive parsed collection[0].
Also works for Lists.
**Fiddle or Project**
```
  class Program
    {
        static void Main(string[] args)
        {
            HtmlDocument doc = new HtmlDocument();
            doc.LoadHtml("<h3> <a class=\"marginright5\"> a1 <strong>text1</strong> </a> </h3>"
                       + "<h3> <a class=\"marginright5\"> a2 <strong>text2</strong> </a> </h3>");
            HtmlNodeCollection collection = doc.DocumentNode.SelectNodes("//a[@class=\"marginright5\"]");
            foreach (var i in collection)
                Console.WriteLine("ELEMENT_TEXT: " + i.InnerText + "PARSED_TEXT: " + i.SelectSingleNode("//strong").InnerText);
        }
    }
```
**Further technical details**
.Net Core project, framework version 3.1

**Comment by JonathanMagnan** [comment]
Hello @opadfnezig ,

- `\\` means relative to the document root
- `.\\` means relative to the current node

So you must use `.\\`

```csharp
HtmlDocument doc = new HtmlDocument();
doc.LoadHtml("<h3> <a class=\"marginright5\"> a1 <strong>text1</strong> </a> </h3>"
		   + "<h3> <a class=\"marginright5\"> a2 <strong>text2</strong> </a> </h3>");
HtmlNodeCollection collection = doc.DocumentNode.SelectNodes("//a[@class=\"marginright5\"]");
foreach (var i in collection)
	Console.WriteLine("ELEMENT_TEXT: " + i.InnerText + "PARSED_TEXT: " + i.SelectSingleNode(".//strong").InnerText);
```

Online Example: https://dotnetfiddle.net/NgA3C6 

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
