### ISSUE TITLE
NuGet package install error on VS2012

### ISSUE THREAD

**Issue by spaziosoft** [zzzprojects/html-agility-pack#40]
hi,
i m not an expert !
two year ago i have used this package successfully.
now, on my vs2012, when try to install the package result on this error "HtmlAgilityPack' already has a dependency defined for 'System.Net.Http'."

thanks for any support
regards

**Comment by JonathanMagnan** [comment]
Hello @spaziosoft ,

I'm not sure if this error is related to our library or to NuGet Package Manager. Could you try to use the latest version of NuGet as recommend from someone having something that looks to have the same issue as you: https://stackoverflow.com/questions/25725545/nuget-x-already-has-a-dependency-defined-for-y

Best Regards,

Jonathan

**Comment by spaziosoft** [comment]
Hello Jonathan,

thank for support
i have tryed that solutions, but not solve my issue
at this time the only solution is vs2015, try on another workstation and go well

Best regards,
giordano

**Comment by JonathanMagnan** [comment]
Np,

As said, it's probably an issue caused by NuGet.

Since you have an issue with the `System.Net.Http` reference, I will also assume you are using .NET Core

.NET Core reference can be a nightmare on VS2015 but work way better on VS2017.

Best Regards,

Jonathan

**Comment by yuanrui** [comment]
In VS 2010 install HtmlAgilityPack -Version 1.6.10	has same error :-(

**Comment by JonathanMagnan** [comment]
Hello @yuanrui ,

Make sure to have the latest `NuGet Package Manager`.

If that's the same error, there is nothing we can do about it since it's not related to the library. Some other library can throw a similar error.

The only way to fix it is ensuring to use the latest version of the `NuGet Package Manager`.

Best Regards,

Jonathan
