### ISSUE TITLE
Css Query Selectors - "nth-of-type"

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#402]
Hello there

I am using the [CssSelector](https://github.com/hcesar/HtmlAgilityPack.CssSelector) ad-on to your library, but I wondered if you would like to incorporate CSS Selectors into your offical project?  
The library doesn't seem to have been worked on since late 2017, so I would feel more confident using something offical from ZZZ,

Anywho, the CSS Selector business seems to work okay, but I have a requirement to use [nth-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) CSS selector.  
I have just this minute seen [this answer](https://html-agility-pack.net/knowledge-base/13501108/select-nth-child-node-in-html-document), but it will take me some time to study it and convert my CSS selector to XPath or use a combination of both, I have a CSS selector like this:
`SECTION.slide-1 H1:nth-of-type(1)`

Thanks,

Luke

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

Could you try https://www.nuget.org/packages/Fizzler.Systems.HtmlAgilityPack/ instead and see if that's working?

The owner of this library has made several awesome libraries around `HAP` and is usually is very pro-active when supporting features.

This is usually the library I recommend for `CSS Selectors`

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by LukeTOBrien** [comment]
Thanks - I haven't seen that libiray before.  
Turns out that it wasn't that tricky, just get the index in the collection.

```csharp
HtmlNode element = null;
if (sel.Contains("nth-of-type"))
{
	var splitty = sel.Split(':');
	var elements = rootNode.QuerySelectorAll(splitty[0]);
	var n = int.Parse(Regex.Match(splitty[1], @"(\d)").Value);
	element = elements[n - 1];
}
```

**Comment by LukeTOBrien** [comment]
I am going to reopen this because I have found that my basic workaround did not work for more complex nested selectors and the Fizzler library does not support `nth-of-type` either and is lacking some methods which I used in the [CssSelector ](https://github.com/hcesar/HtmlAgilityPack.CssSelector)

* Extension for `HtmlDocument`
* Extension for `HtmlNodeCollection`

I got the following error:
```
System.FormatException: Unknown functional pseudo 'nth-of-type'. Only nth-child and nth-last-child are supported.
```

I think it would be ideal to include an official CSS QuerySelector into HAP, I would feel more confident in code managed by ZZZ Projects

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

Unfortunately, with the current time we have, that's currently impossible on our side to do such request ;(

**Comment by LukeTOBrien** [comment]
This is the solution I came up with, I will close this as it works okay for my purposes:  
I am using the package `using HtmlAgilityPack.CssSelectors.NetCore;`

    public static class QuerySelectorExtensions
    {
        public static HtmlNode NthOfTypeQuerySelector(this HtmlNode element, string selector)
        {
            if (selector.Contains("nth-of-type"))
            {
                var matches = Regex.Matches(selector, @"([a-zA-Z0-9.-]\s?)+(:nth-of-type\(\d\))");
                for (int i = 0; i<matches.Count;i++)
                {
                    var match = matches[i];
                    var splitty = match.Value.Split(':');
                        var elements = element.QuerySelectorAll(splitty[0]);
                        var n = int.Parse(Regex.Match(splitty[1], @"(\d)").Value);
                        element = (n - 1 < elements.Count) ? elements[n - 1] : elements[0];
                }
            }
            else
            {
                element = element.QuerySelector(selector);
            }
            return element;
        }
    }
