### ISSUE TITLE
OuterHtml and InnerText properies returning "XXX" instead of original value

### ISSUE THREAD

**Issue by Tabraizahmed** [zzzprojects/html-agility-pack#406]
### Description
I am using html-agility-pack for the first time. I need to grab some values from [Bank of America website](https://www.bankofamerica.com/mortgage/refinance-rates/) but I am unable to access the exact value. Although it is returning me the exact HTML element it replaces the actual value with "X.XXX%". 

### Sample Code
```
HtmlWeb website = new HtmlWeb();

website.AutoDetectEncoding = false;

website.OverrideEncoding = Encoding.Default;

HtmlDocument Doc = website.Load("https://www.bankofamerica.com/mortgage/refinance-rates/");

var content = Doc.DocumentNode.SelectSingleNode(".//span[@class='update-partial']").OuterHtml;

Console.WriteLine(content)
```
### Further technical details
- HAP version: 1.11.24
- NET version (net472):

**Comment by JonathanMagnan** [comment]
Hello @Tabraizahmed ,

You can try the [From Browser](https://html-agility-pack.net/from-browser) method which can wait till some element is populated.

However, depending on what you have to do, I would probably recommend you https://www.selenium.dev/ WebDriver which can do what a browser does. 

Another idea could be calling their web services yourselves: https://www.bankofamerica.com/home-loans-sales/getProductRates 

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
