### ISSUE TITLE
Remove dependancy on System.Xml

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/html-agility-pack#408]
Hello there,

I am developing a WYSIWYG Makdown editor app in Blazor Web assembly,  
I am using [Markdig](https://github.com/lunet-io/markdig) for Markdown compilation and the Html Agility Pack to process the resulting HTML.  
Because it is a web app, I am trying to minimise downloads as much as I can, 'System.Xml.dll' is 1MB, I know what you will say to this, but would it be possible to remove the dependency on 'System.Xml'? How much work would be involved?  
HAP itself is not such a big download.

(Also I think you have 'System.Data' as a dependency?)

![download-size-sept](https://user-images.githubusercontent.com/16164373/93661800-a7efe300-fa52-11ea-8022-c2af824f2c51.png)

Thanks!

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

`XPathNavigator` and some other methods that use `XmlWriter` will have to be removed.

I believe the best in your case would probably to create a fork and remove it as I don't think we will release a version without those dependencies.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by LukeTOBrien** [comment]
Okay - Thanks for taking a look :-)
