### ISSUE TITLE
Closing tags in a table are not inserted appropriately

### ISSUE THREAD

**Issue by Sorashi** [zzzprojects/html-agility-pack#41]
I'm trying to scrape a website with HtmlAgilityPack `1.5.2-beta2`.

Raw `curl` of the page returns a tacky `table` (simplified):

```html
<table>
    <thead>
        <tr><th>A<th>B<th>C
    </thead>
    <tbody>
        <tr><td>x<td>y<td>z
        <tr><td>i<td>j<td>k
    </tbody>
</table>
```
Chrome can deal with this by inserting the closing tags appropriately:
```html
<table>
    <thead>
        <tr><th>A</th><th>B</th><th>C</th></tr>
    </thead>
    <tbody>
        <tr><td>x</td><td>y</td><td>z</td></tr>
        <tr><td>i</td><td>j</td><td>k</td></tr>
    </tbody>
</table>
```
However, HtmlAgilityPack deals with it differently and that prevents me from easily parsing the document. `HtmlDocument.LoadHtml(string)` and then `HtmlDocument.DocumentNode.InnerHtml`:
```html
<table>
    <thead>
        <tr><th>A<th>B<th>C
        </th></th></th></tr>
    </thead>
    <tbody>
        <tr><td>x<td>y<td>z
        <tr><td>i<td>j<td>k
        </td></td></td></tr>
        </td></td></td></tr>
    </tbody>
</table>
```
I can of course solve this with a recursive approach and many conditions. I'd just like to point this out, since HAP is meant specifically for HTML parsing. It should be able to deal with specific situations like this one.

**Comment by JonathanMagnan** [comment]
Hello @Sorashi ,

Thank you for reporting. My developer will try to look at this issue during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Sorashi ,

To fix this issue, you must enable the option `OptionFixNestedTags = true`. Honestly, I'm not sure why this option is not enabled by default but to stay backward compatible, we must leave this option as `false` by default until we code && release a major version

```csharp
var doc = new HtmlAgilityPack.HtmlDocument();
doc.OptionFixNestedTags = true;
doc.LoadHtml(html);
```

Let me know if enabling this option has fixed your issue.

Best Regards,

Jonathan

**Comment by Sorashi** [comment]
It works, thank you so much. It's wierd that I hadn't noticed this option when I tried to solve it myself.
