### ISSUE TITLE
InnerHtml replacement BUG

### ISSUE THREAD

**Issue by GF-Huang** [zzzprojects/html-agility-pack#416]
### Description
This code will changes the `InnerHtml`, even if **break** the contents. 

```cs
var scriptNode = doc.SelectSingleNode("/html/head/script[contains(text(), 'function init()')]");
scriptNode.InnerHtml = scriptNode.InnerHtml;
```

#### The left is before assign, the right is after assign:

![image](https://user-images.githubusercontent.com/4510984/100579165-a8dca500-331e-11eb-9a0f-fb9f43ac30be.png)

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- HAP version: `1.11.28`
- NET version (net472, netcore, etc.): `.NET 5`

**Comment by GF-Huang** [comment]
I think this is the key cause wrong parsing:

![image](https://user-images.githubusercontent.com/4510984/100580144-67e59000-3320-11eb-838a-b75d91c2ad28.png)

**Comment by JonathanMagnan** [comment]
Hello @GF-Huang ,

Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

At this moment, some critical information such as the HTML and the exact code to use is missing.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by GF-Huang** [comment]
OK, I will send it later.

**Comment by JonathanMagnan** [comment]
Hello @GF-Huang ,

The problem with the code you send us is you take the text from the `script` tag. The `InnerHtml` returns the plain text.

However, when you set the text, our library is limited and doesn't know it was coming from a `script` tag so it tries to parse it as a normal HTML and find the `<ErrCode>` which it assumes it's an `HTML` tag.

Unfortunately, besides giving the reason why this is happening, I don't think we can fix it for your current scenario.

However, one solution for you is to use the parent tag which contains the `<script>` part such as:

```csharp
scriptNode.ParentNode.InnerHtml = scriptNode.ParentNode.InnerHtml;
```

Let me know if this alternative solution could work for you.

Best Regards,

Jon

**Comment by GF-Huang** [comment]
I found another workaround, that is 
```cs
scriptNode.ParentNode.ReplaceChild(HtmlNode.CreateNode(scriptNode.InnerHtml), scriptNode);
```

**Comment by GF-Huang** [comment]
Close this issue if you feel it is necessary.

**Comment by JonathanMagnan** [comment]
Great, I'm happy you succeed to make it works.

Yes,, let close it in this case.
