### ISSUE TITLE
Make library CLS-compliant

### ISSUE THREAD

**Issue by cptjazz** [zzzprojects/html-agility-pack#42]
Currently, this library is not marked as CLS-compliant which makes it a pain to include in projects striving to be CLS-compliant.

Please consider making this library CLS-compliant.

**Comment by JonathanMagnan** [comment]
Hello @cptjazz ,

Thank you for reporting,

We will look about CLS-compliant (pro & con) this week,

Best Regards,

Jonathan

**Comment by cptjazz** [comment]
Thanks!
For what I've see when skimming over the code, the only type that will make trouble is the CRC32 class.

**Comment by atifaziz** [comment]
Any update on this? Absence of CLS-compliance makes other libraries that are CLS-compliant and that expose HtmlAgilityPack types issue warnings like [CS3001][CS3001] (*Argument type of '…' is not CLS-compliant*) and [CS3002][CS3002] (*Return type of '…' is not CLS-compliant*).


[CS3001]: https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs3001
[CS3002]: https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs3002

**Comment by JonathanMagnan** [comment]
Hello @cptjazz , @atifaziz ,

Sorry for the delay, we have a task for the end of September to push the pull made by @cptjazz to make our library CLS-Compliant since it's a breaking change.

The v1.5.6- beta1 has been released which should be CLS-Compliant,

Could you guys check it and let me know if that works correctly?

Best Regards,

Jonathan

**Comment by atifaziz** [comment]
> it's a breaking change

I'm curious, how is it a breaking change? If it is, shouldn't you be increasing the major version number?

Thanks for addressing this.

**Comment by atifaziz** [comment]
@JonathanMagnan Ah, just saw the release notes for [v1.5.6-beta1](https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.5.6-beta1) and saw the breaking change mentioned in there:

> **BREAKING CHANGE**: The crc32 class is now internal to be CLSCompliant (Issue #42, Pull #57)

**Comment by atifaziz** [comment]
> Could you guys check it and let me know if that works correctly?

What's there to check? The [`[CLSCompliant]` attribute](https://msdn.microsoft.com/en-us/library/system.clscompliantattribute.aspx) just needs to be decorated on the assembly and the C# compiler will flag any non-compliant members.

Also, you don't need to make `crc32` internal in order make the assembly CLS-compliant as you can just mark that class as being non-compliant.

**Comment by cptjazz** [comment]
1. Nothing is breaking in my pull request.
I *marked the CRC32 type as obsolete* to discourage its usage and created an *internal* replacement to drop references to the type.
This is *binary compatible* and only a *minor change*.

2. CLS compliancy is another topic and should easily be achievalble by marking the assembly as CLS compliant and marking the (public) CRC32 type as [CLSCompliant(false)]

**Comment by JonathanMagnan** [comment]
Hello @atifaziz ,

It's a breaking change since a `public` class has been marked `internal`. I didn't feel to make a major release only for this since probably zero developers use it (I may be wrong in this statement)

It was somewhat already planned to make it soon or later internal.

Hello @cptjazz ,

You are right, nothing was breaking in your pull. But as you specified, we will need to remove the `crc32` class.

After having read your both comment, I will more comfortable to reverse the change on the `crc32` class and only mark it as `[CLSCompliant(false)]` as you suggested.

So no breaking change will be made.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @cptjazz , @atifaziz 

The v1.5.6-beta2 has been released.

The class has been reversed to `public` and marked `[CLSCompliant(false)]`

Thank you for your feedback,

Best Regards,

Jonathan

**Comment by atifaziz** [comment]
@JonathanMagnan I'm afraid that v1.5.6-beta2 doesn't address the issue for .NET Core projects because the attribute is not applied to libraries built for the .NET Standard.

Assuming v1.5.6-beta2 has been primed in the NuGet cache, I ran the following command-line on a PowerShell prompt:

```ps1
dir -Recurse (Join-Path $env:USERPROFILE .nuget\packages\HtmlAgilityPack\1.5.6-beta2\lib\HtmlAgilityPack.dll) |
  % { echo ($_.FullName -replace '^.+[/\\](?=HtmlAgilityPack[/\\])', '');
      ildasm /text $_ | findstr CLSCompliant }
```

It disassembles all `HtmlAgilityPack.dll` in the package and scans for the `CLSCompliant` attribute in the disassemblies. As you can see from the result below, the `netstandard1.3`, `netstandard1.6` and `netstandard2.0` ones are missing the attribute completely:

```
HtmlAgilityPack\1.5.6-beta2\lib\Net20\HtmlAgilityPack.dll
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\Net40\HtmlAgilityPack.dll
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\Net40-client\HtmlAgilityPack.dll
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\Net45\HtmlAgilityPack.dll
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [mscorlib]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\NetCore45\HtmlAgilityPack.dll
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\netstandard1.3\HtmlAgilityPack.dll
HtmlAgilityPack\1.5.6-beta2\lib\netstandard1.6\HtmlAgilityPack.dll
HtmlAgilityPack\1.5.6-beta2\lib\netstandard2.0\HtmlAgilityPack.dll
HtmlAgilityPack\1.5.6-beta2\lib\portable-net45+netcore45+wp8+MonoAndroid+MonoTouch\HtmlAgilityPack.dll
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid+MonoTouch\HtmlAgilityPack.dll
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
HtmlAgilityPack\1.5.6-beta2\lib\uap10.0\HtmlAgilityPack.dll
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 01 00 00 ) 
  .custom instance void [System.Runtime]System.CLSCompliantAttribute::.ctor(bool) = ( 01 00 00 00 00 ) 
```

**Comment by Elsensee** [comment]
Hey, sorry to bring up this topic again after so much time has passed, but what has happened for the CLS compliance of the .NET standard library versions? Why is the CLSCompliant attribute no applied there as well?

**Comment by JonathanMagnan** [comment]
Hello @Elsensee ,

I'm not exactly sure of the reason but perhaps we just forgot about this request.

The v1.8.10 has been released which also include `NET Standard` version to be CLSCompliant.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by Elsensee** [comment]
Hey @JonathanMagnan,

thanks for your quick answer! Indeed, with 1.8.10 everything works as expected. Thanks a lot! :)

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
