### ISSUE TITLE
Xpath element not found

### ISSUE THREAD

**Issue by tbremard** [zzzprojects/html-agility-pack#420]
### Description
I use firefox to generate an Xpath of a html file
I load the file to html agility, and the node is not found.

### Further technical details
- NET version ( netcore 3.1,)
- VS2019

https://www.galaxus.de/de/s1/product/zotac-zbox-magnus-en72070v-intel-core-i7-9750h-0gb-pc-13590721
File saved: 2020-12-21_22-40-43__GalaxusZotac72070_805_dl.html   <<<<<<<<<<< file is attached

[2020-12-21_22-40-43__GalaxusZotac72070_805_dl.html.txt](https://github.com/zzzprojects/html-agility-pack/files/5726693/2020-12-21_22-40-43__GalaxusZotac72070_805_dl.html.txt)

Node not found: '/html/body/div/div/div[2]/div/main/div/div[1]/div/div[2]/div/div[1]/strong'

expected node to be found: "1194,16"
below screen shot in firefox of the portion of page that i want to extract:
![image](https://user-images.githubusercontent.com/36224228/102825677-8a2e7300-43df-11eb-8747-0df10b9e2c30.png)

below the comand that i do with firefox to generate the xpath:
![image](https://user-images.githubusercontent.com/36224228/102825725-a3372400-43df-11eb-9cf2-3298c237742a.png)

firefox creates xpath:
/html/body/div/div/div[2]/div/main/div/div[2]/div/div[2]/div/div[1]/strong

Regards.

C#code which uses htmlagility (works succesfully on other pages:xpath):

```
        protected override IDataTruck GetOutput(IDataTruck data)
        {
            IDataTruck ret;
            try
            {
                var htmldoc = new HtmlDocument();
                htmldoc.LoadHtml(data.GetText());
                var node = htmldoc.DocumentNode.SelectSingleNode(_xPath);
                if (node == null)
                {
                    _log.Error($"Node not found '{_xPath}'");
                    ret = DataTruck.CreateText(NOT_FOUND);
                }
                else
                {
                    ret = DataTruck.CreateText(node.InnerText.Trim());
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                ret = DataTruck.CreateText(NOT_FOUND);
            }
            return ret;
        }
```

**Comment by JonathanMagnan** [comment]
Hello @tbremard ,

Thank you for reporting,

My developer will look at it and see if there is some issue that we could find on our side

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @tbremard ,

Firefox and Chrome create the following xpath `/html/body/div/div/div[2]/div/main/div/div[2]/div/div[2]/div/div[1]/strong` (the one you also reported,

However, you seem to report this xpath which is different doesn't work: `'/html/body/div/div/div[2]/div/main/div/div[1]/div/div[2]/div/div[1]/strong`

(See this part: `/main/div/div[1]` which is `/main/div/div[2]` when browser report it)

When using the right xpath, everything works on our side.

Is it a problem on your side? Or there is a reason why you use a different xpath than the one reported?

Best Regards,

Jon

**Comment by tbremard** [comment]
Hello @JonathanMagnan ,
thank you very much for your analysis.
You spotted on my enquiry that I have 2 different Xpath : 
'''
mycode:  /html/body/div/div/div[2]/div/main/div/**div[1]**/div/div[2]/div/div[1]/strong
Firefox:    /html/body/div/div/div[2]/div/main/div/**div[2]**/div/div[2]/div/div[1]/strong
'''
I didn t noticed this difference.
I think the website targeted did updated its content after I hardcoded the Xpath, and I didn't noticed this change of Xpath, as it is very long and differs with only a character.
Congratulation to your tool which spotted that I give incorrect Xpath.

you can close the ticket
Regards.
Thierry Bremard
