### ISSUE TITLE
Innertext property is not parsed correctly 

### ISSUE THREAD

**Issue by krishna-babu** [zzzprojects/html-agility-pack#423]
### Description
InnerText of element is not resolved correctly. This is observed if the element has ID property filled

![image](https://user-images.githubusercontent.com/12712808/105551751-dce99c00-5cb7-11eb-9f94-6025568b2269.png)

### Exception
No Exception

**Comment by JonathanMagnan** [comment]
Hello @krishna-babu ,
 
Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
