### ISSUE TITLE
LoadFromWeb when isBrowserScriptCompleted  in net core

### ISSUE THREAD

**Issue by manoochehrkateb** [zzzprojects/html-agility-pack#424]
Hello there
In **net framework** we have this overload :
`public HtmlDocument LoadFromBrowser(string url, Func<string, bool> isBrowserScriptCompleted = null);`
we use that for load document when is fully ready 
but in **net core** we haven't that overload . 

is there any other way to do that in net core ?

using : asp.net net core 3.1

**Comment by JonathanMagnan** [comment]
Hello @manoochehrkateb ,

Unfortunately, the `WebBrowser` is not available in .NET Core, so this method is not also available.

We often recommend using Selenium web driver which is a powerful browser. Here is a getting started introduction: https://riptutorial.com/selenium-webdriver/learn/100000/overview

Unless the `Microsoft` team add it back in a `NuGet` package, there is nothing we can do (we don't want to code a `WebBrowser`!

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by manoochehrkateb** [comment]
> Hello @manoochehrkateb ,
> 
> Unfortunately, the `WebBrowser` is not available in .NET Core, so this method is not also available.
> 
> We often recommend using Selenium web driver which is a powerful browser. Here is a getting started introduction: https://riptutorial.com/selenium-webdriver/learn/100000/overview
> 
> Unless the `Microsoft` team add it back in a `NuGet` package, there is nothing we can do (we don't want to code a `WebBrowser`!
> 
> Best Regards,
> 
> Jon
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

Thanks for answer . 
Please add warning note to the [document ](https://html-agility-pack.net/from-browser ). I took me very long time to find out it's not supported in .Net Core .

**Comment by JonathanMagnan** [comment]
Thank for the suggestion, the page has been update to add a note about .NET Core is not supported.
