### ISSUE TITLE
The above copyright notice?

### ISSUE THREAD

**Issue by kurema** [zzzprojects/html-agility-pack#426]
## 1. Description
In LICENSE it says

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

But there is no copyright notice. It's not a issue but sounds a little odd.

**Comment by JonathanMagnan** [comment]
It seems like the official `MIT` license text: https://opensource.org/licenses/MIT

So nothing we can really do here, and we don't care at all if someone adds it or not if you ask.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by kurema** [comment]
The first line of MIT license in your [link](https://opensource.org/licenses/MIT) is

> Copyright &lt;YEAR&gt; &lt;COPYRIGHT HOLDER&gt;

which is copyright notice. But I have no problem if you don't care.

If you want to add the line, don't forget to change `<YEAR>` and `<COPYRIGHT HOLDER>`.

Closing the Issue.
