### ISSUE TITLE
Error in using htmlagilitypack in multithreading

### ISSUE THREAD

**Issue by NodeGreenHand** [zzzprojects/html-agility-pack#428]
1、Does htmlagilitypack support multithreading and thread safety？The current situation is that the call will be stuck in multithreading.

In the process of splitting elements, parentnode is null occasionally, 
such as splitting #text element 
Before splitting, text: Hello world, parentnode is not null
After splitting:  text1: hello; text2: world, parentnode is null

**Comment by JonathanMagnan** [comment]
Hello @NodeGreenHand ,

HAP supports multithreading if you use the document instance in only one thread such as an object like a dictionary, but if you start to use the same document in multiple threads then like pretty much everything, no this is not supported.

Let me know if that answers your question.

Best Regards,

Jon

**Comment by NodeGreenHand** [comment]
Hello @JonathanMagnan 

The application scenario is as follows:

Extract all P elements from an HTML file, and deeply copy each P element through cloneNode. At this time, analyze the content of each P element through multithreading, and errors will appear.

I have analyzed the following. Even if each P element is deeply copied, there is an owndocument attribute in the copied P element, and the value of this attribute is still the content of the entire HTML file that was originally loaded.

Best Regards,
NodeGreenHand

**Comment by JonathanMagnan** [comment]
So no, in your is not thread-safe.

As you commented, the document instance (ownerdocument attribute) is passed and potentially modified in multiple threads.

**Comment by NodeGreenHand** [comment]
Hello @JonathanMagnan 

What I do now is: use every P element“ HtmlNode.CreateNode (P. outerhtml) "re create, and then use multithreading analysis, but there will be additional time overhead, is there a better way

Best Regards,
NodeGreenHand

**Comment by JonathanMagnan** [comment]
Do you really need multi-threading for this kind of stuff? It sounds like overkill and probably slower than a single thread but I guess, you do a lot of more stuff in your thread which could explain why.

Unfortunately, no. There is no easy solution to make it works in your multi-thread environment. You could parse the document for every thread, use a binary serializer for every thread, or other similar solution but in all cases, it looks that you will need to have one document per thread.
