### ISSUE TITLE
Sponsor button displayed error

### ISSUE THREAD

**Issue by tno2007** [zzzprojects/html-agility-pack#430]
When clicking the "Sponsor" button in the github project, a FUNDING.yml error is displayed.

Here is a screenshot:

![html-agility-pack](https://user-images.githubusercontent.com/6169249/109972548-1b836500-7d00-11eb-8896-349d6ef0154c.png)

This is a minor issue, but I think it is important to fix since the project's readme mentions contributing to this project. The error may scare off potential contributors.

**Comment by JonathanMagnan** [comment]
Hello @tno2007 ,

Thank you for reporting it.

You are right, I always test the page by clicking on the heart in the "Sponsor this project" section which works. Strangely, the "sponsor" button at the top doesn't work.

We will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Thank again @tno2007 for reporting,

The issue has been found and fixed.
