### ISSUE TITLE
Loading a HTML file

### ISSUE THREAD

**Issue by ajtruckle** [zzzprojects/html-agility-pack#432]
I am looking at the sample code for loading a HTML file:

https://html-agility-pack.net/from-file

But it has no error handling at all.

- The path might not be valid
- The HTML might be corrupt

I am testing for the path before making the call by using `File.Exists(...) `but what is the approved way to validate the file was loaded?

     // Load the HTML document
     var doc = new HtmlDocument();
     doc.Load(args[0]);

**Comment by JonathanMagnan** [comment]
Hello @ajtruckle ,

There is no really any error handling done by HAP.

If the file doesn't exists, you will get a `FileNotFoundException`.

If the HTML is corrupted, `HAP` will try to still read it the best way he can do.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by ajtruckle** [comment]
Hi

Alright. So the best thing to do is wrap **all** my code in a try catch block I guess.
