### ISSUE TITLE
Seems there is no method to RemoveAttribute in a HtmlNode?

### ISSUE THREAD

**Issue by cesaryuan** [zzzprojects/html-agility-pack#435]
## 1. Description
I'd like to remove some attribute from a certain HtmlNode, but i didn't find a method to do it.
Only found `GetAttributeValue` but no `RemoveAttribute`.

## 2. Any further technical details

- HAP version: 1.11.32.0
- NET version: net4.8

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @cesaryuan ,

It looks like that's already possible but you need first to access the `HtmlAttributeCollection` such as:

```csharp
doc.DocumentNode.Attributes.Remove("theAttributeName");
```

Let me know if that solves your issue.

Best Regards,

Jon
