### ISSUE TITLE
Make repository more friendly to contributors by reducing the set of TargetFrameworks

### ISSUE THREAD

**Issue by ViktorHofer** [zzzprojects/html-agility-pack#436]
Most libraries already target .NET Standard 2.0 or a supported platform that support .NET Standard 2.0 like

- .NET Core 2.0 and above
- .NET Framework 4.6.1 and above
- UAP10.0.16299

I would suggest to consider dropping support for .NET Standard 1.3 and older .NET Framework versions in favor of a broader API set a simplified dependency graph. Other open source repositories are dropping support for older targets as well, i.e. xunit v3. I would be willing to send a PR but wanted to open an issue to discuss this first.

There are a lot of target still in the source branch and it's very hard to reason about which APIs are supported on which platform and where code should be contributed to and on what platform to test on:

![image](https://user-images.githubusercontent.com/7412651/115620015-f15c2580-a2f4-11eb-8d9f-c9f254c41ecd.png)

**Comment by JonathanMagnan** [comment]
Hello @ViktorHofer ,

Almost all codes is added in the `Shared` project. Supporting multiple versions is not really harder for us.

We might eventually drop the support for `.NET Standard 1.3` but at this moment, it doesn't make anything harder so I don't really see the point (I don't have any good argument to support it either besides this is here...).

This project has been created a long time ago, we cannot simply drop some .NET Version such as .NET 40, we know that some people still use this version with our library.

Obviously, if we add something that's not supported in the `.NET Standard 1.3`, we will keep going forward and only this version will not have it.

Thank you for your suggestion but at this moment, we prefer just not doing that kind of change but perhaps we will change our mind in a few months (as soon as the `.NET Standard 1.3 will give us a few trouble we will probably remove it as we did with another of our library).

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by ViktorHofer** [comment]
Makes perfect sense. Thanks for your reply.
