### ISSUE TITLE
(DISCUSSION) Plan for .NET 5 support?

### ISSUE THREAD

**Issue by Reapism** [zzzprojects/html-agility-pack#438]
### Is there a plan for .NET 5 support?

If this has been discussed for this library, what does the timeline look?

**Comment by JonathanMagnan** [comment]
Hello @Reapism ,

The library already supports .NET 5 and probably every upcoming framework release.

The library support `.NET Standard 2.1` which is compatible with `.NET 5`.

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by Reapism** [comment]
Hi @JonathanMagnan 

That is awesome! When I was looking at the dependencies on the nugget manager, I didnt see .NET 5. 

Today, I learned. Thank you!
