### ISSUE TITLE
Attributes without a value

### ISSUE THREAD

**Issue by FireSon** [zzzprojects/html-agility-pack#439]
Is it possible to write Attributes without a value? If I supply an empty value and use the `QuoteType = AttributeValueQuote.None;` I still get the = character in the output. Would it be possible to add a QuoteType which omits the Value in the OuterHtml? 
Thanks!

- HAP version: 1.11.33
- NET version (net5)

**Comment by JonathanMagnan** [comment]
Hello @FireSon,

That's a good question, I don't think that's currently possible.

I will ask my developer if he can add something like: `AttributeValueQuote.WithoutValue`


Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @FireSon ,

The v1.11.33 has been released.

The option `AttributeValueQuote.WithoutValue` has been added:

```csharp
var doc1 = new HtmlDocument();
doc1.GlobalAttributeValueQuote = AttributeValueQuote.WithoutValue;
```

Best Regards,

Jon

**Comment by FireSon** [comment]
Woo thanks a lot!! 
Will check it out as soon as possible.
Thanks very much for the quick solution!
