### ISSUE TITLE
QuerySelector("h2>span") and QuerySelectorAll("h2>span") are not working properly

### ISSUE THREAD

**Issue by RakeshYadvanshi** [zzzprojects/html-agility-pack#440]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description

htmlNode.QuerySelector("h2>span") is not 3properly

According to **>** selector definition. it should be only selecting bold span. however, it always selects the first one which is inside the div

Same with the QuerySelectorAll("h2>span"). it is selecting both the nodes. div as well as span

## 2. Any further technical details
Add any relevant detail can help us, such as: 

- NET version (.Net Framework 4.7.2)

## 3. Sample Input

```
<h2 class="jobTitle jobTitle-color-purple jobTitle-newJob">
       <div class="new topLeft holisticNewBlue desktop">
             <span class="label">new</span>
       </div>
      <span title="Warehouse Associate II (Returns)">
            Warehouse Associate II (Returns)
      </span>
</h2>
```

**Comment by JonathanMagnan** [comment]
Hello @RakeshYadvanshi ,

There is no `QuerySelector` in `HAP`.

You probably use a third party library that extends our library with `QuerySelector` such as https://www.nuget.org/packages/Fizzler.Systems.HtmlAgilityPack/

Make sure to contact the right package owned as there is nothing we can really do on our side.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by RakeshYadvanshi** [comment]
Thanks. That's on me. my bad.
