### ISSUE TITLE
Attribute original name is not preserved after clone

### ISSUE THREAD

**Issue by POFerro** [zzzprojects/html-agility-pack#443]
Hi,

When working with a document that has attributes in other than lowercase, even with option `OptionOutputOriginalCase `after a Clone attribute names are written in lowercase. 

An example of this is if I have a document:
`<html><body><button ngIf="something"></body></html>`

If I output a document right after read with `OptionOutputOriginalCase ` all is right, if I clone the node button I get the output:
`<html><body><button ngIf="something"><button ngif="something"></body></html>`

In elements everything works fine.

Thanks
POFerro

**Comment by JonathanMagnan** [comment]
Thank you for reporting, we will look at it but your pull request makes a lot of sense.

If approved, it should be released early next week or before.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by POFerro** [comment]
Hi Jon,

Thanks for the quick reply, I'll wait :)

Best regards
POFerro

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

The v1.11.35 has been released.

Could you try it and let us know if everything is working as expected?

Best Regards,

Jon

**Comment by POFerro** [comment]
Thanks @JonathanMagnan , everything works like a charm.
Thanks for the mention in the release I was flattered :).
