### ISSUE TITLE
Feature - Would be nice to have an option to set UseOriginalName to a default value

### ISSUE THREAD

**Issue by POFerro** [zzzprojects/html-agility-pack#445]
Hi,

There's a way to set `UseOriginalName` after the document is loaded and to specific tagName's only. It would be nice to set a default value for attributes and nodes to behave preserving original name.

This is specially useful for example in angular html templates, since casing is relevant in these cases ex: *ngIf="condition"

Thanks
POFerro

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

Thank you for your suggestion, we will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

The v1.11.35 has been released.

Here is the commit related to the pull: https://github.com/zzzprojects/html-agility-pack/commit/d8208348c70ede999ca5e0f089d1dc8364f16ffc

If I missed something, let me know.

Best Regards,

Jon

**Comment by POFerro** [comment]
Thanks @JonathanMagnan , everything works like a charm.
Thanks for the mention in the release I was flattered :).
