### ISSUE TITLE
</form> is recognized as a Text node

### ISSUE THREAD

**Issue by osjoberg** [zzzprojects/html-agility-pack#45]
Hello!

When parsing html &lt;/form&gt; is recognized as a #text node.

Small repro.
```
var document = new HtmlDocument();
document.LoadHtml("<div></div>");
var result = document.DocumentNode.Descendants().Select(dn => new { dn.NodeType, dn.Name, dn.OuterHtml }).ToArray();
```

Result contains:
```
new [] 
{
    new { NodeType = HtmlNodetype.Element, Name = "div", OuterHtml = "<div></div>" }
}
```

Seems reasonable, however changing "&lt;div&gt;&lt;/div&gt;" to "&lt;form&gt;&lt;/form&gt;" in the repro above yields an unexpected output
```
new [] 
{
    new { NodeType = HtmlNodeType.Element, Name = "form", OuterHtml = "<form>" },
    new { NodeType = HtmlNodeType.Text, Name = "#text", OuterHtml = "</form>" }
}
```

Obviously my real scenario has a full HTML document, with html, head, body, etc, but the error stays the same.

**Comment by JonathanMagnan** [comment]
Hello @osjoberg ,

Thank you for reporting,

We will look at this issue.

Best Regards,

Jonathan

**Comment by Tarmil** [comment]
Hi @JonathanMagnan, I am a developer of the WebSharper web framework for F#. We are using HtmlAgilityPack for our templating engine, and we are being hit by this and #48. Is there any ETA for a fix on these issues?

**Comment by emmatb1** [comment]
Hello @Tarmil ,

My developer provided me a pull request yesterday.

I'm currently checking the side effect of this pull request.

If there is nothing wrong, it should be released probably Wednesday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Tarmil ,

My developer provided me a pull request yesterday.

I'm currently checking the side effect of this pull request.

If there is nothing wrong, it should be released probably Wednesday.

Best Regards,

Jonathan

**Comment by Tarmil** [comment]
That's great news, thanks!

**Comment by JonathanMagnan** [comment]
Hello @osjoberg , @Tarmil ,

The issue should be fixed, the `Form` is no longer recognized with an flag `Empty`

Soon, we will rework the logic to fix all this kind of issue with tag.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @osjoberg , @Tarmil ,

We will close this issue since it should be fixed.

Feel free to re-open if you still have this issue.

Best Regards,

Jonathan
