### ISSUE TITLE
ClonedNode with attributes without quote (like <input disabled />) becomes <input disabled='' /> when written

### ISSUE THREAD

**Issue by POFerro** [zzzprojects/html-agility-pack#450]
Hi,

I have a node like this: `<input disabled />`
After a clone operation like
`var cloned = node.Clone(true);`
if I call for example:
`Console.WriteLine(cloned.OuterHtml);`
it is written as `<input disabled='' />` I was expecting node to be unchanged :(.

Thanks and best regards
POFerro

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by POFerro** [comment]
Hi @JonathanMagnan ,

Any news on this issue? Have you seen my PR? I really need this fix :(.

Thanks in advance and best regards.
POFerro

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

Thank you for the remember, indeed I didn't see your PR. My assistant didn't add it to our issue tracker.

I will review it but I don't see any issue so far so it will probably be merged and released at the beginning of next week.

Best Regards,

Jon

**Comment by POFerro** [comment]
Hi @JonathanMagnan ,

Thanks a million ;).

Best regards

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

The v1.11.37 has been released with your pull request ;)

Thank again for your contribution.

Best Regards,

Jon

**Comment by POFerro** [comment]
Perfect @JonathanMagnan , thanks once again :).
