### ISSUE TITLE
Closing </p> are removed if the loaded Html contains <ul>

### ISSUE THREAD

**Issue by mark1701** [zzzprojects/html-agility-pack#452]
Hi,

I seem to have bumped into some strange behaviour or bug.

When loading some Html code that contains ```<ul>``` surrounded by paragraph tags the closing ```</p>``` are removed within the documentNode object.

I created a Fiddle to reproduce the issue:
https://dotnetfiddle.net/Rx3Xl2

I'm using version 1.11.36 but this was working correctly in the past, for sure with version 1.9.0. 

I'm running my project on the .Net Framework 4.8 but the Fiddle is able to reproduce the problem with 4.7.2 as well

**Comment by JonathanMagnan** [comment]
Hello @mark1701 ,

From what I understand, a `ul` tag cannot be in a `p` tag. So it get implicitly closed.

See the following answer:  https://stackoverflow.com/a/5681796/5619143

The browser also has the same behavior.

Let me know if that explains correctly the current behavior.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by mark1701** [comment]
Hi @JonathanMagnan 

Yes, that makes sense.

Many thanks for checking and for your prompt reply.
