### ISSUE TITLE
Can you make a code compatible?

### ISSUE THREAD

**Issue by colindcli** [zzzprojects/html-agility-pack#453]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description

```
<a href="/list.html" class="left" alt="" /><img class="img" src="/about.jpg" alt="" /></a>
```

a tag, there is an extra "/", <a  /><img /></a>

```
var doc = new HtmlDocument();
doc.LoadHtml("<a href=\"/list.html\" class=\"left\" alt=\"\" /><img class=\"img\" src=\"/about.jpg\" alt=\"\" /></a>");
var res = doc.DocumentNode.OuterHtml;
```

Output result:

```
<a href="/list.html" class="left" alt=""></a><img class="img" src="/about.jpg" alt="">
```
![a](https://user-images.githubusercontent.com/3311217/138665954-2ba89ea7-6364-40c3-85ae-98b1532486c8.jpg)

## 2. Exception

```
Exception message:
Stack trace:  Can you make a code compatible?
```

## 3. Any further technical details
Add any relevant detail can help us, such as: 

- HAP version:
- NET version (.net 4.6)

**Comment by JonathanMagnan** [comment]
Hello @elgonzo ,

After looking at this request, we choose to leave it like this.

While you are right about the `a` behavior is one problem with HAP is the library is not `HTML5` compatible. Every time we do some fix/change like this one, it fires back to us as some people use it with the current behavior and are expecting the library to keep being a simple `HTML` parser.

Looking at how browsers parse the `a` tag, they simply ignore the self-closing behavior and include the `img` in your example. We currently do not support such behavior, if the `a` tag is closed then the library closes it.
