### ISSUE TITLE
Release version package should not include pdb file and file type should lower case

### ISSUE THREAD

**Issue by kelicto** [zzzprojects/html-agility-pack#455]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
![image](https://user-images.githubusercontent.com/23723575/140637012-84ab9496-b764-48b4-8f69-ee0504e18bda.png)

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
If you are able,

Provide a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
Add any relevant detail can help us, such as: 

- HAP version:
- NET version (net45, .net core 3.1, etc.)

**Comment by JonathanMagnan** [comment]
Hello @kelicto ,

We keep things like this for backward compatibility (even if that's not really a big thing). Unless it causes an issue, I don't think we will do anything about this.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
