### ISSUE TITLE
When using LoadFromBrowser, a popup window appears if the content is in json.

### ISSUE THREAD

**Issue by ogosengi** [zzzprojects/html-agility-pack#457]
When using LoadFromBrowser, a popup window appears if the content is in json.
Can I disable the pop-up window?
Language: C#
HtmlAgilityPack ver: 1.11.38
Point of Popup 

HtmlAgilityPack.HtmlDocument doc = web.LoadFromBrowser(strurl);

![json](https://user-images.githubusercontent.com/66983885/144340160-4ed5e48f-f880-4b3d-aa9b-a1a0aa9db455.png)

**Comment by JonathanMagnan** [comment]
Hello @ogosengi ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ogosengi ,

The v1.11.39 has been released.

Could you try it and let me know if everything is fixed

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by ogosengi** [comment]
Thank you for Your fast reply.
But It hasn't been fixed yet.

I am coding in VisualStudio2019(WindowsForm, .NET Framework 4.7.2)
example code:
string str1 = "https://infuser.odcloud.kr/oas/docs?namespace=15074473/v1";
HtmlWeb web = new HtmlWeb();
HtmlAgilityPack.HtmlDocument doc = web.LoadFromBrowser(str1);

The pop-up window still appears.

**Comment by JonathanMagnan** [comment]
Hello @ogosengi ,

Unfortunately, I don't get a popup anymore on my side even with the URL and config you provided. So that makes it pretty much impossible to fix it on my side.

Could you check if you still get the popup with this code:

```csharp
string str1 = "https://infuser.odcloud.kr/oas/docs?namespace=15074473/v1";

var webBrowser = new WebBrowser();
webBrowser.ScriptErrorsSuppressed = true;
webBrowser.NewWindow += WebBrowser_NewWindow;
webBrowser.Navigate(str1);

private void WebBrowser_NewWindow(object sender, CancelEventArgs e)
{
	e.Cancel = true;
}
```

If yes, try to fix it if you can and we will apply your change. As said, we cannot reproduce it so we cannot go anything more on our side.

Best Regards,

Jon

**Comment by ogosengi** [comment]
Hello @JonathanMagnan 

It is same problem. 
From googling, It seems that it is probably a problem with IE Setting on my computer.
Perhaps htmlagilityPack was made based on IE.

If I try the URL in IE, it will try to download the file in the same way.
![json2](https://user-images.githubusercontent.com/66983885/144824791-f660b1a3-af7b-45c2-833c-167fd2d09ede.png)

I Try Selenium Chrome Driver (very slow ㅜㅜ)

private void button2_Click(object sender, EventArgs e)
{
	ChromeOptions options = new ChromeOptions();
	ChromeDriverService driverService = ChromeDriverService.CreateDefaultService();
	driverService.HideCommandPromptWindow = true;

	options.AddArgument("headless");  
	ChromeDriver driver = new ChromeDriver(driverService, options);

	driver.Navigate().GoToUrl("https://infuser.odcloud.kr/oas/docs?namespace=15074473/v1");
	textBox1.Text = driver.PageSource;
}

It is not Popup

**Comment by JonathanMagnan** [comment]
Hello @ogosengi ,

Unfortunately, we cannot add a reference to selenium to our project.

**Comment by ogosengi** [comment]
I solved it in another way.
https://stackoverflow.com/questions/6114360/ie-prompts-to-open-or-save-json-result-from-server

I try Registry Update, It work.

[JSON mime type](http://mikesknowledgebase.azurewebsites.net/SampleCode/MakeIEshowJSONdata.zip)



----
Windows Registry Editor Version 5.00
;
; Tell IE to open JSON documents in the browser (rather than always demanding that it saves
; the JSON data into an external file first).  
; 25336920-03F9-11cf-8FD0-00AA00686F13 is the CLSID for the "Browse in place" .
;
; Taken from:
; http://stackoverflow.com/questions/2483771/how-can-i-convince-ie-to-simply-display-application-json-rather-than-offer-to-do

[HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/json]
"CLSID"="{25336920-03F9-11cf-8FD0-00AA00686F13}"
"Encoding"=hex:08,00,00,00

[HKEY_CLASSES_ROOT\MIME\Database\Content Type\text/json]
"CLSID"="{25336920-03F9-11cf-8FD0-00AA00686F13}"
"Encoding"=hex:08,00,00,00

**Comment by tewuapple** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你的邮件已收到。
亮亮
