### ISSUE TITLE
Not all attributes are removed with Remove() if there are multiple attributes of the same name

### ISSUE THREAD

**Issue by kawaicheung** [zzzprojects/html-agility-pack#461]
## 1. Description
When using `Remove()` on the `HtmlAttributeCollection` where there are multiple attributes of the same name, only some get removed.

In the fiddle below, the attribute `class` appears five times. Upon calling `Remove("class")` on the attribute collection, I would expect all five would be removed but instead two still remain.

## 2. Fiddle or Project
(https://dotnetfiddle.net/zrfFnI)

## 4. Any further technical details
Add any relevant detail can help us, such as: 

- NET version (net45)

**Comment by elgonzo** [comment]
Quick analysis

The removal logic is broken:
https://github.com/zzzprojects/html-agility-pack/blob/def26b2d2f5ea8e6a077d1dd8ec145004a6cf424/src/HtmlAgilityPack.Shared/HtmlAttributeCollection.cs#L358-L365

Removing an element at position `i` will "shift" the next element to now be at position `i`.

As the loop is iterating in incrementing fashion, removing an element will therefore cause the loop to ignore/skip over the element following a removed element.

As a fix i would suggest to let the _for_ loop iterate in decrementing fashion, thus it won't skip any elements:
```C#
for (int i = items.Count - 1; i >= 0; i--)
{
    HtmlAttribute att = items[i];
    if (String.Equals(att.Name, name, StringComparison.OrdinalIgnoreCase))
    {
        RemoveAt(i);
    }
}
```

**Comment by JonathanMagnan** [comment]
Hello @kawaicheung ,

Thank you for reporting, we will look at it.

Thank also @elgonzo for your detailed answer. The current issue is a very common mistake. We will check if we will apply the fix you provided or create a list of thing to remove which is both usually 2 good solutions for this issue.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @kawaicheung ,

The v1.11.40 has been released.

My developer preferred to do it a little bit differently but the current issue should be fixed.

Let me know if everything is now working correctly.

Best Regards,

Jon
