### ISSUE TITLE
CaptureRedirect isn't work for LoadFromWebAsync

### ISSUE THREAD

**Issue by Kannagi0303** [zzzprojects/html-agility-pack#462]
```
var web = new HtmlWeb();
web.CaptureRedirect = true;
var doc = await web.LoadFromWebAsync(url);
Debug.WriteLine(web.ResponseUri); // will be null
```
if use ```web.Load(url);``` no problem!

HtmlAgilityPack 1.11.39

**Comment by JonathanMagnan** [comment]
Hello @Kannagi0303 ,

Unfortunately, both methods have completely different codes.

The `LoadFromWebAsync` has never set the `ResponseUri` value

My developer checked how to get this value from a `HttpClient` but unfortunately didn't find anything that worked correctly. So unless you know a way to get the right value from here: https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlWeb.cs#L2376 , there is not so much we can do right now as we failed on our side to find a solution.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by Kannagi0303** [comment]
thanks for your answer.

I didn't watch in detail, but i find this line.
https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlWeb.cs#L2400

when client is ```HttpClient```
```
var e = await client.GetAsync(uri, cancellationToken).ConfigureAwait(false);
var reponseurl = e.RequestMessage.RequestUri; //this way can catch it
```
The solution I ended up using self coding for get contents and use it at
```
var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(html);
````
