### ISSUE TITLE
HtmlAttributeCollection: ICollection<HtmlAttribute>.Clear() and ICollection<HtmlAttribute>.Remove(HtmlAttribute) methods forget to update Hashitems

### ISSUE THREAD

**Issue by elgonzo** [zzzprojects/html-agility-pack#463]
## 1. Description
When taking a look at the fix for https://github.com/zzzprojects/html-agility-pack/issues/461 out of curiosity, i noticed another two issues with HtmlAttributeCollection's `ICollection<HtmlAttribute>.Clear()` and `ICollection<HtmlAttribute>.Remove(HtmlAttribute)` implementations.

Both method implementations forget to update the _Hashitems_ dictionary after directly altering the _items_ collection.

https://github.com/zzzprojects/html-agility-pack/blob/127fe37b86c552dae95b144ae2e4037f2d2e99d7/src/HtmlAgilityPack.Shared/HtmlAttributeCollection.cs#L154-L157

https://github.com/zzzprojects/html-agility-pack/blob/127fe37b86c552dae95b144ae2e4037f2d2e99d7/src/HtmlAgilityPack.Shared/HtmlAttributeCollection.cs#L231-L234

The issue manifests and becomes easily observable when working with an _HtmlAttributeCollection_ referenced by a `ICollection<HtmlAttribute>` variable **without repeatedly re-obtaining the collection from the owning node's `HtmlNode.Attributes` property**. (Emptying the internal _items_ list by either clearing or removing the last element from it will cause the getter of the _HtmlNode.Attributes_ property to create and provide a new HtmlAttributeCollection, thus masking the issue.)

## 2. Fiddle or Project
https://dotnetfiddle.net/D735Ot

<details>
  <summary>Click to expand the source code</summary>

```C#
using HtmlAgilityPack;
using System;
using System.Collections.Generic;
using System.Linq;

namespace HtmlAttributeCollection_RemoveAndClearNotUpdatingHashItems
{
    class Program
    {
        static void Main(string[] args)
        {
            Remove_Issue_Demo();

            Console.WriteLine();
            Console.WriteLine();

            Clear_Issue_Demo();
        }


        static void Remove_Issue_Demo()
        {
            Console.WriteLine("Demo of AttributeCollection item removal issue");
            Console.WriteLine("----------------------------------------------");
            var (doc, attributes) = CreateHtmlDocument();

            Console.WriteLine($"Number of attributes in collection before removal: {attributes.Count}");
            var attrBeforeRemoval = attributes["class"];
            Console.WriteLine($"Attribute obtained through this[\"class\"] indexer before removal: {attrBeforeRemoval.Name}={attrBeforeRemoval.Value}");

            RemoveAnAttribute(attributes);

            Console.WriteLine($"Number of attributes in collection after removal: {attributes.Count}");
            var attrAfterRemoval = attributes["class"];
            Console.WriteLine($"Attribute obtained through this[\"class\"] indexer after removal: {attrAfterRemoval.Name}={attrAfterRemoval.Value}");



            static void RemoveAnAttribute(ICollection<HtmlAttribute> attributes)
            {
                var attr = attributes.First();
                attributes.Remove(attr);
            }
        }


        static void Clear_Issue_Demo()
        {
            Console.WriteLine("Demo of AttributeCollection clearing issue");
            Console.WriteLine("------------------------------------------");
            var (doc, attributes) = CreateHtmlDocument();

            Console.WriteLine($"Number of attributes in collection before clearing: {attributes.Count}");
            var attrBeforeClearing = attributes["class"];
            Console.WriteLine($"Attribute obtained through this[\"class\"] indexer before clearing: {attrBeforeClearing.Name}={attrBeforeClearing.Value}");

            Clear(attributes);

            Console.WriteLine($"Number of attributes in collection after clearing: {attributes.Count}");
            var attrAfterClearing = attributes["class"];
            Console.WriteLine($"Attribute obtained through this[\"class\"] indexer after clearing: {attrAfterClearing.Name}={attrAfterClearing.Value}");


            static void Clear(ICollection<HtmlAttribute> attributes)
            {
                attributes.Clear();
            }
        }


        static (HtmlDocument doc, HtmlAttributeCollection attributes) CreateHtmlDocument()
        {
            var html = @"<div class=""foobar"">Hello world!</div>";

            var htmlDoc = new HtmlDocument();
            htmlDoc.LoadHtml(html);
            return (htmlDoc, htmlDoc.DocumentNode.SelectSingleNode("//div").Attributes);
        }
    }
}
```
</details>

Note how after the attribute removal or clearing of the attribute collection the item count of the collection is being reported as `0`, yet the removed attribute can still be accessed through the `this[string name]` indexer.

## 3. Any further technical details
- HAP version: 1.11.40
- NET 5.0

**Comment by JonathanMagnan** [comment]
Hello @elgonzo ,

Thank you for reporting,

We will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @elgonzo ,

Just to let you know that the fix for this issue will be part of next release (probably next week).

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @elgonzo ,

The v1.11.41 has been finally released.

Both methods are now calling methods that were handling correctly the `Hashitems` : https://github.com/zzzprojects/html-agility-pack/commit/d0dbd836dc6cba01edd6b57546790eb905afca72

Best Regards,

Jon

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by elgonzo** [comment]
I can confirm that 1.11.41 fixes the issue! :)
