### ISSUE TITLE
startIndex 不能大于字符串长度。\r\n参数名: startIndex

### ISSUE THREAD

**Issue by SanQi2211** [zzzprojects/html-agility-pack#469]
Hi：
there is something wrong when i bebug my code whit v1.11.42

here this the code

    var lst = doc.DocumentNode.SelectNodes(".//ul/li");//count=7， the Attributes datas are right
    
  foreach (var item in lst)
   {
  the Attributes["data"] said "startIndex 不能大于字符串长度。\r\n参数名: startIndex"

//something
}
here is the html:
 

> <div id="content">
	<ul class="nav">	
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam.png>
	        <div>
	            <p>20220217235553</p>
	            <span>未开始</span>
	            	        </div>
	    </li>
					
						
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam.png>
	        <div>
	            <p>20220217235424</p>
	            <span>未开始</span>
	            	        </div>
	    </li>
					
		        	           						
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam.png>
	        <div>
	            <p>20220217235014</p>
	            <span>未交</span>
	            	            <span class="fr">剩余199小时8分钟</span>
	            	        </div>
	    </li>
					
		        	           						
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam.png>
	        <div>
	            <p>20220217234833</p>
	            <span>未交</span>
	            	            <span class="fr">剩余199小时8分钟</span>
	            	        </div>
	    </li>
					
		        	           						
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam.png>
	        <div>
	            <p>20220217223855</p>
	            <span>待批阅</span>
	            	            <span class="fr">剩余221小时56分钟</span>
	            	        </div>
	    </li>
					
		        	           						
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam.png>
	        <div>
	            <p>1</p>
	            <span>已完成</span>
	            	            <span class="fr">剩余200小时29分钟</span>
	            	        </div>
	    </li>
							
		        	           						
	    <li onclick="goTask(this);" data="https://www.baidu.com/android/mtaskmsgspecial?taskrefId=1812692&msgId=0&courseId=219542307&userId=119979361&clazzId=43960908&type=exam&enc_task=d26ededb3e5f914ae97171357f204e15">
	        <img src=/images/exam/phone/task-exam-gray.png>
	        <div>
	            <p>20220217235743</p>
	            <span>未交</span>
	            	        </div>
	    </li>
	</ul>
</div>

**Comment by elgonzo** [comment]
> the Attributes["data"] said "startIndex 不能大于字符串长度。\r\n参数名: startIndex"

I cannot reproduce, as this that's not what Attributes["data"] is saying. Dotnetfiddle: https://dotnetfiddle.net/lCcqny

**Comment by JonathanMagnan** [comment]
Hello @SanQi2211 ,

My developer also tested it and he got the same result as @elgonzo . He cannot reproduce it either.

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @SanQi2211,

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide a runnable project. 

Best regards,

Jon
