### ISSUE TITLE
.Net 3.5 version does not has strong name

### ISSUE THREAD

**Issue by iskiselev** [zzzprojects/html-agility-pack#478]
.Net 3.5 version of assembly does not have strong name. It is broken since 1.11.1 release (it has strong name in 1.11.0). Potentially connected issue: #86.

**Comment by JonathanMagnan** [comment]
Hello @iskiselev, 

Thank you for reaching out to ZZZ Projects, due to summer vacation we will have limited email access which may cause some delays from May 26 to June 1.
We are sorry for any inconvenience.

Best regards, 

Sara

**Comment by iskiselev** [comment]
Thank you, it is good now!
