### ISSUE TITLE
SelectSingleNode must be executed second time to succeed

### ISSUE THREAD

**Issue by aisen0921** [zzzprojects/html-agility-pack#479]
it's my code:
var doc = new HtmlDocument();
doc.LoadHtml(html);
var types = doc.DocumentNode.SelectSingleNode("//div[@class='page_menu']/ul").SelectNodes("li");
var mainTypeUrls = types.Select(x => "https://travel.dl.gov.tw" + x.SelectSingleNode("./a")
.Attributes["href"].Value.Replace("amp;", ""));

website:
https://travel.dl.gov.tw/ch/website/folder/2

I expected the "mainTypeUrls" is:
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=23
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=26
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=27
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=28
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=29
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=30
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=36

but the first executed result is:
https://travel.dl.gov.tw/ch/website/travel/list?module=tourgame&id=23
https://travel.dl.gov.twlist?module=tourfood&id=32" class="nav-link">
https://travel.dl.gov.tw            </div>
https://travel.dl.gov.tw                               <li class="nav-ite
https://travel.dl.gov.twpopup="true" aria-expanded="false">
https://travel.dl.gov.twpdown">                            <div class="
https://travel.dl.gov.tw>

If I execute from code "doc.LoadHtml(html);" again then the result will be as my expected.
I have tried with different xpaths but still the same result.

- HAP version: 1.11.42
- NET version: 4.7.2

**Comment by JonathanMagnan** [comment]
Hello @aisen0921 ,

Tried with the following code: 

```csharp
var html = @"https://travel.dl.gov.tw/ch/website/folder/2";
HtmlWeb web = new HtmlWeb();

var doc = web.Load(html);

var types = doc.DocumentNode.SelectSingleNode("//div[@class='page_menu']/ul").SelectNodes("li");
var mainTypeUrls = types.Select(x => "https://travel.dl.gov.tw" + x.SelectSingleNode("./a").Attributes["href"].Value.Replace("amp;", ""));
```

And I got the expected result.

Could you provide the `html` you used with the `LoadHtml` method?

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by aisen0921** [comment]
Hi @JonathanMagnan Thanks for reply.
I used your code but still the same.

The html from LoadHtml method:
[html](https://jsbin.com/regetuviru/1/edit?html,output)

**Comment by aisen0921** [comment]
@JonathanMagnan I found a weird thing is I add a breakpoint on `var mainTypeUrls `next line, the `mainTypeUrls `content is what I want even next line is just `{ }`.
I tried to delete the /bin folder and rebuild project but not work.
