### ISSUE TITLE
End tag removed when option tag found in html

### ISSUE THREAD

**Issue by Schaeri** [zzzprojects/html-agility-pack#48]
When I retrieve such a simple html snippet containing option fields from the backend:
```
<option selected="selected" value="">Select a cell</option>
<option value="a52059e6-f7f0-4444-ab9d-bac7847d85fe">C1</option>
<option value="7befd28a-5653-473e-b925-1ffa1271df22">C2</option>
```

Then load this content into a html document and get the outer html via htmlDocument.DocumentNode.OuterHtml the html agility pack will remove the option end tag. The output looks like this:
```
<option selected="selected" value="">Select a cell
<option value="a52059e6-f7f0-4444-ab9d-bac7847d85fe">C1
<option value="7befd28a-5653-473e-b925-1ffa1271df22">C2

```
End tag was removed.

When I change my backend to return 
```
<option2 selected="selected" value="">Select a cell</option2>
<option2 value="a52059e6-f7f0-4444-ab9d-bac7847d85fe">C1</option2>
<option2 value="7befd28a-5653-473e-b925-1ffa1271df22">C2</option2>

```
The output is correct of the htmlDocument.DocumentNode.OuterHtml. It looks like this:
```
<option2 selected="selected">Select a cell</option2>
<option2 value="764ccc86-9d51-4c07-89ad-67b574bde117">C1</option2>
<option2 value="0160ff28-7f92-434c-8d67-eb19ca78ec95">C2</option2>

```
We using the HtmlAgilityPack nuget package with version 1.5.1

Is this a bug or do I understand here something wrong. Thanks for the help.

**Comment by JonathanMagnan** [comment]
Hello @Schaeri ,

Thank you for reporting. We will try to look at this issue during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Schaeri ,

Unfortunately, it will take a few more week for fixing this kind of issue.

In September, we will try to look at it and fix all this kind of issue.

Best Regards,

Jonathan

**Comment by atifaziz** [comment]
@JonathanMagnan Per bc0dd476da7dbd89e577cd35b4a4893b3c872fbc comment, it addressed this issue. Any reason it's still open?

**Comment by JonathanMagnan** [comment]
Hello @atifaziz ,

The parser currently have some problem and don't respect rule fully.

That's why this is still open.

We currently already have started to work on a v2.x version that will respect all latest HTML standard.

Best Regards,

Jonathan

**Comment by atifaziz** [comment]
Thanks for the explanation, Jonathan.

> We currently already have started to work on a v2.x version that will respect all latest HTML standard.

Where is this version 2 being developed? [Doesn't seem like there is a branch for it](https://github.com/zzzprojects/html-agility-pack/branches). Is there a roadmap?

**Comment by JonathanMagnan** [comment]
Hello @atifaziz ,

The real source are keeping in TFS with all others projects (we have many paid projects that we started on TFS, so currently I prefer to keep all sources in one place and simply copy it to GitHub when some open source project are released).

Thank you for the proposition, I will certainly think about it to see if something can be done.

Currently, my priority for some obvious reason, stay on paid library and focusing to support .NET Core
Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Just to give an update here,

@atifaziz  contacted me directly about the road map, we will work together to make sure the v2.x will fit user expectation.

Best Regards,

Jonathan

**Comment by Schaeri** [comment]
Thanks for the feedback. Currently we have added some workarounds in our test because of this bug. When will be the release date for the version 2.0?

**Comment by JonathanMagnan** [comment]
Hello @Schaeri ,

Could you ask again the same question in 2 weeks?

There is a lot of discussion in progress about the future of HtmlAgilityPack and I will in a better position to give you a proper answer.

Best Regards,

Jonathan

**Comment by Schaeri** [comment]
Hallo @JonathanMagnan 

Yes sure. No Problem. Thanks again for the very fast feedback.

**Comment by Tarmil** [comment]
Hi, what's the status on this?

**Comment by JonathanMagnan** [comment]
Hello @Tarmil ,

Is your status on this issue or about the v2.0?

Best Regards,

Jonathan
---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by Tarmil** [comment]
I was asking about this specific issue.

**Comment by JonathanMagnan** [comment]
Hello @Tarmil , @Schaeri ,

The v1.6.6 has been released.

We changed the behavior how `option` tag was handled. Please let me know if you find any issue.

Best Regards,

Jonathan

**Comment by Schaeri** [comment]
Hello @JonathanMagnan 
Thanks a lot for fixing this issue. I updated our project and tested the new package. The problem with the option tag is resolved. Great thanks again.

**Comment by ankit1985** [comment]
I am facing same issue. even if  i have Updated HtmlAgilityPack.dll with version 1.8.9.0.
