### ISSUE TITLE
The default encoding in HtmlDocument is Encoding.Default which causes problems

### ISSUE THREAD

**Issue by StefH** [zzzprojects/html-agility-pack#480]
## 1. Description
The default encoding in [HtmlDocument](https://github.com/zzzprojects/html-agility-pack/blob/af2f02fb42e9a70b90a8651579ec6702f42648dc/src/HtmlAgilityPack.Shared/HtmlDocument.cs#L251) is **Encoding.Default** which causes problems, better to just use **UTF8** ?

## 2. Exception
- no exception

## 3. Fiddle or Project
``` c#
var web = new HtmlWeb();
var doc = web.Load("https://www.mstack.nl");
```

The title should actually be:
![image](https://user-images.githubusercontent.com/249938/180068148-4508b470-140f-4403-a486-b9621483ecc9.png)
Which is in html:
``` html
<title>MSTACK – next level consulting and development</title>
```

But when debugging the internals from HtmlWeb, it's:
``` html
<title>MSTACK â next level consulting and development</title>
```

Which looks like:
![image](https://user-images.githubusercontent.com/249938/180068637-a1be0441-312c-44ca-92b5-39edb44ad69d.png)

- HAP: latest
- NET version: net6.0 & netstandard2.0

**Comment by tewuapple** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你的邮件已收到。
亮亮

**Comment by StefH** [comment]
It's clear, thank you. I'll use your code.
