### ISSUE TITLE
Option OutputOptimizeAttributeValues does not parse empty attribute strings correctly

### ISSUE THREAD

**Issue by nikolai-mb** [zzzprojects/html-agility-pack#484]
Parsing a simple document with the OutputOptimizeAttributeValues enabled results in invalid attribute syntax being generated.

See the code below:

```
HtmlDocument doc = new() { OptionOutputOptimizeAttributeValues = true };

doc.LoadHtml("<!doctype html><html><table style=\"\" width=\"100%\">Example</table></html>");

Console.WriteLine(doc.DocumentNode.OuterHtml);
```

Code above prints the following output: `<!doctype html><html><table style= width=100%>Example</table></html>`

Running the output HTML in a browser leads to incorrect attribute parsing:

![image](https://user-images.githubusercontent.com/35340657/187427466-223c4149-5565-41bb-847f-6829a2cf853e.png)

![image](https://user-images.githubusercontent.com/35340657/187427450-30483e65-d265-4e98-bb60-ac1eea66bd85.png)

Browser now interprets the separate width attribute as the value of the previous style attribute, instead of the style attribute being empty. This is the case for all empty attributes, and is not limited to style.

One potential solution could be preserving the quotes for empty attribute values, but i'm not sure if that's the only solution.

The following HTML would be interpreted correctly in the browser: `<table style="" width=100%>Example</table>`

Reproduced on .NET 6 running HAP 1.11.42 and 1.11.45

**Comment by JonathanMagnan** [comment]
Hello @nikolai-mb ,

Why are you using the option `OptionOutputOptimizeAttributeValues` ?

Not saying the behavior of this option is perfect, but that is pretty much how it behaves when writing the HTML:
https://github.com/zzzprojects/html-agility-pack/blob/master/src/HtmlAgilityPack.Shared/HtmlNode.cs#L2365

Depending of what you want achieve, perharp you are looking for another options such as:

```csharp
var doc1 = new HtmlDocument();
doc1.GlobalAttributeValueQuote = AttributeValueQuote.Initial;
```

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by nikolai-mb** [comment]
Thanks for the quick reply.

I'm using the option in order to store HTML in the smallest form possible.
Seeing how the option generates valid HTML in seemingly all cases except this one, i thought it could be used for free space savings.

I'm also using the GlobalAttributeValueQuote option to standardize the quotes in the document. Using both options together seems to omit the quotes where possible, which saves quite a lot of space in large documents depending on the size, while it preserves the quotes specified in the GlobalAttributeValueQuote in the cases where the attribute quotes cannot be omitted (such as style='font-family 10px "Verdana"' for example)

If the option wasn't designed for this purpose, it's no problem for me to stop using it :)

**Comment by JonathanMagnan** [comment]
We are not the original owner of this library, so I cannot exactly tell you why this option was originally added.

So yes, I guess the easier would probably not using this option ;)

Best Regards,

Jon
