### ISSUE TITLE
StackOverflowException with the file

### ISSUE THREAD

**Issue by otto-git** [zzzprojects/html-agility-pack#486]
Thrown exception when parse with html by URL:
`https://otto-git.github.io/all-contact-data/bugurl.html`

**Comment by JonathanMagnan** [comment]
Hello @otto-git ,

The v1.11.46 has been released.

The parsing is slow, but it now works.

Best Regards,

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by otto-git** [comment]
Thanks. It's working
