### ISSUE TITLE
Some nodes are lost

### ISSUE THREAD

**Issue by wpyok500** [zzzprojects/html-agility-pack#487]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description

Some nodes are lost

## 2. Exception
url:  http://www.weather.com.cn/weather/101230203.shtml

![QQ截图20221006230441](https://user-images.githubusercontent.com/14154547/194350479-2e978001-8b53-4e25-ad52-14c8968dcc50.png)

![图片1](https://user-images.githubusercontent.com/14154547/194350536-eaea6f9e-0721-4dad-a0c8-a22001633d40.png)

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
If you are able,

Provide a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
Add any relevant detail can help us, such as: 

- HAP version:
- NET version (net45, .net core 3.1, etc.)
net472

**Comment by JonathanMagnan** [comment]
Hello @wpyok500 ,

You are comparing HAP with the HTML rendered (so after some javascript has been run).

If you check the source code, you will see the node also have no value:

```html
<em>
<span title="无持续风向" class="NNW"></span>
<span title="无持续风向" class="NNW"></span>
</em>
```

See the following answer to have more information about this kind of issue: https://github.com/zzzprojects/html-agility-pack/issues/482#issuecomment-1224098483

> There are 2 way to solve it:
> Use LoadFromBrowser if you are still with .NET Framework: https://html-agility-pack.net/from-browser
> Use Selenium library that will allow you to interact with the HTML (so once the page is loaded).

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by wpyok500** [comment]
@JonathanMagnan 
The tag <i><3级</i> exists when HtmlDocument.LoadHtml() is used, and the <i><3级</i> tag is lost after using SelectNodes .
The same is true with HtmlWeb()


~~~
           WebClient web = new WebClient();
            web.Encoding = Encoding.UTF8;
            var t = web.DownloadDataTaskAsync("http://www.weather.com.cn/weather/101230203.shtml");
            string html = Encoding.UTF8.GetString(t.Result);

            //var web2 = new HtmlWeb();
            //var doc = web2.Load("http://www.weather.com.cn/weather/101230203.shtml");
            HtmlDocument doc = new HtmlDocument();
            doc.LoadHtml(html); //  The document contains <i><3级</i> tags
            HtmlNodeCollection nodes = doc.DocumentNode.SelectNodes("//*[@id=\"7d\"]/ul"); // 有问题：丢失风力 ＜3级  Missing <i><3级</i> tags after SelectNodes
            //CSS选择器需要再nuget: HtmlAgilityPack.CssSelectors
            HtmlNode hnode = doc.DocumentNode.QuerySelector(".t.clearfix");  // 有问题：丢失风力 ＜3级
            HtmlNode hnode1 = doc.DocumentNode.QuerySelector(".c7d");
~~~

**Comment by wpyok500** [comment]
LoadFromBrowser() does not exist

![image](https://user-images.githubusercontent.com/14154547/194441770-2ab9058f-8390-4c20-8178-92284dc366ad.png)

**Comment by elgonzo** [comment]
HtmlAgilityPack does not simply lose the content of the \<i\> nodes when using _SelectNodes_.

Proof: https://dotnetfiddle.net/rtBnoM

Note the `<i><3级</i>` appearing in the output of the inner html of the selected \<ul\> node.

**Comment by JonathanMagnan** [comment]
Hello @wpyok500 ,

Sorry, you are indeed right, the text is part of the source code, I checked the wrong part of the source.

However, @elgonzo is also right; in the latest version, no bug seems to exist. Here is another Fiddle copied from the one from @elgonzo that also do the `QuerySelector` part, and all the 3 output have no problem returning the value: https://dotnetfiddle.net/hfma4k

Best Regards,

Jon

**Comment by wpyok500** [comment]
@elgonzo @JonathanMagnan  Greetings

I found that there is a problem of losing the i tag when using 1.11.46. After rolling back 1.11.45, the i tag will not be lost. After upgrading to 1.11.46 again, there is no such problem.

![image](https://user-images.githubusercontent.com/14154547/194681562-a377302f-6a49-488b-8668-835eb203e841.png)
