### ISSUE TITLE
Signed dlls required!

### ISSUE THREAD

**Issue by WELL-E** [zzzprojects/html-agility-pack#489]
Is there a digital signed version of HtmlAgilityPack.dll?

**Comment by JonathanMagnan** [comment]
Hello @WELL-E ,

No, but the library is strongly named (however, the key is public).

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by WELL-E** [comment]
Thanks!
