### ISSUE TITLE
[Feature Request] expose library to Component Object Model (COM)

### ISSUE THREAD

**Issue by smfukaya** [zzzprojects/html-agility-pack#492]
It would be great if HTML Agility Pack could be used in Microsoft Office/VBA projects in order to parse ill-formed HTML and use its xpath features.

## 1. Description
Expose all classes to Component Object Model (COM) in order to be referenced by VBA applications.

## 4. Any further technical details
- [Exposing .NET components to COM](https://learn.microsoft.com/en-us/dotnet/framework/interop/exposing-dotnet-components-to-com)
- [Exposing .NET Components to COM](https://www.codeproject.com/Articles/3511/Exposing-NET-Components-to-COM)

**Comment by JonathanMagnan** [comment]
Hello @smfukaya ,

Feel free to make a fork and make this request, but on our side, that's currently not in our plan to expose our library to COM.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)
