### ISSUE TITLE
Angular html  code is modified  when save

### ISSUE THREAD

**Issue by luver225** [zzzprojects/html-agility-pack#494]
before saving：
`<nz-form-label nzrequired nznocolon nzspan="8"></nz-form-label>`

after saving:
`<nz-form-label nzrequired="" nznocolon="" nzspan="8"></nz-form-label>`

every directive in angular html is followed by =""

How to avoid or fix problems？

**Comment by elgonzo** [comment]
Try setting the `GlobalAttributeValueQuote` property on your _HtmlDocument_ instance to `AttributeValueQuote.Initial`:

    var myHtmlDoc = new HtmlDocument() { GlobalAttributeValueQuote = AttributeValueQuote.Initial };

(dotnetfiddle: https://dotnetfiddle.net/i2qjne)

It's documented very poorly, with very sparse and barely comprehensible Intellisense/code comments for both [_GlobalAttributeValueQuote_](https://github.com/zzzprojects/html-agility-pack/blob/08aae949868908de457a77668a9489d73f0280b9/src/HtmlAgilityPack.Shared/HtmlDocument.cs#L170-L171) and [_AttributeValueQuote_](https://github.com/zzzprojects/html-agility-pack/blob/08aae949868908de457a77668a9489d73f0280b9/src/HtmlAgilityPack.Shared/HtmlAttribute.cs#L330-L357) the only documentation i could find. Therefore, i am not sure if this property does something i am not aware of, and i strongly advise you to not blindly rely on my suggestion but rather verify the result of setting _GlobalAttributeValueQuote_ on a more complex html sample.

**Comment by JonathanMagnan** [comment]
Hello @luver225 ,

@elgonzo is right, is you want to keep the current `AttributeValueQuote`, you need to set it to `AttributeValueQuote.Initial`

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by luver225** [comment]
thanks，it works
