### ISSUE TITLE
Setting node name seems to work only partially

### ISSUE THREAD

**Issue by arekdygas** [zzzprojects/html-agility-pack#497]
## 1. Description
When I execute the following code:

```
var node = HtmlNode.CreateNode("<div data-num=\"10\">aaa</div>");
//node.Attributes.Remove("data-num");
node.Name = "p";
Console.WriteLine(node.Name);
Console.WriteLine(node.OuterHtml);
```
`node.Name` is correctly displayed as `p`, but there's still `div` in OuterHtml. But after uncommenting the line with attribute removal, this works correctly.

I suspect this has something to do with setting `_changed` flag, which is not called on Name setter.

## 2. Exception
--

## 3. Fiddle or Project
https://dotnetfiddle.net/6s8zO7

## 4. Any further technical details
- HAP version: 1.11.46
- NET version 4.8

**Comment by JonathanMagnan** [comment]
Hello @arekdygas ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by JonathanMagnan** [comment]
Hello @arekdygas ,

Sorry for the long delay.

This issue has been fixed in the v1.11.47

Let me know if everything now works as expected.

Best Regards,

Jon

**Comment by arekdygas** [comment]
Hello @JonathanMagnan ,

Looking at the code changes, it's probably fixed, but my test failed again, because you uploaded version 46 as 47 to nuget ;)

Best regards,
Arek

**Comment by JonathanMagnan** [comment]
Hello @arekdygas ,

100% my mistake! The v1.11.48 has been released with the right assembly version and with the fix this time ;)

Best Regards,

Jon

**Comment by arekdygas** [comment]
Fixed now - thanks! :)

Best regards,
Arek
