### ISSUE TITLE
[Feature Request] Get specific property value of 'style' attribute

### ISSUE THREAD

**Issue by pycxu** [zzzprojects/html-agility-pack#501]
## Description
I'm trying to get specific property values from the 'style' attribute of a html node.

GetAttributeValue("style", "") returns a string of all the styles separated with semicolon:
    e.g. "left: 48.1542mm; top: 34.6604mm; z-index: 101; width: 48.9479mm; height: 33.6021mm; outline: none; overflow: hidden;"

I have to split and parse the string to get the property (please advise if there are better ways to do it):
```
  var styles = node.GetAttributeValue("style", "")
                  .Split(';').Where(x => string.IsNullOrEmpty(x) == false).Select(x => x.Trim())
                  .Select(x => x.Split(':')).Select(x => new KeyValuePair<string, string>(x[0], x[1]));
  
  decimal.TryParse(styles.Where(style => style.Key == "left").Single().Value.ToSignedFloat(), out positionStartX);
```

I am wondering if is possible to have similar [APIs like the CSS Object model.](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)

Cheers

**Comment by JonathanMagnan** [comment]
Hello @pycxu ,

I would recommend you create your own extension methods. So your could use it this way:

```
node.GetAttributeValue("style", "").GetComputedStyle("left");
```

You pretty much already have the code you want for this method.

I do not believe at this moment we will add it on our side.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by elgonzo** [comment]
Just an FYI: Getting a _computed_ style properly is not simply done by parsing the source HTML document and extracting the style values from the "style" attribute. To get actual _computed_ styles would require more or less a layout engine plus possibly a Javascript engine, something that is well beyond a "simple" HTML parser.

If you really need _computed_ style properties of an element in your HTML document (emphasis on "computed"), the best approach is probably using a head-less browser engine, something like [CEF](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-introduction) (for which there is also a .NET wrapper: [CefSharp](https://cefsharp.github.io/))

**Comment by pycxu** [comment]
> 



> Just an FYI: Using the function name `GetComputedStyle` here is likely misleading. Getting a _computed_ style properly is not simply done by parsing the source HTML document and extracting the style values from the "style" attribute. To get actual _computed_ styles would require more or less a layout engine plus possibly a Javascript engine, something that is well beyond a "simple" HTML parser.
> 
> If you would really need _computed_ style properties of an element in your HTML document (emphasis on "computed"), the best approach would be probably using a head-less browser engine, something like [CEF](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-introduction) (for which there is also a .NET wrapper: [CefSharp](https://cefsharp.github.io/))

Thanks for the heads up. That makes so much sense. I will do that with [Puppeteer Sharp](https://www.puppeteersharp.com/api/index.html).
