### ISSUE TITLE
Does not load the page

### ISSUE THREAD

**Issue by DomenicoFormoso** [zzzprojects/html-agility-pack#504]
Don't load page if url ends with .html

Uri LinkProdotto = new Uri("https://www.eaton.com/it/it-it/skuPage.177633.html");
            HtmlAgilityPack.HtmlWeb web = new HtmlAgilityPack.HtmlWeb();
            try
            {
                HtmlAgilityPack.HtmlDocument doc = web.Load(LinkProdotto);

HtmlAgilityPack 1.11.48
.Net Framework 4.8

**Comment by elgonzo** [comment]
It seems the web server you are trying to load from is taking issue with HtmlAgilityPack's default UserAgent string.

https://github.com/zzzprojects/html-agility-pack/blob/c12580b2025144d618d3397dec1fd81132e3f822/src/HtmlAgilityPack.Shared/HtmlWeb.cs#L100

Set the UserAgent to an empty string, and (with respect to the URL you are using) Bob should be your uncle.
```C#
Uri LinkProdotto = new Uri("https://www.eaton.com/it/it-it/skuPage.177633.html");
HtmlAgilityPack.HtmlWeb web = new HtmlAgilityPack.HtmlWeb()
{
    UserAgent = null
};
...
```

(Side note: In case you are not already aware of it, keep in mind that HtmlAgilityPack is "just" a HTML parser and not a web browser engine and therefore does not execute Javascript, WASM or other dynamic content. It will only parse the source HTML page as provided by the web server. If the page contains Javascript, WASM or other dynamic content, the source HTML page parsed by HtmlAgilityPack can look quite different from the HTML document dynamically created from that source HTML page within a web browser.)

**Comment by basicn86** [comment]
I run into the same issue. I have no clue why it happens either. It appears as though that these websites have some type of protection against crawlers or scrapers. For example, I can visit `https://microcenter.com/` just fine on Firefox, but on HTML Agility Pack, it returns some strange page asking me to enable JavaScript. It probably has to do something with cookies or JavaScript. Even when I used `curl`, I get the same issue. Setting the user agent doesn't change a thing. I think some websites are just impossible to crawl through.

**Comment by elgonzo** [comment]
@basicn86 yeah, if you need to process dynamic web content, HAP in itself is not the right (or sole) tool to use. As i mentioned in the side note in my first comment, HAP is just a HTML parser, not a web browser and therefore doesn't have facilities such as a javascript engine or wasm host required for generating dynamic page content. In such cases, the right tool for the job is -- depending on the nature of the application -- either a (headless-capable) browser engine such as CEF as part of your application, or a browser automation tool like Selenium WebDriver plus whichever stand-alone web browser Selenium supports.

**Comment by JonathanMagnan** [comment]
I will close this issue as it looks to be answered by @elgonzo 

On my side, whenever I need to do something beyond the purpose, HAP can do, such as processing dynamic web content, I always such [Selenium WebDriver](https://riptutorial.com/selenium-webdriver), which allows me to do pretty much everything including automating some action such as login, submitting form, etc.

Best Regards,

Jon
