### ISSUE TITLE
The default value of NodeReturnType in XPathAttribute is InnerText

### ISSUE THREAD

**Issue by rwecho** [zzzprojects/html-agility-pack#507]
After the PR #506 merged,  I used 1.11.50 in my project. 

Now there is a question of reality,  We must specify the NodeReturnType  with InnerHtml or OuterHtml to the nested node. 

Because in the previous version the code we use the innerHtml for Encapsulation:
``` csharp
innerHtmlDocument.LoadHtml(htmlNode.InnerHtml);
```

Now we use the innerText as default for Encapsulation:
https://github.com/zzzprojects/html-agility-pack/blob/2e98e144d8a89c0c0a8a8482fb6c4ee7bfaf0ec8/src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs#L821

In other words, it can lead exception to upgrade the version to 1.11.50, if we use like the below code :

``` csharp

    [HasXPath]
    public class InnerHtml
    {
        [XPath("//div")]
        public List<Link> Links { get; set; } = new List<Link>();

        [HasXPath]
        public class Link
        {
            [XPath("//a", "href")]
            public string Href { get; set; }
        }
    }

        var html = @"
<div>
<a href='1.html' >1</a>
</div>

      //...
      var innerHtml = document.DocumentNode.GetEncapsulatedData<InnerHtml>();
";
```
It will throw not found error because the Links find in the InnerText. If want the code running success , we must add the  [XPath("//div", ReturnType.InnerHtml)]

@elgonzo
@JonathanMagnan 

I'm sorry to bring this up so late. Please assess whether this is a hidden danger and whether it may have an impact on some important projects

In my opinion, Explicit declaration is maybe a correct things.

**Comment by elgonzo** [comment]
Yeah, that's a nice catch and a very good question.

If backwards compatibility here is important, i have an idea that both maintains backwards compatibility while also enabling proper usage of the NodeReturnType property.

The foundation underlying my idea is to make XPathAttribute keeping state about whether NodeReturnType has been explicitly set or not. For tracking whether an XPathAttribute instance or attribute annotaton sets the NodeReturnType explicitly, XPathAttribute will use a boolean property/field indicating exactly that. I name it `IsNodeReturnTypeExplicitlySet`. It should be an internal property/field so that the HAP library itself can query it but it otherwise remains invisible to user code consuming the HAP library.

Something like this (abridged version of the suggested XPathAttribute implementation):
```C#
public sealed class XPathAttribute : Attribute
{
    ...

    internal bool IsNodeReturnTypeExplicitlySet { get; private set; }
    
    public ReturnType NodeReturnType
    {
        get => _nodeReturnType;
        set
        {
            _nodeReturnType = value;
            IsNodeReturnTypeExplicitlySet = true;
        }
    }
    private ReturnType _nodeReturnType;
    
    ...
    
    public XPathAttribute(string xpathString, ReturnType nodeReturnType)
    {
        XPath = xpathString;
        NodeReturnType = nodeReturnType;
        IsNodeReturnTypeExplicitlySet = true;
    }
```
This is done specifically in a way to keep the IsNodeReturnTypeExplicitlySet flag operable even when a user only updates HAP without recompiling their user code/classes that make use of the \[XPath\] attribute.

The second step necessary is a modification of those call sites of Tools.GetHtmlForEncapsulation that didn't account for the NodeReturnType in the old HAP codebase. Those call sites should only pass NodeReturnType values explicitly specified in an \[XPath\] attribute notation/instantiation, otherwise they should pass whatever would match the old code behavior, e.g., something like this (i am basing this on your PR https://github.com/zzzprojects/html-agility-pack/pull/506):

https://github.com/zzzprojects/html-agility-pack/blob/2e98e144d8a89c0c0a8a8482fb6c4ee7bfaf0ec8/src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs#L180

would change into something like this:
```C#
    innerHtmlDocument.LoadHtml(
        Tools.GetHtmlForEncapsulation(
            htmlNode,
            (xPathAttribute.IsNodeReturnTypeExplicitlySet) ? xPathAttribute.NodeReturnType : ReturnType.InnerHtml
        )
    );
```
and

https://github.com/zzzprojects/html-agility-pack/blob/2e98e144d8a89c0c0a8a8482fb6c4ee7bfaf0ec8/src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs#L298

would in the same manner change into something like this:
```C#
    innerHtmlDocument.LoadHtml(
        Tools.GetHtmlForEncapsulation(
            node,
            (xPathAttribute.IsNodeReturnTypeExplicitlySet) ? xPathAttribute.NodeReturnType : ReturnType.InnerHtml
        )
    );
```

What do you think about this approach?

**Comment by elgonzo** [comment]
As an addendum, i pondered a while whether it is worthwhile to keep backward compatibility here, even though i gave an idea about how to maintain it. The old behavior from the old codebase is quite a bit inconsistent, and inconsistent behavior plus adding something more is at the end of the day still inconsistent behavior, just with some topping on it. :-P And trying to understand (or explain to someone) these inconsistencies in the GetEncapsulatedData behavior when it is used in somewhat complex scenarios could become a bit of a challenge, i fear.

Backwards compatibility is a rather strong argument, and usually i gravitate towards maintaining backwards compatibility unless there is a good reason not to. But i also feel the inconsistencies in the old GetEncapsulatedData implementation (including the related attributes such as \[XPath\]) related to the NodeReturnType handling are such a good reason to not keep this particular case of backwards compatibility. Just my 2c, of course. No strings attached, i am not a stakeholder in HAP, so feel free without worries to completely dismiss my expressed opinion if you disagree. :-)

**Comment by rwecho** [comment]
@elgonzo I'm very glad that you could come and discuss this issue with me. 
If we keep the backward compatibility, we can also modify the code :

``` csharp
innerHtmlDocument.LoadHtml(Tools.GetHtmlForEncapsulation(node, xPathAttribute.NodeReturnType==ReturnType.InnerText ? ReturnType.InnerHtml: xPathAttribute.NodeReturnType)); 
```

Because in the context of the code, if has checked the HasXPathAttribute
https://github.com/zzzprojects/html-agility-pack/blob/2e98e144d8a89c0c0a8a8482fb6c4ee7bfaf0ec8/src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs#L114

To the LoadHtml method, It should want an HTML instead of text (Are there any special cases that I haven't thought of?).

After all, this is a very old project, and I believe that maintaining compatibility is of higher priority. Additionally, we should also listen to @JonathanMagnan's advice.

**Comment by elgonzo** [comment]
> @elgonzo I'm very glad that you could come and discuss this issue with me. If we keep the backward compatibility, we can also modify the code :
> 
> ```cs
> innerHtmlDocument.LoadHtml(Tools.GetHtmlForEncapsulation(node, xPathAttribute.NodeReturnType==ReturnType.InnerText ? ReturnType.InnerHtml: xPathAttribute.NodeReturnType)); 
> ```
I don't think this is a good behavior for a public API. Here's why:

If a user defines an annotation like `[XPath("//whatever", NodeReturnType = ReturnType.InnerText)]`, even for a type, then the behavior of GetEncapsulatedData should be as mandated by this attribute annotation. Which means, it should honor the explicitly specified ReturnType.InnerText. If for whatever reason the GetEncapsulatedData implementation cannot honor a a specified NodeReturnType value for technical reasons, then it should produce some exception/error in that regard.

In my opinion, the GetEncapsulatedData implementation should not try to be smarter than the user and sneakily override a user-specified NodeReturnType, as this will make the NodeReturnType property of the XPathAttribute ambiguous, thus making it more difficult to read code with XPathAttribute annotations using NodeReturnType values correctly. Correct understanding of such user code would then essentially put a burden on the user (or reviewer) about having to understand the additional context or conditions regarding when which NodeReturnType values would mean exactly what in reality. Given the sparse documentation surrounding GetEncapsulatedData, i would be very hesitant to make its behavior and that of its related attributes "clever", fuzzy and less obvious.

<br>

> Additionally, we should also listen to @JonathanMagnan's advice.

Oh, i fully agree with you. In the end it's zzzproject / Jonathan's decision how to proceed as they have to maintain the library and deal with user feedback etc.

<br>

(A pointless side note :-) Yes, HAP is a very old library, dating back to 2005 or so. But the GetEncapsulatedData API is a baby in comparison, added to HAP "only" in 2018. Still five years, though...)

**Comment by rwecho** [comment]
@elgonzo As you say, the code should not guess the user purpose, I take your advice and create a PR #509 .
And more , I add a default constructor, to make it possible to get some html from some properties. After all, some front-end writing methods are too flexible these days. 

``` csharp
public XPathAttribute(string xpathString, string attributeName, ReturnType nodeReturnType)
```
@elgonzo @JonathanMagnan We can assess whether this pull request is appropriate

**Comment by rwecho** [comment]
@elgonzo https://github.com/zzzprojects/html-agility-pack/blob/2e98e144d8a89c0c0a8a8482fb6c4ee7bfaf0ec8/src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs#L216
In the code, it can handle the conversion of DateTime type, but it is unable to convert DateTime? correctly. I don't know how you handle this. 

Currently, my project has enabled Nullable globally, but it appears that HAP does not adapt well to this configuration.

**Comment by elgonzo** [comment]
> https://github.com/zzzprojects/html-agility-pack/blob/2e98e144d8a89c0c0a8a8482fb6c4ee7bfaf0ec8/src/HtmlAgilityPack.Shared/HtmlNode.Encapsulator.cs#L216
> 
> In the code, it can handle the conversion of DateTime type, but it is unable to convert DateTime? correctly. I don't know how you handle this. In fact, this is just a feature and does not affect the functionality of the code.
> 
> Currently, my project has enabled Nullable globally, but it appears that HAP does not adapt well to this configuration.

That's a valid and real issue, but unrelated to NodeReturnType. Best to move this into its own issue report (and which i just did: https://github.com/zzzprojects/html-agility-pack/issues/510)

**Comment by JonathanMagnan** [comment]
Hello @rwecho ,

I will close this issue has the v1.11.51 has been released with your latest fix.

Thank again for your contribution ;)

Best Regards,

Jon
