### ISSUE TITLE
Trailing slash on void element becomes part of the attribute name

### ISSUE THREAD

**Issue by austinw-fineart** [zzzprojects/html-agility-pack#514]
## 1. Description
In the HTML standard, the trailing slash can exist on a void element with no effect, except when directly preceded by unquoted attribute values. Therefore the following is valid HTML:
`<input id=foo disabled/>`
However, HAP will parse this as having an attribute named `disabled/` which is incorrect. The trailing slash should only be parsed as part of an unquoted attribute's value, such as `<input id=foo disabled=/>` and produce the attribute `(name: "disabled", value: "/")`

## 2. Exception
N/A

## 3. Fiddle or Project
https://dotnetfiddle.net/aAyPFj

## 4. Any further technical details
- HAP version: 1.11.53
- NET version: net7.0

**Comment by JonathanMagnan** [comment]
Hello @austinw-fineart ,

The v1.11.54 has been released.

This issue should now be fixed in this version. The `/` will not be part of the attribute name anymore.

Best Regards,

Jon

**Comment by austinw-fineart** [comment]
Much appreciated! Can confirm, closing as fixed.
