### ISSUE TITLE
LoadHTML leads to wrong result when node is named "base"

### ISSUE THREAD

**Issue by mausoma** [zzzprojects/html-agility-pack#520]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
The following html is not read correctly:

```csharp
            var html = @"<root><base>A</base></root>";

            var doc = new HtmlDocument();
            doc.LoadHtml(html);
            var result = doc.DocumentNode.OuterHtml;
            Trace.WriteLine(result);
```

The result is a missing end tag for <base>:
    <root><base>A</root>

P.S. if I change the input , everything is correct:
            var html = @"<root><another_base>A</another_base></root>";
    ... leads to ....
     <root><another_base>A</another_base></root>

## 2. Exception
I would expect :
```
    <root><base>A</base></root>
```

## 4. Any further technical details

    HAP version: 1.11.54
    NET Framework 4.7.2

**Comment by JonathanMagnan** [comment]
Hello @mausoma ,

The `base` tag is a tag that doesn't close: https://www.w3schools.com/tags/tag_base.asp

So, this is an expected behavior for an `HTML` parser.

You are currently trying to use `XML` in a `HTML` parser. so different behaviors are expected.

Best Regards,

Jon

**Comment by mausoma** [comment]
You're right, but for some reasons I cannot move to XmlDocument (to name one, I cannot have multiple root elements). Thanks for your answers. Somehow I have to deal with it...
:)
