### ISSUE TITLE
Closing tag in script is recognized as HTML

### ISSUE THREAD

**Issue by shravan2x** [zzzprojects/html-agility-pack#521]
When an HTML script tag contains JS that includes </script>, the HTML script tag is closed instead. For example,

```
<html lang="en-US" prefix="og: https://ogp.me/ns#" class="" itemtype="https://schema.org/Blog" itemscope="" style="margin-top: 69.1979px !important">
   <body class="aitool-template-default single single-aitool postid-26456 wp-custom-logo wp-embed-responsive footer-on-bottom hide-focus-outline link-style-no-underline content-title-style-normal content-width-normal content-style-boxed content-vertical-padding-show non-transparent-header mobile-non-transparent-header kadence-elementor-colors e-lazyload elementor-default elementor-kit-1339 elementor-page-20666 trigger-position-right quick-links-position-left trigger-size-small trigger-color-blue mysticky-welcomebar-apper e--ua-blink e--ua-chrome e--ua-webkit cookies-not-set" data-elementor-device-mode="desktop">
      <script type="text/javascript">!function(e){fucript"===a?(e=l.createElement("div"),e.innerHTML="<script>
      </script>",e=e.removeChild(e.firstChild)):s)}]));</script>
   </body>
</html>
```

Here the website has JS like `e.innerHTML="<script></script>"`. HAP interprets this closing HTML script tag to close the HTML script tag instead. This results in broken parsing like this for the `body` tag:

```
[
  "Text(\n      )",
  "Element(script)",
  "Text(\u0022,e=e.removeChild(e.firstChild)):s)}]));)",
  "Text(\n   )"
]
```

Chrome seems to be able to parse HTML like this correctly. Is there something the library could do as well?

- HAP version: 1.11.54
- NET version (net45, .net core 3.1, etc.): .NET 7

**Comment by elgonzo** [comment]
> Chrome seems to be able to parse HTML  like this correctly.

You seem to be mistaken.

Chrome 118.0.5993.118 behavior is equivalent to what you observed with HtmlAgilityPack. Loading your example HTML into Chrome yields this result:
![Ch](https://github.com/zzzprojects/html-agility-pack/assets/6129198/4a1e0641-90a2-4d19-b225-58ff0ee70bf5)
Note how the part of the intended Javascript code after the first occurence of `</script>` is treated as text content for the HTML body.

Firefox 118.0.2 behaves in the same manner as Chrome and HtmlAgilityPack:
![ff](https://github.com/zzzprojects/html-agility-pack/assets/6129198/00fe3132-69d1-4a87-b8f5-9ba70e77042a)

Also, in case you aren't already aware of it, worth of note in this context are also the restrictions the HTML standard places on the content of script elements: https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements

**Comment by JonathanMagnan** [comment]
Hello @shravan2x ,

Let me know if the answer from @elgonzo is good.

I tested it also on Firefox and got the same behavior as him and `HAP`.

Best Regards,

Jon
