### ISSUE TITLE
Bad ZZZ Code.AI suggestion

### ISSUE THREAD

**Issue by scarabdesign** [zzzprojects/html-agility-pack#522]
## 1. Description
Unless I'm doing something wrong, it looks like Code.AI is suggesting bad code. I wasn't sure where to report this issue, but since it's linked directly in the HAP documentation, I figured this was probably the best place. https://html-agility-pack.net/select-nodes

As per the suggestion on the HTML Agility Pack documentation page, I asked the following question: 
https://zzzcode.ai/answer-question?id=447c1b4a-136f-411b-8c1a-7c6536a90ec0

## 2. Exception
```
blazor.webview.js:1  '.class1, .class2, .class3' has an invalid token.
   at MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression(String xpathExpression)
   at System.Xml.XPath.XPathExpression.Compile(String xpath, IXmlNamespaceResolver nsResolver)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at HtmlAgilityPack.HtmlNode.SelectNodes(String xpath)
   at Viands.Data.ViewModels.VList.GetMenuBrief()
   at Viands.Data.ViewModels.VList.get_FilteredDescription()
   at Viands.Pages.Index.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

## 3. Fiddle or Project
Here is the code that the AI suggests:
```
HtmlDocument htmlDoc = new HtmlDocument();
htmlDoc.Load("path/to/your/html/file.html");

HtmlNodeCollection nodes = htmlDoc.DocumentNode.SelectNodes(".class1, .class2, .class3");

if (nodes != null)
{
    foreach (HtmlNode node in nodes)
    {
        // Do something with the selected nodes
    }
}
```

Here is my code:
```
        public string GetMenuBrief()
        {
            if (!string.IsNullOrEmpty(Description) && !IsSet && !IsTemplate)
            {
                var wholeString = new HtmlDocument();
                wholeString.LoadHtml(Description);
                var desc = new List<string>();
                wholeString.DocumentNode?.SelectNodes(".class1, .class2, .class3")?.ToList().ForEach(e =>
                {
                    desc.Add(e.InnerText.Replace("&nbsp;", " ").Trim());
                });
                return string.Join(", ", desc);
            }

            return Description;
        }
```

## 4. Any further technical details
- HAP version: 1.11.54
- NET version (.net8 preview)

Maybe I'm doing it wrong, but it looks like the AI is spewing bad results (as ChatGPT is wont to do).

**Comment by elgonzo** [comment]
> Unless I'm doing something wrong, it looks like Code.AI is suggesting bad code. I wasn't sure where to report this issue [...]

While i am just a user of HAP and not associated with the HAP project nor its authors/maintainers, i would like to point out that the issue tracker for HAP is not the right place to report issues with zzzcode.ai. Instead, i would like to suggest you report the problem you encountered in the issue tracker for zzzcode.ai, whose project site (including its issue tracker) is also on github: https://github.com/zzzprojects/zzzcode.ai

**Comment by malamai123** [comment]
Nice 👍👍👍👍

**Comment by elgonzo** [comment]
@JonathanMagnan
note that currently, after the fix, the AI code generator generates an example code like
```C#
HtmlNodeCollection nodes = doc.DocumentNode.SelectNodes("//div[contains(@class, 'class1') or contains(@class, 'class2')]");
```
This is still not entirely correct. Someone who due to a lack of knowledge has to ask such a question to an AI assistant might intuitively expect that the given answer/code example selects div nodes having the CSS classes "class1" or "class2".
But the answer/code example provided by the bot also selects div nodes with the classes "class13", "class21", "subclass10", etc., which arguably is not what the asking person is looking for.

MStackOverflow Q&A i linked to in my previous post demonstrates the most robust and accurate XPath expression for selecting CSS classes that should be suggested by the bot instead:

    //div[contains(concat(' ', normalize-space(@class), ' '), ' Test ')]

It's not pretty (because it involves padding the `@class` attribute value as well as the class name with spaces), but that's what is needed to get a robust and accurately working XPath expression for this task.

**Comment by JonathanMagnan** [comment]
Hello @elgonzo ,

We don't choose what ChatGPT generates. It might either help or lead you in a bad way, but the more time passes, the better it becomes.

Eventually, it will be easier to train a custom model for a specific subject, and then we will be able to provide him with a ton of examples about what the best practices should be despite what he already knows. Open AI is growing quickly with new features every month, so I believe by the end of 2024, they will provide an easier way to train a custom model dedicated to Html Agility Pack (it's already possible with some third-party software at this moment).

**Comment by JonathanMagnan** [comment]
Happy New Year @elgonzo  ;)

**Comment by scarabdesign** [comment]
Whether the AI is improving or not, just like other modern early adopters of GPT, your going to get bad results, and those bad results taint the believability of GPT. I'm not sure I'll fully trust the AI for accurate answers from any source or subject, as it's just a text prediction algorithm, not artificial intelligence. You may say is a good thing to not trust it fully, however, when your product is so light on documentation and relies so heavily on PGT, you're generating support calls and confusion.

IMO, you may want to pop it back in the oven until it's done.
