### ISSUE TITLE
PreviousSibling not retrieving the entire html content

### ISSUE THREAD

**Issue by alekthecar** [zzzprojects/html-agility-pack#523]
For this html snippet:

```
<p>
  Example paragraf text
  <span class="bold">
    <strong>
      example bold text
    </strong>
  </span>.
</p>
<div class="informaltable table-responsive">
  <table class="informaltable frame-void rules-all">
    ...table content...
  </table>
</div>
```

and this line of code (informaltableDiv is HtmlNode corresponding to <div> element with "informaltable" class):

`var prevSibling = informaltableDiv.PreviousSibling;`

prevSibling (more precisely, it's OuterHtml) evaluates to:

```
<p>
  Example paragraf text
  <span class="bold">
    <strong>
      example bold text
    </strong>
  </span>.
</p>
```

which is expected!

However, for this html snippet (p element replaced by "titlepage" div element):

```
<div class="titlepage">
  <div>
    <div class="title">
      <h6 class="title">
        Example title text.
        <a class="header-link" data-anchorid="#UUID-8cceb3c9-e47e-ae17-e408-3b9d9e53f42c_section-idm4646452276537633786433809635" data-original-title="" title="">
          <i class="fa fa-link"></i>
        </a>
      </h6>
    </div>
  </div>
</div>
<div class="informaltable table-responsive">
  <table class="informaltable frame-void rules-all">
    ...table content...
  </table>
</div>
```

and the same line of code:

`var prevSibling = informaltableDiv.PreviousSibling;`

expected (prevSibling to evaluates to):

```
<div class="titlepage">
  <div>
    <div class="title">
      <h6 class="title">
        Example title text.
        <a class="header-link" data-anchorid="#UUID-8cceb3c9-e47e-ae17-e408-3b9d9e53f42c_section-idm4646452276537633786433809635" data-original-title="" title="">
          <i class="fa fa-link"></i>
        </a>
      </h6>
    </div>
  </div>
</div>
```

actual (missing h6 element):

```
<div class="titlepage">
  <div>
    <div class="title">
    </div>
  </div>
</div>
```

* target framework is .NET 6.0

I'm expecting to get entire content of html node with PreviousSibling. Am I missing something?

**Comment by JonathanMagnan** [comment]
Hello @alekthecar ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

I create a fiddle and I have the expected result: https://dotnetfiddle.net/gyKAHn

Best Regards,

Jon

**Comment by alekthecar** [comment]
Hello Jon,

first of all, thanks for the quick reply!

After looking at your fiddle and extensive investigation, I found out PreviousSibling works just fine and that my project code actually changed the content of HtmlNode by removing <h6> element. I apologize for the confusion I might create.

Best Regards,

Aleksandar
