### ISSUE TITLE
update System.Net.Http to 4.3.4

### ISSUE THREAD

**Issue by drma-dev** [zzzprojects/html-agility-pack#527]
![image](https://github.com/zzzprojects/html-agility-pack/assets/12803050/24d29e6e-1612-46c3-bd7b-f491278434e8)
This version is already very outdated and full of security flaws.

**Comment by JonathanMagnan** [comment]
Hello @drma-dev ,

The v1.11.55 has been released: https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.11.55

We updated 2 packaged that had some vulnerability.

Thank you again for reporting this, and let us know if we missed a package.

Best Regards,

Jon
