### ISSUE TITLE
HAP does not fix nested anchors

### ISSUE THREAD

**Issue by superstator** [zzzprojects/html-agility-pack#53]
I've run into an issue where HAP isn't fixing nested <a> tags in html. 

https://stackoverflow.com/questions/45362431/closing-anchor-tags-with-htmlagilitypack

I see that OptionFixNestedTags is advertised as only applying to table/list elements, but I have some changes on my machine that seem to let it work properly for all non-self-nestable tags. I'm probably missing a pitfall somewhere, but would you like me to push a branch with those changes and we can take a look at it?

**Comment by JonathanMagnan** [comment]
Hello @superstator ,

The v1.6.0-beta1 has been released,

Please reopen this issue if you still have the problem.

Best Regards,

Jonathan
