### ISSUE TITLE
(2) The html rendering result is different from the html output result

### ISSUE THREAD

**Issue by colindcli** [zzzprojects/html-agility-pack#532]
Similar to the previous situation in #529 

![spandiv](https://github.com/zzzprojects/html-agility-pack/assets/3311217/d8b9908a-75d4-4e6c-9c03-7807f047d16f)

``` c#
var html = @"<span><div></div></span>";
var doc = new HtmlDocument();
doc.LoadHtml(html);
var newHtml = doc.DocumentNode.OuterHtml;  //<span></span><div></div>
var res = @"<span><div></div></span>"; //chrome or edge rendering results
var b = newHtml == res;  //false
```

Test URL: [https://dotnetfiddle.net/HrDL5G](https://dotnetfiddle.net/HrDL5G)

**Comment by colindcli** [comment]
**second example:**

There is also a more special code. The code has been simplified to the minimum. The outermost div is abnormal.

![other](https://github.com/zzzprojects/html-agility-pack/assets/3311217/3a9c09bd-b141-4135-a722-c0a25d2ada44)

``` C#
            var html = @"
<div>
    <span>
        <font>
            <div>
                <span>
                    <div></div>
                </span>
            </div>
        </font>
    </span>
    <span></span>
</div>";
            var doc = new HtmlDocument();
            doc.LoadHtml(html);
            var newHtml = doc.DocumentNode.OuterHtml;
```

**newHtml value is:**
``` C#
<div>
    <span>
        <font>
            <div>
                <span></span>
                <div></div>
            </div>
        </font>
    </span>
</div>
<span></span>
```

`div` position is wrong!

**Comment by JonathanMagnan** [comment]
Hello,

Thank you for reporting. We are already aware of this issue here: https://github.com/zzzprojects/html-agility-pack/issues/531

It should be fixed really soon.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @colindcli , @Jagailo 

The code added in v1.11.57 has been reverted in v1.11.58, so this issue should no longer happen.

More information can be found in the issue [#529](https://github.com/zzzprojects/html-agility-pack/issues/529#issuecomment-1914001589) for you @colindcli 

Best Regards,

Jon
