### ISSUE TITLE
it happened again after a Rolled back to version HtmlAgilityPack 1.11.50, then again to HtmlAgilityPack 1.11.57 and it worked.

### ISSUE THREAD

**Issue by ovolkov** [zzzprojects/html-agility-pack#534]
Rolled back to version HtmlAgilityPack 1.11.50, then again to HtmlAgilityPack 1.11.57 and it worked.
Microsoft Visual Studio Community 2022

_Originally posted by @ovolkov in https://github.com/zzzprojects/html-agility-pack/issues/533#issuecomment-1913137152_

**Comment by JonathanMagnan** [comment]
Hello @ovolkov ,

We will close this issue as I'm not sure exactly if there is still an issue or not.

Look like, with your last comment everything is working correctly.

Best Regards,

Jon

**Comment by ovolkov** [comment]
Hi, see issue #535. Ver.1.11.50 worked fine, but next versions is broken

пн, 29 січ. 2024 р., 00:17 користувач Jonathan Magnan <
***@***.***> пише:
