### ISSUE TITLE
Can't find a node used HtmlAgilityPack 1.11.57

### ISSUE THREAD

**Issue by ovolkov** [zzzprojects/html-agility-pack#535]
## 1. Description
I found html file with a comment "Use 2 alternating methods of displaying tax due to confuse screen scrapers".
I need to pull out the 'Assessed Tax:' value from there.
I used two different versions of XPATH but they don't work:
//ul[@id='cphMainContent_cphRightColumn_taxDue2']/li[2]
//*[contains(text(),'Assessed Tax:')]/ancestor::li[1]/following-sibling::li[1]

`<div><span><section><span><section><div><div><div>
                        
                        

                        <ul id="cphMainContent_cphRightColumn_taxDue2" class="block-grid six-up mobile-four-up">
                            <li>
                                <label>
                                    <section><div><div><section><span><div>
                                    Assessed Tax:
                                </div></span></section></div></div></section>
                                </label>
                            </li>
                            <li>
                                <span><div><span><div><span><section><span>

                                $1,249.24

                                </span></section></span></div></span></div></span>
                            </li>
                            <li>
                                <div><section><span><div><div><span><div><section>
                                <label>Tax Paid:</label>
                                </section></div></span></div></div></span></section></div>
                            </li>
                            <li>
                                <span><span><span>
                                $0.00
                                </span></span></span>
                            </li>
                            <li>
                                <div><div><section><section><section><span><div><div><section>
                                <label>Total Due:</label>
                                </section></div></div></span></section></section></section></div></div>
                            </li>
                            <li>

                                <a href='TaxDue.aspx?TaxYear=2023' class='text-blue'
                                    title="Click for a Tax Stub printout" data-toggle="wait">
                                    $1,274.22
                                </a>

                            </li>
                        </ul>
                        </div></div></div></section></span></section></span></div>`
## 3. Fiddle or Project
[Tester.zip](https://github.com/zzzprojects/html-agility-pack/files/14072376/Tester.zip)
`using HtmlAgilityPack;

var filepath=Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "notfoundTpage.html");
var doc=new HtmlDocument();
doc.Load(filepath);
var node=doc.DocumentNode.SelectSingleNode("//ul[@id='cphMainContent_cphRightColumn_taxDue2']/li[2]");
if (node == null)
{
    Console.WriteLine("XPATH not found 1");
}

node = doc.DocumentNode.SelectSingleNode("//*[contains(text(),'Assessed Tax:')]/ancestor::li[1]/following-sibling::li[1]");
if (node == null)
{
    Console.WriteLine("XPATH not found 2");
}`

## 4. Any further technical details
.NET 7.0
HtmlAgilityPack 1.11.57

**Comment by JonathanMagnan** [comment]
Hello @ovolkov ,

The changes we made in the v1.11.57 has been reverted yesterday.

I just upgraded your project to the v1.11.58 and everything work fine again.

Let me know if that's fixed for you.

Best Regards,

Jon
