### ISSUE TITLE
The html rendering result is different from the html output result when we have two unclosed tbody tags

### ISSUE THREAD

**Issue by pauloortins** [zzzprojects/html-agility-pack#540]
When we have two unclosed tbody tags the output is different from the way chrome renders it.
While chrome closes the first tbody before the second opening tbody, HAP adds two closing tbody tags at the end.

```txt
HTML: <table><tbody><tr><td></td></tr><tbody><tr><td></td></tr></table>
HAP Result: <table><tbody><tr><td></td></tr><tbody><tr><td></td></tr></tbody></tbody></table>
Chrome Result: <table><tbody><tr><td></td></tr></tbody><tbody><tr><td></td></tr></tbody></table>
```

This is the test I used:

```
var html = @"<table><tbody><tr><td></td></tr><tbody><tr><td></td></tr></table>";
var doc = new HtmlDocument();
doc.LoadHtml(html);
var newHtml = doc.DocumentNode.OuterHtml;  //<table><tbody><tr><td></td></tr><tbody><tr><td></td></tr></tbody></tbody></table>
var res = @"<table><tbody><tr><td></td></tr></tbody><tbody><tr><td></td></tr></tbody></table>"; //chrome or edge rendering results
var b = newHtml == res; //false
```

**Comment by JonathanMagnan** [comment]
Hello @pauloortins ,

Thank you for reporting.

We will add a rule similar to what we did here for `<tbody>`: https://github.com/zzzprojects/html-agility-pack/commit/a7b18a357121919964481a773e56cafadbf624ea

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @pauloortins ,

[v1.11.60](https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.11.60) is now available. The `tbody` will now be closed when the parent tag is also a `tbody`, like in your case.

Best Regards,

Jon
