### ISSUE TITLE
bug: SelectSingleNode not returning anything

### ISSUE THREAD

**Issue by ghost** [zzzprojects/html-agility-pack#547]
Hi

.NET Framework 4.8
HtmlAgilityPack 1.11.60

I don't know if I found a bug, but something is not working in following code.
I want to get all the Radio Shows at the right of this website: https://www.trancepodcasts.com/

![afbeelding](https://github.com/zzzprojects/html-agility-pack/assets/166885027/b6000c68-d6aa-4d0a-91ba-ffe89b043cc3)

I use following code but nothing is printed at all. I used similar code on other websites and there it worked perfectly. What is going on here?
Using F12 in Mozilla Firefox, I found they should be in there

![afbeelding](https://github.com/zzzprojects/html-agility-pack/assets/166885027/4e64d69c-e54d-47d6-b304-76fc8506db39)

```
HtmlWeb web = new HtmlWeb();

HtmlAgilityPack.HtmlDocument document = web.Load("https://www.trancepodcasts.com/");

HtmlNode node = document.DocumentNode.SelectSingleNode("//ul[class='sub-menu mm-listview']");

if (node != null)
{
    // Select all a nodes within the ul
    HtmlNodeCollection links = node.SelectNodes(".//li");

    if (links != null)
    {
        foreach (HtmlNode link in links)
        {
            Console.WriteLine(link.OuterHtml);
        }
    }
}
```

I checked and "node" is null in the code example. Why is it null?

**Comment by JonathanMagnan** [comment]
Hello @trance-babe ,

A little bit like your other issue, what appears on the screen is not what has been loaded by HAP.

If you check the source, you don't find this HTML code: view-source:https://www.trancepodcasts.com/

The HTML code look more like this:

```html
<ul class="sub-menu">
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126821"><a href="https://www.trancepodcasts.com/a-dream-radio/">A Dream Radio</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-104457"><a href="https://www.trancepodcasts.com/a-state-of-trance/">A State Of Trance</a></li>
	<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-106361"><a href="https://www.trancepodcasts.com/a-world-into-trance/">A World Into Trance</a></li>
</ul>
```

Nothing works on this website due to having dynamic HTML or HTML modified after the page is loaded

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
HAP is more used to parse HTML than to work with dynamic HTML.

I believe you are asking for Selenium Web Browser: https://riptutorial.com/selenium-webdriver/learn/100000/overview

You can find how to setup in the tutorial we make years ago: https://riptutorial.com/selenium-webdriver/learn/100001/setup-selenium

Unfortunately, my time doesn't permit me to help you with it. However, using ChatGPT should get you started.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
I'm really sorry,

I would like to help you more, but as I already said, my time is very limited (I barely have time to myself at this moment). Using selenium is another tool to learn. In short, it opens a new browser, and you can interact with it.

The first thing you should learn in this case is ChatGPT (or other alternative), and even ask your parent to provide a paid subscription: https://chat.openai.com/

This becomes a day-to-day tool for anybody who can use and take advantage of it. It's pretty simple to use; this is a Chat box that provides information (it might be bad or good, but for any common subject, it's accurate enough).

Best Regards,

Jon
