### ISSUE TITLE
System.Net.Http 4.3.3 vulnerability

### ISSUE THREAD

**Issue by ThordaineRWS** [zzzprojects/html-agility-pack#550]
## 1. Description
System.Net.Http 4.3.3 has a vulnerability according to this Microsoft Security Advisory - 
https://github.com/dotnet/announcements/issues/88
 

- HAP version: 1.11.61
- NET version - Any .NET Core application that runs on a .NET Core 1.0.x runtime with a version number of 1.0.12 or lower, or a .NET Core application that runs on a .NET Core 1.1.x runtime with a version number of 1.1.9 or lower, or a .NET Core application that runs on a .NET Core 2.0.x runtime.

**Comment by elgonzo** [comment]
> *  NET version - Any .NET Core application that runs on a .NET Core 1.0.x runtime with a version number of 1.0.12 or lower, or a .NET Core application that runs on a .NET Core 1.1.x runtime with a version number of 1.1.9 or lower, or a .NET Core application that runs on a .NET Core 2.0.x runtime.


Read the advisory you referred to and act accordingly:

> System administrators are advised to update their .NET Core runtimes to versions 1.0.13, 1.1.10 and install the latest 2.1 runtime, ensuring that any 2.0 applications are migrated to 2.1 as soon as possible.
>
> Developers are advised to update their .NET Core SDK to versions 1.1.11 and migrate any [.NET Core](https://docs.microsoft.com/dotnet/core/migration/20-21) or [ASP.NET Core 2.0](https://docs.microsoft.com/aspnet/core/migration/20_21?view=aspnetcore-2.1) applications to 2.1 and redeploy.

**Comment by ThordaineRWS** [comment]
Just wondering if this part is relevant from that advisory?

Additionally package authors should check their dependencies to ensure they aren't depending on a vulnerable version of the following package:

Package name:
System.Net.Http
Vulnerable versions: 2.0.20126.16343, 2.0.20505, 2.0.20710, 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.3.0, 4.3.1, 4.3.2, 4.3.3 
Secure versions: 4.3.4 or later

Thanks

**Comment by JonathanMagnan** [comment]
Thank you again, @elgonzo, for answering.

We already took action starting from v1.11.55: https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.11.55

We now use the v4.3.4 as @elgonzo specified.

Best Regards,

Jon

**Comment by ThordaineRWS** [comment]
Thank you @elgonzo and @JonathanMagnan for clarifying.

Best Regards,
@ThordaineRWS
