### ISSUE TITLE
Incorrect output parsing minified table with a footer

### ISSUE THREAD

**Issue by dylanstreb** [zzzprojects/html-agility-pack#562]
## 1. Description
Incorrect output when parsing minified HTML data including a table with a footer.

The minified output is generated by WebMarkupMin. Chrome is able to display the minified output correctly, so I believe the output from that library is correct. The minified HTML removes end tags, and I believe HAP is not re-adding them in the correct location.

## 2. Fiddle or Project
Fiddle: https://dotnetfiddle.net/c3wmTU

The relevant part of the minified input is `<td>Text<tfoot>`

I believe this is relying on the fact that tfoot can only be a child of table to skip the closing tags for td, tr, and tbody. This is what Chrome does - it places the tfoot after the tbody element.

HAP's output is to put the tfoot as a child of td - `<td>Text<tfoot><tr><td colspan="3">Footer</td></tr></tfoot></td>`

## 3. Any further technical details
Add any relevant detail can help us, such as: 

- HAP version: 1.11.62
- NET version: .NET 6.0.32
- WebMarkupMin.Core: 2.17.0

**Comment by JonathanMagnan** [comment]
Hello @dylanstreb ,

Thank you for reporting. Indeed, I don't think HAP currently supports `foot` correctly. I don't remember having added any code related to it when we fixed recently some issue on the `thead` and `tbody`.

We will look at it.

Best Regards,

Jon

**Comment by dylanstreb** [comment]
@JonathanMagnan Your mention of a recent fix gave me enough of a head start to try it. The PR I just submitted fixes my sample code.

**Comment by JonathanMagnan** [comment]
Hello @dylanstreb ,

The [v1.11.63](https://github.com/zzzprojects/html-agility-pack/releases/tag/v1.11.63) has been released.

Thank again for your contribution and helping us to improve this library :)

Best Regards,

Jon
