### ISSUE TITLE
An attribute read without quotes is written without quotes even after the value has been set

### ISSUE THREAD

**Issue by POFerro** [zzzprojects/html-agility-pack#565]
Hi @JonathanMagnan ,

I stumbled upon a situation where an attribute that is read without quotes is written without quotes even after gaining a value.
This is when the GlobalDefaultQuote type is set to initial on the document, the attribute gets this value on Value set and then writes no quotes when serializing.

I created PR #564 to correct this issue, could you please have a look?

Thanks and best regards

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

Sure, I will take a look this weekend :)

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @POFerro ,

Thank you again for your contribution. Indeed, that was a good catch for this special case.

Your PR has been merged and released in the v1.11.64

Best Regards,

Jon
