### ISSUE TITLE
Condition for HtmlParseErrorCode.CharsetMismatch 

### ISSUE THREAD

**Issue by aktzbn** [zzzprojects/html-agility-pack#60]
There is a special error HtmlParseErrorCode.CharsetMismatch  during parsing of document. Now its condition is: 

`if (_declaredencoding.WindowsCodePage != _streamencoding.WindowsCodePage).`

Some encoding like Latin1 and ASCII have the same 1252 windows code page. But their are different and produce different results when parsing document. Propose to use CodePage property of encoding instead of WindowsCodePage.

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

Thank you for reporting,

We will try to look at this issue soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

A new version has been released v1.5.2-beta4,

We made the change as you recommended.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

We will close this issue, feel free to re-open if you still have it.

Best Regards,

Jonathan
