### ISSUE TITLE
Does HtmlAgilityPack work on Xamarin.Forms?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [zzzprojects/html-agility-pack#64]
Does HtmlAgilityPack work on Xamarin.Forms?

**Comment by JonathanMagnan** [comment]
Hello @nguyenthanhliemfc ,

I believe it works but partially. Not all features will be here.

The best is to try it on your side.

Best Regards,

Jonathan

**Comment by nguyenthanhliemfc** [comment]
1. I Intall it on PCL project or all Project?
2. Can you suggest me some sample code!

**Comment by nguyenthanhliemfc** [comment]
Thank you!

**Comment by SubramanymRajuB** [comment]
Please find it from www.bsubramanyamraju.blogspot.com/2019/03/htmlagilitypack-html-parsing-in.html

**Comment by nguyenthanhliemfc** [comment]
Thank you, SubramanymBajuB!
