### ISSUE TITLE
How to press a submit button on Web?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [zzzprojects/html-agility-pack#65]
How to press a submit button on Web using HtmlAgilityPack?

**Comment by JonathanMagnan** [comment]
Hello @nguyenthanhliemfc ,

HtmlAgilityPack is not a web browser but an HTML parser.

It still possible to achieve such feature by example using LoadFromBrowser method and waiting some time...

```csharp
bool isClicked = false;
string url = "http://html-agility-pack/from-browser";

var web1 = new HtmlWeb();
var doc1 = web1.LoadFromBrowser(url, o =>
{
	var webBrowser = (WebBrowser) o;

        if(!isClicked)
        {
              // You have access to the webBrowser, so you can click on element from it.
        }

	// WAIT until the dynamic text is set
	return !string.IsNullOrEmpty(webBrowser.Document.GetElementById("uiDynamicText").InnerText);
});
var t1 = doc1.DocumentNode.SelectSingleNode("//div[@id='uiDynamicText']").InnerText
```

It's possible to do such thing but I'm not sure if this is the right library for it or not depending on your requirement.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @nguyenthanhliemfc ,

I will close this issue since it seems there is no more question about it.

Best Regards,

Jonathan
