### ISSUE TITLE
cant install html-agility-pack when install Newtonsoft.Json

### ISSUE THREAD

**Issue by Mehrdad1991h** [zzzprojects/html-agility-pack#67]
dear
I want to know why i can't install your pakage with Newtonsoft.Json and get this error :
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred while retrieving package metadata for 'Newtonsoft.Json.10.0.3' from source 'C:\Users\......\packages'.			0	
```

I try to use from both of them in .net 4
And i try to install them from nuget package

anyway for install i can use from `ignore dependence` option  in `package manager > install and update option > dependence behavior` but sometimes when app is running and i got error...

can you give me solution ?

![2017-08-20_20h42_24](https://user-images.githubusercontent.com/14166038/29496457-5f9edac0-85e8-11e7-92ae-0552fab47e8b.png)

**Comment by JonathanMagnan** [comment]
Hello @Mehrdad1991h ,

HAP doesn't use Newtonsoft.Json, there is no dependency to this library.

Often, this kind of issue is solved by downloading the latest NuGet Package Manager: https://stackoverflow.com/a/25844391/5619143

Let me know if you successfully fixed it by using the latest version.

Best Regards,

Jonathan

**Comment by Mehrdad1991h** [comment]
successfully fixed !
