### ISSUE TITLE
Can you change the internal  HtmlDocument.Text to public?

### ISSUE THREAD

**Issue by williamreg** [zzzprojects/html-agility-pack#69]
Can you change the HtmlDocument.Text(internal string Text) to public(public string Text)?

**Comment by JonathanMagnan** [comment]
Hello @williamreg ,

Could you point me the method in the source code? HtmlDocument does not have a `Text` method.

Best Regards,

Jonathan

**Comment by williamreg** [comment]
https://github.com/zzzprojects/html-agility-pack/blob/5950151b700f48d830c1b734ed926ce6838bf4b6/src/HtmlAgilityPack/HtmlDocument.cs#L50

`internal string Text;`

**Comment by JonathanMagnan** [comment]
Hello @williamreg ,

Is there a reason you want to set the `Text`? By doing it, most functionality will not longer work since you will set a text that has not been parsed yet by the library.

It's only to get the `Text` or to set it also?

Best Regards,

Jonathan

**Comment by williamreg** [comment]
@JonathanMagnan 

Thanks!

when:
```
HtmlWeb hw = new HtmlWeb();
var html = hw.Load(url);
```

When debug, the internal html.Text is:
```
{"html":"<table cellpadding='0' cellspacing='0' width='100%'><tr><td colspan='2' rowspan='2' >Hello World!<\/td><\/table><script>gScrollContext = 1;<\/script>"}
```

I can get the html.DocumentNode.OuterHtml:
```
{"html":"<table cellpadding='0' cellspacing='0' width='100%'><tr><td colspan='2' rowspan='2' class='image_map'>Hello World!<script></script></td></tr></table>
```
But I can't get the internal html.Text,

I am sorry that i only know a little English!
I hope you can understand what I said.

**Comment by williamreg** [comment]
I want to get the source code instead of setting the `Text`(the source code)。

**Comment by JonathanMagnan** [comment]
Hello @williamreg ,

Thank you for the explanation. We will add a method this week to provide you a way to get the value of the `Text` field.

Best Regards,

Jonathan

**Comment by williamreg** [comment]
Hello @JonathanMagnan ,

Thank you very much!

Best Regards,

William

**Comment by JonathanMagnan** [comment]
Hello @williamreg ,

The v1.5.6-beta1 has been released.

A new property has been added `HtmlDocument.ParsedText` which returns the `Text` value.

Best Regards,

Jonathan
