### ISSUE TITLE
Homepage example code uses variable name as string literal

### ISSUE THREAD

**Issue by ThunderFrame** [zzzprojects/html-agility-pack#7]
The first example on http://html-agility-pack.net/ has an error on the last line:

```
// From File
var htmlDoc = new HtmlDocument();
html.Load(filePath);

// From String
var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(html);

// From Web
string url = "http://html-agility-pack.net/";
HtmlWeb web = new HtmlWeb();
HtmlDocument document = web.Load("url");  // <-- Should be web.Load(url);
```

The `web.Load` method should take the value of `url` not the string-literal `"url"`

**Comment by JonathanMagnan** [comment]
Hello @ThunderFrame ,

Thank you for reporting.

Both examples in the home page has been fixed.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: Example on home page fixed
