### ISSUE TITLE
I found that removing elements was wrong in the  HtmlNodeCollection

### ISSUE THREAD

**Issue by Wscar** [zzzprojects/html-agility-pack#70]
HtmlNodeCollection.RemoveAt();
Unable to remove elements ;
error:System.NullReferenceException.
And the collection is not empty ,
Final:
`  HtmlNodeCollection liNodes= node.SelectNodes("//ul/li");
                              List<HtmlNode> nodes= liNodes.ToList();`
version="1.5.1"

**Comment by JonathanMagnan** [comment]
Hello @Wscar ,

Thank you for reporting it.

We successfully reproduced and fixed this issue.

A new version will be available later today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Wscar ,

The v1.5.2 has been released.

The RemoveAt should not longer throw a NullReferenceException.

Please reopen this issue if the bug is not fully fixed.

Best Regards,

Jonathan
