### ISSUE TITLE
Can't compile on ARM

### ISSUE THREAD

**Issue by lpaso** [zzzprojects/html-agility-pack#72]
Hi,

I'm trying to develop a Universal App for Windows using HtmlAgilityPack and I can't compile the project on ARM.
When I'm trying to compile on ARM, I got an error stating that the HtmlAgilityPack.dll in the uap10.0 folder is only for x86 processor.Is that normal ?Is there a chance HTMLAgilityPack to become available for ARM processor ?

Thanks.

**Comment by JonathanMagnan** [comment]
Hello @lpaso ,

The v1.5.4 has been released. I have modified the build for any CPU for the UWP project.

Let me know if that fixes this issue.

Best Regards,

Jonathan

**Comment by lpaso** [comment]
Wow, fast !

PS : Jonathan Magnan… That sound pretty French (or Canadian maybe ?)
If that’s the case… Merci ! 😉

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jonathan Magnan<mailto:notifications@github.com>
Envoyé le :jeudi 7 septembre 2017 19:45
À : zzzprojects/html-agility-pack<mailto:html-agility-pack@noreply.github.com>
Cc : lpaso<mailto:lpaso@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [zzzprojects/html-agility-pack] Can't compile on ARM (#72)


Hello @lpaso<https://github.com/lpaso> ,

The v1.5.4 has been released. I have modified the build for any CPU for the UWP project.

Let me know if that fixes this issue.

Best Regards,

Jonathan

**Comment by lpaso** [comment]
Hi again,

Seems the issue still there (sorry, capture is from French VS) :

[cid:image001.png@01D32812.76358E20]

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jonathan Magnan<mailto:notifications@github.com>
Envoyé le :jeudi 7 septembre 2017 19:45
À : zzzprojects/html-agility-pack<mailto:html-agility-pack@noreply.github.com>
Cc : lpaso<mailto:lpaso@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [zzzprojects/html-agility-pack] Can't compile on ARM (#72)


Hello @lpaso<https://github.com/lpaso> ,

The v1.5.4 has been released. I have modified the build for any CPU for the UWP project.

Let me know if that fixes this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Bonjour,

Effectivement, je suis de Québec ;)

The image has not been attached correctly. If you want, you can also contact me directly here: info@zzzprojects.com

Cordialement,

Jonathan

**Comment by lpaso** [comment]
Super ! On va pouvoir continuer en Français alors, ce sera plus simple (surtout pour moi 😉).

Voilà le message d’erreur :

[cid:image002.png@01D32814.9B10E8F0]

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jonathan Magnan<mailto:notifications@github.com>
Envoyé le :jeudi 7 septembre 2017 20:01
À : zzzprojects/html-agility-pack<mailto:html-agility-pack@noreply.github.com>
Cc : lpaso<mailto:lpaso@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [zzzprojects/html-agility-pack] Can't compile on ARM (#72)


Bonjour,

Effectivement, je suis de Québec ;)

The image has not been attached correctly. If you want, you can also contact me directly here: info@zzzprojects.com<mailto:info@zzzprojects.com>

Cordialement,

Jonathan

**Comment by jmcruvellier** [comment]
Bonjour,

même problème pour moi, impossible de compiler en ARM après une upgrade de la version 1.5.1 en 1.5.4. J'ai également essayé avec les versions 1.5.2 et 1.5.3 mais avec le même résultat. En fait le problème vient de l'ajout de la dépendance UAP (version 10.0).

Le message d'erreur est : 
L'architecture de processeur du projet "ARM" en cours de génération ne correspond pas à celle de la référence "C:\Users\xxx\.nuget\packages\HtmlAgilityPack\1.5.4\lib\uap10.0\HtmlAgilityPack.dll", "x86". Cela peut entraîner des échecs au moment de l'exécution. Essayez de modifier l'architecture de processeur ciblée de votre projet à l'aide du Gestionnaire de configuration de façon à utiliser les mêmes architectures de processeur entre votre projet et les références, ou choisissez une dépendance sur les références dont l'architecture de processeur correspond à l'architecture de processeur ciblée de votre projet.

Jean-Marc

**Comment by JonathanMagnan** [comment]
Bonjour,

Pouvez-vous essayer avec la version 1.5.5, elle devrait maintenant fonctionner? Je crois que ce n’étais qu’un problème de configuration de mon côté. Il continuer de faire un build sur “x86” même si “ANY CPU” était spécifier.

Cordialement,

Jonathan

**Comment by lpaso** [comment]
Dès qu’elle est dispo sur mon NuGet, je fais l’update et vous tiens au courant 😉

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jonathan Magnan<mailto:notifications@github.com>
Envoyé le :vendredi 8 septembre 2017 16:52
À : zzzprojects/html-agility-pack<mailto:html-agility-pack@noreply.github.com>
Cc : lpaso<mailto:lpaso@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [zzzprojects/html-agility-pack] Can't compile on ARM (#72)


Bonjour,

Pouvez-vous essayer avec la version 1.5.5, elle devrait maintenant fonctionner? Je crois que ce n’étais qu’un problème de configuration de mon côté. Il continuer de faire un build sur “x86” même si “ANY CPU” était spécifier.

Cordialement,

Jonathan

**Comment by lpaso** [comment]
C’est tout good pour moi ! Merci pour la réactivité ! 😊

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jonathan Magnan<mailto:notifications@github.com>
Envoyé le :vendredi 8 septembre 2017 16:52
À : zzzprojects/html-agility-pack<mailto:html-agility-pack@noreply.github.com>
Cc : lpaso<mailto:lpaso@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [zzzprojects/html-agility-pack] Can't compile on ARM (#72)


Bonjour,

Pouvez-vous essayer avec la version 1.5.5, elle devrait maintenant fonctionner? Je crois que ce n’étais qu’un problème de configuration de mon côté. Il continuer de faire un build sur “x86” même si “ANY CPU” était spécifier.

Cordialement,

Jonathan

**Comment by JonathanMagnan** [comment]
Merci de votre aide aussi ;)

Cordialement,

Jonathan

**Comment by wkfry** [comment]
I'm using the new 1.9.0 release, and I'm running into the same issue. I thought perhaps there was a regression, so I went back to 1.5.5 and some builds in between, but I'm still seeing the Mixed Processor error when compiling using UAP. 

Is there something else that I'm missing?

**Comment by JonathanMagnan** [comment]
Hello @wkfry ,

I recommend you to follow this thread: https://github.com/zzzprojects/html-agility-pack/issues/283

We are supported to look at it tomorrow.

Best Regards,

Jonathan

**Comment by wkfry** [comment]
Perfect, thanks! 1.9.1 totally fixed the issue. I really appreciate the fix!

**Comment by JonathanMagnan** [comment]
Great ;)
