### ISSUE TITLE
Load "invalid" html cause to create empty node

### ISSUE THREAD

**Issue by Waynezhi** [zzzprojects/html-agility-pack#73]
Tried to parse an html not well-formed like this:
`<div class=""> <strong>blablabla (< 5cm)</strong> </div>`
After calling LoadHtml, document turned into:
`<div class=""> <strong>blablabla (<></strong> </div>`
when i select the //strong/*, i get a empty node with `< 5cm)` inside
however, Chrome shows correctly this html with "less then" character.

I use another parser AngleSharp, which encodes the < to `&lt;` and i think HtmlAgilityPack is supposed to do so.

i use v1.4.9

**Comment by JonathanMagnan** [comment]
Hello @Waynezhi ,

Thank you for reporting.

Yes, since the first character of the `tag` start with a non alpha character, it should not be considered as a tag.

We will investigate this issue.

Best Regards,

Jonathan

**Comment by Waynezhi** [comment]
thanks @JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @Waynezhi ,

The v1.5.6-beta2 has been released

This issue should no longer cause you a problem.

Best Regards,

Jonathan

**Comment by Waynezhi** [comment]
Great, thanks
