### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by aktzbn** [zzzprojects/html-agility-pack#78]
Hi,

I have StackOverflowException when loading https://eprint.iacr.org/complete/ .

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

Thank you for reporting.

I can successfully reproduce it, I will try to check it today or during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

We can now successfully read the URL provided.

We are currently looking to improve this fix and make it more generic as there is several similar issues that will be probably reported until we redo the parser.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aktzbn  ,

The v1.6.0-beta1 has been released,

Please reopen this issue if you still have the problem.

Best Regards,

Jonathan
