### ISSUE TITLE
&apos; html entity is not supported by HtmlEntity.DeEntitize

### ISSUE THREAD

**Issue by badyam** [zzzprojects/html-agility-pack#79]
I expect from 
`HtmlEntity.DeEntitize("mouse&apos;s house")`
to return "mouse's house", but it returns input as is.

I realize that "&amp;apos;" is not valid HTML entity in HTML4 specs, but it's valid in XHTML1.0 and HTML5.
So I believe it should be supported.

**Comment by JonathanMagnan** [comment]
Hello @badyam ,

Thank you for reporting.

We currently successfully reproduced the issue and found how to fix it.

We will look this weekend if some other characters are also missing.

A fix should be available on Monday.

Best Regards,

Jonathan

**Comment by aktzbn** [comment]
Hi,

>>  if some other characters are also missing

I would say that most of characters from list https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references are missing. :)

In my code that use HAP I'm deentitizing by myself.

Best Regards,

Boris

**Comment by JonathanMagnan** [comment]
Wow, that's a lot of named characters!

Thank you for the link, that will for sure help us

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

The issue has been fixed, I have looked at all common character and I only found this one missing.

I will for sure keep this list in mind when we will re-write this functionality.

The fix should be available before Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @badyam , @aktzbn ,

The v1.6.0-beta1 has been released,

Please reopen this issue if you still have the problem.

Best Regards,

Jonathan

**Comment by aktzbn** [comment]
May be it is useful to create separate issue for full list of entities?

**Comment by JonathanMagnan** [comment]
Hello @aktzbn ,

I don't think that's necessary.

All common one I believe is added. The complete list will be added with the creation of HAP v2.x

Better keep the number of issues low, it makes easier to track and review them.

Best Regards,

Jonathan
