### ISSUE TITLE
Inner HTML does not return anything

### ISSUE THREAD

**Issue by sebastianolafhandjojo** [zzzprojects/html-agility-pack#8]
HTMLAgility Pack 1.5.0-beta2

if tag format like this 
the InnerHTML doesn't return anything

Example link : http://www.mangahere.co/manga/tower_of_god/c331/
content: 

<option value="http://www.mangahere.co/manga/tower_of_god/c331/" selected="selected">1</option>
<option value="http://www.mangahere.co/manga/tower_of_god/c331/2.html" >2</option>
<option value="http://www.mangahere.co/manga/tower_of_god/c331/3.html" >3</option>
<option value="http://www.mangahere.co/manga/tower_of_god/c331/4.html" >4</option>

**Comment by JonathanMagnan** [comment]
Hello @sebastianolafhandjojo ,

I believe there is something missed in your question.

> if tag format like this

I believe this part is incomplete or I don't understand it.

I currently don't have enough information to reproduce it:

```csharp
string url = @"http://www.mangahere.co/manga/tower_of_god/c331/";

HtmlWeb web = new HtmlWeb();
HtmlAgilityPack.HtmlDocument doc = web.Load(url);

var inner = doc.DocumentNode.InnerHtml;
```

Best Regards,

Jonathan

**Comment by sebastianolafhandjojo** [comment]
Hi Sorry, i wrote that at 1AM
so a bit half a sleep

 string url = @"http://www.mangahere.co/manga/tower_of_god/c331/";
var _web = new HtmlWeb();

HtmlDocument document = _web.Load(url);
var options = document.DocumentNode.Descendants("option");

foreach (var option in options)
{
string someinnertext = option.InnerText.Trim();
Console.WriteLine("Inner Text = {0}", someinnertext);
}

![image](https://cloud.githubusercontent.com/assets/10486790/26525592/4b4260c0-438e-11e7-9c41-3cb76af2f86b.png)

**Comment by sebastianolafhandjojo** [comment]
i have test this many times,
it seems something wrong with word "option" it does not populate any value for InnerText or InnerHtml
but if try with any random text as Html Tag, it populate value 

below is example i use to test 

HtmlDocument document = new HtmlDocument();
                string text = "olaf";
// notice i put a space between double quote and closing tag " > 
// plus somehow in the result , it trims down see screenshot 
                document.LoadHtml("<"+text +" value=\"http://www.mangahere.co/manga/tower_of_god/c331/5.html\" >5</"+text+">");

                var options = document.DocumentNode.Descendants(text).ToList();

                int i = 0;
                foreach (var option in options)
                {
                    string someinnertext = option.InnerText.Trim();
                    string someinnerhtml = option.InnerHtml.Trim();
                    string someouterhtml = option.OuterHtml.Trim();
                    Console.WriteLine("{0}) {1} = {2} --> {3}",i++, someinnertext, someinnerhtml, someouterhtml);
                }



using Random word as Tag 

![image](https://cloud.githubusercontent.com/assets/10486790/26525973/45ad7ed0-439b-11e7-93bd-d83f1943ce31.png)

using word option as tag

![image](https://cloud.githubusercontent.com/assets/10486790/26525980/69690a74-439b-11e7-93e6-62dd2438aab0.png)

**Comment by sebastianolafhandjojo** [comment]
Above i test with beta2, and I saw that you have release beta5
but with beta5 still has same problem

**Comment by sebastianolafhandjojo** [comment]
Ok, so I saw in your source code for "option" somehow got "special" treatment,
so am thinking to replace word "option" with other random text, using ReplaceChild method,
But I don't understand how to use HtmlNode use? and what index means ?

Do you have any example for this method ?

Thank you !

![image](https://cloud.githubusercontent.com/assets/10486790/26526152/94f755fe-43a2-11e7-94a7-eaaff2e40cf7.png)

**Comment by JonathanMagnan** [comment]
Hello @sebastianolafhandjojo ,

It looks option tag have some weird behavior.

You can find two solutions here:
https://stackoverflow.com/questions/13977243/how-can-i-parse-innertext-of-option-tag-with-htmlagilitypack

```csharp
// REMOVE option from "special tag"
HtmlAgilityPack.HtmlNode.ElementsFlags.Remove("option");

string url = @"http://www.mangahere.co/manga/tower_of_god/c331/";
HtmlWeb web = new HtmlWeb();
HtmlAgilityPack.HtmlDocument doc = web.Load(url);

var options = doc.DocumentNode.Descendants("option");

foreach (var option in options)
{
    string someinnertext = option.InnerText.Trim();
}
```

**Comment by JonathanMagnan** [comment]
As you noticed.

Some tag has some custom behavior. When we will re-write the 2.0 version of this library, we will make sure to check them and fix some issue like this one.

Let me know if the solution above worked correctly.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
You can find an example here about ReplaceChild: http://html-agility-pack.net/replace-child

**Comment by sebastianolafhandjojo** [comment]
ok I will try first and let you know

**Comment by sebastianolafhandjojo** [comment]
both working, Thank You!

**Comment by JonathanMagnan** [comment]
Closing comment: Issue solved confirmed
