### ISSUE TITLE
HtmlNode.innerText contains HTML comments from original markup

### ISSUE THREAD

**Issue by badyam** [zzzprojects/html-agility-pack#80]
HtmlNode.innerText returns value containing comments markup from original html.

Example:
```
var document = new HtmlDocument();
document.LoadHtml("<p><!-- comment 1 -->Expected <!-- comment 2 -->value</p>");
Console.WriteLine(document.DocumentNode.FirstChild.InnerText);
```
Prints out `<!-- comment 1 -->Expected <!-- comment 2 -->value`

I expect to see `Expected value`.

I believe InnerText should not contain HTML comments.

Chrome, FireFox and Edge at least do not include comments into node.innerText. 
The same scenario in that browsers 
```
<html>
<body><p><!-- comment 1 -->Expected <!-- comment 2 -->value</p></body>
<script>
	console.log(document.childNodes[0].innerText);
</script>
</html>
```
gives "Expected value".

**Comment by JonathanMagnan** [comment]
Hello @badyam ,

Thank you for reporting.

We will look at this issue this weekend how "comment" tag is used in `HAP`

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @badyam ,

The issue has been fixed.

I'm still not yet sure why in the code, they added a line to display it:

```csharp
if (_nodetype == HtmlNodeType.Comment)
	return ((HtmlCommentNode)this).Comment;
```

The fix should be available before next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @badyam ,

The v1.6.0-beta1 has been released,

Please reopen this issue if you still have the problem.

Best Regards,

Jonathan
