### ISSUE TITLE
DOCTYPE Not Working With OptionOutputAsXml

### ISSUE THREAD

**Issue by mbrierst** [zzzprojects/html-agility-pack#82]
DOCTYPEs are required for XHTML files.  But I can't get DOCTYPE to work with OptionOutputAsXml.  For myself, I have a workaround for this by saving to a string and editing it before saving to a file.
Here's a demo of the problem in C#:
```C#
var htmlDoc = new HtmlDocument { OptionOutputAsXml = true /* false for a normal file */ };
htmlDoc.LoadHtml("<p>test document</p>");
var hcn = htmlDoc.CreateComment("<!DOCTYPE html>");
htmlDoc.DocumentNode.PrependChild(hcn);
var sb = new StringBuilder();
var sw = new StringWriter(sb);
htmlDoc.Save(sw);
MessageBox.Show(sb.ToString());
```

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

Thank you for reporting, I will investigate this issue today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

The problem happen in the method `GetXmlComment(HtmlCommentNode comment)` which normally expect comment starting with `<!--` and not `<!DOCTYPE`

I could fix it but I'm not sure that will give you the desired result.

Could you provide me the expected result on your side, just to make sure?

Best Regards,

Jonathan

**Comment by mbrierst** [comment]
For this example:
```C#
var htmlDoc = new HtmlDocument { OptionOutputAsXml = true /* false for a normal file */ };
htmlDoc.LoadHtml("<p>test document</p>");
var hcn = htmlDoc.CreateComment(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.1//EN"" ""http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"">");
htmlDoc.DocumentNode.PrependChild(hcn);
var sb = new StringBuilder();
var sw = new StringWriter(sb);
htmlDoc.Save(sw);
MessageBox.Show(sb.ToString());
```
The expected output should be:
```
<?xml version="1.0" encoding="iso-8859-1"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><p>test document</p>
```

**Comment by JonathanMagnan** [comment]
Thank you, 

I will continue to check this one,

The problem is possible side impact of this fix. The library seem to currently put everything in a `span` (if more than one child)

```csharp
var htmlDoc = new HtmlAgilityPack.HtmlDocument { OptionOutputAsXml = true /* false for a normal file */ };
htmlDoc.LoadHtml("<p>test document</p><p>test document</p>");
//var hcn = htmlDoc.CreateComment(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.1//EN"" ""http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"">");
//htmlDoc.DocumentNode.PrependChild(hcn);
var sb = new StringBuilder();
var sw = new StringWriter(sb);
htmlDoc.Save(sw);
var s = sb.ToString();
```

which return `<?xml version=\"1.0\" encoding=\"iso-8859-1\"?><span><p>test document</p><p>test document</p></span>`

I must understand first why the `span` is added since the `<!DOCTYPE` must be outside otherwise, it's an invalid XML

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

For the same reason as explained in the issue #83, this case has been fixed but you will need to set the option `BackwardCompatibility = false`

This change should be released before next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

The v1.6.1 has been released.

Please reopen this issue if more change is required.

Best Regards,

Jonathan

**Comment by mbrierst** [comment]
This seems to be working for me.  Thanks!

**Comment by Tags-han** [comment]
I invested time searching for a solution and finally found the answer



https://screen-readers69.github.io/nikolai4/
