### ISSUE TITLE
Invalid boolean (empty) attribute followed by end-tag parsing

### ISSUE THREAD

**Issue by RomanGolovanov** [zzzprojects/html-agility-pack#87]
Hello!
I've noticed a strange behavior when reading HTML with boolean attributes at the tag ends. If source HTML contains code like this:
`<input type="button" value="TestButton" disabled/>`
it will be deserialized as 
`<input type="button" value="TestButton" disabled/="" />`
so Html DOM will contain Attribute node with name **disabled/**, which is not true.

**Comment by JonathanMagnan** [comment]
Hello @RomanGolovanov ,

Looking at some browser inspector, this is the default behavior.

A value must be specified for the attribute `disabled`.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @RomanGolovanov ,

I will close this issue, feel free to reopen if you have more question about it.

Best Regards,

Jonathan
