### ISSUE TITLE
Text exported by AIT WordToTFS from TFS to Word is cut

### ISSUE THREAD

**Issue by tfs-dev** [zzzprojects/html-agility-pack#90]
I'm using [AIT WordToTFS ](https://marketplace.visualstudio.com/items?itemName=vs-publisher-99152.AITWordToTFS#overview) that internally uses html-agility-pack.
I experienced following bug. Sometimes the text exported from [TFS](https://www.visualstudio.com/tfs/) to Word is cut of last text line. I tried to investigate this bug e it seems caused by span or p tags inside html, it seems that html-agility-pack is not able to properly handle span or p tags.

Follows an example: 
1) This is an example of html value that WordToTFS exports cut in last text line
2) This is an example of html value that WordToTFS properly exports

1) If I have following html (captured with FireBug directly from TFS web interface)

```text
<body contenteditable="true"><p class="MsoNormalCxSpFirst">IN QUALITÁ di utente </p>
<p class="MsoNormalCxSpMiddle">DEVO POTER premere un pulsante sull'interfaccia
</p>
<p class="MsoNormalCxSpMiddle">AL FINE DI stampare il modulo da interfaccia web.</p></body>
```

WordToTFS exports only following text:

```text
IN QUALITÁ di utente
DEVO POTER premere un pulsante sull'interfaccia
AL FINE DI stampare il modulo d  <---- TEXT CUT!!!
```

2) If I have following html inside System.Description

```text
<body contenteditable="true"><span><p>IN QUALITÁ di utente</p>
<p>DEVO POTER premere un pulsante sull'interfaccia</p>
<p>AL FINE DI stampare il modulo da interfaccia web.</p></span></body>
```

WordToTFS properly exports the entire text 

```text
IN QUALITÁ di utente
DEVO POTER premere un pulsante sull'interfaccia
AL FINE DI stampare il modulo da interfaccia web.
```

Do you already know this bug? Maybe I found this workaround: if I add 150 nbsp at the end of any HTML field, I didn't get cut text in word export.  Anyway do you have any suggestion or workaround to avoid unproperly text cut?

**Comment by JonathanMagnan** [comment]
Hello @tfs-dev ,

If you try it directly from HAP, everything work fine.

I don't believe this issue is beyond HAP as the library doesn't cut the text in the middle of a string.

I don't think there is anything on my side I can do since it look to be a problem from `AIT WordToTFS`.

So unless you provide me something I can fix inside HAP, I believe we should close this issue and open one for `AIT WordToTFS` as the issue look to be on their side.

Best Regards,

Jonathan
