### ISSUE TITLE
Optimize usage of ToLower()

### ISSUE THREAD

**Issue by braaaanob** [zzzprojects/html-agility-pack#93]
Hi,
while profiling your parser, I found out that calling string.ToLower() is actually consuming lot of resources and in many cases it's not necessary. 2 simple optimizations which could be done:

1. HtmlAttributeCollection
initialize Hashitems like this:
`
internal Dictionary<string, HtmlAttribute> Hashitems = new Dictionary<string, HtmlAttribute>(StringComparer.OrdinalIgnoreCase);
`
and remove all ToLower() when reading/writing to Hashitems

2. HtmlNode
initialize ElementsFlags like this:
`
ElementsFlags = new Dictionary<string, HtmlElementFlag>(StringComparer.OrdinalIgnoreCase);
`

and again remove all ToLower() when reading/writing to dictionary

I'm sure there are more places like this, but these are called most often when parsing html document.

Thank you

**Comment by JonathanMagnan** [comment]
Hello @burjaniv ,

Thank you for reporting, I will certainly look at it during the weekend.

I will also try to make some benchmark since I'm curious about what kind of performance difference we will get.

Best Regards,

Jonathan

**Comment by burjaniv** [comment]
Thank you. Actually, maybe StringComparer.OrdinalIgnoreCase will be even faster than StringComparer.InvariantCultureIgnoreCase.

**Comment by JonathanMagnan** [comment]
Without a surprise and intensive testing, your solution is faster than using `ToLower()`

In addition to your two suggestion, I have also modified the `Nodesid` dictionary.

I will review the change and try to put it in production for next Monday.

Best Regards,

Jonathan

**Comment by burjaniv** [comment]
Perfect! Thanks a lot.

**Comment by JonathanMagnan** [comment]
Hello @burjaniv ,

The v1.6.2 has been released.

We made some optimization on dictionary as requested.

Let me know if everything works fine.

Best Regards,

Jonathan

**Comment by braaaanob** [comment]
Hello, yes everything works fine. Thank you

Branislav
