### ISSUE TITLE
HtmlWeb Class Missing When HAP is upgraded.

### ISSUE THREAD

**Issue by dbolak** [zzzprojects/html-agility-pack#94]
Xamarin.Forms application with PCL and UWP, iOS and Droid implementations. PCL is configured as TargetFrameworkVersion = v4.5 and TargetFrameworkProfile = Profile111. Have no problems running HAP with version 1.5.1 but when I upgrade to 1.6.1, the HtmlWeb class is not available anymore and is not shown in the Object Browser either. Recommendation ?

**Comment by JonathanMagnan** [comment]
Hello @dbolak ,

Do you think you could tell us to which package directory inside `HtmlAgilityPack` package the version for v1.5.1 and v1.6.1 are pointing?

Perhaps there is a small difference here and that will help us to understand what's happening.

Best Regards,

Jonathan

**Comment by dbolak** [comment]
Currently I have 1.5.1 installed and the reference inside the PCL project points out to:

C:\Users\HDBolak\Source\Repos\OOVxfAtInvstr\packages\HtmlAgilityPack.1.5.1\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid+MonoTouch\HtmlAgilityPack.dll

I will upgrade to 1.6.1 and report.

**Comment by dbolak** [comment]
With 1.6.2 (sorry about the typo earlier):

C:\Users\HDBolak\Source\Repos\OOVxfAtInvstr\packages\HtmlAgilityPack.1.6.2\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid+MonoTouch\HtmlAgilityPack.dll

**Comment by dbolak** [comment]
And here is the error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'HtmlWeb' could not be found (are you missing a using directive or an assembly reference?)	OOVxfAtInvstr	C:\Users\HDBolak\Source\Repos\OOVxfAtInvstr\OOVxfAtInvstr\OOVxfAtInvstr\Popovers\popOverPageSendSharedExternalContent.cs	221	Active

HtmlDocument class is used in the next line and there is no problem on that line.

**Comment by JonathanMagnan** [comment]
Thank you @dbolak ,

The issue has been found. I will try to fix it and make a new release on Tuesday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @dbolak  ,

The v1.6.3 has been released,

`HtmlWeb` should now be available again. I'm really sorry for this mistake, that happened when I moved all file into a shared project.

Let me know if that's fixed.

Best Regards,

Jonathan

**Comment by dbolak** [comment]
@JonathanMagnan Thank you very much for your kind attention. The issue is fixed. Kind Regards. Dogan.
