### ISSUE TITLE
Colons In Attribute Names Mangled With OptionOutputAsXml and LoadHtml

### ISSUE THREAD

**Issue by mbrierst** [zzzprojects/html-agility-pack#95]
When using LoadHtml to import html containing attribute names containing colons (for example when using namespaces) and using `OptionOutputAsXml = true`, the attribute names become horribly mangled.  See this example which works fine:
```C#
var d = new HtmlDocument { OptionOutputAsXml = false };
d.LoadHtml("<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><script xlink:href=\"cool-script.js\" type=\"text/ecmascript\"/></svg>");
MessageBox.Show(d.DocumentNode.InnerHtml);
```
And this example where the attribute names are badly mangled:
```C#
var d = new HtmlDocument { OptionOutputAsXml = true };
d.LoadHtml("<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><script xlink:href=\"cool-script.js\" type=\"text/ecmascript\"/></svg>");
MessageBox.Show(d.DocumentNode.InnerHtml);
```

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

Thank you for letting me know, I will check how attribute is managed in this library later today probably.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mbrierst ,

The v1.6.3 has been released,

attribute name should now be parsed correctly

Let me know if that's fixed.

Best Regards,

Jonathan

**Comment by mbrierst** [comment]
Looks like this fixed it for me.  Thanks!
