### ISSUE TITLE
NestedOptionsTests Missing

### ISSUE THREAD

**Issue by anish714** [zzzprojects/html-agility-pack#99]
Attempting to build Solution HtmlAgilityPack.sln.  HtmlAbilityPack.Tests/NestedOptionsTests.cs is missing.

**Comment by JonathanMagnan** [comment]
Hello @anish714 ,

I'm not aware of any file named `NestedOptionsTests.cs`

Are you sure you have taken the source from this repository?

Best Regards,

Jonathan

**Comment by anish714** [comment]
Sorry, this did come from a different repo.

**Comment by JonathanMagnan** [comment]
No problem ;) Just for my curiosity, from which repo this was coming?

**Comment by anish714** [comment]
https://github.com/jstedfast/HtmlAgilityPack
Trying to locate the master repo for this library lol.
